### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by CaseyHudson** [MicrosoftDocs/windows-itpro-docs#10038]
"Use TPM technology for platform device authentication by using the TPM’s unique RSA key, which is burned into itself."

Should read "Use TPM technology for platform device authentication by using the TPM’s unique RSA key, which is burned into it."

The RSA key is not "burned into itself." It is burned into the chip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a149789-67c1-e126-129b-6e77e831086d
* Version Independent ID: dd04d845-c098-46e5-fedf-92ba8fc64615
* Content: [Trusted Platform Module Technology Overview (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview)
* Content Source: [windows/security/information-protection/tpm/trusted-platform-module-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @CaseyHudson The issue is under review.

Please note that you can come up with your improvement to the article via the GitHub platform. The IT Pro documentation is partly open-source. Here’s a link to the article source: https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/tpm/trusted-platform-module-overview.md

Thank you for the feedback.
