### ISSUE TITLE
Hard Link

### ISSUE THREAD

**Issue by vinsi024** [MicrosoftDocs/windows-itpro-docs#1007]
How a hard link could lead to a malicious activity and in what scenarios a hard link is created by a user or a software. Please help us understand this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e574aa-9e89-b78d-e60a-242828d4b82e
* Version Independent ID: 7e72855c-2850-5cb7-878d-0eb5b9a6cff4
* Content: [4664(S) An attempt was made to create a hard link. (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4664#security-monitoring-recommendations)
* Content Source: [windows/security/threat-protection/auditing/event-4664.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/event-4664.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@vinsi024 I am passing along a reply from an auditing expert here with Microsoft:

I can think of two ways off the top of my head.

1) Hard link, with a different name and to a different folder, an existing program file such as a Windows command line executable, so that it can be launched to avoid detection based on auditing sec event 4688.

2) Responders look at hard links as a quick way to identify Windows binaries.  An attacker can hard link malware into the winsxs folders to make the malware look like a Windows binary.

The above works because Windows binaries are hard linked from the sxs folders to all over Windows. 

If I recall correctly, you can create hard links without sec event 4688 disclosing what was done.

**Comment by vinsi024** [comment]
Hi Justin,

But question arises here that
 1. How it can be identified that a hard link created is of which file
 2. What is the criteria of a hard link creation or what is the parameter
which identifies that a particular link is a hard link of some file.

Regards
Vinod Singh

**Comment by Justinha** [comment]
Hi Vinod, 
I did some searching. For #1, there is a tool named find that is included in this download package: https://www.microsoft.com/en-us/download/details.aspx?id=23754 

find . -links +1

Looks like fsutil might report hard links too. 

For #2, there is a CreateHardLink function that might cover the parameters you are asking about, see https://msdn.microsoft.com/en-us/library/windows/desktop/aa363860(v=vs.85).aspx and https://msdn.microsoft.com/en-us/library/windows/desktop/aa365006(v=vs.85).aspx 

Does that help?

Thanks,
Justin

**Comment by vinsi024** [comment]
Hi Justin,

I have read the links but how can we check the syntax of a newly created
hard link or an existing file in which we can find those parameter values.

**Comment by R2D2components** [comment]
Hi I’m the original owner of this computer and devices the email. This computer was unauthorized to be reconfigured per manufacture please revert what work was done and email me when work is complete thank you please hurry. 

Jason Robertson

**Comment by Justinha** [comment]
@R2D2components these issues are intended to be about the document 4664(S) An attempt was made to create a hard link. (Windows 10). Please clarify any question you have about that topic.
