### ISSUE TITLE
BranchReadinessLevel removed from 21H2 ADMX templates

### ISSUE THREAD

**Issue by danielniccoli** [MicrosoftDocs/windows-itpro-docs#10096]
Policy `\Policies\Microsoft\Windows\WindowsUpdate\BranchReadinessLevel` was removed from the 21H2 ADMX templates.

Could you please clarify whether 21H2 is the first Windows version where support for this policy has been removed, or whether it was removed in an earlier version already?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684b30a-3187-85ce-0cf7-10d1b8298b7f
* Version Independent ID: 9b7170fc-2b39-8e46-7898-894a45de8623
* Content: [Configure Windows Update for Business - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-configure-wufb#feedback)
* Content Source: [windows/deployment/update/waas-configure-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-configure-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley can you advise?

**Comment by arcarley** [comment]
Branch Readiness Level exists on all Windows versions; HOWEVER, it did move to a different location (onto the manage preview builds page).

Note BRL 16 and 32 were combined into simply 16 (a single release channel) in 2004 release and are no longer relevant to set from that point on unless you are using them for preview builds (Insider Dev, Beta or Release Preview channels).

Best,
Aria

**Comment by danielniccoli** [comment]
@arcarley I am not sure I can follow. I updated from the 21H1 to the 21H2 admx templates this week. If the policy would have simply been moved from one place to another, without changing the registry key underneath it, wouldn't this be reflected in the GPO report? Instead I see an unmanaged registry key:

![image](https://user-images.githubusercontent.com/2971735/141280334-557a32a1-098c-45d4-b5db-0aad402332bf.png)

**Comment by arcarley** [comment]
Hi, first of all the Windows 10 21H2 templates have not been released since Windows 10 21H2 has not yet been released… You updated to the Windows 11 21H2 template (Download ADMX Templates for Windows 11 October 2021 Update [21H2] from Official Microsoft Download Center<https://www.microsoft.com/en-us/download/details.aspx?id=103507>) which is actually goo because it is what I would recommend! 😊


Note this should have BRL still in the registry, but a value of 16 or 32 certainly shouldn’t be.
***@***.***

However, you may note that we do have a different subfolder structure in Win 11 for GP:
***@***.***

BRL is going to be “Manage updates offered from Windows Update” > “Manage preview builds”

***@***.***

You’ll note there is NO LONGER an option for 16 or for 32 – neither of those values have been relevant since Windows 10 2004 so we decided to remove them completely. Since Windows 10 2004 there has been simply one release channel and by default you are on it unless you select a pre-release channel.

Does this help clarify?

**Comment by Lovygoogle** [comment]
مرحبا يمكنك أن تلقى نضره على موقعي لتقد "https://Liungle.blogspot.com"
م لي ملاحضه
شكرا لزيارتكم

2021-11-25 3:30 غرينتش+03:00, Onur ***@***.***>:
> Closed #10096.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10096#event-5669960432


-- 
مع أطيب التحيات
      [فريق، Liungle]
