### ISSUE TITLE
Reference for systems other than WHfB affected by PIN Complexity GPOs

### ISSUE THREAD

**Issue by EdwardsCP** [MicrosoftDocs/windows-itpro-docs#10094]
Regarding the PIN Complexity Group Policy settings that are described on this page: it explains that the settings are not specific to WHfB, but there is no reference to other systems that use these same PINs.  It would be helpful if there were a cross-reference to other systems that use it, because I've never encountered any and can't find any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec90f64-9a12-fdf9-25db-0e83cf77b7a2
* Version Independent ID: fb68756c-2d0c-c28c-4bda-ef6a876576e7
* Content: [Configure Windows Hello for Business Policy settings - certificate trust - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-cert-trust-policy-settings.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
This is primarily in reference to convenience PIN and Windows Hello PINs for Microsoft connected accounts. Convenience PIN can be enabled using the "Turn on convenience PIN policy" under Administrative Templates\System\Logon. Convenience PIN uses the same Windows service as WHFB but is a password stuffer instead of using public-private key pairs for AD authentication. Local accounts also use convenience PIN because they don't authenticate to an identity provider. 

Microsoft connected accounts can be added to a domain joined machines and users can setup a PIN for logon. This will be subject to PIN complexity policy applied to the device.

**Comment by Lovygoogle** [comment]
مرحبا يمكنك أن تلقى نضره على موقعي لتقد "https://Liungle.blogspot.com"
م لي ملاحضه شكرا لزيارتكم 2021-11-25 3:30 غرينتش+03:00, Onur
***@***.***>: > Closed #10096. > > -- > You are
receiving this because you are subscribed to this thread. > Reply to
this email directly or view it on GitHub: >
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10096#event-5669960432
-- مع أطيب التحيات [فريق، Liungle]

2021-11-25 3:29 غرينتش+03:00, Onur ***@***.***>:
> Closed #10094.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MicrosoftDocs/windows-itpro-docs/issues/10094#event-5669955368


-- 
مع أطيب التحيات
      [فريق، Liungle]
