### ISSUE TITLE
missing information at "Connect to remote Azure Active Directory-joined PC"

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/windows-itpro-docs#10107]
[Enter feedback here]

Hi

I looked for a solution to "Connect to remote Azure Active Directory-joined PC". Here in the article is only described, how to enable remote connection and not more.

Where is described how I can "Connect to remote Azure Active Directory-joined PC"? Which tool do I need. Which PC name should I use. What happen, if the PC is not located in my TCP subnet? Which user name format and credential must I use? Can you provide a diagram how this should work?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @bedo1976 ,
**Where is described how I can "Connect to remote Azure Active Directory-joined PC"?** - it doesn't differ from RDP connections to any other PC. It is not described in the article since this documentation section is intended for IT professionals, not for users, so it is focused on the configuration aspects.
**Which tool do I need.** - remote desktop connection
**Which PC name should I use.** - name resolvable from the network where you are connecting from
**What happen, if the PC is not located in my TCP subnet?** - behavior doesn't differ from any other remote connection. If it is discoverable, routable and if RDP port is open, it will connect.
**Which user name format and credential must I use?** - AzureAD\yourloginid@domain.com, where yourloginid@domain.com is user that has permissions for remote connections (it is described in the article)
Thank you
