### ISSUE TITLE
Confusing Note

### ISSUE THREAD

**Issue by cmc099** [MicrosoftDocs/windows-itpro-docs#10157]
>The NetworkQoSPolicy configuration service provider is officially supported for **devices that are Intune managed and Azure AD joined**. Currently, this CSP is not supported on the following devices:

>Azure AD Hybrid joined devices.
Devices that use both GPO and CSP at the same time.

>The **minimum operating system** requirement for this CSP is **Windows 10, version 2004**. This CSP is **supported only in Microsoft Surface Hub prior to Windows 10, version 2004**.

The Note above seems contradictory in multiple ways. Devices that are Intune managed and Azure AD joined implies a broad range of devices. The last sentence then states that only Microsoft Surface Hub devices are supported. Additionally, the last two sentences conflict. The first sentence states that at least Win 10 2004 is required. The next sentence states that only versions prior to Win 10 2004 are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb8b93e-0c1a-8b47-472f-effef5f9209e
* Version Independent ID: 8a2615e2-a77b-c08e-b91c-3ce33e0539b2
* Content: [NetworkQoSPolicy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/networkqospolicy-csp)
* Content Source: [windows/client-management/mdm/networkqospolicy-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/networkqospolicy-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
@ManikaDhiman - In an update to a document on Sep,28,2020. You have mentioned that *This CSP is supported only in Microsoft Surface Hub for versions prior to Window 10, 2004.*

Can you please explain if this is only supported by Surface Hub devices or it can be applied to other devices but for Surface Hub, it can only be applied if the Surface Hub is running a prior version of Windows 10, 2004? 

Here is the blame link when this comment was added https://github.com/MicrosoftDocs/windows-itpro-docs/commit/cdcb6c958f95bfbbda7166b19101191fcda365a1

**Comment by aczechowski** [comment]
I started an internal thread to try and track down the source of this sentence. I agree that it's confusing.

**Comment by aczechowski** [comment]
Some followup on this.

First, we're in process to revamp how we handle all of the CSP docs, to automate the content based on the DDF XML from the OS itself. As part of that transition, we will copy some of the existing content, but mostly rely on what's explicitly listed for each CSP.

In this specific instance, here's the description directly from the CSP (which theoretically we'll use verbatim going forward):

> This CSP was added in Windows 10, version 1703. This CSP is supported only in Microsoft Surface Hub prior to Window 10, version 2004.

So perhaps the current note in the doc was a misinterpretation of that description? 🤔 

Two actions I'm taking right now:

- As an FYI, assign to @vinaypamnani-msft who is spearheading the CSP content effort. When we work on this content, we need to look into this.
- Closing this specific issue. Since the content will soon be automated, I don't want to make any changes right now, but we'll address as part of the migration project.
