### ISSUE TITLE
Images missing in archived content / active content linking to hard to read archived content

### ISSUE THREAD

**Issue by grangeway** [MicrosoftDocs/windows-itpro-docs#10168]
Hello Team,

The section on DPC_WATCHDOG_VIOLATION and debugging links to a guide on how to analyze this particular error message, which goes to archived content at https://docs.microsoft.com/en-us/archive/blogs/ntdebugging/determining-the-source-of-bug-check-0x133-dpc_watchdog_violation-errors-on-windows-server-2012

For the variant where parameter is 1, it then links to https://docs.microsoft.com/en-us/archive/blogs/ntdebugging/part-3-etw-methods-of-tracing - where none of the images in the content work any longer.

Is there any chance of getting this content recovered, or of updating the original links to provide a current guide to how to set up ETW kernel tracing ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b85544e-69dc-04ef-3ae7-98864d7a7529
* Version Independent ID: af0af832-7663-ab3b-7283-2948819465ac
* Content: [Advanced troubleshooting for Stop error or blue screen error issue - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-stop-errors)
* Content Source: [windows/client-management/troubleshoot-stop-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-stop-errors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
Afternoon I am going to add windows 20H1 and 20H2 links to this article.

**Comment by RAJU2529** [comment]
@0ei,   Created new PR #10171  for a different issue. so verify it

**Comment by michaelAngeloEgypt** [comment]
What does "none of the images in the content work any longer" mean? the images seem fine. The only difference between those images in https://docs.microsoft.com/en-us/archive/blogs/ntdebugging/part-3-etw-methods-of-tracing and images in any other article like https://docs.microsoft.com/en-us/archive/blogs/ntdebugging/save-support-dollars-by-checking-your-memory-dump-before-calling-support is that in the first case clicking on the image points to the containing page, while in the second case  clicking an image downloads it.
However I can't edit the content of the first link because it is not on Github.
