### ISSUE TITLE
WDAC - mimimumfileversion not described.

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/windows-itpro-docs#10165]
Table 2. Windows Defender Application Control policy - file rule levels
This table does not describe how MinimumFileVersion is actually used:
- for allow rules, it works as expected: files with at least the specified version are allowed to run.
- for deny rules, it works the other way around: files upto the specified version are blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74ef7917-edec-5597-4689-1ffbf6735918
* Version Independent ID: 41f7ceb2-ad16-812c-3766-b9a9a72a42c1
* Content: [Understand Windows Defender Application Control (WDAC) policy rules and file rules (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#table-2-windows-defender-application-control-policy---file-rule-levels)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @jsuther1974
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @Rvvhub - Thank you for posting your query. Can you please share the reference document where MinimumFileVersion related settings are elaborated? I cannot find anything related to the minimum file version in the current document table 2. https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#table-2-windows-defender-application-control-policy---file-rule-levels

Can you please refer anything so that I can better help you or update the document, if required.

**Comment by Rvvhub** [comment]
Hi there, that is the thing: there is no public doc on MinimumFileVersion as far as I can tell.

In an internal thread, this is what I received from Tom Caldwell on it:  
_"While it says 'minimumfileversion' the logic for that field is inverted for deny rules and it should only be blocking version the version specified and below."_

**Comment by vinaypamnani-msft** [comment]
@Rvvhub Thanks for submitting the feedback. I've fixed this, but the fix will go live in a few weeks along with some other changes. I'm closing this issue now.
