### ISSUE TITLE
MS Defender Application Guard 

### ISSUE THREAD

**Issue by AllanLundy** [MicrosoftDocs/windows-itpro-docs#10178]
The page describing MS Defender Guard Application for Firefox and Chrome is contradictory.  At the top it says that it applies to Windows 10.  But under prereqs, it says it applies to Windows 10 Professional.  Like the great majority of users, I have Windows 10 Home.  It is not clear if it applies to this.  Thanks for any comments.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e41c70e9-2889-a930-9f1b-1dfbffe0830f
* Version Independent ID: ae228f28-6128-b670-7aeb-2e8384237dc5
* Content: [Microsoft Defender Application Guard Extension - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/md-app-guard-browser-extension#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-application-guard/md-app-guard-browser-extension.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-application-guard/md-app-guard-browser-extension.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @martyav
* Microsoft Alias: **v-maave**

**Comment by RAJU2529** [comment]
@AllanLundy . Thanks for your feedback, I will take your consideration.

**Comment by MaratMussabekov** [comment]
Hello @AllanLundy ,
Microsoft Defender Application Guard is not supported by Windows 10 Home.
It is not mentioned in the article since it is out of its scope, system requirements are described in dedicated article - [System requirements for Microsoft Defender Application Guard](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-application-guard/reqs-md-app-guard).
Thank you
