### ISSUE TITLE
Script not pulling some IPs?

### ISSUE THREAD

**Issue by zerrikan** [MicrosoftDocs/windows-itpro-docs#10271]
Ran this script and it appears to be missing some IPs for Teams according to https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

Missing:
52.238.119.141 and 52.244.160.207

Are these needed for Teams US?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18462dc7-4de9-9c76-a534-010c11a8ee00
* Version Independent ID: 20f73c06-753e-1ba5-1604-c778aaac2408
* Content: [Optimizing Office 365 traffic for remote workers with the native Windows 10 or Windows 11 VPN client - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-office-365-optimization)
* Content Source: [windows/security/identity-protection/vpn/vpn-office-365-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/vpn/vpn-office-365-optimization.md)
* Product: **m365-security**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **jajo**

**Comment by MaratMussabekov** [comment]
Hello @zerrikan ,
just went through the script to check your information, and it looks like the script only adds IPs in the "Optimize" category:
```
# Invoke endpoints method to get the new data #
$uri = "$baseServiceUrl" + "/endpoints/worldwide?clientRequestId=$clientRequestId"

# Invoke endpoints method to get the data for the VPN profile comparison #
$endpointSets = Invoke-RestMethod -Uri ($uri)
$Optimize = $endpointSets | **Where-Object { $_.category -eq "Optimize" }**
$optimizeIpsv4 = $Optimize.ips | Where-Object { ($_).contains(".") } | Sort-Object -Unique
```
More about IP categories you can read [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide#new-office-365-endpoint-categories)

**Missing: 52.238.119.141 and 52.244.160.207** - these are in "Allow" category:

```
$endpointSets | ? {$_.ips -like "*52.238.119.141*" -or $_.ips -like "*52.244.160.207*"} | select category

category
--------
Allow
Allow
Allow
```


It is also confirmed in the article:
_This allows you to define IP-based exclusions even when using force tunneling in order to "split" certain traffic to use the physical interface while still forcing all other traffic via the VPN interface. Traffic addressed to specifically defined destinations (**like those listed in the Office 365 optimize categories**) will therefore follow a much more direct and efficient path_

If you want to include all IP addresses, you can modify the script.

Thank you
