### ISSUE TITLE
Is there a way to add an AAD group to local remote desktop users group?

### ISSUE THREAD

**Issue by tnewton1** [MicrosoftDocs/windows-itpro-docs#10324]
Is there a way to add an Azure AD security group to the local desktop users group? In a legacy environment, we have a GPO that adds "RDP Enabled" group to the local remote desktop users group on domain joined PCs. Is this functionality supported or do I have to script bulk adding/removing users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by michaelAngeloEgypt** [comment]
I found this [link](https://www.prajwaldesai.com/add-azure-ad-user-to-remote-desktop-users/) which should address the question posted here. 
I guess the technique to add an Azure AD group to the remote desktop users group will be similar to that used to add an Azure AD user to such group, except that the identifier used in the below command will have to be for the group instead of the user:
"AzureAD\username@domain.onmicrosoft.com"

**Comment by ak47uk** [comment]
> 

I tried to add a group in this way and it failed but in MEM, Endpoint security, Account protection I added a new policy to Add (Update) an AAD group to Remote Desktop Users then assigned it to the relevant group. I need to test it still but looks like it worked.
