### ISSUE TITLE
Encoding?

### ISSUE THREAD

**Issue by dfconroy** [MicrosoftDocs/windows-itpro-docs#1033]
Every time I download the data and save the evtx file I get "The event log file is corrupt". 

Is it possible to have the data returned via the /Export be .xml rather than export to evtx?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a84b842f-150d-f006-0563-db5a0f01a64f
* Version Independent ID: 7dd55cbe-abc2-9c33-3fef-843b87f26312
* Content: [DiagnosticLog CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/diagnosticlog-csp)
* Content Source: [windows/client-management/mdm/diagnosticlog-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/diagnosticlog-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @dfconroy ,
**Is it possible to have the data returned via the /Export be .xml rather than export to evtx? -** DiagnosticLog CSP doesn't allow to change output file format.

**Every time I download the data and save the evtx file I get "The event log file is corrupt".** - are you sure all the parameters under ./Vendor/MSFT/DiagnosticLog/EtwLog/Collectors are correct? Do you experience the same for all devices?

Thank you

**Comment by mypil** [comment]
@dfconroy - We would like to follow up. Can you please respond to the query of MaratMussabekov?
