### ISSUE TITLE
Reference to Intunmem equivalent 

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/windows-itpro-docs#10386]
Hi,

Just wondering if there is any thoughts on including a section that refers to the intune\mem equivalent. This would add people who are moving away from GPO's as a configuration plane and towards Intune\MEM with Autopilot to manage their fleet. 

If the the setting is configurable via one of the inbuilt templates just refer to that, or as is the case here call out that a CSP or alternate method should be used for deploying this setting.

Regards
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ded1fc-7605-b135-d643-fdc2f40fbb0c
* Version Independent ID: 3e5a97a6-4557-19a1-9980-fbc602251573
* Content: [Network access Do not allow storage of passwords and credentials for network authentication (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-storage-of-passwords-and-credentials-for-network-authentication)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-storage-of-passwords-and-credentials-for-network-authentication.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-access-do-not-allow-storage-of-passwords-and-credentials-for-network-authentication.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@vinaypamnani-msft Please help us in resolving this issue. Thanks

**Comment by vinaypamnani-msft** [comment]
Thanks @Jlouden9 for the feedback. While I see this as a beneficial change, we do not have the resources to do this work for all the policies, so I'm going to close this as not planned. We do have plans to update CSP docs using automation, and intend to add information about settings catalog there if possible. I'll see if we can make changes to https://learn.microsoft.com/en-us/windows/client-management/mdm/policies-in-policy-csp-supported-by-group-policy and see if we can list the GPO display name there, so that would provide a reference of GPO's that have an MDM equivalent.
