### ISSUE TITLE
Good sample - needs builder

### ISSUE THREAD

**Issue by Degies** [MicrosoftDocs/windows-itpro-docs#10394]
Good page and good info. A builder to generate that xml would be nice for those of us to scared to code stuff and break stuff. 
thx thx help help pls pls export | would be valuable = true
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88a1cfd-be05-05d9-41b8-9eb201b03262
* Version Independent ID: 08c5ce8e-63c9-2f24-c0ee-8ac5d5218371
* Content: [Policy CSP - ExploitGuard - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-exploitguard)
* Content Source: [windows/client-management/mdm/policy-csp-exploitguard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-exploitguard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by vinaypamnani-msft** [comment]
Thanks @Degies  for taking the time to provide feedback on Windows! This idea is an interesting idea, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
