### ISSUE TITLE
This value type of the SystemDrivesEnablePrebootInputProtectorsOnSlates is wrong

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#10436]
This value type of the SystemDrivesEnablePrebootInputProtectorsOnSlates is wrong.
I try do at strings and integers are all wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/bitlocker-csp?source=docs)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@goxia , when enabled this policy through GPO , FVE key  is added to  Machine\Software\Policies\Microsoft\

Value name:: OSEnablePrebootinputProtectorsOnSlates

Type :: REG_DWORD
Data :: 1

**Comment by goxia** [comment]
@RAJU2529 , Thank you for your reply. Yes, I understand the GPO, but the configuration information given in this document is incorrect because following this configuration will not take effect and there will be errors. Also confirm that the information in the document is correct.

**Comment by RAJU2529** [comment]
@goxia  I don't have any information about CSP , so authors of this document should conform .

**Comment by aczechowski** [comment]
Thanks @goxia for the feedback. All of the DDFv2 CSP articles (which is most of them) are recently refreshed based on the DDF XML from the Windows build. Take another look at the revised section for the [SystemDrivesEnablePrebootInputProtectorsOnSlates](https://learn.microsoft.com/windows/client-management/mdm/bitlocker-csp#systemdrivesenableprebootinputprotectorsonslates) policy, as that information is now pulled from the XML and/or the ADMX.

If there are any inaccuracies, because the data comes from the OS itself, it needs to be treated as product feedback and shared with the engineering team via the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). If you do so, make sure to note that it's an issue with the CSP DDF XML.

While most of the article's content is auto-generated, there are editable sections as well. So if further clarification is needed, please reopen this issue and provide further information to clarify.
