### ISSUE TITLE
How does a PIN login affect network shares and remote desktop access

### ISSUE THREAD

**Issue by TomTurkington** [MicrosoftDocs/windows-itpro-docs#10469]
Though I understand how a PIN login may be more secure for local logons directly onto a device via the logon screen, this article does not address how it changes mapped drive access and RDP access.  If I can still access the device via a mapped drive or RDP using username/password, it would seem the PIN enhancement would be nullified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34dbafa-df3c-a5a5-32d5-2ce152893534
* Version Independent ID: cebdd9a6-45d7-6306-373c-7d31121f9e16
* Content: [Why a PIN is better than an online password (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-why-pin-is-better-than-password.md)
* Product: **m365-security**
* GitHub Login: @Gitprakhar13
* Microsoft Alias: **prsriva**

**Comment by MaratMussabekov** [comment]
Hello @TomTurkington ,
**this article does not address how it changes mapped drive access and RDP access** - because it doesn't change it. PIN doesn't work remotely, it works only in connection with the device.
PIN+device authenticates the user. For example, you have PIN for device A. You can use it to login to device A locally. You can also use it to login via RDP from device A to device B. But you cannot use it to login via RDP from device B to device A.
Thank you
