### ISSUE TITLE
4647 (S) ：使用者啟動登出, 當主機上有登入10個使用者時..1位使用者登出, 10位使用者都會同時執行此觸發...

### ISSUE THREAD

**Issue by clfvz** [MicrosoftDocs/windows-itpro-docs#10500]
你好, 

我使用這個事件來觸發記錄使用者登出主機時需要執行的作業..
4647 (S) ：使用者啟動登出

但是當主機上有登入10個使用者時..1位使用者登出, 10位使用者都會同時執行此觸發...
請問要如何修正此問題??

謝謝  

Wolf Wang
---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 7bfeaeb0-e08a-c011-29a4-2a649a8d9a07
* Version Independent ID: f0d88d1f-a7b0-6fc0-17bb-07a86bb2b681
* Content: [4647 (使用者) 登出。 (Windows 10) - Windows security](https://docs.microsoft.com/zh-tw/windows/security/threat-protection/auditing/event-4647#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4647.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/main/windows/security/threat-protection/auditing/event-4647.md)
* Product: **m365-security**
* Technology: **windows-sec**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@-

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
