### ISSUE TITLE
Windows 11 Auto-Upgrade when Revert back to Windows 10

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#10546]
This issue has been discussed in the past in **https://answers.microsoft.com**  but because it is important, I will have to share it again. 

When users upgrade to Windows 11 from the Windows 10, they have up to 10 days to rollback (we could extend it) but when they rollback, their device will upgrade to Windows 11 again and this is troublesome for them.

There is a trick to modify registry and prevent the upgrade, but it is not easy for many users and consider scenario a user upgrade to Windows 11 and for any reason want to roll back and stay in Windows 10 for a while (maybe upgraded to Windows 11 later) but this should be in control of the user.

Please pass this feedback to the Windows team so after user rollback to Windows 10, show optional upgrade to Windows 11, instead of force download and install Windows 11 which is a negative user experience.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa733db-e564-bd3f-d41b-241b27b13b40
* Version Independent ID: ef647afb-e298-af7b-5523-2076d3f2c9c6
* Content: [Prepare for Windows 11 - What's new in Windows](https://docs.microsoft.com/en-us/windows/whats-new/windows-11-prepare)
* Content Source: [windows/whats-new/windows-11-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-prepare.md)
* Product: **w11**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by RAJU2529** [comment]
@aczechowski , please take feedback .  I am one of the volunteer moderators under the windows category.

**Comment by aczechowski** [comment]
Thanks @RAJU2529 for taking the time to provide feedback on Windows! This idea is an interesting feature, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as there's nothing actionable for docs at this time. If you disagree, please reopen and provide more information on what info we can add to docs to help with this scenario.
