### ISSUE TITLE
GPO settings adjust

### ISSUE THREAD

**Issue by johanvjr** [MicrosoftDocs/windows-itpro-docs#1055]
Hi, can we overrule the GPO settings that are set by shared pc? We are looking for a configuration where more then one person can logon, use the device, save stuff (for example local onedrive). This is a hybrid joined device registrated in intune mdm. any advise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14b376e2-39bd-faca-a76c-dd21bad8d8fd
* Version Independent ID: a76cabb0-59b9-7e97-6603-eec7d37f1fd4
* Content: [Set up a shared or guest PC with Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc#customization)
* Content Source: [windows/configuration/set-up-shared-or-guest-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/set-up-shared-or-guest-pc.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@johanvjr I checked with the product team for Shared PC. Generally, we don't recommend modifying the policy settings that are set by Shared PC, because some policies can conflict with other policies/components are set up. I asked specifically about your scenario of allowing people to save, and the suggestion is to override "Admin Templates > Windows Components > OneDrive > Prevent the usage of OneDrive for file storage" and you might also need to set RestrictLocalStorage to "false" (https://docs.microsoft.com/en-us/windows/client-management/mdm/sharedpc-csp#restrictlocalstorage). I hope that helps!

**Comment by jdeckerms** [comment]
I don't know of any better method, @johanvjr
