### ISSUE TITLE
Defender Catch-Up Scan Tooltip and Docs are backwards and confusing.

### ISSUE THREAD

**Issue by MgramTheDuck** [MicrosoftDocs/windows-itpro-docs#10553]
### The tooltip for Defender Catch-Up settings are currently directly opposing the name of the setting.

The policy name is "Disable Catch-Up Scans" however the tooltip and documentation suggest that the correct setting for "Catch-Up Scans" to be enabled, would be "Yes" which is directly opposing what the name of the policy is. 

For example: 
DisableCatchupFullScan = Yes (**according to docs, this means they are NOT disabled**)

This also appears in the documentation listed here: https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-disablecatchupfullscan

```
This policy setting allows you to configure catch-up scans for scheduled full scans. A catch-up scan is a scan that is initiated because a regularly scheduled scan was missed. Usually these scheduled scans are missed because the computer was turned off at the scheduled time.

If you enable this setting, catch-up scans for scheduled full scans will be turned on. If a computer is offline for two consecutive scheduled scans, a catch-up scan is started the next time someone signs in to the computer. If there's no scheduled scan configured, there will be no catch-up scan run.

If you disable or don't configure this setting, catch-up scans for scheduled full scans will be turned off.
```

![image](https://user-images.githubusercontent.com/85346345/169449554-bc02238d-8ea1-425a-87d4-189fca63f142.png)

(admin edit: add article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#disablecatchupfullscan)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@CMDRMgram This is indeed confusing, I looked into the setting more. DisableCatchupFullScan by default has a value of 1 (True/Yes), which indeed means the catch up scans are disabled by default. To turn catch up scans on, you need to Enable the setting which is done by setting it to 0 (No/False), which does contradict the Intune settings catalog. I believe the Intune Settings Catalog is flipping the logic to make it easier to configure the setting, but I've reached out to some folks to confirm this before I add any clarification in the docs.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by vinaypamnani-msft** [comment]
I've updated the docs to reflect the proper description, so I'll close this issue now.

**Comment by TCGL23** [comment]
@vinaypamnani-msft can you check the docs are published as still confusing, 
If you leave as default/Enabled Get-MPPREFERENCE shows DiableCatchupQuickScan is True so the scans are disabled where if you set to Disabled Get-MPPREFERENCE shows DiableCatchupQuickScan is False so the scans should be enabled or is this incorrect?

**Comment by vinaypamnani-msft** [comment]
Sorry I haven't published the doc changes yet, but for both DisableCatchup*Scan settings, setting them to True disables quick scan. The changes are pending some other reviews as part of a larger PR, and will be live later this week.

**Comment by TCGL23** [comment]
@vinaypamnani-msft thank you for the update and confirmation
