### ISSUE TITLE
Web Portal for Remote Assistance no longer works with latest version of Quick Assist 2.0.6.0

### ISSUE THREAD

**Issue by ckh-rcit** [MicrosoftDocs/windows-itpro-docs#10601]
The following page requires an 8 digit code:
https://remoteassistance.support.services.microsoft.com

Since Quick Assist 2.0.6.0 codes are now 6 digits and alphanumeric.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfcd14cd-f887-660f-8a4c-465b3495e90e
* Version Independent ID: 121eead7-eb87-f033-024a-f688866c58a0
* Content: [Use Quick Assist to help users - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/quick-assist)
* Content Source: [windows/client-management/quick-assist.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/quick-assist.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
@aczechowski Please help us in resolving this issue. Thanks

**Comment by aczechowski** [comment]
Thanks @ckh-rcit for taking the time to provide feedback on Windows! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

For more immediate response, I suggest raising a case with Microsoft Support through your most appropriate channel.
