### ISSUE TITLE
Please note that current certificate for SetupDiag.exe v1.6.2107.27002 has expired on 12/02/2021

### ISSUE THREAD

**Issue by SwimmeRM** [MicrosoftDocs/windows-itpro-docs#10614]
Please note that current certificate for SetupDiag.exe v1.6.2107.27002 has already expired on 12/02/2021.
Unless you're going to provide another update of same tool I hope that at least you can soon just ensure that same tool it's published again with a non expired yet certificate.
Thanks for attention.
Best Regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
@aczechowski Please help us in resolving this issue. Thanks

**Comment by aczechowski** [comment]
Thanks @SwimmeRM for taking the time to provide feedback on Windows! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
