### ISSUE TITLE
Need update to reflect Windows 10 version 1803

### ISSUE THREAD

**Issue by timmytandian** [MicrosoftDocs/windows-itpro-docs#1064]
Can you please add some information for the documentation in "17. Settings &gt; Privacy" section? Windows 10 version 1803 hasn't been included here yet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd3113-b803-87b6-ef7f-6893bcc5ceb5
* Version Independent ID: 6f7ca1ee-d19c-42bb-7db5-6158fc160e32
* Content: [Manage connections from Windows operating system components to Microsoft services (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services#whats-new-in-windows-10-version-1803-enterprise-edition)
* Content Source: [windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Within settings, we link out to here : https://privacy.microsoft.com/en-us/general-privacy-settings-in-windows-10

Is there anything specifically you're interested in?
This documentation has IT admins as it's main audience, so we usually try to discuss how to control settings on a large scale, rather than drilling down to manual configurations in settings.

**Comment by thewabbit0** [comment]
It is pretty obvious that this documentation is not comprehensive in regard to 1709 and 1803. 

I've found at least one instance of each of the following:
- group policy name labels have changed in 1709/1803-adml files while the old labels are still referred to in this document
- Options superseded by newer options are not pointed out: for instance, the "Insider Preview Builds" policy is clearly documented as only being supported in 1703 and has been superseded by the "Manage preview builds" as of 1709 and later
- Where paths were fixed in 1803, the old (and wrong) paths are still used in this document like the "Turn Off notifications network usage" GPO setting which has moved from "User Configuration" to "Computer Configuration"

**Comment by DaniHalfin** [comment]
@thewabbit0 - I'll look into making  changes to the topic to reflect name changes across versions. If you'd like, you can also use the "edit" button on the topic itself to suggest the specific changes you'd like to see. 
Thanks!

**Comment by thewabbit0** [comment]
@DaniHalfin thanks for looking into this. I am not quite sure if it would really help if I just commented on the changes I'd like to see. As this is official documentation for privacy-related settings which is being taken as authoritative, there is the expectation of correctness and comprehensiveness.

If readers are getting the impression that the documentation is outdated or sloppy, it loses most of its value, down to the level of any arbitrary ZDNet or PCWorld "reclaim your privacy" blog entry.

And unfortunately, I have to conclude that this document has not been reviewed for 1709/1803-specific changes, at least not thoroughly. @timmytandian already noted that section 17 has not been updated in respect to newly available or renamed settings (e.g. the new name for "Getting to know you", the new privacy functions for app access to "Automatic file downloads", "Documents", "Pictures", "Video") . As I wrote, GPO-related information is heavily affected as well.

In my opinion, the entire document *really* needs a thorough review at this point to ensure that the information is still correct, up-to-date and comprehensive.

Regards,
Denis
