### ISSUE TITLE
Type on 

### ISSUE THREAD

**Issue by stevens-scott** [MicrosoftDocs/windows-itpro-docs#10667]
Should the below sentence notate "INfrequently" versus what's currently stated?

"Feature updates: Released annually. Feature updates add new features and functionality to Windows 10. Because they are delivered **frequently** (rather than every 3-5 years), they are easier to manage"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7945e873-514b-d650-91be-4524567486cb
* Version Independent ID: 31b8f828-3e70-7ddb-ea23-4b9128ce0ccb
* Content: [Windows client updates, channels, and tools - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/get-started-updates-channels-tools#types-of-updates)
* Content Source: [windows/deployment/update/get-started-updates-channels-tools.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/get-started-updates-channels-tools.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @stevens-scott, I think that's accurate. Feature updates are released more frequently than full versions of Windows. So it's easier to manage a relatively smaller feature update using existing update management tools, instead of deploying a new OS from media. I'm closing this issue, but let me know if you have further questions.
