### ISSUE TITLE
Missing information about configuring per-profile proxy settings

### ISSUE THREAD

**Issue by rovingclimber** [MicrosoftDocs/windows-itpro-docs#10666]
Hi!

This page is referenced from the HoloLens 2 documentation (https://docs.microsoft.com/en-us/hololens/hololens-network) in regard to setting per-wifi-profile proxy settings:

[WiFi CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/wifi-csp): per-profile Wi-Fi proxy

However the mentions of proxy settings on this page don't give any useful information, just statements like:

"Proxy Don't use. Using this configuration in Windows 10 client editions will result in failure."
"Using Proxyis in Windows 10 client editions (Home, Pro, Enterprise, and Education) will result in failure."

I believe this CSP is still in use / relevant to HoloLens / Windows Holographic, which seems to use per-connection proxy setting (at least it's available in the UI), but without the documentation it's impossible to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0c33a6-9251-9737-3f75-04be41fe9716
* Version Independent ID: e9806355-0616-cff1-e527-95d7c13ae06e
* Content: [WiFi CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/wifi-csp)
* Content Source: [windows/client-management/mdm/wifi-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/wifi-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by rovingclimber** [comment]
I can now confirm from testing that the missing CSP information is definitely still relevant to current Windows Holographic version. The tree should be:

./Device/Vendor/MSFT
WiFi
---Profile 
------SSID
---------WlanXML
---------WiFiCost
---------Proxy    (proxy server for this connection in SERVER:PORT format)
---------ProxyPacUrl    (URI for proxy .pac file for this connection e.g. http://mypacserver/proxy.pac)
---------ProxyWPAD   (True / False - use WPAD to discover proxy on this connection)

I believe these per-connection proxy settings were dropped in Windows desktop >1809, but remain current in Windows Holographic 22H1. They certainly still work when pushed as SyncML code, and still available in Intune.

**Comment by aczechowski** [comment]
Thanks @rovingclimber for the feedback and info. This article, along with all of the DDFv2-based CSPs, were recently converted to mostly auto-generated from the DDF XML (and ADMX if available). At a quick glance, it looks like the tree information is updated and similar to what you noted.

While there are editable sections of the doc, since most of it is auto-generated from the Windows build, any changes to that information needs to go to the engineering team via the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) - if you do go that route make sure to note that it's the CSP DDF XML descriptions that need more info/revision/etc. 

I'm going to close this issue. If you read the new version of this article and there's any further clarification that should be added to an editable section, please reopen this issue with additional information to clarify.
