### ISSUE TITLE
After trying the many ways to fix this listed by Microsoft, I found one that worked

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/windows-itpro-docs#10696]
Link to fix for the KB defender update issue

https://answers.microsoft.com/en-us/protect/forum/all/protection-definition-update-failed-error-code/5e0c085c-b5fb-4ef5-ba9e-75437139f261?page=2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#how-do-i-reset-windows-update-components)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This article was migrated to the Windows troubleshooting content library, which is owned by another team in support. I've shared this issue with them if they want to take action on it. I'm closing this issue as there's nothing actionable for my team since this content no longer exists in this repository.
