### ISSUE TITLE
Update Compliance v2 Preview Issues

### ISSUE THREAD

**Issue by SkipToTheEndpoint** [MicrosoftDocs/windows-itpro-docs#10745]
I'm attempting to test the Update Compliance v2 Preview detailed [here ](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-v2-overview) however I'm seeing strange behaviour. 

According to the docs, v2 is supposed to create 6 new tables:
- UCClient
- UCClientReadinessStatus
- UCClientUpdateStatus
- UCDeviceAlert
- UCServiceUpdateStatus
- UCUpdateAlert

However as you can see in the following image where I've tested deploying both to separate Log Analytics Workspaces, v2 (left) and the current UC solutions (right) seem to be creating the same hybrid mix of old and new tables:
![image](https://user-images.githubusercontent.com/104939301/182163977-e5ca4b95-e59d-4376-a095-03b41a8f4ffc.png)

I notice that both implementation guides point to the same Update Compliance Solution in the Azure Marketplace (https://azuremarketplace.microsoft.com/marketplace/apps/Microsoft.WaaSUpdateInsights?tab=Overview), so I'm not sure if v2 is supposed to have a different solution link?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ec4f306-1640-aaec-a44c-de4a9f3eedf7
* Version Independent ID: 7ec4f306-1640-aaec-a44c-de4a9f3eedf7
* Content: [Update Compliance overview - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-v2-overview)
* Content Source: [windows/deployment/update/update-compliance-v2-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-v2-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by SkipToTheEndpoint** [comment]
I've noted that #10893 has been raised. It would be good to know if to get a full set of data currently you have to configure both v1 and v2 versions of the Update Compliance (i.e. deploy a setting specifically to push the CommercialID as well as the AllowCommercialDataPipeline setting)

**Comment by yogkumgit** [comment]
@mestew Please help us in resolving this issue. Thanks

**Comment by mestew** [comment]
Thanks @SkiptoTheEndpoint I'm closing issue since it's been made obsolete at this point. Update Compliance v1 and v2 (now known as Windows Update for Business reports) have been seperated now and v1 is no longer accepting new onboarding requests. CommercialID is no longer required or usable for v2 nor is the Azure Marketplace solution. The solution that v1 and earlier preview iterations of v2 relied on has been pulled from the marketplace completely. V1 will be fully retired on March 31, 2023. Let me know if additional clarification is required. 

Thanks for bringing this to my attention @yogkumgit
