### ISSUE TITLE
Hyper-V does not work

### ISSUE THREAD

**Issue by thons-dnb** [MicrosoftDocs/windows-itpro-docs#10750]
Hyper-V is not supported on Autopilot. Pre-Provisioning fails in securing your hardware because of the missing TPM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@thons-dnb Thank you for your feedback. From the feedback from the product team, Hyper-V is supported on Autopilot and the steps in the document should ideally help. If you continue to face issues, I'd recommend you create a support ticket with Microsoft, so that a support engineer can assist you in fixing the issue.

Hope this helps!

Thanks
Sri
