### ISSUE TITLE
Prevent installation of removable devices

### ISSUE THREAD

**Issue by ryanturcotte** [MicrosoftDocs/windows-itpro-docs#10755]
Is there a reason this page does not use the "Prevent installation of removable devices" in Steps 4 and 5 to simplify the USB block? Aren't all USBs removal devices?

(admin edit: refresh metadata with latest)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d16b09d3-4174-28ba-20f4-b1ff12c5afee
* Version Independent ID: 18f87d50-6662-afd9-cfe0-7fa3a29345c5
* Content: [Manage Device Installation with Group Policy (Windows 10 and Windows 11) - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/manage-device-installation-with-group-policy)
* Content Source: [windows/client-management/manage-device-installation-with-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/manage-device-installation-with-group-policy.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by yogkumgit** [comment]
@aczechowski Please help us in resolving this issue. Thanks

**Comment by aczechowski** [comment]
Assigning to @vinaypamnani-msft to help

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by ryanturcotte** [comment]
If it makes your life easier you can just close this issue. I don't remember the full reason why I made this comment, and looking back on the thread it seems more complicated than it was (or it was edited after i made my comment).

I know a lot more about GP device install restrictions and know now that "Prevent installation of removable devices" doesnt provide any fine-grained control for what to allow and disallow.
