### ISSUE TITLE
This page is missing description for error 0xC8000710 -939522288 hrDiskFull

### ISSUE THREAD

**Issue by someguyinbaltimore** [MicrosoftDocs/windows-itpro-docs#10870]
This page is missing description for error 0xC8000710 -939522288 hrDiskFull

I had a user having this issue and it turns out they didn't have enough space to complete the update. I found this information on this page: http://inetexplorer.mvps.org/answers/63.html .

Thanks for checking and thank you in advance for updating it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb9f2a2-76ad-8301-7d80-e33a7bb80a1b
* Version Independent ID: dd070c32-53d5-53d6-7ba2-a4361b5263bb
* Content: [Windows Update common errors and mitigation - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/windows-update-errors)
* Content Source: [windows/deployment/update/windows-update-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-errors.md)
* Product: **w10**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This article was migrated to the Windows troubleshooting content library, which is owned by another team in support. I've shared this issue with them if they want to take action on it. I'm closing this issue as there's nothing actionable for my team since this content no longer exists in this repository.
