### ISSUE TITLE
WUDOStatus

### ISSUE THREAD

**Issue by MRusbridge** [MicrosoftDocs/windows-itpro-docs#10893]
Will delivery optimization be brought over from WUDOStatus, or do we need to keep using the v1 schema for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9c4ac3-5a1b-1e7c-6062-30656a54f44f
* Version Independent ID: 5e9c4ac3-5a1b-1e7c-6062-30656a54f44f
* Content: [Update Compliance (preview) data schema - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/update-compliance-v2-schema)
* Content Source: [windows/deployment/update/update-compliance-v2-schema.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-v2-schema.md)
* Product: **w10**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Closing issue since it's become obsolete. Update Compliance v1 and v2 (now known as Windows Update for Business reports) have been completely seperated and v1 is no longer accepting new onboarding requests. [UCDOStatus](https://learn.microsoft.com/windows/deployment/update/wufb-reports-schema-ucdostatus) & [UCDOAggreatedStatus](https://learn.microsoft.com/windows/deployment/update/wufb-reports-schema-ucdoaggregatedstatus) have been added to the Windows Update for Business reports schema to replace WUDOStatus and WUDOAggregatedStatus from v1.
