### ISSUE TITLE
Whitelisting sites

### ISSUE THREAD

**Issue by Dirk-Manderin** [MicrosoftDocs/windows-itpro-docs#10922]
Is there a way to whitelist sites so this prompt doesn't display?  A good example would be the Microsoft Remote Desktop web client at https://client.wvd.microsoft.com/arm/webclient/index.html.    Entering your corporate credentials here is a perfectly valid thing to do, and users shouldn't be annoyed by the pop-up warning every time they login.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22e6cac6-7f29-c1d9-9619-667d253d2956
* Version Independent ID: 22e6cac6-7f29-c1d9-9619-667d253d2956
* Content: [Enhanced Phishing Protection in Microsoft Defender SmartScreen - Windows security](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/phishing-protection-microsoft-defender-smartscreen?tabs=gpo)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/phishing-protection-microsoft-defender-smartscreen.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/phishing-protection-microsoft-defender-smartscreen.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @v-mathavale
* Microsoft Alias: **v-mathavale**

**Comment by dariomws** [comment]
Hi @Dirk-Manderin, thank you for your feedback.

I'm not aware of an option to whitelist sites. I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/. 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request. 

Thank you for your contribution to making the Microsoft documentation better! Much appreciated!

**Comment by yogkumgit** [comment]
Thanks @Dirk-Manderin  for taking the time to provide feedback on Windows! This idea is an interesting feature, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) 
For more info, see [Send feedback to Microsoft with the Feedback Hub app] https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332. 
I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
