### ISSUE TITLE
Export-StartLayout must be run as the user

### ISSUE THREAD

**Issue by jtaylor1273** [MicrosoftDocs/windows-itpro-docs#1093]
In the Export the Start Layout section, bullet number 2 says.

"2.  At the Administrator: Windows PowerShell command prompt, enter the following command: "

When run as the administrator the start menu layout is not captured.  The line should read

2.  As the user that customized the Start Menu, open the Windows PowerShell command prompt and enter the following command:

**Comment by jdeckerms** [comment]
@jtaylor1273 I successfully exported the start layout using both Powershell (non-admin) and Powershell (admin), but using Powershell (admin) does assume that the account you used to customize and export has admin rights. Since admin permissions aren't strictly required, I'm updating the topic today to remove that part and also to clarify that the same account has to be used to customize and then to export. Thanks for pointing this out!
