### ISSUE TITLE
Would like more details when a Safeguard Hold is indicated

### ISSUE THREAD

**Issue by nighrv** [MicrosoftDocs/windows-itpro-docs#10971]
It would be nice to see what specifically is blocking an upgrade to Windows 11 from Windows 10 Pro.  If it's something as simple as removing a printer or uninstalling an application that uses VirtualBox, I can do that and reinstall those things later after the upgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5cb56ccb-bf6e-52dd-13c2-54c7d7918c41
* Version Independent ID: 41af3e1a-89c9-6a78-68b3-e8d58700c08f
* Content: [Safeguard holds - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/safeguard-holds)
* Content Source: [windows/deployment/update/safeguard-holds.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/safeguard-holds.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@nighrv Thank you for your feedback. Since this is product feedback, we recommend you post this in our main feedback portal ( https://feedbackportal.microsoft.com/) so that our Dev/product engineer can review and respond.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @nighrv  for taking the time to provide feedback on Windows! This idea is an interesting feature, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) 

For more info, see [Send feedback to Microsoft with the Feedback Hub app] https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332. 

I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
