### ISSUE TITLE
Your solutions for Manage Windows Defender Credential Guard, just does not work as expected

### ISSUE THREAD

**Issue by UdiShoshan** [MicrosoftDocs/windows-itpro-docs#11045]
On my Win11 Pro 22H2  OS Build : 22621.819
Whenever I try to connect to VPN or RDP, Windows security ask me for Credentials
It is VERY annoying.

How to avoid this "feature" ?

Thx,
Udi Shoshan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows)](https://learn.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#disable-windows-defender-credential-guard)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @UdiShoshan and thank you for reaching out. Which part of the article did you try to resolve your issue?
If the steps described do not work for you, please clarify what you tried so that I can update the documentation.

**Comment by paolomatarazzo** [comment]
Hello @UdiShoshan, I understand your frustration but without more information I cannot make any updates to the documentation. I would suggest opening a support request to have the issue investigated. Once we determine that all the steps in the article have been followed and the issue is not resolved, then we can figure out how to update the article.

**Comment by paolomatarazzo** [comment]
@UdiShoshan I closed this because it may not be an issue related to the documentation. As explained above, I suggest to open a support request so that Support can investigate further. Once we determine the root cause, then we can update the documentation accordingly. Keeping this open wouldn't help resolving the issue, as this is not a technical support channel.
