### ISSUE TITLE
ADMX_Power/DiskDCPowerDownTimeOut_2 - Does not work on Windows Business 

### ISSUE THREAD

**Issue by stevenm5781** [MicrosoftDocs/windows-itpro-docs#11068]
Hi,

This specific settings does not work on the Windows 10/11 Business SKU due to licensing error. Some machines will allow it, some wont. All machines are patched to 22H2.

MDM PolicyManager: Policy is rejected by licensing, Policy: (DiskDCPowerDownTimeOut_2), Area: (ADMX_Power), Result:(0x82B00006) Unknown Win32 Error code: 0x82b00006.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 776a0510-217f-8fc3-0a3d-53f47390acd8
* Version Independent ID: cbcd7c1b-665a-df96-c191-9f63b27a9ec7
* Content: [Policy CSP - ADMX_Power - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-power)
* Content Source: [windows/client-management/mdm/policy-csp-admx-power.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-power.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
We are completely refactoring the CSP documentation, automating the creation of the reference content based on information directly from the DDF and ADMX files. We'll migrate *some* of the relevant information from the existing content, but generally rely on the DDF/ADMX info as the source of truth. This process also involves automating the CSP applicability based on the details in the DDF. For example, see https://learn.microsoft.com/windows/client-management/mdm/policy-csp-defender which is already updated to the new format. Here's a snip of one of the applicability tables:
![image](https://user-images.githubusercontent.com/26784733/212386261-fe2c3dad-7e98-47fc-b928-563110f26eb1.png)
You'll notice that the Business SKU is missing from that list...that's because it's NOT identified in the DDF. We're working with the engineering team to determine a method to identify additional applicability categories in the future, but for now it's unfortunately out of scope because the data isn't there. So it's a known issue that we're working on, but it actually does require engineering effort to surface the data in a way that we can consume it with our automation. I'm closing this issue.
