### ISSUE TITLE
Update Compliance is gone from the Azure Marketplace, this doc should be updated to reflect that.

### ISSUE THREAD

**Issue by tomattto2** [MicrosoftDocs/windows-itpro-docs#11080]
The Update Compliance solution referenced in this doc has been removed from the Azure Marketplace.  The link to it in this doc return a 404.  Please update the doc to remove this guidance.  Thanks, you are awesome! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5549abd-da28-5d11-49c6-e66ecf5cd0b6
* Version Independent ID: 0ad6a1a2-5c75-baeb-00de-a6649592ec69
* Content: [Get started with Update Compliance - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started#add-update-compliance-to-your-azure-subscription)
* Content Source: [windows/deployment/update/update-compliance-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/update-compliance-get-started.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@tomattto2 I'll get this fixed up shortly. Thanks for FYI'ing me on it.

**Comment by mestew** [comment]
@tomattto2  Hey Matt, the Marketplace URL is no longer valid since Update Compliance is no longer accepting new onbaording since it's been deprecated. Part of this was pulling that solution. I've updated the doc to note that the instructions on the page are now just for verification puposes for existing Update Complince users.
