### ISSUE TITLE
User v. Device GPO "Enable Hello for Business"

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/windows-itpro-docs#1113]
I noticed there are separate user policies and device policies on "Enable Hello for Business".  
1. Is the end-user experience different when one of these is enabled and the other isn't?
2. Do both have to be enabled?
3. If not, what happens when a domain user logs on with only the computer policy "Use Hello for Business" enabled? What about a local user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789566d4-463a-4c64-bf89-fb963ac29f80
* Version Independent ID: 02946732-bb29-d8e6-cedd-7f5e508f8798
* Content: [Manage Windows Hello in your organization (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-manage-in-organization)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-manage-in-organization.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Hi @thedrum808 , as with most policies that duplicate across user and computer configuration, the main intent is to allow admins the flexibility of targeting users or computers with the policy, dependent on their scenario.

In some cases, you'd want to enable a policy for a specific set of users, while in other cases, it would be more fitting to target a specific set of computers\devices, and enable it for everybody who is using them.

**Comment by thedrum808** [comment]
@DaniHalfin - Thanks, that clears it up a bit. So there's no functional difference between enabling one v. the other, other than targeting purposes. 

Thanks!

**Comment by DaniHalfin** [comment]
That's right. Just to reiterate - targeting the computer will enable it for anyone that signs in to that device, while targeting a user means it'll be enabled for that user on any device. You can call that a functional difference, but it's a functional difference on the group policy level, rather than on the feature (WHfB) level. 


If you next question is what happens when these collide, I can expand on that as well :)

**Comment by thedrum808** [comment]
@DaniHalfin can you elaborate?

**Comment by DaniHalfin** [comment]
The short version is whichever applies later wins, meaning that the user configuration will generally win over the computer configuration (there are some exceptions).

It's worth noting that enabled vs "not configured" is not contradicting. Only enabled vs disabled is.
This is really a lot more complex, since there are multiple level of depth to processing group policy on a client machine, but the simplest answer is that the user configuration wins in most cases.

For more info, read this not-so-short blog post (first hit I got for GP client processing) : https://blogs.technet.microsoft.com/musings_of_a_technical_tam/2012/02/22/group-policy-basics-part-3-how-clients-process-gpos/

**Comment by thedrum808** [comment]
Awesome, thanks for the clarification. Feel free to close this topic.
