### ISSUE TITLE
Exportable\Importable Pin Groups

### ISSUE THREAD

**Issue by AdamFlowers** [MicrosoftDocs/windows-itpro-docs#11278]
While Pin Groups can be created in the Win11 start menu, they are not shown in the exported JSON and therefore do not get imported when the JSON is deployed out. Either the feature needs to be added or the documentation needs to be updated to reflect what exactly is exportable so that enterprise deployments can be properly planned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5508bf53-3aa5-7ce1-de3b-7da45b4b495b
* Version Independent ID: 86918067-b0b6-f0f3-a0a8-ece6c8f13c94
* Content: [Add or remove pinned apps on the Start menu in Windows 11 - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/customize-start-menu-layout-windows-11)
* Content Source: [windows/configuration/customize-start-menu-layout-windows-11.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/customize-start-menu-layout-windows-11.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by msbemba** [comment]
@AdamFlowers Thank you for your feedback. This is a feature request/design change and needs to be routed to the Product group. I'd recommend you post the feedback on our main feedback portal ( https://feedbackportal.microsoft.com/ ) so that the Dev/product team can assist.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @AdamFlowers  for taking the time to provide feedback on Windows! This idea is an interesting feature, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) 
For more info, see [Send feedback to Microsoft with the Feedback Hub app] https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332. 
I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
