### ISSUE TITLE
Is this required on Windows 10 PCs?

### ISSUE THREAD

**Issue by immanuelbaker** [MicrosoftDocs/windows-itpro-docs#1128]
We will be using Windows Upgrade Readiness for our Windows 10 In place Upgrades (e.g. 1607 to 1709).

We are aware that Windows 10 PCs can be configured for telemetry using the built in group policy option.

Do these PC still need to run this script? If so, will they also be required to run it periodically (i.e. every 30 days)?

We are confused as there is a fair bit of contradiction on the internet regarding this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f029a728-1f53-4576-a6ca-8a19a92626e6
* Version Independent ID: 85f27ad5-84e2-0787-082f-59d2d66c99b5
* Content: [Upgrade Readiness deployment script (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-deployment-script)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-deployment-script.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-deployment-script.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
I apologize for the delay.

Yes, you should run the script.

You have to set the diagnostic data levels by using Group Policy, MDM (Intune), or ConfigMgr; then the script verifies that the levels are set as needed for Upgrade Readiness to work, as well as many other useful things like presence of key updates and verifying accessibilty of endpoints. It also starts the inventory scan.

It is useful, though not strictly required, to re-run the script periodically in order to catch any changes in the environment.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@immanuelbaker - From our understanding, the issue you raised has been answered by jaimeo. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
