### ISSUE TITLE
Why its only possible with phones? Can't you just enable all bluetooth devices?

### ISSUE THREAD

**Issue by Kulturn1lpf3rd** [MicrosoftDocs/windows-itpro-docs#11301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31b8df15-a1c0-99c7-4d5d-7c0e450b909a
* Version Independent ID: 0eafe3aa-09fb-fd82-fd36-95e4b576f52c
* Content: [Dynamic lock](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-dynamic-lock)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-dynamic-lock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-dynamic-lock.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by msbemba** [comment]
@Kulturn1lpf3rd Thank you for your feedback. That is a great idea and we recommend you post this directly on our main feedback portal- https://feedbackportal.microsoft.com/  as our Dev/ Product engineers can look at it and respond. This feedback section is for corrections or modifications in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
Thanks @Kulturn1lpf3rd  for taking the time to provide feedback on Windows! This idea is an interesting feature, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) 
For more info, see [Send feedback to Microsoft with the Feedback Hub app] https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332. 
I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by paolomatarazzo** [comment]
under bluetooth you can configure a class of devices, including wearables. it's not limited to phones...
