### ISSUE TITLE
ExcludedProcesses | ExcludedPath | ExcludedExrensions

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#11328]
Hello,

Found possible bugs with Defender ExcludedProcesses | ExcludedPath | ExcludedExrensions and with a document.

1. It is not written what can be added in the ExcludedProcesses/ExcludedPath/ExcludedExrensions. Like which format is supported, what can be added here
2. If using Intune | Endpoint Security | Antivirus policy, add into those fields 406 rand char guid values, then the RealTimeProtection will return False
3. Using Intune Compliance policy, which checks if RealTimeProtection is ON -> will result in Failure and set the device as non-compliant
4. By Removing entries from Intune | Endpoint Security | Antivirus policy or unassign policy, entries are still stuck in the Registry.

Example:
![image](https://user-images.githubusercontent.com/39700914/217569779-7f516323-d76c-4b1c-8541-1fdf6ff5029f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#excludedprocesses)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@lightupdifire We've updated the descriptions for these three policies, the changes should be live later today or next week and this issue will be closed.

As for potential bugs, I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.
