### ISSUE TITLE
Prohibit Mispelled

### ISSUE THREAD

**Issue by pkutz5700** [MicrosoftDocs/windows-itpro-docs#11351]
ProhitConnectionToNonDomainNetworksWhenConnectedToDomainAuthenticatedNetwork
should be spelled
ProhibitConnectionToNonDomainNetworksWhenConnectedToDomainAuthenticatedNetwork

Prohibit
On the linked header.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad2d7264-e0a4-ead4-d110-08b5b915ef2e
* Version Independent ID: 0e7961d5-6bdf-2765-7fdc-20fc469122a4
* Content: [WindowsConnectionManager Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowsconnectionmanager)
* Content Source: [windows/client-management/mdm/policy-csp-windowsconnectionmanager.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-windowsconnectionmanager.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by vinaypamnani-msft** [comment]
@pkutz5700 This CSP doc is generated automatically and unfortunately, the typo is in the actual policy Name itself. I would suggest that you submit feedback for the policy name itself via the Feedback Hub app so it can be fixed in the Windows code. For more information, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
