### ISSUE TITLE
Lost Bitlocker key process

### ISSUE THREAD

**Issue by uhurusurfa** [MicrosoftDocs/windows-itpro-docs#11353]
There is no information on what to do if the Bitlocker recovery key is lost and requires a re-install. How do you get the Windows product key for the OS in this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e21c26e-1320-04e1-d103-e64751235f9f
* Version Independent ID: 48b4da0f-2bb0-98d8-20f9-acd30a0e4a34
* Content: [BitLocker recovery guide](https://learn.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
This article is about recovery from a BitLocker lockout if you do have the key or other method to authenticate. It isn't about what to do if the key is lost or you do not have access to the key, nor is it about reinstalling Windows, nor how to obtain a Windows product key. In other words, the topics you are suggesting are irrelevant to this article. There are many other articles regarding installing Windows and Windows product keys that do cover the subject.

FYI, for most of the major OEMs on devices manufactured within the last few years, obtaining a Windows product key is not necessary because the product key is stored in the firmware/BIOS of the device. When Windows is installed, Windows will automatically look for this product key in the firmware/BIOS of the device and automatically use it if found. This makes needing to manually enter a product key unnecessary on most modern devices.
