### ISSUE TITLE
Is there a documantation about line continuation on Win11 Command Prompt?

### ISSUE THREAD

**Issue by songyuc** [MicrosoftDocs/windows-itpro-docs#11397]
I have known that a multi-line command of Win11 Command Prompt can be separated with the caret (`), but it seems to have not been explicitly described in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 983a1d4b-d026-ab96-5db2-f0edcf190b7a
* Version Independent ID: 983a1d4b-d026-ab96-5db2-f0edcf190b7a
* Content: [Windows 11 overview for administrators - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/windows-11-overview)
* Content Source: [windows/whats-new/windows-11-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-overview.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @songyuc, thanks for the feedback. We don't currently have any documentation on the Windows Command prompt, and no plans to add any.

## Note 1

For Windows 11 command prompt, the caret `^` provides a line wrap at the command prompt or in a batch script. for example:

```cmd
C:\Users\aaroncz>ping localhost ^
More? -t
```

is functionally the same as `ping localhost -t`

## Note 2

The tick mark that you noted ( \` ) is the line continuation character for PowerShell.

## Note 3

I'd recommend switching to PowerShell instead of command line and batch files. 😄
