### ISSUE TITLE
There is no replacement for what WIP did!

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/windows-itpro-docs#11425]
Microsoft has made a grave error in deprecating WIP since there is no comparable replacement for protecting all corporate data on Windows 10/11 devices, particularly personally owned ones that doesn't require classifying everything with AIP--a burden on everyone just to handle a use case that was previously handled by WIP.

WIP was simple and comprehensive. All other technologies do not address the MAM features that are now only available on Android and iOS devices. 

Do you realize that you've now made **Windows devices secondhand citizens** when it comes to protecting corporate data on endpoint devices and supporting selective wipe on personally owned Windows 10/11 devices when users depart an organization?

Just an awful business decision.

If I'm wrong tell me how you use other products to replicate the protection and functionality offered by WIP and perhaps I'll change my mind...

Bill

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d016c711-b1f4-668e-adbc-ff6911965851
* Version Independent ID: 64b2a1a4-1efe-35da-721e-7cbb0b1c684e
* Content: [Protect your enterprise data using Windows Information Protection](https://learn.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hiya @wcneumann219 ! Blast from the past 😄 

Thanks for taking the time to provide feedback on Windows! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by aczechowski** [comment]
Oh I should also add - I *did* share your feedback with the product managers. But no promises on any outcomes. I do suggest sending feedback through the Feedback Hub as I mentioned.
