### ISSUE TITLE
Why is there no content on how to configure things for AD FS

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/windows-itpro-docs#11479]
So looking at the content for Configure AD FS for Hybrid deployments it seems to be lacking a whole lot of configuration steps when compared to the on-premises certificate trust configuration.

It actually calls out the permissions required on the certificate templates, and how to setup the Enrollment Agent certificate and how to validate that it got the RA certificate.

Also the Hybrid Cert Trust talks about using a Service Account for AD FS rather than gMSA in the other one.  Is there a reason for this?

If the reason for not really covering AD FS configuration is because it is expected that the AD FS is already being used for Azure Federation setup then it would be good to call this out, as well as pointing to content on how to do this!  You should not assume that the tenant is already federated.  I do not see anywhere it states that the Azure tenant needs to be federated for this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24d7753d-30e1-db13-429a-c0b4eaf2c9c5
* Version Independent ID: 5be668ea-fc9d-0fb5-585d-4f5d5575b416
* Content: [Configure Active Directory Federation Services in a hybrid certificate trust model](https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Hello @RobG-MSFT, this article describes how to configure AD FS specifically for the WHFB deployment model. It's not intended to cover how to deploy AD FS from scratch or how to configure device registration. Those are considered prerequisites. Since the content is already described in other articles, it's called out in the prerequisites section. 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/74918781/234119138-ce6f951a-ac61-4911-a2c2-ea4e07a84c35.png">

Regarding the observation about gMSA, I didn't get a chance to test and refresh that part of documentation to use gMSA. If you already have the process outlined, please feel free to make a contribution to the deployment guide.
