### ISSUE TITLE
Topic is titled "what's new", but the only thing you won't find out is what's new

### ISSUE THREAD

**Issue by Oobiewan** [MicrosoftDocs/windows-itpro-docs#11488]
The article is titled "what's new in..." but the only thing it mentions about what's new is "quality improvements to the overall Windows experience in existing feature areas". What these "quality" improvements are is not mentioned either, neither can I find a link to the list of these quality improvements. Otherwise the article is talking about servicing schedule, update tools, and channels, which is "update information" or something like that, not "what's new".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26b9d6c3-b5bc-129c-e985-ca03b43b3235
* Version Independent ID: 26b9d6c3-b5bc-129c-e985-ca03b43b3235
* Content: [What's new in Windows 10, version 22H2 for IT pros - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-22h2)
* Content Source: [windows/whats-new/whats-new-windows-10-version-22H2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/whats-new-windows-10-version-22H2.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Oobiewan for the feedback. We originally didn't have this article because as the [release blog](https://blogs.windows.com/windowsexperience/2022/10/18/how-to-get-the-windows-10-2022-update/) states (which we copied verbatim to this article): *Windows 10, version 22H2 is a scoped release focused on quality improvements to the overall Windows experience in existing feature areas such as quality, productivity and security.* In other words, no new features. But we got enough feedback from customers about the lack of a "what's new" article for Windows 10, version 22H2, that we decided to create the article to help reinforce that message. 

As for the list of quality improvements, as the article states:

> To learn more about the status of the Windows 10, version 22H2 rollout, known issues, and build information, see [Windows 10 release information](https://learn.microsoft.com/windows/release-health/release-information).

From that article you can see the updates to Windows 10, and if you expand the table of contents on the left side, you'll see other articles for [Known issues](https://learn.microsoft.com/windows/release-health/status-windows-10-22h2) and [Resolved issues](https://learn.microsoft.com/windows/release-health/resolved-issues-windows-10-22h2).
