### ISSUE TITLE
Please share vulnerable drivers on Virustotal

### ISSUE THREAD

**Issue by goosvorbook** [MicrosoftDocs/windows-itpro-docs#11499]
Hi Microsoft,

To perform some additional research and generate more Indicators of Compromise, it would be nice if you could share the source files with platforms such as Virustotal.

Right now, some of the items in the XML have zero hits on virustotal, so it is hard to analyze them .
E.g. 

[WinIO32B.sys](https://www.virustotal.com/gui/search/f1c8c3926d0370459a1b7f0cf3d17b22ff9d0c7f)
[netfilterdrv.sys](https://www.virustotal.com/gui/search/e74b6dda8bc53bc687fc21218bd34062a78d8467)
[bandai.sys](https://www.virustotal.com/gui/search/0f780b7ada5dd8464d9f2cc537d973f5ac804e9c)
etc.

It would help the security community if you could share all files, at least on virustotal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8740b8-c1f2-4b88-3d4d-66cdbf20215f
* Version Independent ID: 7986a684-b35d-06bd-be30-dfca9923cb9c
* Content: [Microsoft recommended driver block rules (Windows)](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jgeurten
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @goosvorbook for taking the time to provide feedback on Windows! This idea is an interesting feature, and I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
