### ISSUE TITLE
"A general error occurred that is not covered by a more specific error code" while Set-CimInstance for Multi app kiosk

### ISSUE THREAD

**Issue by Hoto-Cocoa** [MicrosoftDocs/windows-itpro-docs#11553]
I tried provisioning multi app kiosk for our store.

I tried this command:
```
$namespaceName="root\cimv2\mdm\dmmap"
$className="MDM_AssignedAccess"
$obj = Get-CimInstance -Namespace $namespaceName -ClassName $className
Add-Type -AssemblyName System.Web
$obj.Configuration = [System.Web.HttpUtility]::HtmlEncode(@"
<?xml version="1.0" encoding="utf-8" ?>
<AssignedAccessConfiguration
xmlns="http://schemas.microsoft.com/AssignedAccess/2017/config"
xmlns:win11="http://schemas.microsoft.com/AssignedAccess/2022/config">
    <Profiles>
        <Profile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}">
            <AllAppsList>
                <AllowedApps>
                    <App AppUserModelId="Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"/>
                </AllowedApps>
            </AllAppsList>
            <win11:StartPins>
                <![CDATA[
                { "pinnedList":[
                    { "appUserModelId":"Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge" }
                ] }
                ]]>
            </win11:StartPins>
            <Taskbar ShowTaskbar="true"/>
        </Profile>
    </Profiles>
    <Configs>
        <Config>
            <Account>KioskUser</Account>
            <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
        </Config>
    </Configs>
</AssignedAccessConfiguration>
"@)

Set-CimInstance -CimInstance $obj
```

And I got this error:
```
Set-CimInstance : 보다 구체적인 오류 코드가 적용되지 않는 일반 오류가 발생했습니다. (A general error occurred that is not covered by a more specific error code.)
위치 줄:1 문자:1
+ Set-CimInstance -CimInstance $obj
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MDM_AssignedAcc..../Vendor/MSFT"):CimInstance) [Set-CimInstance], CimExce
   ption
    + FullyQualifiedErrorId : MI RESULT 1,Microsoft.Management.Infrastructure.CimCmdlets.SetCimInstanceCommand
```

I tried It on multiple devices and multiple versions of Windows. Of course, I updated Windows to latest version, even reinstalled with latest ISO.

At first I tried multiple apps, but posted XML is single, because Just I wanted know what is wrong. But AllowedApps was not the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6eac98f-6a12-c1ae-1ed3-485ac97e8fb3
* Version Independent ID: a6eac98f-6a12-c1ae-1ed3-485ac97e8fb3
* Content: [Set up a multi-app kiosk on Windows 11 - Configure Windows](https://learn.microsoft.com/en-us/windows/configuration/lock-down-windows-11-to-specific-apps)
* Content Source: [windows/configuration/lock-down-windows-11-to-specific-apps.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/lock-down-windows-11-to-specific-apps.md)
* Product: **windows-client**
* Technology: **itpro-configure**
* GitHub Login: @lizgt2000
* Microsoft Alias: **lizlong**

**Comment by Hoto-Cocoa** [comment]
It suddenly fixed after reboot many time.

**Comment by Hoto-Cocoa** [comment]
As noted in [this page](https://learn.microsoft.com/en-us/windows/configuration/kiosk-mdm-bridge), the command should work in Windows 10. However, It doesn't work at my multiple Windows 10 devices. I used command that copied from linked page, but not works. Is that document wrong?

**Comment by theemstra** [comment]
The mentioned example XML on [this tutorial](https://sccmentor.com/2019/10/26/windows-10-kiosk-mode-without-intune-notes-from-the-field/) seems to inject for me with no error, though it uses the W10 start layout instead of the new W11 method, which is mentioned in this documentation article.

The XML example as mentioned in [docs](https://learn.microsoft.com/en-us/windows/configuration/lock-down-windows-11-to-specific-apps) does not work. Even with an empty app list, any content within the <win11:StartPins> results in the same error as OP.

This specific element is what we're on about:
```
<win11:StartPins>
        <![CDATA[  
          { "pinnedList":[
            {"packagedAppId":"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"},
            {"packagedAppId":"Microsoft.Windows.Photos_8wekyb3d8bbwe!App"},
            {"packagedAppId":"Microsoft.BingWeather_8wekyb3d8bbwe!App"},
            {"desktopAppLink":"%ALLUSERSPROFILE%\\Microsoft\\Windows\\StartMenu\\Programs\\Accessories\\Paint.lnk"},
            {"desktopAppLink":"%APPDATA%\\Microsoft\\Windows\\StartMenu\\Programs\\Accessories\\Notepad.lnk"}
          ] }
        ]]>
</win11:StartPins>
```
Full example as used by us in our test VM: [inject_kiosk_mode_powershell.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/11775836/inject_kiosk_mode_powershell.txt)

Reproduce by:
1. Download PS Tools
2. Command: pstools\PsExec.exe -i -s cmd
3. Command: powershell
4. Rename inject_kiosk_mode_powershell.txt to inject.ps1
5. Run .\inject.ps1

Tested on clean W11 22H2 22621.1702 installation.

What I did find is a [Technet](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/multi-app-kiosk-mode-now-available-in-windows-11/ba-p/3845558) article explaining it's only become available now. Maybe it was published in the documentation before and only has become available very recently?

**Comment by theemstra** [comment]
We found out that the error is caused by a missing update ["Windows Configuration Update"](https://support.microsoft.com/en-us/topic/may-24-2023-windows-configuration-update-cae8524a-4b62-4d38-bb67-f070bd282fff), it would only run after enabling the 'Get updates first' setting in Windows Updates. 

Attached an example of what we got it to work with.
[Injecteer kiosk mode.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/11776388/Injecteer.kiosk.mode.txt)

We ended up removing the Users group and adding the user to the guest group, though it will still cause some trouble here because they won't be able to download any files for (for ex.) Citrix. We did expect it would wipe the browsing history etc, but it didn't do anything.

**Comment by theemstra** [comment]
After googling for a long time I found a rant on a website that summarizes my past few days too, exactly the same issues we've had in this regard: https://www.aftersixcomputers.com/i-loath-bad-documentation/

**Comment by snowmountainer** [comment]
Hello

In my test environment I could see the same error situation.

After a long search, I realized that the "Multi app kiosk" will only be activated with the "optional non-security preview release (27th June) for Windows 11, version 22H2".
**Source:** https://www.anoopcnair.com/first-windows-11-controlled-feature-rollout/

However, the "Moments 3 feature" can already be activated for tests with the "Vivetool".
**Source:** https://pureinfotech.com/install-moment-3-feature-drop-update-windows-11/

After activation ... 

`vivetool /enable /id:41655236`

...and a restart I was able to set the required configuration...

`<![CDATA[{ "pinnedList":[
    { "desktopAppLink": "%ALLUSERSPROFILE%\\Microsoft\\Windows\\Start Menu\\Programs\\Remote Desktop Connection.lnk" },
    { "desktopAppLink": "%ALLUSERSPROFILE%\\Microsoft\\Windows\\Start Menu\\Programs\\Restart.lnk" },
    { "desktopAppLink": "%ALLUSERSPROFILE%\\Microsoft\\Windows\\Start Menu\\Programs\\Shutdown.lnk" }
    ] }
]]>
`

...without any problems.

**Comment by Mattia-Nocerino** [comment]
I'm still not able to add multiapp kiosk on windows 11, latest update.

Can anyone provide a bare minimum working XML? Cause I'm starting to think that this won't work whatsoever

**Comment by Glader222** [comment]
Hello, i got this to work on the latest Windows 11 build, building from the Sample Assigned Access XML that Microsoft has provided for Win 11.  

To get it to work with the default sample that Microsoft has provided: 
```
<Config>
      <Account>MultiAppKioskUser</Account>
      <DefaultProfile Id="{9A2A490F-10F6-4764-974A-43B19E722C23}"/>
    </Config>
```
You have to create a user in computer management beforehand named "MultiAppKioskUser"

In my case i wanted an autologin feature to work. So i instead went with this: 

```
<Config>
      <!--AutoLogon account-->
      <AutoLogonAccount />
      <DefaultProfile Id="{814B6409-8C51-4EE2-95F8-DB39B70F5F68}" />
    </Config>
```

This automatically creates the kioskuser and the autologin actually works.

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
