### ISSUE TITLE
Formatting Information

### ISSUE THREAD

**Issue by MasterBear7** [MicrosoftDocs/windows-itpro-docs#1161]
[Enter feedback here]Formatting Information:   I'm a bit of a stickler folks, but as I grew up, info was presented in a very different way.  A program presented for download was presented with the most up-to-date version available, and not referencing people to some location farther down the page. 

Additionally, basic documentation on what the program is, what is does, how it does it, etc. should be near the front or at least be at an easily referenced subsection for first time users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag#)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by greg-lindsay** [comment]
I'm not sure what is actionable here. It's possible that the page has been updated since the issue was created and the problem no longer exists. I apologize for not seeing this issue until now. I've just updated my search and notification process for issues in the 1000 or so pages that I own and they shouldn't escape me so long now.

To the OP if you can provide a list of specifically what you think should be changed on the page, I'll try to accommodate. As I see the page currently, the most up to date version of this tool is presented along with what it does.
