### ISSUE TITLE
Unlocking computer

### ISSUE THREAD

**Issue by Git-Goner** [MicrosoftDocs/windows-itpro-docs#11628]
I can't seem to find any documentation on this. Is there any way to configure the federated sign in to remember the last signed in user, or to carry over the email address of the user? Right now the process is a bit wonky as the user types in longemailaddress@longschooldomain.com and then has to do it over again.

When unlocking the computer they again have to enter their full email address, which is a bit of a hassle. 

Is there any option to allow cached or offline login? Currently unlocking the computer requires internet access.

**Comment by paolomatarazzo** [comment]
Hello @Git-Goner, there's no way to remember the last signed in user since the login happens at the IdP via web (hence the requirement of Internet connectivity). For 1:1 configuration, Windows will remember the IdP, redirecting to the IdP login page. The IdP can offer a multitude of login option. For example, if you use QU code you may need a simple identifier like student ID instead of full UPN.
