### ISSUE TITLE
Format and Eject Removable Media should be integer not string

### ISSUE THREAD

**Issue by sweenster247** [MicrosoftDocs/windows-itpro-docs#11638]
[devices_allowedtoformatandejectremovablemedia](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-LocalPoliciesSecurityOptions?WT.mc_id=Portal-Microsoft_Intune_Workflows#devices_allowedtoformatandejectremovablemedia). For those auditing CIS L1 2.3.4.1.2

0 | Only administrators of the computer.
1 | Only administrators and power users.
2 | Only administrators and the local current user. (interactive)

Intune settings catalog also allows for the string input which does accept the various integer values.

Full disclosure, I'm newer at auditing this but looks like there might be a discrepancy here. 

(admin edit: adding article metadata for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [LocalPoliciesSecurityOptions Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-LocalPoliciesSecurityOptions#devices_allowedtoformatandejectremovablemedia)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @sweenster247 for the feedback. Most of the CSP content is automated pulling info from the DDF and/or ADMX XML files in the OS itself. Especially things like data types I think come directly from the DDF. Especially since you're seeing that in the Intune settings catalog, which also pulls from the DDF. So it's actually an OS bug that needs to be filed via the Feedback Hub for the engineering team to fix in the DDF, then that change will flow through to the Intune settings catalog and the CSP documentation.

For more info, see https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference

**Comment by sweenster247** [comment]
@aczechowski - Wow! Thank you for the info! I learned something new today!
