### ISSUE TITLE
The "more information" link redirects to a broken page

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/windows-itpro-docs#11671]
The More information is available at< link in this article redirects to a broken link :

https://go.microsoft.com/fwlink/?linkid=2116430%3E

Can we please get this fixed to the correct link?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfb90783-6580-dcf3-cb44-ff304ee66d74
* Version Independent ID: cfb90783-6580-dcf3-cb44-ff304ee66d74
* Content: [ADMX_sam Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-sam)
* Content Source: [windows/client-management/mdm/policy-csp-admx-sam.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-sam.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by RAJU2529** [comment]
Tomorrow I will add new link

**Comment by aczechowski** [comment]
I commented some of this on the linked PR:

For more info, see [Contributing to the CSP reference articles](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference) - it explains more.

The link in question exists in the non-editable description that comes from the ADMX. So if I accept your change, it will revert back in a week or so when the automation reruns. 

@tomdan-MSFT you should [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). Making sure to note that the string needs to change in the source ADMX, which is where that policy description comes from. That feedback should go to the engineering team who would need to file a bug to fix the string in the ADMX code.

I can also fix fwlink 2116430 so that it points to https://support.microsoft.com/windows/update-your-security-processor-tpm-firmware-94205cbc-a492-8d79-cc55-1ecd6b0a8022, so that will help as well.

(NOTE: Vinay is out right now, so I don't know if he had something else in mind...)

**Comment by aczechowski** [comment]
The fwlink is updated, and as I previously mentioned, feedback otherwise should go to the Feedback Hub for the engineering team. I'm closing this issue.
