### ISSUE TITLE
TPM Version Disagrees with other Microsoft Pages

### ISSUE THREAD

**Issue by ketchup201** [MicrosoftDocs/windows-itpro-docs#11672]
This page states that the minimum TPM version is 2.0.
In https://learn.microsoft.com/en-us/windows/whats-new/windows-11-requirements
it states that the minimum TPM version is 1.2.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db554047-b9ca-f5c9-d79f-4a70686a66db
* Version Independent ID: e05bf4bc-ab29-9d32-bd53-5ca3e70aba1b
* Content: [Windows 11 requirements - What's new in Windows](https://learn.microsoft.com/en-us/windows/whats-new/windows-11-requirements)
* Content Source: [windows/whats-new/windows-11-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/whats-new/windows-11-requirements.md)
* Product: **windows-client**
* Technology: **itpro-fundamentals**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Hi @ketchup201  
I'm not seeing where  v1.2 for TPM is listed in this page: 
https://learn.microsoft.com/en-us/windows/whats-new/windows-11-requirements
Can you point me to the line where you see it, or was there another URL you meant to paste into this issue?

**Comment by ketchup201** [comment]
OMG copy paste error! Thanks for noticing and responding! I meant to use THIS link:
https://support.microsoft.com/en-us/windows/ways-to-install-windows-11-e0edbbfb-cfc5-4011-868b-2ce77ac7c70e

**Comment by mestew** [comment]
Ok. That article pretty clearly calls out that you can reghack your way around the TPM v2.0 requirement, but it's totally not recommended. There is a warning link noted right above the registry change that calls out the risks of doing so (security updates may not function, compatability issues, etc.): https://support.microsoft.com/en-us/windows/installing-windows-11-on-devices-that-don-t-meet-minimum-system-requirements-0b2dc4a2-5933-4ad4-9c09-ef0a331518f1  

Changing the registry to bypass the TPM version requirement is primarily meant for lab/testing situations. I'm closing this issue since the Windows 11 requirements doc doesn't require an update. Thanks much.

**Comment by ketchup201** [comment]
That page says that 1.2 is a minimum requirement for Windows, but I totally understand why you said what you did. 
Thanks so much for looking into it so fast! Also, ugh that means my work PC will need to be replaced. Sigh!
