### ISSUE TITLE
"Your Phone" / "Link to windows"

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windows-itpro-docs#11681]
A lot of this documentation seems outdated and often refer to the old app for this feature in Android, but now days this functionality is built-in and accessed through Settings on the phone.

Example: [Phone Link app requirements and setup](https://support.microsoft.com/en-us/topic/phone-link-app-requirements-and-setup-cd2a1ee7-75a7-66a6-9d4e-bf22e735f9e3)

**Comment by aczechowski** [comment]
Thanks @Bartolomeus-649 for sharing the feedback. While there is some overlap between who works on content between support.microsoft.com and learn.microsoft.com for Windows, it's not entirely. This specific feedback system is for learn.microsoft.com, and specifically Windows client for IT pros. That support article is actually owned by another team. We do have a broader project underway to address old/stale content across both sites, so at some point in the future we'll likely catch those articles regarding phone link. I'll pass this along to the other team, but closing this issue otherwise.
