### ISSUE TITLE
Windows 11 and WDAC

### ISSUE THREAD

**Issue by bdel83** [MicrosoftDocs/windows-itpro-docs#11702]
On Windows 11, you seem to only be able to use 22 custom WDAC policies.

Even when you turn off smart app control. Using the CITool only shows the Default Driver policy in effect in addition to custom policies.

However, using 23 custom policies appears to result in blue screen errors.

Is this a known issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84501a94-f40e-9624-32ce-70324e20f9ce
* Version Independent ID: 84501a94-f40e-9624-32ce-70324e20f9ce
* Content: [Inbox WDAC policies - Windows Security](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/operations/inbox-wdac-policies)
* Content Source: [windows/security/application-security/application-control/windows-defender-application-control/operations/inbox-wdac-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/application-security/application-control/windows-defender-application-control/operations/inbox-wdac-policies.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @jsuther1974
* Microsoft Alias: **jsuther**

**Comment by aczechowski** [comment]
There's one listed in the WDAC known issues article for [Boot stop failure (blue screen) occurs if more than 32 policies are active](https://learn.microsoft.com/windows/security/application-security/application-control/windows-defender-application-control/operations/known-issues#boot-stop-failure-blue-screen-occurs-if-more-than-32-policies-are-active), which @jsuther1974 [just added back in April](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/ef394d0bd5c9171225aaecb420c5600b1c8a61b1#diff-658ae51b37ffc836b103b33b4244015ec304c03bbe17fb4944afe49ed699ba21).

So unless Jeffrey wants to comment further, I think the best option is to refer @bdel83 to other options to provide the best level of support for this question:

- Post to [Windows on Q&A](https://docs.microsoft.com/answers/products/windows). These are moderated by community members who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://support.microsoft.com/windows) to search for the issue, or open a case with professional support.
- Contact your Microsoft Unified Support team, such as a Customer Engineer or Customer Success Account Manager.

Alternative, you can [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) to it directly into the hands of the engineering team. I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress.

I'm closing this issue as I don't think there's anything actionable for docs at this time.

**Comment by bdel83** [comment]
I disagree. It may not be a bug, but the documentation should make it clear that the mere presence of the Inbox WDAC files counts towards the 32 policy limit. The CITool may only show that the Drivers policy is active, but this is misleading. There are 3 x policy files present in the EFI partition, 6 x policy files for WDAC Inbox policies which appear to be inactive present in the CIPolicies\Acive folder, plus the drivers policy. What this means is that you can only run 22 x custom policy files of your own. The documentation needs to reflect this and highlight if there is a technique to remove or reduce the quantity of the inbox policy files.

**Comment by bdel83** [comment]
Update:
- It seems like a bug or an issue.
- Custom WDAC policy quantity of 18 and you will kill a new Win11 build, or one upgraded from Win10 where the policies worked fine.
- If you reduce the policy count to 10, the Win11 build remains stable.
- Starting with single base policy and gradually working your way up to 22 custom policies for some reason seemed to hold yesterday.
- I have logged a bug via the feedback app on Windows 11.

**Comment by bdel83** [comment]
Update:
* Failure is the best teacher.
* One of the supplemental policies was actually a base.
* I am still not sure why Win10 didn't have any issue with it, but Win11 did.
* The only thing I can come up with, without spending further time investigating is that perhaps Win10 honours the "Boot audit failure" in the initial base and I was accidentally in audit mode without realizing, but Win11 overrides with defaults from the secondary base. Particularly since the secondary base was not modelled on the "AllowAll" template and would have override the "AllowMicrosoft" rules from the first base.
