### ISSUE TITLE
CPL_Personalization_ForceDefaultLockScreen should have 'Pro' and 'Windows SE' Editions set to ❌ instead of ✅

### ISSUE THREAD

**Issue by Borgquite** [MicrosoftDocs/windows-itpro-docs#11734]
According to the note for CPL_Personalization_ForceDefaultLockScreen, 'This setting only applies to Enterprise, Education, and Server SKUs.'

The 'Editions' section for this policy should reflect this - 'Pro' and 'Windows SE' show as ❌instead of ✅ to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fde44969-534c-2e4f-c173-2b2ec4aa91b0
* Version Independent ID: 08f6f33b-f6b0-d136-d0e1-c1db33975ee3
* Content: [ADMX_ControlPanelDisplay Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-admx-controlpaneldisplay)
* Content Source: [windows/client-management/mdm/policy-csp-admx-controlpaneldisplay.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-admx-controlpaneldisplay.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @Borgquite for the feedback. 🤔 The [applicability info comes from the DDF](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference#feedback-for-policy-applicability), and the description comes from the ADMX - if you look at the corresponding group policy, it has the same note about editions. Since this content is now automated, the feedback needs to go to the engineering team via the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) - they need to determine which one is correct and then fix the other. Once that change happens in either the DDF or ADMX, then it will flow through to the docs eventually.

I'm closing this issue as there's nothing actionable for docs at this time. (For more info on automation of CSP docs, see [Contributing to the CSP reference articles](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference).)

**Comment by Borgquite** [comment]
@aczechowski I've submitted it to the Feedback Hub https://aka.ms/AAmx3nb

(In my experience the Feedback Hub is an utter black hole by the way - no confidence that anyone even looks at it. Oh well.)
