### ISSUE TITLE
Minimum password age

### ISSUE THREAD

**Issue by matchups** [MicrosoftDocs/windows-itpro-docs#11743]
It would be really nice if, when a user is unable to change their password due to this setting, that they were informed of this, rather than being told that the password does not conform to length, complexity, or history requirements.  We've wasted a lot of time for several people tracking down this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98f30760-4999-dcb1-26da-097477dc31bc
* Version Independent ID: 6cef6a81-a4aa-bb3b-4f1c-78cf98aba958
* Content: [Minimum password age - Windows Security](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-age)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/minimum-password-age.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @matchups for taking the time to provide feedback on Windows! I want to make sure it gets directly into the hands of the engineering team. Fortunately, we've got dedicated channels for that very purpose. :) For more info, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. I'm closing this issue as there's nothing actionable for docs at this time.
