### ISSUE TITLE
New services with Windows 2022

### ISSUE THREAD

**Issue by BO0168** [MicrosoftDocs/windows-itpro-docs#11742]
There's 3 new user services coming with Windows 2022 (desktop experience enabled):
CredentialEnrollmentManagerUserSvc
DeviceAssociationBrokerSvc
UdkUserSvc
What are the description of those services ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaa890d7-00c3-8e74-54af-3f3aa2aeb4c4
* Version Independent ID: 0ad75b5c-a4e1-a954-163a-fd8922b8f760
* Content: [Per-user services - Windows Application Management](https://learn.microsoft.com/en-us/windows/application-management/per-user-services-in-windows)
* Content Source: [windows/application-management/per-user-services-in-windows.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/application-management/per-user-services-in-windows.md)
* Product: **windows-client**
* Technology: **itpro-apps**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by aczechowski** [comment]
Thanks @BO0168 for the feedback. I'm refreshing this article and updating the list of services based on Windows 11 version 23H2. This issue will automatically close when my pull request is merged. Given the holiday break, the changes may not publish live for a few days.
