### ISSUE TITLE
Feedback:  Where's CMTrace? Also, CMD line issue

### ISSUE THREAD

**Issue by RayDeanTech** [MicrosoftDocs/windows-itpro-docs#11757]
1. This article mentions that CMTrace is helpful to have, which I would agree, but it does not explain how to obtain it, [nor did the page that it linked to](https://learn.microsoft.com/en-us/mem/configmgr/core/support/cmtrace) :(
2. When optionally installing WSUS, the first line works independently, but the 2nd line does not work "raw" with PowerShell.  `postinstall` is not recognized as a cmdlet.  I had to do it from a CMD line.  Alternatively, line 2 needs to be adjusted to allow it to run from PowerShell directly:
```
Install-WindowsFeature -Name UpdateServices, UpdateServices-WidDB, UpdateServices-Services, UpdateServices-RSAT, UpdateServices-API, UpdateServices-UI
"C:\Program Files\Update Services\Tools\wsusutil.exe" postinstall CONTENT_DIR=C:\WSUS
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab08370-69ab-d025-cea2-c41c3aa4b908
* Version Independent ID: 9f5603f8-10e6-2651-3120-6d5627217cc9
* Content: [Prepare for deployment with MDT (Windows 10) - Windows Deployment](https://learn.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt)
* Content Source: [windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/prepare-for-windows-deployment-with-mdt.md)
* Product: **windows-client**
* Technology: **itpro-deploy**
* GitHub Login: @frankroj
* Microsoft Alias: **frankroj**

**Comment by frankroj** [comment]
Thank you for the feedback @RayDeanTech. I have made corrections to the PowerShell command line so that it can be run directly in a PowerShell window. I also have updated the info on CMTrace to clarify that it's only available with Microsoft Configuration Manager (it's not available as a stand-alone download). I have also added info regarding also using Support Center OneTrace as a log viewer.

Please also note that MDT is no longer in development and doesn't support Windows 11. For this reason, we are planning to retire this article in the near future. I have gone ahead and made the requested changes this time, but in the future the article won't be receiving any further updates.
