### ISSUE TITLE
Docs incorrect regarding block of Windows driver deployment via Intune

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/windows-itpro-docs#11756]
Hi all,

I'm referring to this sentence: "Intune: Windows Drivers update setting for the update ring set to Allow"
Question: Doesn't have the setting be set to "Block" instead of "Allow" in order to block Windows drivers in Windows update? Because allowing Windows drivers does not block them, right? The Intune UI toggle is used the other way around compared to the GPO, CSP and registry settings named above.

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23930da8-26b8-5d6c-5eba-5c74912ede4b
* Version Independent ID: 23930da8-26b8-5d6c-5eba-5c74912ede4b
* Content: [Deploy drivers and firmware updates - Windows Update for Business deployment service](https://learn.microsoft.com/en-us/windows/deployment/update/deployment-service-drivers#policies-that-exclude-drivers-from-windows-update-for-a-device)
* Content Source: [windows/deployment/update/deployment-service-drivers.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/deployment-service-drivers.md)
* Product: **windows-client**
* Technology: **itpro-updates**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by OneUser1** [comment]
Added a feedback using the new feedback system. Closed issued though not resolved.
