### ISSUE TITLE
Shared or non-shared devices?

### ISSUE THREAD

**Issue by manelrodero** [MicrosoftDocs/windows-itpro-docs#11787]
Since the option to enable federated login is fairly recent (just before the summer) I think there are some inconsistencies in the text.

The benefits of federated login indicate that it is intended for individual devices (1:1) and it is not recommended to activate it on shared devices (e.g. a classroom, the janitors' computer, etc.).

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/26098260/8d3dde7c-1a58-4f5b-aa94-0bc074e296cd)

However, more recently, the possibility of configuring this login on shared computers has been added.

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/26098260/9555eb10-540a-4d3b-bd3d-696705947438)

That is, on the one hand it is not recommended but then it explains how to do it. I think the entire document should be clarified more to make it coherent.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4889cf2-86cb-9607-32d5-2851f68f63f6
* Version Independent ID: d4889cf2-86cb-9607-32d5-2851f68f63f6
* Content: [Configure federated sign-in for Windows devices - Windows Education](https://learn.microsoft.com/en-us/education/windows/federated-sign-in?tabs=intune)
* Content Source: [education/windows/federated-sign-in.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/education/windows/federated-sign-in.md)
* Product: **windows-client**
* Technology: **itpro-edu**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by aczechowski** [comment]
Thanks @manelrodero! I think @paolomatarazzo has already finessed the wording in this article, but he can comment further :)

**Comment by paolomatarazzo** [comment]
Hello @manelrodero I already updated the article, please check it and let me know if you think it needs further clarification.

**Comment by manelrodero** [comment]
Thanks Paolo. Now, at least, it is clear that it can be used on shared devices ;-)

What I don't quite understand is why they have different names (federated sign-in vs web sign-in) when in both cases the external IdP against which your domain is federated is used. That is, in both cases federation is used through SAMLv2.

Another thing, I think this table is wrong because the licenses that allow this configuration are the educational ones.

![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/26098260/701dcc4d-9c45-4ed2-9950-359d9aeddb53)

Can you review it?

**Comment by paolomatarazzo** [comment]
@manelrodero thank you for the feedback one more time!

They have 2 different names mainly because the two featured were developed for different reasons:

- *Federated sign-in* (note the uppercase **F**) was developed specifically for student scenario, and the initial plan was to have it as an exclusive Windows SE feature. Plans changed, and over time the feature made it to Pro Edu and Education editions
- *Web sign-in* was initially developed to support a Microsoft Entra ID feature called Temporary Access Pass. Some AAD documentation needs to be updated, and we'll get to it. With Sept moment the Windows and Identity PGs worked closely to extend the capabilities of Web sign-in, essentially *reusing* some of the work that was done for Federated sign-in

A couple of things worth noting:
- Federated sign-in is not available in non-EDU editions and is optimized for 1:1 due to the behaviors explained in the document. It's unclear if we'll extend the feature for shared devices, given that now Web sign-in can be used too for federated identities. If that will be the case, then this document will need another update :)
- The difference in sign-in experience between Federated sign-in and Web sign-in in is subtle, but at the same time can be significant for specific EDU scenarios

I believe the majority of EDU scenarios have more benefits using Web sign-in rather that Federated sign-in.

Thank you for pointing out the table. We have automation in place to generate it, and I need to take a look at the source, which is clearly wrong.

Hope this helps clarifying, please let me know if you have other questions or feedback.

**Comment by manelrodero** [comment]
No, thanks to you for clarifying it.

I am going to explain this to my colleagues in the network of Spanish universities.

Our Executive Higher Education told us that Federated sign-in could be a solution to log in to Windows with tenant users who belong to a federated domain with an IdP that does not support WS-Federation/WS-Trust, that is, it only supports SAMLv2.

Just before the summer we tested the 1:1 option and in September we saw that the shared option had appeared (which was better for classroom devices).

The user experience has been more or less good (once you know that you have to deploy the device using Autopilot Self-Deployed so that it applies the configuration profile from Intune and then you can log in).

In any case, I think there are things to improve such as the texts that indicate Student (even though the person who logged in is a Staff) or that, sometimes, the web login screen goes blank. That is, our SSO/IdP website does not appear.

If there is any place where we can comment/explain/learn more about this technology, it would be very interesting for us.

Greetings and thanks for the help.

**Comment by paolomatarazzo** [comment]
You can always submit feedback using the Feedback Hub app (WIN+F).
