### ISSUE TITLE
Windows Web sign-in: panic inducing

### ISSUE THREAD

**Issue by teejayen** [MicrosoftDocs/windows-itpro-docs#11823]
I encountered an undocumented 'WsiAccount' on a critical system and was unable to locate any official information on its purpose or origin. After an extensive search, I discovered a Twitter post referencing an insightful article at https://f12.hu/2023/10/31/windows-web-sign-in-my-notes/ that sheds some light on the matter.

To aid others in understanding this account, I suggest updating the relevant documentation to reflect this information. I plan to propose changes via a pull request to include these details if they are not addressed promptly.

(admin edit: adding article metadata for proper linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9be6d74c-9de9-6180-fded-2ddca8747141
* Version Independent ID: 9be6d74c-9de9-6180-fded-2ddca8747141
* Content: [Web sign-in for Windows - Windows Security](https://learn.microsoft.com/en-us/windows/security/identity-protection/web-sign-in/?tabs=intune)
* Content Source: [windows/security/identity-protection/web-sign-in/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/web-sign-in/index.md)
* Product: **windows-client**
* Technology: **itpro-security**
* GitHub Login: @paolomatarazzo
* Microsoft Alias: **paoloma**

**Comment by paolomatarazzo** [comment]
Thank you for the feedback, @teejayen. I'll check with the feature owner and update the article as needed.

**Comment by aczechowski** [comment]
Related reference: [What is the WDAGUtilityAccount local account?](https://learn.microsoft.com/windows/security/application-security/application-isolation/microsoft-defender-application-guard/faq-md-app-guard#what-is-the-wdagutilityaccount-local-account-)

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
