### ISSUE TITLE
Windows Defender Catchup Scans in InTune

### ISSUE THREAD

**Issue by dbenn3268** [MicrosoftDocs/windows-itpro-docs#11842]
There is a ticket #10553 that addresses some of the unclear wording--but the wording addressed in such issue is no longer present in InTune.
While it is still confusing, it is now directly contradictory to the MS Docs, so if that could be fixed, that would be great. I think I can understand the difference between the enable/disable, but I cannot deploy DisableCatchupFullScan because I cannot figure out the right setting.
Here are my notes:
With both DisableCatchupQuickScan and DisableCatchupFullScan set to not configured/disabled in InTune, a device with the policy shows both settings as True in MpPreference. I assume this means that the catch up scans are not occurring.
Here is the InTune description of Full Scan
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/106715637/0e4f11ae-0753-48c6-a2a9-8474aa47143c)

and here is the same segment in MS Docs
![image](https://github.com/MicrosoftDocs/windows-itpro-docs/assets/106715637/10e4cc19-2449-4bc8-9a3d-f008a9c04041)

In docs, enabling the setting turns the scans on. In InTune, enabling the setting disables the scans. Can this conflict be resolved?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66b1ab2e-1964-5580-7c99-4bd4cd480075
* Version Independent ID: f7b5da46-04cb-3501-65fa-870a3c6f09b8
* Content: [Defender Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender?WT.mc_id=Portal-fx)
* Content Source: [windows/client-management/mdm/policy-csp-defender.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-defender.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by dbenn3268** [comment]
I have submitted an issue in both places, so hopefully someone will see it somewhere. I find the new process much less intuitive and I also cannot use Markdown formatting, which is disappointing. Though, my main focus is the product in this issue so I will focus on that for now.
