### ISSUE TITLE
EnableVirtualizationBasedSecurity Licensing Inconsistency 

### ISSUE THREAD

**Issue by arourke** [MicrosoftDocs/windows-itpro-docs#11854]
When attempting to apply the CSP EnableVirtualizationBasedSecurity to a computer running Windows 11 Pro, Intune returns an error. In the event log on the computers where this is occuring, the following error is present: "MDM PolicyManager: Policy is rejected by licensing, Policy: (EnableVirtualizationBasedSecurity), Area: (DeviceGuard), Result:(0x82B00006) Unknown Win32 Error code: 0x82b00006."

Normally, when a policy does not apply due to licensing constraints, Intune shows it as "not applicable". The page linked below indicates this policy should work with Pro editions of Windows.

Should the policy work with Pro editions of Windows or not? If it does not, this article should be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329b43eb-db67-4458-730a-65e21a5d95c2
* Version Independent ID: 3bb2c84f-60db-0512-c44c-e6c011c36285
* Content: [DeviceGuard Policy CSP - Windows Client Management](https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deviceguard?WT.mc_id=Portal-fx#deviceguard-requireplatformsecurityfeatures)
* Content Source: [windows/client-management/mdm/policy-csp-deviceguard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-deviceguard.md)
* Product: **windows-client**
* Technology: **itpro-manage**
* GitHub Login: @vinaypamnani-msft
* Microsoft Alias: **vinpa**

**Comment by aczechowski** [comment]
Thanks @arourke for the feedback, but we [auto-generate that content from the DDF XML](https://learn.microsoft.com/windows/client-management/mdm/contribute-csp-reference), which is supposedly authoritatively declaring that applicability. 

So two possible next steps for you:

- Go through Intune Support to help troubleshoot the issue, perhaps there's something else causing the issue. Like you said, it usually returns a different error when the policy isn't applicable.

- If it truly doesn't apply to Pro edition and the DDF is wrong, then it needs to go to the Windows engineering team via the [Feedback Hub](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). I think it’s important that you submit it directly, because that allows you to receive notifications and more closely monitor the progress. 

I'm closing this issue as there's nothing actionable for docs at this time.
