### ISSUE TITLE
Trick for making this work with generic USB-SATA cables.

### ISSUE THREAD

**Issue by heder** [MicrosoftDocs/windows-itpro-docs#1187]
I recently had an issue where we quickly needed to restore the SSD of a Surface Hub at an exhibition.
The USB to SATA cable we had available unfortunately did not pass through the name of the drive, naming it "Generic Disk USB Device" in device manager. Because of this the tool did not find the drive as it only accepts the drive name as mentioned in this article.

I solved this by going into the registry - HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USBSTOR and changed the "FriendlyName" key on the node below the actual device to "LITEON L CH-128V2S". By doing this, the tool found the drive and the restore worked and saved the day for us.

I understand that maybe this does not work with all brands of USB-&gt;SATA cables out there, but for us it did, and this might save some other out there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78f073c-9f6b-b9d2-cd94-0a31998f10d9
* Version Independent ID: 5beaeca4-3d07-c65c-018b-a88cda5ceb9a
* Content: [Using the Surface Hub Recovery Tool](https://docs.microsoft.com/en-us/surface-hub/surface-hub-recovery-tool)
* Content Source: [devices/surface-hub/surface-hub-recovery-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/surface-hub-recovery-tool.md)
* Product: **surface-hub**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by danieldhudson** [comment]
@heder Thank you so much for posting this! I bought the UGREEN cable as recommended in this section and it would only appear as a Generic USB Mass Storage Device. Did exactly as you have mentioned above and am currently rebuilding my Surface Hub SSD.

**Comment by danieldhudson** [comment]
So I've been looking into the issue above and it appears that the drive name will not be reported to Windows if using a USB 2.0 to SATA cable, I checked by UGREEN cable and I've actually received a different model to the one Amazon said it would be. Having now received a replacement that is the correct cable, they are essentially identical except for the model number (the correct one is model 20231) and the fact it says "USB 3.0 to SATA III Hard Drive Adapter" rather than "USB 2.0 to SATA II Hard Drive Adapter".

I've also been able to confirm that the Surface Hub Recovery Tool is NOT supported if running Windows 10 on a Mac under Bootcamp. While the tool completes successfully and the drive appears OK, the Surface Hub doesn't recognise it when inserted and asks for boot media to be added. Still not sure of the actual cause but you do need to use a standard PC and not a Mac (even in Bootcamp).

**Comment by yanickb** [comment]
Hi all, your solution didn't work for me but thanks to you I was able to find a solution
I have changed the friendly name but not in the USBSTOR but under scsi
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\SCSI
Thank for your help

**Comment by striver27** [comment]
Hello there , i have tried the above trick but unfortunately did not work ? Any idea

**Comment by striver27** [comment]
Does the process requires any licensing after completion ??

**Comment by illfated** [comment]
@striver27 : I recommend that you contact Microsoft Support directly to get help for your problem. It seems too difficult to troubleshoot your issue here in the docs.microsoft.com documentation issue tracker, intended for documentation improvement only.

**Comment by TA-JohnR** [comment]
> Hi all, your solution didn't work for me but thanks to you I was able to find a solution I have changed the friendly name but not in the USBSTOR but under scsi HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\SCSI Thank for your help

Thanks @yanickb - this was the solution for me as well with the Sabrent SATA to USB 3.0 model EC-SSHD
