### ISSUE TITLE
Signed on credentials only

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/windows-itpro-docs#1240]
The table comparing different Remote Desktop connection security options states that Remote Credential Guard supports "Signed on credentials only". How does it correlate with the Remote Credential Guard requirements section saying "Must be running at least Windows 10, version 1703 to be able to supply credentials"? What's the purpose of suppling credentials on Windows 10,  version 1703 if the Remote Credential Guard should not allow them by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c826587d-2e65-083f-254d-75f188158f08
* Version Independent ID: 746596b5-c1df-9ea0-abcc-f6ff97874e40
* Content: [Protect Remote Desktop credentials with Windows Defender Remote Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/remote-credential-guard)
* Content Source: [windows/security/identity-protection/remote-credential-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/remote-credential-guard.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by DaniHalfin** [comment]
@shortpatti @lizap @andreabichsel please re-assign to me. Thanks!

@MichaelFirsov - Thanks for reaching out. I'll address your questions as soon as possible.

**Comment by MichaelFirsov** [comment]
"Thanks for reaching out. I'll address your questions as soon as possible" - thank you!

**Comment by prmdbr** [comment]
This article has two critical issues.  I would like to, at your pleasure, address these issues in hopes to see the document amended.

Issue 1
"Enabling Remote Credential Guard [sic] on the host" While the article provides that critical information, it never explains 'WHY' it would be done this way.  A scenario of an IT organization implementing RCG having to manually, on its self, makes me uncomfortable.  There are many ways to automate the distribution of REGKEY.  Group Policy pretty -- nails this.  But unlike ADMX templates, create a GP to write a REGKEY is more of a slippery slope.  If it could simply be explained 'why does this REGKEY have to manually be set?"  ... and why is not distributed is credssp current WIndows distros.

2.  This article has a glaring omission.  In the 'considerations' portion of this document, there is no mention of the fact that: Windows Defender Remote Credential Gaurd and RD Gateway Services.  

::::::: More plainly, RD GATEWAY SERVICES is not supported 'currently' by remote credential guard ::::::::

Considering that most attacks originate from the Internet, this information should be in this document.

I am, BTW a huge fan of everything that ecompasses Windows Defender.  I would like to see these engineering documents be as thorough as possible so that people like me can be effective with these awesome tools

**Comment by rolstead** [comment]
"Remote Credential Guard supports "Signed on credentials only""
is this true or not?  Windows 10 1803 does not seem to allow credentials other than signed on user.  I don't want to sign on to my Tier 2 laptop with my Tier 1 credentials just to use RCG.  If I use a smart card to provide alternate credentials to laptop, would this still be a circle of trust violation?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MichaelFirsov - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@MichaelFirsov i think the confusion comes from the fact that the word "credentials" is used for more than one thing in the article. 

"Must be running at least Windows 10, version 1703 to be able to supply credentials" -> in this case, the credentials are the hash and TGT, that are supplied to the remote host.

When a user logs in via RDP to a machine that has Remote Credential Guard enabled, there is no credential prompt, there are no credentials sent over, so there is no hash in memory that can be extracted. The SSO experience is provided by RCG.

If you don't use /remoteguard you will be prompted for credentials.

**Comment by MichaelFirsov** [comment]
Does it mean in this case the wording should be "Must be running at least Windows 10, version 1703 to be able to use RCG" ?

Regards,

Michael Firsov 
>Суббота, 23 марта 2019, 23:47 +03:00 от VLG17 <notifications@github.com>:
>
>@MichaelFirsov i think the confusion comes from the fact that the word "credentials" is used for more than one thing in the article.
>"Must be running at least Windows 10, version 1703 to be able to supply credentials" -> in this case, the credentials are the hash and TGT, that are supplied to the remote host.
>When a user logs in via RDP to a machine that has Remote Credential Guard enabled, there is no credential prompt, there are no credentials sent over, so there is no hash in memory that can be extracted. The SSO experience is provided by RCG.
>If you don't use /remoteguard you will be prompted for credentials.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Михаил Фирсов

**Comment by VLG17** [comment]
@MichaelFirsov I would say the wording is correct, just that "credentials' does not stand for password in this sentence.

**Comment by MichaelFirsov** [comment]
Yes, I understand - thank you veru much for the clarification!

Regards,
Michael Firsov


>Воскресенье, 24 марта 2019, 0:51 +03:00 от VLG17 <notifications@github.com>:
>
>@MichaelFirsov I would say the wording is correct, just that "credentials' does not stand for password in this sentence.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Михаил Фирсов

**Comment by mypil** [comment]
@MichaelFirsov - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by 4L3K5** [comment]
is there any way to access to other network resources from RDP with RCG enabled without enter credentials?
