### ISSUE TITLE
Bitlocker Pre-Provisioning

### ISSUE THREAD

**Issue by wow-6432** [MicrosoftDocs/windows-itpro-docs#1245]
Although the article states that pre-provisioning is now supported in this version, it does not work in SCCM OSD. We've tried on both Windows 7 and Windows 10 but the system reports that the TPM is not in the correct state when the Invoke-MBAMClientSetup script is run. 

The goal is for the drive to be fully encrypted during the OSD process.

Please clarify how to get this working or remove it as a supported feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11e1beb-b1ed-8a2d-f3d9-810e777fe594
* Version Independent ID: e4f95ae3-0ac2-37b6-ba5e-d1ff67855109
* Content: [How to Enable BitLocker by Using MBAM as Part of a Windows Deployment](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25#feedback)
* Content Source: [mdop/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/how-to-enable-bitlocker-by-using-mbam-as-part-of-a-windows-deploymentmbam-25.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by VLG17** [comment]
@wow-6432 As far as i can see the "Invoke-MbamClientDeployment.ps1" does not have logic in it to check/clear the TPM. In order to get it to work, you should make sure in advance that your TPM is in the correct state (the error you are getting confirms it is not in the correct state).

You could do something similar to what's described [here](https://social.technet.microsoft.com/Forums/en-US/8b06d019-487d-41b9-8410-ac8f35e69fe5/invokembamclientdeploymentps1-fails-during-task-sequence?forum=mdopmbam)

"MBAM client install

Powershell.exe "Initialize-TPM"

Configure/Initiate bitlocker via the Invoke powershell script "Invoke-MbamClientDeployment.ps1" from the document above. "

If it still fails, i would advise opening a support ticket.

**Comment by e0i** [comment]
Hello @wow-6432  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
