### ISSUE TITLE
quality bars

### ISSUE THREAD

**Issue by alphanimal** [MicrosoftDocs/windows-itpro-docs#1296]
What's are "quality bars"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Deploy updates using Windows Update for Business (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-manage-updates-wufb)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by shortpatti** [comment]
@jaimeo, can you take a look at this one?

**Comment by Tdiwestyguy** [comment]
For the order of "methods" to ascribe updates.. 

Shouldn't it be, Intune first, SCCM second, GPO last?

I mean Satya said Cloud first, right?  I think to align with that value, the article should be changed.   Logically it also does not make sense to put Intune last, because the future of Microsoft is Service based updates, and that's not done by GPO, or SCCM, unless MDM connected to Intune, which still makes SCCM second, because it does connect to Intune for the Win10 MDM device updates.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @mypil , this issue was fixed in PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/1329
please check.

**Comment by mypil** [comment]
@alphanimal - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
