### ISSUE TITLE
Education/PrinterNames - Not Applicable

### ISSUE THREAD

**Issue by xonaecom** [MicrosoftDocs/windows-itpro-docs#1360]
When deploying this MDM policy to Windows 10 1803 Enterprise AAD joined devices I'm getting a "Not Applicable" state from the device configuration profile. In the end the printers are not being configured in the device.

Printers are being configured like \\&lt;serverName&gt;\&lt;printerName&gt; and deployed to a user group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98e451f-2a48-aef5-a2c9-b8c1af4b4c31
* Version Independent ID: 902b9a78-5d7d-ef2c-13d8-df6f537e45bb
* Content: [Policy CSP - Education](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-education#education-printernames)
* Content Source: [windows/client-management/mdm/policy-csp-education.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-education.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
Hello, @xonaecom  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
Looks like @officedocsbot is unable to make changes to issues it has closed. (I don't know why, though.)

**Comment by e0i** [comment]
@officedocsbot assign @e0i
