### ISSUE TITLE
How does SCEP affect this?

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/windows-itpro-docs#1361]
When using SCCM and SCEP to manage Windows Server 2016 antimalware, are these automatic exclusions used? In other words, if we use SCEP, must we re-define all these exclusions for our Windows Server 2016 servers? Or need we only add any additional exclusions that we require?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Automatic and customized exclusions for Windows Defender AV on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by e0i** [comment]
@officedocsbot assign e0i

**Comment by e0i** [comment]
Hello, @gaknigge thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
