### ISSUE TITLE
windows Configuration Designer Problem

### ISSUE THREAD

**Issue by amirhosseinfaraji** [MicrosoftDocs/windows-itpro-docs#1425]
hi guys. i have a problem in using windows Configuration Designer. I stuck in  the  step of 'Configure kiosk account and app'  and show me waiting icon and project have not finished. how can i resolve this problem??

![123](https://user-images.githubusercontent.com/15232909/43676756-668c86de-980c-11e8-9fce-37440858adcf.png)

**Comment by jdeckerms** [comment]
@amirhosseinfaraji Could you paste here the full string that you entered for the app?

**Comment by amirhosseinfaraji** [comment]
@jdeckerms thank you.
full path is : *"C:\Program Files\Microsoft VS Code\code.exe"*
vscode path.

**Comment by jdeckerms** [comment]
@amirhosseinfaraji Your screenshot doesn't show quotation marks at the start -- do you have quotation marks at the end?

**Comment by amirhosseinfaraji** [comment]
@jdeckerms Not quoted in the path.

**Comment by jdeckerms** [comment]
@amirhosseinfaraji I can't see any reason that the tool wouldn't validate that page the way you have it, that's why I was wondering if there was an extraneous character at the end of the app path. I used your same values in WCD and it worked fine. You can try some general ways to work around it -- try WCD on a different machine, try the Store version if you're using the desktop version (and vice versa), start a new package and see if it happens again, reboot...

Otherwise, all I can recommend is to contact Support: https://support.microsoft.com/en-us/contactus/
