### ISSUE TITLE
Able to save to desktop in MultiApp Kiosk mode

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1531]
While testing a MultiApp Kiosk, our testers found they could save a document in LibreOffice Writer, reboot, and open it again. Only the desktop is available - is this something that should be able to happen?

**Comment by jdeckerms** [comment]
@Niglb What build of Windows 10 is the device running? Also, what do you mean by "Only the desktop is available"?

**Comment by Niglb** [comment]
They could save documents, and reopen from Desktop. No other locations allowed this functionality, as they blocked via policy. Patched 1803 - 10.0.17134.228

**Comment by jdeckerms** [comment]
@Niglb I'll check with the engineering team to see if they have any insight.

**Comment by Niglb** [comment]
Thank you very much - as all other file locations are blocked I can't see why we can read \ write to the kiosk users desktop.

**Comment by jdeckerms** [comment]
@Niglb I didn't realize this, but this is expected behavior. All drives (A through Z) are blocked, but the kiosk user can save to any folder in the user's profile (which defaults to desktop).

That behavior will change in the next feature update, however, and the profile folders will also be blocked.

We recommend that you choose appropriate apps to use in your kiosk. If you select apps that have save/open action as a key functionality, exposing this app in the kiosk may cause end user confusion due to the file explorer restrictions.

**Comment by Niglb** [comment]
Oh interesting - so this may \ will change in updates? We can also modify permissions on the user folder to block this behavior in the mean time.

**Comment by Niglb** [comment]
An option to clear these user profile folders on an interval or log out \ reboot would be ideal.

**Comment by Niglb** [comment]
We liked the account maintenance mechanism found when using the Guest account modes - Downloads folder still available, but clear on log out \ reboot.

**Comment by jdeckerms** [comment]
Thanks, @Niglb I'll pass on your feedback.
