### ISSUE TITLE
Azure AD Groups

### ISSUE THREAD

**Issue by PeterKlapwijk** [MicrosoftDocs/windows-itpro-docs#1580]
Would be nice if we could add an Azure AD group to a local group.
for example add the Helpdesk group to the local administrators group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0c28c15-f0be-d732-4d9e-cf5df5e64e8b
* Version Independent ID: 17eba45f-d200-e656-42b9-e1a512931eea
* Content: [Policy CSP - RestrictedGroups](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-restrictedgroups)
* Content Source: [windows/client-management/mdm/policy-csp-restrictedgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-restrictedgroups.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
Hello @PeterKlapwijk  Thank you for providing feedback.

Note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@e0i : Just a thought - any chance you could find out who coded @officedocsbot so you could check with that person if there are limitations to what the bot can and cannot do?

**Comment by e0i** [comment]
@illfated Yes, We have just received the bot source are currently working on updating our documentation on its capabilities. :+1:

**Comment by illfated** [comment]
Nice, that is awesome. Looking forward to the improved usage. Thank you for keeping me updated! 👍

**Comment by chanderjeet** [comment]
Hi, so is it now possible to add an azure group to local admins using this CSP?
