### ISSUE TITLE
Windows 10 v1803 - Provisiong package causes OS corruption

### ISSUE THREAD

**Issue by SirBeredan** [MicrosoftDocs/windows-itpro-docs#1585]
Originally developed a provisioning package against the 1607 version of the tool. Had this provisioning package baked in to a wim running 1703 with out an issue.
Updated one of these machines to 1803 and then reset the PC however and now the machine is completely unusable due to major profile issues, services crashing and none of our scripts actually ever running.
If we perform the following before the reset the issue does not occur
-Removing the package and resting the machine resolves the issue.
-Rebuilding the identical provisioning package while using the 1803 version of the tool and then copying it over top resolves the issue.
This creates an additional overhead that we were originally hoping to avoid when provisioning packages where advertised to us by Microsoft as a major solution to our evolving operating system but instead now we will have to retrospectively update our provisioning package to resolve this issue.

**Comment by shortpatti** [comment]
@SirBeredan, what topic are you referring to for this doc issue?

**Comment by SirBeredan** [comment]
Sorry didn't realise this didn't get linked back to the actual article. My bad i guess. https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-packages

**Comment by jdeckerms** [comment]
@SirBeredan Could you report your experience through the Feedback Hub so it goes directly to the engineering team? Thanks!

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @SirBeredan  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

**Comment by e0i** [comment]
@officedocsbot close
