### ISSUE TITLE
SyncML Examples

### ISSUE THREAD

**Issue by akmatthewsuk** [MicrosoftDocs/windows-itpro-docs#1616]
Please could you start providing SyncML examples for policies that are ADMX backed. I have been able to produce working SyncML for some policies but a few policies (PreventInstallationOfMatchingDeviceIDs) are cryptic.

A little bit of help would go a long way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c30e8535-b5d1-da85-117d-bcfd78c7e826
* Version Independent ID: 6189b9b2-f3ff-8ad0-1963-66c93bb061b1
* Content: [Policy CSP - DeviceInstallation](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deviceinstallation#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-deviceinstallation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-deviceinstallation.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by Justinha** [comment]
@akmatthewsuk thanks for the suggestion. SyncML examples are added now. We'll try to add them for other policies too.

**Comment by RobbieNelson** [comment]
Technological side of this issue is quite necessary to learn for everyone who is involved there. 

By the way, I want to say that for a long time I had small bunch of knowledge in the sphere of SynchMl as it seemed really difficult to me to comprehend it better. Nevertheless, a couple of days ago I found this resource https://termsdepot.com/synchml/  where there was information about what is SynchMl and how to helps to make synchronization of data between disparate systems. 

Many people also try to use it in order to simplify the process of using their digital devices.
