### ISSUE TITLE
Device Registration Pre-Requisites

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windows-itpro-docs#1643]
Under "Device Registration" there are 2 prerequisites shown: "Azure Active Directory Device writeback" and "Azure Active Directory Premium subscription". In reality, the only prerequisite here is having an Azure AD Premium Subscription, and Device WriteBack can be enabled later on during WHFB implementation, right after enabling DRS in ADFS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eda72c-ccd2-e8d8-4f7e-6edf95b79408
* Version Independent ID: be08aee5-2403-c131-0f39-005e1271d5f1
* Content: [Hybrid Windows Hello for Business Prerequistes (Windows Hello for Business)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs#device-registration)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust-prereqs.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by MikeStephens-MS** [comment]
FIXED!
The configuration is certificate trust, which requires Device writeback. Device writeback is only available with Azure AD Premium.  You CANNOT deploy certificate trust without enabling device writeback-- it will not work as users will be unable to enroll certificates because the device cannot authenticate to AD FS.  Yes, device writeback can be added later using AAD Connect-- but doing that would leave the deployment in a broken state.  That is why it is declared as a prereq; without it cert trust deployment does not work.
