### ISSUE TITLE
Does ComputerName validate with DNS servers? 

### ISSUE THREAD

**Issue by TecumsehSamp** [MicrosoftDocs/windows-itpro-docs#1660]
Computer name validates with [the DNSValidateName](https://docs.microsoft.com/en-us/windows/desktop/api/windns/nf-windns-dnsvalidatename) function, though does it also check to see if the name has already been used? What happens if there is a computername conflict during the AD join? Will it pick another random int till success (if you decided to append a random integer)?

A suggestion would be (if this isn't done yet) to maybe use the [DNSQuery_A](https://docs.microsoft.com/en-us/windows/desktop/api/windns/nf-windns-dnsquery_a) API function to check a computer name against AD DNS, to avoid conflicts within the same domain? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313b8527-ba38-682f-5291-7c56ef58b122
* Version Independent ID: 88d93eac-44d2-46d2-0763-4380dc8cfdb8
* Content: [Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-accounts#computeraccount)
* Content Source: [windows/configuration/wcd/wcd-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-accounts.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @TecumsehSamp I know it's been a while since this issue was opened so thank you for your patience and for your suggestion. I just wanted to follow up if you found the answers to you questions? If not, I think it's best if you [contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. I've also checked the Tech Community and there's normally an error if there's a computer name conflict. You may want to check [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.

If you have suggestions regarding a product or feature, please submit it on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve.

Also, please be informed that this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. 

I will now close this issue. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
