### ISSUE TITLE
AssignedAccessConfiguration support scripts

### ISSUE THREAD

**Issue by DirkMCar** [MicrosoftDocs/windows-itpro-docs#1661]
The CSP examples state how to allow a modern app or a legacy x86 app, but there is no mention of scripts. Since the Configuration node makes use of AppLocker, is there any way to allow for a link to points to a script that fires off a legacy app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8301897-dfa3-ef3b-744f-9e8334c17dc4
* Version Independent ID: d5751dd3-b0ae-49ef-75cd-d4113c4eed3d
* Content: [AssignedAccess CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/assignedaccess-csp)
* Content Source: [windows/client-management/mdm/assignedaccess-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/assignedaccess-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jdeckerms** [comment]
@DirkMCar I'm checking on this, I'll let you know what I learn.

**Comment by jdeckerms** [comment]
@DirkMCar Scripts aren't supported. In the upcoming update, we're adding the ability to set an app to launch automatically, maybe that will work for your situation.

**Comment by DirkMCar** [comment]
Many apps are build to call a .bat file initially to launch that provides parameters as well as performs initialization steps. Are you aware of any workaround that would allow an app like this to run while using AssignedAccessConfiguration?

**Comment by jdeckerms** [comment]
@DirkMCar I don't know of any work-arounds, sorry.

**Comment by egallagh** [comment]
@DirkMCar IMHO using a batch file to launch an application is a very outdated approach. The kind of stuff done in the script that launches an application is usually better accomplished through other methodology. I would take a look at the problem from that direction.
Hope that helps

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @DirkMCar, I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up if you were able to find a workaround? Although in Windows 10, version 1809, you can [automatically launch an app when the user signs in](https://docs.microsoft.com/windows/configuration/lock-down-windows-10-to-specific-apps#allowedapps) by making sure your [XML file](https://docs.microsoft.com/windows/configuration/lock-down-windows-10-to-specific-apps#create-xml-file) references http://schemas.microsoft.com/AssignedAccess/201810/config. I hope this feature will meet your needs.

I will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this doc. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
