### ISSUE TITLE
NativeProtocolType supported values

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windows-itpro-docs#1665]
so, NativeProtocolType does not support SSTP? is that what it means? SSTP is also a protocol among IKEv2,PPTP,L2TP and it does not make sense for it not to be in this list.

also, is this a multi-value configuration node? let's say I want the profile to try just IKEv2 and PPTP but not L2TP or SSTP. can I do that if I simply put: 
&lt;NativeProtocolType&gt;IKEv2,PPTP&lt;/NativeProtocolType&gt; in my XML or it will not work? I know "automatic" is there but I want to know how much fine-tuning I can do as "automatic" will try all 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d13d299-d2d2-87c7-f4e8-33fff0d51fea
* Version Independent ID: cf74cde6-116d-2f4f-c4a5-e759deef3f3a
* Content: [VPNv2 DDF file](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-ddf-file)
* Content Source: [windows/client-management/mdm/vpnv2-ddf-file.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-ddf-file.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @sasanmcp hoping all is well. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up if you found the answers to you questions? According to some community uses, NativeProtocolType supports SSTP, one thing to consider is to ensure you set the correct [VpnStrategy key](https://docs.microsoft.com/openspecs/windows_protocols/ms-rrasm/7574fc0f-3e82-4b69-a4c3-43b588fad4d7). This [TechNet article may be able to provide some insight](https://social.technet.microsoft.com/Forums/en-US/bedc5885-42c6-4965-b44d-7ba4381c849e/always-on-vpn-sstp-configuration?forum=winserverNIS), although there are links shared in there that are not hosted by Microsoft⁠—with information including additional VpnStrategy keys⁠—they may be worth checking (*We can't guarantee their accuracy though*). 

Other than Technet and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers, you can also [contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) if you need immediate assistance.

I will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this doc. Please note that Github site is used as a feedback system to help improve the quality of the technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
