### ISSUE TITLE
Windows 1803 Reset PC

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1669]
Hi there - we use a provisioning package and are now attempting to deploy 1803. Reset PC now does not work when you Reset, keeping the provision package. The PC is unusable and very unstable, failing to re-join our domain. This is the same package from our 1709 deployment. Any ideas on settings now that are not supported ?

**Comment by jdeckerms** [comment]
@Niglb Please report this through the Feedback Hub so the engineering team can investigate, thanks!

**Comment by hopetobethefinal** [comment]
I apologize, however, I don't know how to report through the feedback. I am very overwhelmed, I have close to 150 emails regarding this issue.

Sincerely,
Kari McBee 
5414305892


--------------------------------------------
On Fri, 9/21/18, Jeanie Decker <notifications@github.com> wrote:

 Subject: Re: [MicrosoftDocs/windows-itpro-docs] Windows 1803 Reset PC (#1669)
 To: "MicrosoftDocs/windows-itpro-docs" <windows-itpro-docs@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Friday, September 21, 2018, 6:01 AM
 
 @Niglb
 Please report this through the Feedback Hub so the
 engineering team can investigate, thanks!
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jdeckerms** [comment]
@hopetobethefinal Feedback Hub is part of Windows 10. On a Windows 10 device, in the Start menu list of apps, select "Feedback Hub".

**Comment by Niglb** [comment]
Removing the 'hide oobe desktop' in the provisioning package resolved the issue with reset pc. We set our hide oobe options in our unattend file for reset pc.

**Comment by e0i** [comment]
Hello, @Niglb  Thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

Thanks.

@Andrea - _[Recommended closure]_

**Comment by e0i** [comment]
@Andrea - Recommended closure.

**Comment by e0i** [comment]
@officedocsbot close
