### ISSUE TITLE
Kiosk browser cache

### ISSUE THREAD

**Issue by georgioup** [MicrosoftDocs/windows-itpro-docs#1671]
Is there a way to clear all browser history after the end of a session?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by anwarmahmood1** [comment]
me too
I'm trying to use this for an online public access catalogue (OPAC), a great use case for a Windows 10 kiosk computer. Colleges, Universities and Libraries will benefit from this.

In our case - probably *every* case - the OPAC system can enable kiosk users to logon to reserver a book, etc.  I can get this working, and have set a 5 minute timeout.  However, when the 5 minutes are up, Kiosk Browser does return to the default URL, but the previously logged on user *REMAINS* logged on.  This makes it insecure.  If, however, the the MDM or CSP had a "clear browsing history on timeout" setting, that cleared browser cookies as well as temporary files, the logged on user would become logged off.  This would *GREATLY* improve the Kiosk Browser app.

**Comment by jdeckerms** [comment]
@georgioup There's a bug for cache clearing that is fixed in the next major update. @anwarmahmood1 I've passed the details of your scenario on to the product team, it will help them prioritize getting the bug fix pushed to earlier OS versions.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @georgioup and @anwarmahmood1 I know it's been a while since this issue was opened so thank you both for your patience. The *Enable End Session Button* allows user to clear the cache manually. I would assume your suggestion is to provide an option to do this automatically. As per the existing documentation, this feature is not yet available. What I will recommend is submit this as a suggestion on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). The Microsoft engineering team uses UserVoice feedback to learn what users are asking for or what they want to improve. I will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

NOTE: The bug @jdeckerms mentioned before appears to be with the [End Session](https://social.technet.microsoft.com/Forums/en-US/d17d1749-e699-42c6-bcc4-c7063fba1d98/microsoft-kiosk-browser-end-session-does-not-clear-login-information?forum=win10itprosetup) button.  I can't find any update ([resolved and known issues](https://docs.microsoft.com/windows/release-information/windows-message-center)) related to it though, so perhaps it's still a known bug.

**Comment by jvsam** [comment]
@officedocsbot close
