### ISSUE TITLE
Autopilot and intune DEVICE cal

### ISSUE THREAD

**Issue by PaoloBodini** [MicrosoftDocs/windows-itpro-docs#1690]
Ciao,

It is clear to me that AAD P1/P2 is required but what about PC in kiosk mode? I have thousand PC in kiosk mode all around the world and I would like to start to manage all these with intune and autopilot. I was thinking to buy intune device Cal but reading how autopilot works I think i cannot use it just with intune device Cal. My goal is simple: deploy these kiosks with autopilot and register them in intune. It is possible?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @PaoloBodini hoping all is well. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up if you found the answer to you question? Perhaps these can help:

- [Microsoft Intune announces device-only subscription for shared resources](https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/Microsoft-Intune-announces-device-only-subscription-for-shared/ba-p/280817)
- [Enroll Windows devices in Intune by using the Windows Autopilot](https://docs.microsoft.com/intune/enrollment-autopilot)
- [Windows Autopilot Self-Deploying mode](https://docs.microsoft.com/windows/deployment/windows-autopilot/self-deploying)
- [Windows 10 and Windows Holographic for Business device settings to run as a dedicated kiosk using Intune](https://docs.microsoft.com/intune/kiosk-settings)

I would also recommend that you [contact Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. Please note that this Github site is used as a feedback system to help improve the quality of the technical documentation. If you have suggestions or ideas to make the docs better, you can open an issue on a specific content page by using the feedback feature so it can easily be tracked.

![image](https://user-images.githubusercontent.com/18371314/62007287-83bf9d00-b100-11e9-8ff8-31f16b6f7e76.png)

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @PaoloBodini, we didn’t hear back from you but we hope you've got the answer that you need. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
