### ISSUE TITLE
Technique has limited applicability

### ISSUE THREAD

**Issue by jrshoare** [MicrosoftDocs/windows-itpro-docs#1692]
If you only want to allow users access to a single application then this technique has limited applicability. Although at first it would appear that the user has access to only the application assigned to the custom shell, pressing Ctrl+Alt+Del allows them to access the Task Manager from where they can run many simultaneous tasks including Explorer.exe which brings up the whole desktop experience.

Don't use this technique if you truly want to lock the user down to using one and only one Windows desktop application!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c51c7628-5bb2-e962-e837-24a1b5123582
* Version Independent ID: e59acc13-b986-a5f5-9cd0-f27e5cc69866
* Content: [Use Shell Launcher to create a Windows 10 kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-shelllauncher#wizard)
* Content Source: [windows/configuration/kiosk-shelllauncher.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-shelllauncher.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by egallagh** [comment]
Good point. I'll suggest some changes.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @jrshoare hoping all is well. I know it's been a while since this issue was opened so thank you for your patience. Since the updates suggested to this documentation based from your feedback are already displayed here at docs.microsoft.com, we can now close this issue. You can verify by visiting this URL: https://docs.microsoft.com/en-us/windows/configuration/kiosk-shelllauncher

Thanks for being part of the Microsoft Docs community!

Hi @egallagh, thank you for creating the pull request (See #1714).

**Comment by jvsam** [comment]
@officedocsbot close
