### ISSUE TITLE
Office or office like apps

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#1711]
Our public MultiApp Kiosk project has a requirement for office or office like product. What are the recommendations for this in a Kiosk device that is cloud only (read no KMS server). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2d1007-2cbb-94a6-18aa-a0b879262ab1
* Version Independent ID: 625d9906-0cb0-23eb-3a56-a84ad774d291
* Content: [Guidelines for choosing an app for assigned access (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/guidelines-for-assigned-access-app)
* Content Source: [windows/configuration/guidelines-for-assigned-access-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/guidelines-for-assigned-access-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@Niglb Office apps are available from Microsoft Store or you can set up Microsoft Store for Business for your organization and obtain and distribute the Office apps that way: https://docs.microsoft.com/en-us/microsoft-store/

**Comment by Niglb** [comment]
Thanks -  but will that cover a license for a public use kiosk?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Niglb hope all is well. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up to ask if you found the answer to your question? Hopefully these will help, [Acquire apps in Microsoft Store for Business and Education](https://docs.microsoft.com/microsoft-store/acquire-apps-microsoft-store-for-business) and [Apps in Microsoft Store for Business and Education](https://docs.microsoft.com/microsoft-store/apps-in-microsoft-store-for-business)

> As an admin, you can acquire apps from the Microsoft Store for Business and Education for your employees. Some apps are free, and some have a price.

Please check the App licensing model section as well. 

We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here. 

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @Niglb we didn’t hear back from you so we will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
