### ISSUE TITLE
How to force a reboot immediately after installing?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/windows-itpro-docs#1722]
Is there a way to have all computers (including Win10/Server2016) automatically reboot as soon as they are done installing?  I don't want a 15 minutes timer or anything else.  I want them to install and then reboot regardless of what time it is or if someone is logged in or not because we control the time they install and everyone knows to not be logged in at that time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by RAJU2529** [comment]
put zero inplace of  15 minutes

**Comment by kelemvor33** [comment]
In Group Policy, you can't change the number.  15 is the lowest you can set it.  Otherwise I'd have to do it directly in the registry but don't know if it would accept a lower value in there.

**Comment by RAJU2529** [comment]
i  got  success editing  ,  i inserted  0  instead of 15, by modifying the small value in the WindowsUpdate.admx file

**Comment by kelemvor33** [comment]
And when you did that, your servers now install updates and reboot
immediately?  That's all I'm trying to accomplish is to force all servers
(regardless of OS and regardless of if anyone is logged on or not) to
reboot immediately after installing their updates.

Thanks.

**Comment by e0i** [comment]
Hello, @kelemvor33 Thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

Thanks.

@Andrea - _[Recommended closure]_

**Comment by e0i** [comment]
@officedocsbot close
