### ISSUE TITLE
MDM enrollment fails on the mobile device when traffic is going through proxy

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#1740]
MDM enrollment fails on the mobile device when traffic is going through proxy: does this issue also applies to Windows 10 Desktop computers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19461768-ab73-b97c-f754-24e5c75e261f
* Version Independent ID: 58c7b616-f5c7-c503-a689-4fadde8ee061
* Content: [What's new in MDM enrollment and management](https://docs.microsoft.com/en-us/windows/client-management/mdm/new-in-windows-mdm-enrollment-management#whatsnew1809)
* Content Source: [windows/client-management/mdm/new-in-windows-mdm-enrollment-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/new-in-windows-mdm-enrollment-management.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Martony78 , thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
