### ISSUE TITLE
need clarification

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1741]
if i modify registry key like
HKLM\SOFTWARE\Microsoft\Security Center\Feature DisableAvCheck (DWORD) = 1 
windows security stops checking of third party antivirus also ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RAJU2529 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @RAJU2529 ,
yes, it will, according to [this article](https://blogs.windows.com/windowsexperience/2018/05/16/announcing-windows-10-insider-preview-build-17672/)
Dear @SusanBradley , it was fixed in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/a79f88000ef735a643cae9c4c8d787aab346e410#diff-a9ee0a47fba86a9999f1da444bbff8e3
Dear @rswgnu ,
there is no such fix in the list of changes for this release. However, file system performance increase is announced in new [WSL 2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/)

Thank you

**Comment by RAJU2529** [comment]
Thanks sir, now I understood real reason after reading the article mentioned in your reply.
Thanks for clearing my doubt. Thanks a lot sir. You can close this issue

**Comment by mypil** [comment]
@officedocsbot close
