### ISSUE TITLE
application guard control

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1743]
Can i use  WDAG control  with third-party antivirus product, I disabled windows defender by group policy  &lt; or  is it compatible  with third party products

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529 were you able to find the answer to your question since you've opened this issue? If not, maybe this documentation with [Windows Defender Antivirus compatibility](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility) matrix may help. You may want to check [this support help article](https://support.microsoft.com/help/4072699/windows-security-updates-and-antivirus-software) as well.

If you are experiencing issues on Windows 10 that don't pertain to the documentation, please utilize the proper channel by contacting support and opening a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant. 

Thank you for engaging with the community!

**Comment by RAJU2529** [comment]
@jvsam Thanks  for the links , i have  checked  above  link, in first link about only  windows  defender antivirus  .  But i asked about windows  defender application guard   with  third party  antivirus  Kaspersky total security . I already   disabled  windows defender gpo permanently to avoid conflicts .

I also checked in second link,  KTS has  already  sets  desired registry  key on windows 10 1903

**Comment by jvsam** [comment]
Hi @RAJU2529 good call. I believe support or that forum can assist you better with your question. Thank you for sharing the link here.

**Comment by jvsam** [comment]
Hi again @RAJU2529, since this documentation is still considered accurate and *up-to-date*, we will now close this issue. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
