### ISSUE TITLE
HideOobe for desktop

### ISSUE THREAD

**Issue by NigelbrownIBM** [MicrosoftDocs/windows-itpro-docs#1756]
In Win 10 1803 we are finding when HideOobe for desktop is setup in our provision package, Reset PC will render the device unusable. The document here states a user account must be created - we already have a local Support, and domain users at this point in Reset PC. Removing HideOobe for desktop in the provision package, and adding some hide Oobe nodes in the unattend does provide a workaround, but we did not have this issue when deploying 1709. We are deploying 1803 to all our 1709 devices as an upgrade patch, but this will break Reset PC as these devices have our previous provision package installed with HideOobe for desktop enabled. Any suggestions? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c8e6f62-b786-e077-8fd9-5c34821a67b0
* Version Independent ID: 0e01f920-91e5-0bef-bacf-0b87dfbc4a99
* Content: [OOBE (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-oobe#hided)
* Content Source: [windows/configuration/wcd/wcd-oobe.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-oobe.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @NigelbrownIBM were you able to resolve the conflict between HideOobe and Reset PC? Would you mind letting us know of the status? Please keep us posted here on the resolution or any relevant information that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are useful, accurate and up-to-date.

If you are still experiencing the issue—*and since this Github site is intended for product documentation*—I would recommend contacting support and opening a [service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. 

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi @NigelbrownIBM. We haven't received any response from you. Hopefully, you were able to contact Windows 10 support for assistance. For now, we will close this issue, however, if you believe the documentation needs improvement, please re-open and provide recommendations on what needs to be changed or updated. Again, our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.

Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
