### ISSUE TITLE
Update/PauseFeatureUpdatesStartTime 

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1774]
Update/PauseFeatureUpdatesStartTime 

This says String, but does not offer supported String syntax. 

Please input syntax examples on all policies. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-engagedrestarttransitionschedule)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Tdiwestyguy, thank you for your feedback. Since you've opened three issues related to the [Policy CSP - Update](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-update) article, I am combining #[1774](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1774), #[1775](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1775) and #[1750](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1750) to the request that I will forward to the Windows writing team. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentations.

**Comment by jvsam** [comment]
Hi @Tdiwestyguy, *Update/PauseFeatureUpdatesStartTime* policy description now includes syntax and examples. Also, the updates are displayed on the site so we will now close this issue. Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!

NOTE: *Update/PauseQualityUpdatesStartTime* has also been updated. See #1775

**Comment by jvsam** [comment]
@officedocsbot close
