### ISSUE TITLE
Update/PauseQualityUpdatesStartTime 

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#1775]
Need an example on String TIME entry.  Previous request is how to enter Date as string format. No examples provided.  Also from policy to policy in this list for updates, it appears each has a different format. (needs streamlining/format review)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#update-allowmuupdateservice)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Tdiwestyguy, thank you for your feedback. Since you've opened three issues related to the [Policy CSP - Update](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-update) article, I am combining #[1774](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1774), #[1775](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1775) and #[1750](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1750) to the request that I will forward to the Windows writing team. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentations.

**Comment by jvsam** [comment]
Hi @Tdiwestyguy, *Update/PauseQualityUpdatesStartTime* policy description now includes syntax and examples.  Also, the updates are displayed on the site so we will now close this issue. Thank you again for taking the time to share your feedback and for being part of the Microsoft Docs community!

NOTE: *Update/PauseFeatureUpdatesStartTime* has also been updated. See #1774

**Comment by jvsam** [comment]
@officedocsbot close
