### ISSUE TITLE
AutoPilot Reset (preview) endless loop.??

### ISSUE THREAD

**Issue by damigs** [MicrosoftDocs/windows-itpro-docs#1796]
I attempted to try this on one of my 1809 devices that is fully enrolled and registered.  Only to now be stuck in a endless reset loop problem.   Thoughts..??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a662f1-c2aa-33ad-0e71-d0cbb288d053
* Version Independent ID: 196f1c8d-3179-c173-194f-08bf3a6f82ca
* Content: [Reset devices with remote Autopilot Reset (Preview)](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset-remote)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset-remote.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-reset-remote.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by rajeshkhanikar** [comment]
Same here with Windows 10.0.17134.345. Status of the device says _Wipe(Retain enrollment state and user account) pending_... It worked once (one week ago), but not again. Endless loop with a Lenovo computer and a VM.

**Comment by thedrum808** [comment]
@rajeshkhanikar - 17134.345 does not officially support the feature. Not sure how you cued it.

**Comment by rmcdone** [comment]
I've experienced the same problem today on an HP x360 running Windows 10.0.17763.134. The process gets to the Account setup phase then randomly reboots into "Resetting this PC".

**Comment by Eillirand** [comment]
The delay is brutal. I can understand giving the user a notification and pausing, but please add an option to do the reset instantly as well or at least control the time it takes to deploy the reset.

**Comment by jaikbenhet** [comment]
Is this ever been resolved guys? 

I am experiencing the same problem: After giving the AutoPilot Reset (preview) command, the system goes resetting but cannot complete the "Security Policies" at the "Device Setup" section. After a wait the system goes resetting again which result to nothing (looping). 

We are using Windows 10 version 10.0.17763.194

**Comment by trey1532** [comment]
Our AutoPilot Reset (preview) button is greyed out. Windows build 17763.55  Is this because we don't have access to this feature or has it been disabled because the feature is broken? Asking for a friend..

**Comment by jseerden** [comment]
Experiencing this issue on a 10.0.17763.379 device. On the "Enrollment Status Page", the "Device setup" part hangs on "Identifying", until a time out occurs and it is initiating another Factory Reset. Just stuck in a loop trying over and over again.

**Comment by greg-lindsay** [comment]
Sorry for not answering this for so long. I have had issues with notification, but this should be fixed now.

See the following blog entry about this issue.
https://www.google.com/amp/s/oofhours.com/2019/10/24/new-enrollment-status-page-option-available/amp/

1. You go through the Windows Autopilot deployment process, showing the device ESP and user ESP.  Everything works great.
2. Later, another user account signs into the machine and sees the user ESP appear again.  And it doesn’t work great – it will sit there for a long time, often timing out (based on your ESP settings).
That timeout happens because it’s waiting for another MDM policy sync to figure out what policies need to be tracked for this additional user.  But if this second user signs in more than 2 hours after the device was initially provisioned, that sync might not happen for up to 8 hours.  

As mentioned in the blog, you can change the ESP settings to do the work for you with the new “Only show page to devices provisioned by out-of-box experience (OOBE)”:

•	User ESP will be enabled for the first user.
•	Intune will then send a new policy to the device turning off user ESP (the exact same as the custom OMA URI policy).
•	The next user won’t see the user ESP.

This doesn’t work retroactively though, it only works for newly-deployed devices.  (Devices that were deployed before you set this value won’t get the updated policy setting, so user ESP will still be enabled.)
