### ISSUE TITLE
Nonsense and way behind

### ISSUE THREAD

**Issue by ygoe** [MicrosoftDocs/windows-itpro-docs#1834]
Sorry but this feature is nonsense and way behind competitors. Samsung has this limit at 80% (in a product of 2012) which makes it practical for everyday use. Lenovo even lets you specify custom charge capping and threshold levels, defaulting to 80% and 75% (in a current product). All of this can be switched on the fly with simple GUI vendor tools. 50% effectively makes this feature unusable for daily work. So I'll still have to charge my device up to 100% unless I accept rebooting and spending a few minutes doing complicated configuration every time I switch places from AC to battery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a767ea0-4095-7a35-3828-4b3a17a0ea26
* Version Independent ID: 4ca4088c-1e98-c725-d46b-94cecfa123f2
* Content: [Battery Limit setting (Surface)](https://docs.microsoft.com/en-us/surface/battery-limit)
* Content Source: [devices/surface/battery-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/battery-limit.md)
* Product: **w10**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@ygoe Thanks for your feedback, but it is more about the product design than the documentation. If you'd like to get your feedback heard by the product team who can consider it when planning for future releases, you should submit it using the Feedback Hub.

**Comment by ygoe** [comment]
Done that but it usually doesn't improve the situation unless it gets thousands of upvotes.

**Comment by jdeckerms** [comment]
@ygoe I understand that it feels that way, but it's still the most direct route of registering your opinion. The product teams really do pay attention to what they're hearing from customers in the Feedback Hub.

**Comment by BR77BE** [comment]
"The product teams really do pay attention to what they're hearing from customers in the Feedback Hub."
As evidenced by the many complaints about deleted files for months before the Windows 10 version 1809 fiasco?

**Comment by fizzle7** [comment]
Standard Microsoft response really. Not that it's their fault, they are just one person in a huge corporation. But considering the feedback hub doesn't even work and constantly crashes, let alone being heard in the throng, it deserves to be spammed everywhere. I'm just gonna complain wherever I can until you fix your garbage, Microsoft, so why not here? I mean, can you even imagine, $3000 machine and the feedback hub doesn't work. For frack's sake, it's a glorified simple github-style issue forum.
As for the topic, it's a no-brainer that a custom slider for the charge level needs to be available. I don't even know who comes up with this stuff then decides to just cut it short and leave it to rot in mediocrity forever abandoned in the dungeons of Microsoft while everyone furiously types new lines of codes to add my little pony to minecraft.
You should also explicitly add which devices can use these options to the page. Right now it seems surface pro 3 and 4 can do it, but it would be logical to assume books can too since it's the same operating system and battery drivers. But no, books can't yet. So might as well add that.

**Comment by danraleigh** [comment]
Same crap happening on my $3000 surface book and documented...Couldn't agree more -coming from a software engineer- completely unacceptable to me to have no option other than shelling out $600 for a battery fix that could easily fixed in software. Keep being told it's a hardware issue - hogwash!

**Comment by illfated** [comment]
Sounds a lot like software design inspired by Apple Inc. (just my opinion).

**Comment by andritolion** [comment]
Battery Limit is not designed for daily use. It's designed for use in kiosks...

**Comment by egallagh** [comment]
The problem here is that a solution to a VERY SPECIFIC issue is being misinterpreted by some people as an incorrect implementation for other features that those people desire. If you would like those issues addressed, please make recommendations for those changes through the proper mechanism, like User Voice, so that it can be heard by the right people. This area is to address issues with the current documentation related to existing features and functions. Thank you.
I recommend closing this.

**Comment by BR77BE** [comment]
Same issue. Same feature. Kiosk is only an example in the docs.

**Comment by ygoe** [comment]
To be more precise: I'm well aware that this is the wrong place. But the other places you recommend are dead. Nobody at Microsoft is interested in such proposals. I have never seen a single action taken on Windows feedback, and there is no such thing as hardware feedback. And it's not a misinterpretation of a different feature, it's the big disappointment of the design decision made. I still honestly consider that other feature "nonsense and way behind".

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi all! Everyone in this thread already knows that this Github site is intended for product documentation. But on the other hand, there are also several important details from this issue discussion (*and how it has evolved*) that will be helpful for other users, such as:

1. Where to submit feedback or suggestions related to the documentation. **Answer**: here, of course, but only if it falls under Windows 10 (*This repo is only for Windows 10*).
2. Where to submit feedback (*negative, positive, neutral, etc.*) related to features or products of Microsoft. **Answer**: User Voice. There are different User Voice hubs, but this [one](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) is specific for Windows 10. 

Again, since there is no specific comment that indicates the documentation needs to be updated, we will be closing this issue. If there is, please feel free to re-open it and provide for information. *Personally*, I would like to emphasize though that closing this issue does not mean you cannot continue to add updates on this issue thread if you deem it's useful. I would also *strongly* encourage everyone to utilize the correct channel in submitting feedback, even if you may *think* it's futile. If a lot of people believe a feature suggestion has merits, then please encourage them to upvote it after submitting via User Voice.  

Thank you everyone!

**Comment by jvsam** [comment]
officedocsbot close

**Comment by ygoe** [comment]
Just one little note:

> even if you may think it's futile

I can explain why I think that. Battery handling is something that's unknown to most regular users. They want 100% charge and maximum lifetime, but that's impossible with current technology. It requires the *care of experts*. There will be no masses voting for such an improvement because the masses don't understand why it's necessary. User Voice simply won't work for this issue.

PS: Apple has now added this feature to their devices as well. Just a bit smarter.

PPS: I don't like Apple very much for a number of reasons.

**Comment by jvsam** [comment]
Hi @ygoe I completely understand where you're coming from. Information spreads quickly online, I always believe in the power of *content* in educating users. Good luck.
