### ISSUE TITLE
Support for SP levels?

### ISSUE THREAD

**Issue by NickMo1** [MicrosoftDocs/windows-itpro-docs#1860]
Are all different versions/feature updates of Windows 10 enterprise (e.g. 1511, 1703, 1809 etc) supported with all versions of the MBAM client (e.g. 2.0, 2.5, 2.5 sp1, etc)
We want to ensure we stay within Microsoft supported configurations, and take support applications like MBAM into account when planning feature updates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd86f5e-6388-d226-2460-997fc24945d9
* Version Independent ID: aa827a7d-725a-a5d0-f6aa-3f1df8cc310a
* Content: [MBAM 2.5 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations)
* Content Source: [mdop/mbam-v25/mbam-25-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/mbam-25-supported-configurations.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @NickMo1, thank you for your question. I'll get this over to the Windows writing team for review and to research on the supported Windows 10 Enterprise versions. We really appreciate your patience on this matter. 

And since this site is intended for product documentation, I would also suggest that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get an immediate answer. If you decide to contact support, please update us here on the answer so we can update this document.

**Comment by TokyoScarab** [comment]
@NickMo1 Hello!  Thanks for bringing this up.  I wanted to touch base and see if you had contacted support and heard anything from them.  As for your question, MBAM has supported Windows 10 Enterprise since MBAM 2.5.  The only release of MBAM that doesn't support Windows 10 Enterprise is MBAM 2.0 (as seen [here](https://docs.microsoft.com/microsoft-desktop-optimization-pack/mbam-v2/mbam-20-supported-configurations-mbam-2#-mbam-client-system-requirements) ).  I hope that answers your question.  If you have any other questions on this, feel free to comment them below! Thanks!

**Comment by jvsam** [comment]
@NickMo1 how are you? Do you have any update on @TokyoScarab's question? Thank you.

**Comment by jvsam** [comment]
Hi @NickMo1 , we haven't heard from you. Please let us know if you were able to contact *Support* and if there's any information that needs to be called out in this documentation. Otherwise, we can consider this issue as *resolved*. Thank you and we look forward to hearing from you,

**Comment by NickMo1** [comment]
Thank you for the info!  
I do have 1 other question, with MBAM losing mainstream support next month, what's the enterprise way forward if Azure is not an option?

**Comment by jvsam** [comment]
Hi @NickMo1 you're welcome! Now regarding MBAM, in this [documentation](https://docs.microsoft.com/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises) it says:

>Microsoft BitLocker Administration and Monitoring (MBAM) capabilities will be offered from SCCM in on-prem scenarios in the future.

You can also check this [blog](https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/Microsoft-expands-BitLocker-management-capabilities-for-the/ba-p/544329) for more details. The target date is second half of 2019, but Microsoft Azure Active Directory and Microsoft's Intune BitLocker management are also available as options. Extended support is also another option to consider:

>Microsoft has announced MBAM will end mainstream support on July 9, 2019 and will enter extended support until July 9, 2024. Customers can continue to deploy and use MBAM 2.5 SP1, fully supported by Microsoft during the extended support period.

You can monitor the Tech Community blog for updates.

Anyway, back to this issue, I believe we can now consider it as *resolved*, at least based on what we can support. For now we will close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
