### ISSUE TITLE
Remote Desktop with Biometrics

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windows-itpro-docs#1890]
Is Remote Desktop with Biometrics only available on Windows 10 Enterprise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @dawnwood
* Microsoft Alias: **trudyha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @gabrielluizbh thank you for your question. I've tried looking for information, but I haven't found anything (*yet*) that explicitly confirms it's *only* available for Enterprise. I understand that this issue has been opened since last year, but I believe the best course of action here is for you open a service ticket in your tenant so you can get your answer ASAP. Please follow this link to contact support for Windows 10: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

Please keep us posted here on the answer for it may be something that we can add to the docs to help other users. Thank you again for engaging with the community!

**Comment by jvsam** [comment]
Hi again @gabrielluizbh , we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help improve the contents of this document. 

Since this site is intended for product documentation, you can open a service ticket at https://support.microsoft.com/hub/4338813/windows-help?os=windows-10 if you require Windows 10 support. 

If you have feedback or suggestions related to Windows 10 features or products, please submit it to [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the engineering team and they would love to hear what you think.

Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
