### ISSUE TITLE
Release offline Edge browser offline installer

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#1900]
Why microsoft does not release offline edge browser for the offline  installation , Make compatible with MAC users and if possible release  for the  windows 7 , 8.0 . 8.1  and 10  operating systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Group Policy and Mobile Device Management settings for Microsoft Edge (Microsoft Edge for IT Pros)](https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @RAJU2529  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@RAJU2529 : Also, regarding Microsoft and various software package version releases, it is better to use the Windows Feedback Hub (WindowsKey + F) to provide your own feedback to the tech engineers who should deal with this type of question.

**Comment by RAJU2529** [comment]
Ok thanks sir. I will send now
