### ISSUE TITLE
Logs, event id and registry settings regards to Upgrade Readiness Mgmt Solution after running script

### ISSUE THREAD

**Issue by balait01** [MicrosoftDocs/windows-itpro-docs#1913]
Please advice about the logs, events & registry settings that need to be checked after enabling Upgrade Readiness Management Solution? How to confirm the windows machine is reporting to the solution after running the script

 

Tried generating the report from Upgrade Readiness Management Solution from Setting... But it doesn't show any invented windows machine info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 506a6414-1e08-61d5-a1f1-46d6b8280642
* Version Independent ID: 852c54dd-6610-1df4-10ed-9929c54e0c8e
* Content: [Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-overview)
* Content Source: [windows/deployment/update/windows-analytics-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-overview.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @balait01 the [Get started with Upgrade Readiness](https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-get-started) may be of help, including this article on the Tech Community Blog where it's indicated that *there is a delay of up to 72 hours between the time you run our deployment script*:

https://techcommunity.microsoft.com/t5/Windows-Analytics-Blog/You-can-now-check-on-the-status-of-your-computers-within-hours/ba-p/187213

We hope that you were able to successfully configured Windows Analytics since you've opened this ticket. Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring the contents of the Microsoft Docs are accurate and up-to-date.

**Comment by jvsam** [comment]
Hi again @balait01 , we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help improve the contents of this document. 

Since this site is intended for product documentation, you can open a service ticket at https://support.microsoft.com/hub/4338813/windows-help?os=windows-10 if you require Windows 10 support. 

If you have feedback or suggestions related to Windows 10 features or products, please submit it to [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the engineering team and they would love to hear what you think.

Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
