### ISSUE TITLE
Detailed Steps to Enroll Win7,8.1 and 10 in Windows Analytics

### ISSUE THREAD

**Issue by amrik2309** [MicrosoftDocs/windows-itpro-docs#1923]
Can someone write a detailed step by step of enrolling the different Operating Systems with screenshots ? Its ridiculous to have so my hyperlinks on single page and doesn't solve the purpose....as usual one of the most pathetic experience from Microsoft's documentation.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@amrik2309 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by amrik2309** [comment]
First response roughly after 6 months after opening the bug, I feel so blessed. No offenses to anyone, but this actually concludes that either Microsoft is least bothered or they are slammed with issues so much that they dont have time to look at other problems or low priority issues. Regardless, there is a long way for Microsoft to improve on documentation on many aspects. I am sure I must have pasted the link while opening the issue, but dont know what happened here. I just cant wait for another 6 months for second response and by that time I am sure I wont even remember the issue or the technology itlsef might be outdated.

**Comment by jaimeo** [comment]
@zdvorak please advise.

**Comment by mypil** [comment]
@jaimeo @zdvorak  - We would like to follow up. Do you have any updates on this?

**Comment by mypil** [comment]
@jaimeo @zdvorak - We would like to follow up. Do you have any updates?

**Comment by zdvorak** [comment]
@mypil , apologies but I'm not exactly sure how to fulfil this ask.  Device enrollment for Windows Analytics involves installing a few Windows updates, setting a few policies/regkeys, and then running a PowerShell script _on the client machines themselves._  Since all of these things can be done in many different ways and the exact steps will vary by customer, we don't really have a way to provide step-by-step screenshots of the process.  However, we do link out to a few of the common methods for things like setting a diagnostic data level and downloading Windows quality updates from the Update Catalog.  And while the specifics (like which quality update applies) vary a bit for the different OS versions, the overall steps are the same.  They are outlined on this article: https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started.  

The best way to get prescriptive guidance about what is needed to enroll a particular device in WA is to check the deployment script logs on that device.  They will highlight any prerequisites that are not met, as well as any issues that may have been encountered when attempted to configure the device. 

Let me know if there's anything else I can do to help!

**Comment by mypil** [comment]
@amrik2309 - From our understanding, the issue you raised has been answered by zdvorak. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
