### ISSUE TITLE
Force custom lockscreen wallpaper does not work on windows 10 pro

### ISSUE THREAD

**Issue by rasmuseeg** [MicrosoftDocs/windows-itpro-docs#1946]
I believe this content only applies to education and enterprise? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0286c17f-aca8-c9bc-597c-86b70165c72e
* Version Independent ID: be2bdcde-8667-4ff5-c4e5-bd50696d9341
* Content: [Configure Windows Spotlight on the lock screen (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/windows-spotlight)
* Content Source: [windows/configuration/windows-spotlight.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/windows-spotlight.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by rasmuseeg** [comment]
You should probably also include a link on how to manually change it.

So it's no longer possible to use Gpo to change lockscreen?
________________________________

**Comment by jdeckerms** [comment]
@rasmuseeg The lock screen Group Policy setting is for Windows 10 Enterprise or Education only. You can configure a lock screen image in a provisioning package (https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-personalization), however for it to work on Windows 10 Pro, you also need the SetEduPolicies settings (https://docs.microsoft.com/en-us/windows/client-management/mdm/personalization-csp).

**Comment by rasmuseeg** [comment]
Well that sounds durable. Yet unnecessary limitation? :-/
________________________________

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@rasmuseeg 

This issue has been addressed with the following commit and content has been updated according to your feedback.

[[fdd6437]   Merged PR 12353: clarify lockscreen image group policy ](https://github.com/MicrosoftDocs/windows-itpro-docsURL/commit/fdd643708354bc5d62d42d1d1d3580ff0182e71f)

We are thus closing this issue since it seems to be resolved. Feel free to re-open it if you feel it hasn't been resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
