### ISSUE TITLE
Terminated Credential Guard

### ISSUE THREAD

**Issue by jkd2020-github** [MicrosoftDocs/windows-itpro-docs#1984]
I have tried the suggestions on the Microsoft's support page https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide
But still have been unable to clear whatever switch is needed to allow VM to run. Any other suggestions? I am running to the point of having to reinstall Windows to get it cleared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c2cb44-269d-3334-019a-726eb5432f1c
* Version Independent ID: 251024cc-b818-18c6-a112-4ac0276cb4b1
* Content: [Manage Windows Defender Credential Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#enable-credential-guard-by-using-the-registry)
* Content Source: [windows/security/identity-protection/credential-guard/credential-guard-manage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @jkd2020-github Did you ever get this to work? We did not get enough information from you but perhaps these related issues that contain recommendations from the community may be of help - [1776](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1776) and [1915](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1915).

Otherwise, I would recommend opening a service ticket in your tenant so you can get your issue resolved ASAP. Please follow this link to contact support for Windows 10: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date.

**Comment by jkd2020-github** [comment]
I appear to be working. Thanks for the follow up. 

Sent from Yahoo Mail on Android 
 
  On Sun, Jun 9, 2019 at 11:52, Jo<notifications@github.com> wrote:   
Hi @jkd2020-github Did you ever get this to work? We did not get enough information from you but perhaps these related issues that contain recommendations from the community may be of help - 1776 and 1915.

Otherwise, I would recommend opening a service ticket in your tenant so you can get your issue resolved ASAP. Please follow this link to contact support for Windows 10: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date.

**Comment by jvsam** [comment]
That's great @jkd2020-github . Glad to hear it. 

We will now close this issue. If there is anything in this article that you think should be added or edited, please let us know. Thank you for engaging with the community!

**Comment by jvsam** [comment]
@officedocsbot close
