### ISSUE TITLE
Feature Update 1709

### ISSUE THREAD

**Issue by bally-singh** [MicrosoftDocs/windows-itpro-docs#1991]
Hi All,

Can someone please confirm what the default settings are for Feature Updates?

This would be for the following settings:

Update/AutoRestartDeadlinePeriodInDaysForFeatureUpdates
Update/EngagedRestartDeadlineForFeatureUpdates
Update/EngagedRestartDeadlineForFeatureUpdates
Update/EngagedRestartSnoozeScheduleForFeatureUpdates
Update/EngagedRestartTransitionScheduleForFeatureUpdates

It appears that in 1809 you can configure the above, however, in any version of Windows prior to this it's not possible. We are on 1709.

We want to use Intune & WufB to deploy updates. For deferral or pausing of updates this will take place at the Intune layer.

However, I need to understand how often a user can reschedule and when we can confirm that all users machines have been updated. This is imperative from a compliance and support perspective.

Users will be on laptops so I cannot guarantee that these will be powered on outside of core hours. Therefore, I want to apply 'Auto install and restart at a scheduled time', but allow users to defer updates as necessary. Hence the need to understand the default deadlines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @bally-singh Were you able to find the information you need since you've opened this ticket? If not, I believe the best course of action is for you open a service ticket in your tenant so you can get your answers ASAP. Please follow this link to contact support for Windows 10: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

Please keep us posted here on the resolution or any information that can be called out in the docs. We want to make sure that contents of the Microsoft Docs are always useful and up-to-date.

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi again @bally-singh , we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help improve the contents of this document. 

Since this site is intended for product documentation, you can open a service ticket at https://support.microsoft.com/hub/4338813/windows-help?os=windows-10 if you require Windows 10 support. 

If you have feedback or suggestions related to Windows 10 features or products, please submit it to [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the engineering team and they would love to hear what you think.

Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
