### ISSUE TITLE
Windows Hello in combination with Assigned Access 

### ISSUE THREAD

**Issue by devgaia** [MicrosoftDocs/windows-itpro-docs#1999]
Please explain how Assigned Access / Auto Login and Windows Hello interact. We seem to have a problem where the user is auto logged in but the "Enter PIN dialogue" is shown behind the app set up for assigned access. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@devgaia Which method are you using to configure the kiosk, and which account type does your kiosk use?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @devgaia were you able to successfully configure your kiosk to work with Windows Hello? Would you mind letting us know of the status? If you haven't been successful, I recommend that you open a service ticket in your tenant so this can be resolved ASAP. Please follow this link to contact support for Windows 10: https://support.microsoft.com/hub/4338813/windows-help?os=windows-10

Please keep us posted here on the resolution and if there is something that can be called out in the docs. We want to make sure that contents of the Microsoft Docs are always useful and up-to-date.

Thank you for engaging with the community!

**Comment by jvsam** [comment]
Hi again @devgaia , we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help improve the contents of this document. 

Since this site is intended for product documentation, you can open a service ticket at https://support.microsoft.com/hub/4338813/windows-help?os=windows-10 if you require Windows 10 support. 

If you have feedback or suggestions related to Windows 10 features or products, please submit it to [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the engineering team and they would love to hear what you think.

Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
