### ISSUE TITLE
Is L2TPv3 Supported?

### ISSUE THREAD

**Issue by timedroid** [MicrosoftDocs/windows-itpro-docs#2020]
Does Windows support tunneling Ethernet data using L2TPv3? Previous versions of L2TP didn't support this from what I understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746fd1a2-12c0-692c-f22a-251b370df7d7
* Version Independent ID: 71ca5f84-9afb-4007-6d2d-db953756feca
* Content: [VPN connection types (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-connection-type)
* Content Source: [windows/security/identity-protection/vpn/vpn-connection-type.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/vpn/vpn-connection-type.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
Hello, @timedroid  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
