### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by rlyons38** [MicrosoftDocs/windows-itpro-docs#2025]
Trying to follow this to get to grips and at the "Assign a Windows Autopilot deployment profile" bit, there is no "Assign profile" to click on.
Googled else where to find that you assign the profile to a group and add the new machine to that group for it to apply. But unfortunately, this didn't work and the AutoPilot profile did not apply to the machine on startup.
I still haven't got this working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment on a VM](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by alutgert** [comment]
Hi Ross,

You can do this in the Microsoft Business Store. Check out my post 

https://vmlabblog.com/2019/01/autopilot-lab-part-4-add-vm-to-intune

I hope this will help you!

regards Aad

**Comment by alschneiter** [comment]
Or use a dynamic group to assign devices to the profile: https://docs.microsoft.com/en-us/intune/enrollment-autopilot#create-an-autopilot-device-group

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @rlyons38 have you had a chance to review the document again? There had been several updates since you've opened this issue. On the [Create and assign a Windows Autopilot deployment profile](https://docs.microsoft.com/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm#create-and-assign-a-windows-autopilot-deployment-profile) section, under *Assign Profile*, you'll see links for the following that may help: 

[Create an Autopilot device group and Assign](https://docs.microsoft.com/intune/enrollment-autopilot#create-an-autopilot-device-group)
[Autopilot deployment profile to a device group](https://docs.microsoft.com/intune/enrollment-autopilot#assign-an-autopilot-deployment-profile-to-a-device-group) (Same link provided by @alschneiter )

We haven't received any response from you so hopefully you were able to successfully set-up Windows Autopilot deployment. Would you mind letting us know of the status? If there is anything in article that you think should be added or edited, please let us know. We always welcome suggestions and feedback to improve the docs.

**Comment by jvsam** [comment]
Hi @rlyons38, we haven't received any response or update from you so we will now close this issue. Please feel free to re-open it if you have comments or suggestions to help *improve the contents of this document*. 

Since this site is intended for product documentation, you can open a service ticket at https://support.microsoft.com/hub/4338813/windows-help?os=windows-10 if you require Windows 10 support. 

If you have feedback or suggestions related to Windows 10 features or products, please submit it to [User Voice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Your feedback goes directly to the engineering team and they would love to hear what you think.

Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
