### ISSUE TITLE
Add-ProvisioningPackage fails. Would like to view logs mentioned above

### ISSUE THREAD

**Issue by whampt** [MicrosoftDocs/windows-itpro-docs#2037]
What is the default path of the log folder referenced above? Please provide.

ProvTrace.&lt;timestamp&gt;.ETL - ETL trace file, unfiltered 
and others

Having a provisioning package with a layoutmodification.xml and a default app xml file that is failing to apply, don't know why. Would like to debug and log would help a lot.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9d3111-a801-5fbd-51fd-182c9fcde05d
* Version Independent ID: b6515ca3-15f5-5a24-0aea-612c0f5867ab
* Content: [PowerShell cmdlets for provisioning Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-powershell)
* Content Source: [windows/configuration/provisioning-packages/provisioning-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-powershell.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@whampt I checked with the team; they said logs should be saved to the path you provide with the -LogsFolder parameter when you run the cmdlet or else current directory.

Also, you might check in Event Viewer: Applications and Services Logs > Microsoft > Windows > Provisioning-Diagnostics-Provider. I'm not sure what specific events show up there, but since you're having a provisioning failure, there might be some clues there.
