### ISSUE TITLE
give me direct download link of ACT 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#2058]
i want to download this  act which should be compatible with windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3bbc4c-2f86-d5a9-336c-93695ace49f2
* Version Independent ID: a7c51e81-2cb2-5ad0-a9b5-7fb89921a0be
* Content: [Application Compatibility Toolkit (ACT) Technical Reference (Windows 10)](https://docs.microsoft.com/en-in/windows/deployment/planning/act-technical-reference)
* Content Source: [windows/deployment/planning/act-technical-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/act-technical-reference.md)
* Product: **w10**
* GitHub Login: @eross-msft
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @- thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.

**Comment by e0i** [comment]
@officedocsbot close
