### ISSUE TITLE
Best practices mismatch

### ISSUE THREAD

**Issue by andlommy** [MicrosoftDocs/windows-itpro-docs#2101]
MS Security baseline available at
https://blogs.technet.microsoft.com/secguide/2018/10/01/security-baseline-draft-for-windows-10-v1809-and-windows-server-2019 states recommended minimum password age is 1 day, whereas this document suggest minimum password age of 2 days. Which of the recommended values is the actual recommended best practice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f30760-4999-dcb1-26da-097477dc31bc
* Version Independent ID: 6cef6a81-a4aa-bb3b-4f1c-78cf98aba958
* Content: [Minimum password age (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/minimum-password-age#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/minimum-password-age.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by egallagh** [comment]
Hi andlommy.
A few things to consider: The security baseline referenced in the blog you link to is a draft, not a final document. That blog page does invite your comments on the draft proposals for the baseline.
Also a security baseline and a best practice are not necessarily the same thing and therefor not inconsistent even though they may differ. You might view a security baseline as a set of security minimums that should be implemented as a best practice. You could also have the viewpoint that the security baseline minimums are just that: minimums. You may want to vary the baseline settings to increase security where feasible as a best practice.
So in this case the security baseline says 1 day but the more secure setting in the best practice says 2 days.
I hope that helps a little
Ed

**Comment by andlommy** [comment]
Sorry, my alias should state i'm an MSFT employee, forgot to update it..
The security baseline documentation in the blog was updated for last 15 years or so, SCM initially, now in form of blogs and excel spreadsheet. 

Customers around the world use it as a point of reference of how microsoft recommends it. 
The problem is that once there is a discrepancy, there is confusion.
I've reached out the blog owner (Aaron) and to the MS security community and the answer was united - 2 days is excessive and does not yield any benefit, nor there is any explanation provided as to why this is deemed "more secure". The only reason to have a minpwd age is to delay the user changing their pwd. 2 days is not by an inch more secure than 1 day.

**Comment by egallagh** [comment]
Salute to the Blue Badge!
Actually there is a reason. Delaying the password change prevents someone from cycling through their password history count to get back to their original password, effectively not changing it in the first place. I know people that have done this.
I do agree that 2 days vs 1 day is not really more secure in a practical sense. Unless of course you are only keeping a history of a very few ( 1 or 2 ) previous passwords, in which case 2 days would double the amount of time to cycle back to your original. But in that case you  password history setting is a fault. Does if feel like I'm over analyzing this because I am? :-)

**Comment by andlommy** [comment]
Exactly. Just need the content owners of this best practice to change it back to 1 unless there's a better reason for having it at 2, in such case it should be stated here and then the security baseline should be updated as well...

**Comment by Justinha** [comment]
@andlommy @egallagh Thanks for the discussion guys. It's been changed to 1 to reflect the security baselines, and I added a similar example to the one Ed mentioned.

**Comment by Mike-Crowley** [comment]
The minimum password age is only relevant if users are required to change their password based on a time interval. Because Microsoft's official position is to no longer require password expiration, (as well as strong guidance from NIST), it would seem this min age recommendation should actually be removed all together. 

e.g. https://pages.nist.gov/800-63-FAQ/#q-b5

**Comment by Justinha** [comment]
@Mike-Crowley great point, thanks Mike. We'll change or remove this when the security baseline changes. As of now, it still recommends 1 for Windows 10 version 1809.
