### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by shiomr** [MicrosoftDocs/windows-itpro-docs#2103]
Windows こんにちは for Business が散見されます。
Windows Hello for Business に統一して下さい。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 13c400ea-f52d-b45b-a871-31c94262084d
* Version Independent ID: 9465e043-990f-cb8b-2d4b-33dc8d3c21bf
* Content: [Active Directory の前提条件の検証 (Windows Hello for Business)](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/identity-protection/hello-for-business/hello-cert-trust-validate-ad-prereq.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by mypil** [comment]
@samanthaw @MollyMalone 

cc: @AndreaBarr

**Comment by illfated** [comment]
@shiomr : Unfortunately, I can't read kanji or speak Japanese, so I put some of the issue text into Google Translate. This is the output:
***
Windows Hello for Business will be seen here and there.
Please unify with Windows Hello for Business.

#### Document Details
⚠ _ Do not edit this section. Required at docs.microsoft.com リンク Link of GitHub problem. _
***
I would like to mention what @DaniHalfin commented in a previous issue concerning Japanese content, https://github.com/MicrosoftDocs/windows-itpro-docs/issues/2761#issuecomment-466838921
> Our localized content doesn't offer the ability to directly contribute [ ... ]

If you are looking for ways to contribute to the content of a localized language page, the Microsoft Docs team will have to forward your request for changes and improvements to other Microsoft technicians.
(You may want to add more details about your issue so the MS techs will fully understand what the issue is about.)

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
