### ISSUE TITLE
Users not getting install notifications

### ISSUE THREAD

**Issue by atfernando** [MicrosoftDocs/windows-itpro-docs#2139]
I have set up auto update with the option 3 but users don't get notifications to install updates. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-restart.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by DaniHalfin** [comment]
Have you checked that the settings apply?
@jaimeo - can you have a look. We haven't described any dependencies for AUOptions = 3, but we should maybe make sure we're not missing something in the docs?

**Comment by atfernando** [comment]
@DaniHalfin Thanks for the comment. Yes, I have. 
 I have the following keys in the registry.
![ws update reg](https://user-images.githubusercontent.com/13582810/48679660-1eb5be00-ebe7-11e8-8d67-d5732a0b0342.jpg)

**Comment by e0i** [comment]
Hello, @atfernando thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

Thanks.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure_
