### ISSUE TITLE
UseRemotePassport not detailed

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windows-itpro-docs#2156]
What does UseRemotePassport enable? Does this mean we can authenticate using the Microsoft Authenticator App?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4180b6e-2786-ffb0-8f92-e4456dc343c9
* Version Independent ID: 7722d866-c095-b806-1da8-17e00cfe9a0a
* Content: [PassportForWork CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/passportforwork-csp)
* Content Source: [windows/client-management/mdm/passportforwork-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/passportforwork-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Martony78  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by Martony78** [comment]
This a documentation question, not a problem. I am asking what is the purpose of « useremotepassport » since the documentation does not explain it.

**Comment by e0i** [comment]
@Martony78 Thank you for providing clarification.

We'll pass this issue to technical writing team for review and keep you posted on updates.

Regards.

**Comment by illfated** [comment]
@Martony78 : Based on what I can read from the existing documentation, I understand this to be a method of using 2 units, 1 desktop computer which has already been joined to Azure AD, and 1 registered portable device acting as a companion device to authenticate via Windows Hello for Business by validating the login on the portable companion device. (This should be completely different from the Microsoft Authenticator App, because it uses Windows Hello communication.)

**Comment by e0i** [comment]
@Martony78

Would you confirm that illfated's answer provides a sufficient explanation to your question?

Please indicate whether the documentation might still benefit from an update and we'll proceed accordingly.

Thank you for taking the time to provide feedback and following up.

**Comment by Martony78** [comment]
I understand what it means, but you still don’t explain how it works. Anyway I’ll figure out myself ...

**Comment by illfated** [comment]
OK, I presume you are looking for something like "Step-by-step how to set up and configure PassportForWork" in a similar style to this page:
- https://configmgrblog.com/2016/01/27/support-for-microsoft-passport-win10-for-work-added-to-intune/

I could be wrong, but I think that an image-by-image configuration walkthrough belongs in a different page.

**Comment by lindspea** [comment]
@Martony78 Please advise if you have managed to sort out this issue or if you still need further assistance?

**Comment by e0i** [comment]
@Martony78 

From our understanding your question has been answered based on existing documentation.

Since we haven't got a follow-up from your side, we are marking this issue as resolved.

Feel free to re-open it with your suggestions if you feel that the documentation is still not sufficient.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by Martony78** [comment]
It has not been answered,
I know perfectly how to configure Windows Hello for Business using Intune or GPO but I have never heard about "UseRemotePassport" and the link provided by @illfated does not help at all since it does not mention the "UseRemotePassport". I am really scared to notice no one at Microsoft knows how to configure this setting and what it does... If it is deprecated, just mention it.

**Comment by Martony78** [comment]
Seems like the answer I am looking is here:
https://docs.microsoft.com/en-us/windows/uwp/security/companion-device-unlock

And as I presumed it is (or will soon be) obsolete...

**Comment by illfated** [comment]
Thank you for posting again, as well for the update regarding the solution.
I was just about to go searching for a page suggesting the solution.
Also for the bit about the solution might becoming obsolete.
