### ISSUE TITLE
Non-Hybrid Machines

### ISSUE THREAD

**Issue by rlawrimore** [MicrosoftDocs/windows-itpro-docs#2172]
Can something similar be done with machines from bare metal. We would like to be able to use SCCM to lay down the base image without being domain joined and have the machine go through the OOBE and automatically join AAD.

1. Boot from USB media

2. Select the Task Sequence

3. Install the OS (sysprepped image)

4. Join AAD and be enrolled in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @rlawrimore thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.

**Comment by e0i** [comment]
@officedocsbot close
