### ISSUE TITLE
Limitations and unintended side effects of apply Sensitivity Labels on Windows 10 and  other clients.

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/windows-itpro-docs#2200]
Hi can you confirm that if sensitivity labels are applied. from Public to Highly Confidential then what is the impact on eDiscovery, co-authoring, search, delve in each case. Obviously, enabling encryption is going influence the list as mentioned but to what degree? We are trying to weigh up site / library permissions against these labels and how they can both work in harmony. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561d91d8-458d-bc0c-45af-c0a9ccacee93
* Version Independent ID: 7c1fd8f1-74b6-f7d4-fcb0-0e41a0d6ff42
* Content: [How Windows Information Protection (WIP) protects files with a sensitivity label (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels?branch=vsts17546553)
* Content Source: [windows/security/information-protection/windows-information-protection/how-wip-works-with-labels.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels.md)
* Product: **w10**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@westerdaled great question. I'm sharing some replies from our engineering partners and I will look to add these points to the topic to help clarify. Let me know if this does not help answer your question.

WDATP can add WIP protection if the applied label says the file should have it. WIP files are either indexed locally for search or not based on the WIP policy selection for search (we recommend allowing it, since otherwise Outlook can’t search your work mail).  

To clarify the difference between WIP and Azure Information Protection (AIP (aka RMS)) encryption:

1.	AIP encryption is applied directly to content, and roams with the content as its moved between locations and cloud services. When an RMS encrypted doc is stored in a cloud service like SharePoint Online, then co-auth, eDiscovery, Search, Delve, and so on are impeded because the content isn't scanned/decrypted. Our engineering teams are working on this problem. 
2.	WIP applies to content when its stored directly/locally on a Windows desktop. WIP uses encryption in the background to restrict access and protect content, however the encryption does not roam with the content when its moved off the desktop. Enabling WIP will have no impact on things like co-auth, eDisc, Search, and so on when the content is stored in SharePoint Online. 
        Note, there is a WIP feature that will AIP encrypt a doc on egress - but that still falls back to #1 above.

Head over to https://aka.ms/managemip for more about labels and how each setting works.
