### ISSUE TITLE
Outdated endpoints

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2231]
Endpoints not up-to-date with info at https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#enable-data-sharing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f58247e6-b6a8-e172-941d-b18ee3753a55
* Version Independent ID: b05fe5e8-3490-219a-d0dd-cdbd4c387886
* Content: [Upgrade Readiness data sharing](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-data-sharing)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-data-sharing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-data-sharing.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by greg-lindsay** [comment]
Sorry for the extremely late reply. This should have been assigned to another writer and got lost until I created a more foolproof query for issues assigned to me.

At this time we can't address the doc since the solution is being retired on Jan 31st. https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-overview
