### ISSUE TITLE
Info on group policies effects on AV state

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/windows-itpro-docs#2257]
I would like to see here some reference to the effect of policies like "Turn off Windows Defender Antivirus" and "Turn off real-time protection" may have on WDAV state transitions when 3rd-party AV is installed.
For example, Symantec Endpoint protection recommends DisableAntiSpyware=1 at https://support.symantec.com/en_US/article.TECH237177.html. Although refers specifically to WS2016, I've seen 3rd party AV customers using the same to turn off WDAV in favor of the other AV solution.
Such setting would adversely affect WD-ATP enrollment (https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/troubleshoot-onboarding-windows-defender-advanced-threat-protection#ensure-that-windows-defender-antivirus-is-not-disabled-by-a-policy). 
And the other way around, the effect on having DisableAntiSpyware=0 set when third party AV is installed and the ability of WDAV to go autodisabled or passive.
 
Would also like to see documented the effects of such WDAV policies set (either Enabled/Disabled) on the ability of WDAV to take over 3rd party AV if it goes outdated/stopped/corrupted, etc.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b88aee4-6727-fa98-1180-29708eea027e
* Version Independent ID: 374c671b-b21c-6eac-d887-892491357eb2
* Content: [Windows Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/windows-defender-antivirus-compatibility.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@juanand - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @juanand , I have gone through your query and found the following doc (https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/use-group-policy-windows-defender-antivirus) that describes the complete set of WDAV policies and its implication when those are enabled or disabled. 

For your second query, WDAV is programmed in a way that if something goes wrong with 3rd party AV it will automatically enable and start the protection. Please see

"The automatic disabled mode is enabled so that if the protection offered by a third-party antivirus product expires or otherwise stops providing real-time protection from viruses, malware or other threats, Windows Defender AV will automatically enable itself to ensure antivirus protection is maintained on the endpoint. It also allows you to enable limited periodic scanning, which uses the Windows Defender AV engine to periodically check for threats in addition to your main antivirus app."

**Comment by mypil** [comment]
@juanand - From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
