### ISSUE TITLE
Mapping OID to a universal user group

### ISSUE THREAD

**Issue by pkiluke** [MicrosoftDocs/windows-itpro-docs#2319]
In the Deep Dive into Credential Guard video #7 at around 12:20 Seth talks about running scripts to map an OID to a universal user group. Could anybody please point me to a reference on how to do that?

Thank you.

**Comment by e0i** [comment]
Hello, @pkiluke  thank you for your question.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
