### ISSUE TITLE
PDF Issues in Edge Kiosk

### ISSUE THREAD

**Issue by WatsonNet** [MicrosoftDocs/windows-itpro-docs#2324]
Embedded PDF's on Web Pages appear to work fine, new Tabs are created correctly when clicking links.
However we have an api that connects from our webpage that pulls PDF's from a local HPE CM Instance. These PDF's (and other .docx/.xlsx Docs) are pulled correctly, Edge asks to "Open or Save", but either option attempts to produce a new Browser window, rather than a new tab. This results in the default homepage being opened again, rather than the document requested. Is there any way to force Edge to open all documents without prompting (Kiosks don't need to save) and force new tab versus new window?? All GPO settings I have tried have been ineffective so far.

Thanks in advance.

**Comment by e0i** [comment]
Hello, @WatsonNet  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

**Comment by e0i** [comment]
@officedocsbot close
