### ISSUE TITLE
Stray "Persistent" at end of AutoTrigger description

### ISSUE THREAD

**Issue by tycastMSFT** [MicrosoftDocs/windows-itpro-docs#2329]
The last line in the AutoTrigger description is "Value type is bool. Persistent". The "Persistent" part of this string looks isolated and out-of-place and should be removed since it's a bit confusing to have it there (for example, it looks like there might be a dependency between the AutoTrigger and Persistent settings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b1b81d-3c35-0315-d149-f10af3a409b2
* Version Independent ID: c34e7acb-ece7-d76f-fb41-470e19119ee0
* Content: [VPNv2 CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp)
* Content Source: [windows/client-management/mdm/vpnv2-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/vpnv2-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@tycastMSFT : Thank you for making us aware of this issue. The misplaced text has been removed in the Pull Request **Code Change And Typing Issue** #3149 (as you can see above) and is now merged into the docs. As you probably know, it usually takes a couple of days for the change to migrate to the docs.microsoft.com pages, but since it has taken some extra days to follow up on this issue page, it is now also present in the public pages.

You may also notice that issue ticket #1330 (**Node 'DomainNameInformation' no longer exists**) pointed out that `DomainNameInformation` no longer works, so that keyword has also been replaced by `DomainNameInformationList` instead. Although it has taken some time to follow up on the issues from last year, these issues are now handled and should be completed.

**Comment by tycastMSFT** [comment]
Great – thank you! – TCC

**Comment by mypil** [comment]
@tycastMSFT - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by tycastMSFT** [comment]
Looks like this is fixed and the fix is public. Thanks!
