### ISSUE TITLE
Copy & paste the info?

### ISSUE THREAD

**Issue by TheRobinCM** [MicrosoftDocs/windows-itpro-docs#2355]
If the information about backing up the TPM recovery info to AD hasn't changed, can you not just copy & paste the information over to this page? Clicking the link takes me to a page with a banner across the top implying that the information is old (and thus may be out of date) and with a button that claims to take me to the "recommended version" (which would presumably be this page) but in fact takes me to a useless generic Windows 10 landing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb27d59c-e8d5-f6c7-fc0c-98e9a9dde96e
* Version Independent ID: 14a1583f-f007-6a89-2655-f4f3d9ecc415
* Content: [Back up the TPM recovery information to AD DS (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/backup-tpm-recovery-information-to-ad-ds)
* Content Source: [windows/security/information-protection/tpm/backup-tpm-recovery-information-to-ad-ds.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/tpm/backup-tpm-recovery-information-to-ad-ds.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TheRobinCM  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @TheRobinCM ,
As it states in the article, for windows 10 1507 and 1511 "The procedure is the same as it was for Windows 8.1", that's why there is a link to the related article for Windows 8.1

 **Clicking the link takes me to a page with a banner across the top implying that the information is old (and thus may be out of date)** - it is a standard banner which presents in all articles for the products with expired support period (including windows 8.1)

In this case, you can just ignore the banner and use the described methods for your Windows 10 1507 and 1511 implementations.

Thank you

**Comment by mypil** [comment]
@TheRobinCM - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
