### ISSUE TITLE
What part of easy and fast don't you understand?

### ISSUE THREAD

**Issue by jadelise** [MicrosoftDocs/windows-itpro-docs#2391]
The average staff IT admin wants a simple and fast way to install Features on Demand.  Lets discuss one category in particular that Microsoft has tried but always failed to accomplish this. RSAT. At first the msu packages had to be installed and then separately the features enabled, it worked, but it was slow and hard but not impossible to script. Lots of time for what simply should have been a Next&gt;Next&gt;Next installation.  Then with Windows 10 it was just one operation, improvement. Now with 1809 a backward step because in a WSUS environment the GPO setting is needed to download what is needed and WSUS itself cannot just enable so that security is maintained, of course the option of one or more shares could be set up and put in the GPO, once more extra work.  And of course you could wade through these docs to figure out what is needed to cobble together just the files needed from FOD 1 1809 to run a scripted (REALLY SLOW) RSAT install, Why? So all the other admins who will need RSAT can just click one button, go have coffee or lunch and have the RSAT installed easily.  Would it really have been that difficult to create an installation package and then let WSUS or WSUS for business update them through the regular WSUS update process?  What ivory tower do you guys live in.  The IT staff of most small to midsize companies don't have folks with the expertise or enough of them to take the time to kludge an install.  You just don't get it. Take your heads out of the "Cloud" for a moment and think about the folks in the trenches and remember every time you eliminate one more keystroke, one more mouse click, a shorter mouse swipe or faster hand gesture you do them an immeasurable service. Excelsior!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d423c0e-fd99-9ad5-a11a-45237c2149fc
* Version Independent ID: f30e4101-7a8e-bfa9-a7c0-de7c36499cf5
* Content: [Windows 10 - How to make FoDs and language packs available when you're using WSUS/SCCM](https://docs.microsoft.com/en-us/windows/deployment/update/fod-and-lang-packs)
* Content Source: [windows/deployment/update/fod-and-lang-packs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/fod-and-lang-packs.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by buffbiker23** [comment]
wow, that is the nicest criticism I've ever heard about Microsoft. I would not be so nice as I'm ready to blow a gasket over here after years of this MSBS

**Comment by seamonkey420** [comment]
OMG.. MS you just have ZERO FUCKING CLUE.. RSAT tools.. just leave it the way it was prior to 1809 since anything you add to any feature update of Win10 seems to go horribly wrong or goes undocumentated for months, years with not a single person at MS knowing what the fuck changed.  /rant Win10 admin... windows admin since Windows NT 4.0

**Comment by oleesch** [comment]
Couldn't agree more.

It's fascinating how complicated you can make something if you really try and somehow Microsoft are trying as if their lives depended on it. Now I can go ahead and justify to our security people why some random subset of our clients need to go talk with Windows Update even though all our updates are deployed via WSUS/SCCM. Or I can go ahead and change some GPO setting for everyone, deploy some files on a stupid network share(!), keep those up to date, and then either way I'm STILL going to need an SCCM application or package because Windows needs admin rights to install those features. This is completely ridiculous for something that should be a simple Next->Next->Finish installation.
