### ISSUE TITLE
Missing information on rule exclusions

### ISSUE THREAD

**Issue by Crazyphil** [MicrosoftDocs/windows-itpro-docs#2392]
The intro mentions 4 steps for troubleshooting, whereafter steps 1 (pre-requisites), 2 (audit mode) and 4 (support logs) are described. Step 3 (adding a rule exclusion) is the most crucial step if you want to resolve a false positive quickly without wanting to wait for a response from Microsoft. This step, however, is never described nor linked for further information in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4df15ae9-c8cb-ba48-2f07-c610f4a6cb78
* Version Independent ID: 529d4791-cc0c-2564-35b1-46866bb5e53f
* Content: [Troubleshoot problems with Network protection](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/troubleshoot-np)
* Content Source: [windows/security/threat-protection/windows-defender-exploit-guard/troubleshoot-np.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-exploit-guard/troubleshoot-np.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by illfated** [comment]
Reading through the document, it looks to me as if the author(s) may have considered that point self-explanatory, not needing any extra documentation.

**Comment by duluthit** [comment]
illfated, this is not self-explanatory.  The article starts by describing a scenario in which a website has been blocked incorrectly, then they proceed to list 4 steps for addressing this problem.  This is presented in an outline form which the article follows exactly, with the exception of the omission of step 3 - "Add exclusions for the specified rule (for false positives)".  This is a significant problem, because any IT Administrator would prefer to add an exclusion for a false positive instead of disabling their protection by switching it to "audit" mode.  Spend a couple minutes searching for a way to add a url exception to Windows Defender Exploit Guard Network Protection and you will understand why this missing information is extremely important and not self-explanatory.

**Comment by illfated** [comment]
duluhit, I concur. I just made the assumption about what could have caused the text to be like that.
What I should have done is to also say that it still needs clarification for the general audience.
If you can come up with a reasonably well worded version, we could create a PR to change it.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Crazyphil  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Crazyphil - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
