### ISSUE TITLE
Refers to OMS instead of Azure Solutions

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftDocs/windows-itpro-docs#2422]
Hi - looks like this needs a refresh for the OMS functionality move into the Azure portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f4189bc-bdd3-b634-9845-ed52bb520a25
* Version Independent ID: c98fd62b-df4b-4f12-d599-e3c0f7626cda
* Content: [Monitor the health of devices with Device Health](https://docs.microsoft.com/en-us/windows/deployment/update/device-health-monitor)
* Content Source: [windows/deployment/update/device-health-monitor.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/device-health-monitor.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
The replacement of references to OMS w/ references to Azure Portal isn't a direct 1:1 operation, so we are working with an Azure writer to ensure we get all the right changes in the right places. @bwren is helping us with that and we hope to complete the updates soon.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@markoshea1212 

This issue has had already been addressed with the following commit and content has been updated according to your feedback.

[[747018] cleaning up remaining references to OMS ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/74701833b55995a52407c9a1f04acc4ecee7e855#diff-e57dd497faab9faf95d355660866ff93)

We are thus closing this issue since it seems to be resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
