### ISSUE TITLE
Remote Guard SSPI failure after a period of time

### ISSUE THREAD

**Issue by ericcsinger** [MicrosoftDocs/windows-itpro-docs#2483]
We utilize a security model, in which we have a physical console and an admin workstation (VM).  We remote guard from our console into our admin workstation.  

I have noticed in typically less than 24 hours, my access to remote systems relying on keberose starts to fail with SSPI failures.  For example, if i try to connect to SQL after a few hours, from my admin workstation, i start to get denied access + SSPI errors.

I see this event in my admin workstation.
The Security System detected an authentication error for the server LDAP/%DOMAINCONTROLLER%@%DOMAIN%. The failure code from authentication protocol Kerberos was "Insufficient system resources exist to complete the API.
 (0xc000009a)".

We often disconnect and reconnect the physical console via remote guard to the admin workstation, but I've also seen this occur if I leave my console connected overnight.  Any ideas if this is expected behavior or how to troubleshoot it?

**Comment by e0i** [comment]
@ericcsinger

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by PeteRicha** [comment]
@ericcsinger: I have the same issue. Did you ever solve it? Did you have Device Guard enabled.
