### ISSUE TITLE
Single-app kiosk: can still open task manager and execute explorer.exe

### ISSUE THREAD

**Issue by milasch** [MicrosoftDocs/windows-itpro-docs#2524]
In the beginning of this page the following statement is misleading:
"When the kiosk account signs in, the app is launched automatically. The person using the kiosk cannot do anything on the device outside of the kiosk app."

I setup a kiosk on Windows 10 IoT Enterprise (1809) using the Windows Configuration Designed, for a classical app. It works fine the way I've set up but I'm still open to do open explorer.exe which brings the Windows Shell by:
- Opening Task Manager with CTRL + SHIFT + ESC
- Click More details
- Click on File menu, then "Run new task"
- Type explorer.exe and click OK.

How would I stop this? thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by illfated** [comment]
I'm not an expert on this, but I venture a guess that some form of Group Policy modification is needed to block access to Task Manager in some way.

**Comment by milasch** [comment]
Yeah, I found on [this page](https://docs.microsoft.com/en-us/windows/configuration/kiosk-policies) mentions on Remove Task Manager... Couldn't find anything in the Windows Configuration Designer though... Maybe it needs to be setup outside of the application after you run the package on the target system...

**Comment by jdeckerms** [comment]
@milasch I see you found the [Policies enforced on kiosk topic](https://docs.microsoft.com/en-us/windows/configuration/kiosk-policies) - as you saw, when you configure a device for kiosk mode, those are the policies that should be enforced automatically, including "Remove Task Manager". Please report the problem through the Feedback Hub so that the engineering team can be made aware of the issue. In the meantime, you can use Local Group Policy Editor to configure that policy yourself; the path is User Configuration > Administrative Templates > System > Ctrl+Alt+Del Options.
