### ISSUE TITLE
Single-App Kiosk mode with Edge: how not to clear cookies of sessions 

### ISSUE THREAD

**Issue by LasseWolpold** [MicrosoftDocs/windows-itpro-docs#2525]
Hello

I have set op Single-app mode with Edge, and links to a homepage, that requires cookies from last session. 
How do I disable automatic clearing of cookies (history) when inactivity initiate a new session?

I have Windows 10 pro version 1809.
My kiosk user is preconfigered.
 
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by LasseWolpold** [comment]
Correction: It's a key saved in local storage (in edge)

**Comment by jdeckerms** [comment]
@LasseWolpold Microsoft Edge in single-app kiosk mode doesn't retain user data across sessions. You can configure Edge to be the only app in a multi-app kiosk configuration so that you can select "Normal browsing" mode. For details, see [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
