### ISSUE TITLE
Where is the RequireNetworkInOOBE setting stored?

### ISSUE THREAD

**Issue by DavidVerbruggen** [MicrosoftDocs/windows-itpro-docs#2526]
We would like to have the hardware vendor (in the context of PCaaS in combination with Win10 Modern Management) preprovisioning this setting on our new devices.
In other words, we would like to have this behavior in place during OOBE and not only after a post-enrollment reset. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b2b84b-cf3a-9988-fef9-3d63de907f86
* Version Independent ID: eb60ef27-76ea-d7a1-7f25-e204cdfbd842
* Content: [TenantLockdown CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/tenantlockdown-csp)
* Content Source: [windows/client-management/mdm/tenantlockdown-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/tenantlockdown-csp.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @- thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

**Comment by e0i** [comment]
@officedocsbot close
