### ISSUE TITLE
Creating Groups

### ISSUE THREAD

**Issue by VonRoch** [MicrosoftDocs/windows-itpro-docs#2533]
Is there a way to create Autopilot groups besides when uploading a CSV of new devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc947476-4fc3-cbb1-26c2-1e7dedb7892f
* Version Independent ID: 16bf5a1f-00d8-ad55-f66f-a9a38f115bb6
* Content: [Manage Windows device deployment with Windows Autopilot Deployment](https://docs.microsoft.com/en-us/microsoft-store/add-profile-to-devices#device-information-file-format)
* Content Source: [store-for-business/add-profile-to-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/store-for-business/add-profile-to-devices.md)
* Product: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by e0i** [comment]
Hello, @VonRoch  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
