### ISSUE TITLE
"Active Directory-joined VMs" Section doesn't make sense

### ISSUE THREAD

**Issue by danielharkerdp** [MicrosoftDocs/windows-itpro-docs#2539]
So it tells us to create provisioning package, but doesn't tell us to do anything with it if we are running in Scenario 1 or 2?

Does anyone know how this fits in to a solution that uses Citrix Machine Creation Services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c34b8c-44b9-b3d3-9894-5a7fd68e2309
* Version Independent ID: ea643c8f-e92d-b90e-4e90-f338cea39e79
* Content: [Configure VDA for Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/vda-subscription-activation#azure-gallery-vms)
* Content Source: [windows/deployment/vda-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/vda-subscription-activation.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@danielharkerdp 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by MaratMussabekov** [comment]
Dear @danielharkerdp ,
**So it tells us to create provisioning package, but doesn't tell us to do anything with it if we are running in Scenario 1 or 2?** - as it states in the article, "If you must activate Windows 10 Pro as described for scenario 3, complete the following steps. Otherwise, skip to step 16", so for scenario 1 and 2 part with the package should be ignored

**Does anyone know how this fits in to a solution that uses Citrix Machine Creation Services?** - one of requirement is "VMs must hosted by a Qualified Multitenant Hoster (QMTH)." so no, it doesn't fit Citrix Machine Creation Services.

Thank you

**Comment by e0i** [comment]
@danielharkerdp Would you kindly clarify whether the response MaratMussabekov has provided answers your question? Thank you.

**Comment by e0i** [comment]
@danielharkerdp

We are closing this issue as we haven't heard from you regarding clarification for moving forward with updates.

Feel free to re-open this issue with clarifications and we'd like to follow up with updates.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by illfated** [comment]
From my point of view, the answer provided by MaratMussabekov is on point and precise enough to cover the questions. (I don't know how the OP sees it, though.)

**Comment by BRobertsGPH** [comment]
If you're using MCS in Azure and machines are joined to the Azure domain; Scenario 1 and 2 will work fine.
