### ISSUE TITLE
Locks after 1 minutes

### ISSUE THREAD

**Issue by WalterLuigi** [MicrosoftDocs/windows-itpro-docs#2551]
I have this option enabled for machines to be locked after 900 seconds (15 minutes), but some machines lock after roughly 60 seconds. I have verified the option is set properly in their registry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ab75c2-3bfd-bde6-8341-65ba79e9fe65
* Version Independent ID: 7224910c-ac05-26b2-f712-9a5993432615
* Content: [Interactive logon Machine inactivity limit (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit)
* Content Source: [windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@WalterLuigi Sorry you are having trouble. We'll need more info to help troubleshoot. Like what OS versions, are machines domain-joined or not, are there any local policies configured that could override the domain setting, and more. You could try running GPResult. For expert help, you can also contact Microsoft support.

**Comment by MidSpeck** [comment]
@WalterLuigi The locking after 60 seconds (it was the default 2 minutes for me) can also be caused by some wireless keyboards/mice.  In essence, if the computer is woken up with this device, then it considers it the same as being woken up from the network (e.g., the system doesn't consider this a user device and maybe no one is actually there) so it goes back to sleep much sooner.
If you are stuck with these devices, you'll want to find the setting "System unattended sleep timeout" (usually a hidden setting).

**Comment by andrewtchilds** [comment]
@WalterLuigi Same thing happened with a dozen or so machines in my environment after implementing this policy.

Found out that the machines it was happening on, the user had at some point checked the "On resume, display logon screen" option with a wait time of 1 minute through Control Panel, then unchecked it.

The fix is to remove registry value `ScreenSaveTimeOut` from key `HKEY_CURRENT_USER\Control Panel\Desktop`.

**Comment by illfated** [comment]
> Found out that the machines it was happening on, the user had at some point checked the "On resume, display logon screen" option with a wait time of 1 minute through Control Panel, then unchecked it.
> 
> The fix is to remove registry value `ScreenSaveTimeOut` from key `HKEY_CURRENT_USER\Control Panel\Desktop`.

Thanks, that is quite useful, even in my small environment of 20 users.
