### ISSUE TITLE
What is the value of this method?

### ISSUE THREAD

**Issue by scrubbles** [MicrosoftDocs/windows-itpro-docs#2571]
What is the value of this method over using the configurator tool to create an MSI? I'm not understanding, is it really just to avoid the installation of the Configurator tool, or are there other benefits that I am not seeing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ac548b-be6c-efba-76ee-67dd7af18891
* Version Independent ID: 947b62e7-1225-2f5e-14ba-fe5dccbbe124
* Content: [Use System Center Configuration Manager to manage devices with SEMM (Surface)](https://docs.microsoft.com/en-us/surface/use-system-center-configuration-manager-to-manage-devices-with-semm)
* Content Source: [devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/use-system-center-configuration-manager-to-manage-devices-with-semm.md)
* Product: **w10**
* GitHub Login: @KiranDavane
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@scrubbles It's just an alternate method, as the second paragraph explains.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @scrubbles

We are resolving this issue since your question seems to be answered by _jdeckerms_

Note that the issues section of this repository is intended for documentation feedback.

Please direct similar support questions via the following link so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
