### ISSUE TITLE
Visio PRO/STD Project PRO/STD in one APPV package..?

### ISSUE THREAD

**Issue by NotYourName** [MicrosoftDocs/windows-itpro-docs#2588]
In this scenario, how can you make ONE appV package and still give users access to both Visio Pro, std. and/or Project std/ pro? 

kind regards
Tore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f915edb-0ae6-5c7a-555c-8cc4c4110da5
* Version Independent ID: ca0d2b73-5aea-15b3-d8f8-8d2733695c72
* Content: [Deploying Microsoft Office 2016 by Using App-V](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/appv-v5/deploying-microsoft-office-2016-by-using-app-v#bkmk-deploy-visio-project)
* Content Source: [mdop/appv-v5/deploying-microsoft-office-2016-by-using-app-v.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/appv-v5/deploying-microsoft-office-2016-by-using-app-v.md)
* Product: **w10**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@NotYourName - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@NotYourName in order to give access to both Visio Pro, std. and/or Project std/ pro using just one App-V Package, you need to add Project and Visio as sepparate products in the XML file:

</Product>
<Product ID="VisioProRetail">
<Language ID="en-us" />
</Product>
<Product ID="ProjectProRetail">
<Language ID="en-us" />

I hope this was what you were looking for. If not, please let us know.
