### ISSUE TITLE
When user use pin for login in Windows 10, UNC drivers not work

### ISSUE THREAD

**Issue by KarlosFox** [MicrosoftDocs/windows-itpro-docs#2623]
Hello, when my users with AAD joined devices have configured UNC drivers with network credentials, after restart their devices if they login to Windows with only PIN maped drives cannot resolve saved credentials and show error with user have wrong acc/pass to access on network drive. So only one solution is log off user and relog not with pin but with AAD (O365) password. Can you tell me why it happen?

**Comment by illfated** [comment]
Sorry for not having a practical answer for you. I just wanted to note that your question looks a bit "out of place" when not reported from the doc page describing the related material.

Does your question relate to a specific doc page? If so, please consider placing the question at the bottom of that page instead of the current question without a template.

**Comment by andreabichsel** [comment]
For help with this issue, please try https://support.microsoft.com. Thank you!
