### ISSUE TITLE
Upgrading from 1709 educational to 1809 'business' edition using servicing plans in config manager.

### ISSUE THREAD

**Issue by PBrawn** [MicrosoftDocs/windows-itpro-docs#2632]
Is there a method to performing an in place upgrade from 1709 education edition to '1809 business edition' using configuration manager and servicing plans, or by just deploying the update that's available in config manager's updates section. I only see business and consumer editions available, so it's unclear as to what is the correct path to take.

Thanks,

Paul B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5da9a4b-1942-619f-5d8e-f9611603cce2
* Version Independent ID: e004360e-fb0f-c263-f093-bd2c27021d22
* Content: [Windows 10 edition upgrade (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades)
* Content Source: [windows/deployment/upgrade/windows-10-edition-upgrades.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/windows-10-edition-upgrades.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello, @PBrawn  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
