### ISSUE TITLE
Is there an opposite operation for this?

### ISSUE THREAD

**Issue by jeffdfield** [MicrosoftDocs/windows-itpro-docs#2635]
We removed OneNote UWP and we are going to upgrade to 1809, we want the upgrade to re-provision/install all of the Appx apps. Is there a registry key we can flip prior to the upgrade so it will?

**Comment by e0i** [comment]
Hello, @jeffdfield  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
