### ISSUE TITLE
ARM template fails to update the properties when Tags are not included.

### ISSUE THREAD

**Issue by amrik2309** [MicrosoftDocs/windows-itpro-docs#2668]

**Comment by amrik2309** [comment]
For the below template :- https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2018-11-01/routetables/routes
there are no tags that are defined in it, however if the Azure Policy of "Enable Tags and its value" is enabled on subscription then the above template fails to deploy since there is no tagging in it.

Code Snippet is below :-

{
  "name": "string",
  "type": "Microsoft.Network/routeTables/routes",
  "apiVersion": "2018-11-01",
  "properties": {
    "addressPrefix": "string",
    "nextHopType": "string",
    "nextHopIpAddress": "string"
  }
}

**Comment by VLG17** [comment]
@amrik2309 Although correct, you are describing a specific scenario, where you apply a policy which states that a tag needs to exist. In this case, of course the resourse deployment fails, because it does not have a tag. The article does not treat specific scenarios, such as this one.

In order to add tags via a JSON template, you can use the following expression:

"tags": {
    "TagName": "{\"TagValue1\":\"TagValue2\",\"TagValue3\":\"TagValue4\"}"
},

Please keep in mind that certain Azure resouces do not accept tags. More info [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/tag-support)

If this is still failing, please open a support case from the portal.

**Comment by amrik2309** [comment]
@VLG17 I don't think you even looked at the article that I mentioned. There is no property as tags for that particular resource and even if you specify, the deployment fails. Have a look at the article, test it out yourself for results.

**Comment by VLG17** [comment]
I don't quite understand what you mean by "There is no property as tags for that particular resource".

I have read the article you mentioned and it states that you need to "add the following JSON to the resources section of your template".

You need to create the resources section in your JSON template if it does not exist. After you create it and add what the article mentiones, you can also add tags. It should look something like this:

"resources": [
{
  "name": "string",
  "type": "Microsoft.Network/routeTables/routes",
  "apiVersion": "2019-04-01",
  "properties": {
    "addressPrefix": "string",
    "nextHopType": "string",
    "nextHopIpAddress": "string"
  }
}
]
"tags": {
"TagName": "{"TagValue1":"TagValue2","TagValue3":"TagValue4"}"
},

i will try and test this as soon as i can. In the meantime, could you please share the ARM template or at least the part of it which is not working in your case?

**Comment by e0i** [comment]
Hello @amrik2309  ,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
