### ISSUE TITLE
Not enough resources to display graphical panel

### ISSUE THREAD

**Issue by windson** [MicrosoftDocs/windows-itpro-docs#2669]
Hi,
I'm seeing 'Not enough resources to display graphical panel' when I upgraded the OS from Win 7 to Win 10 1809 build.
But, I don't see the error message 'Not enough resources to display graphical panel' when I upgrade from Win 10 1803 to win 10 1809 on the same machine

So I wonder if there are any changes related to graphics (or something that leads to the above error message) that were not carried from win 7 to win 10 1809 update but they were applied when upgrading from 1803 to 1809.
Any details on this will be of much help.

Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6356b-87ff-8c3a-56ef-1270a823d3ab
* Version Independent ID: 4d6ae878-66cf-0e10-bdf3-bdd6054cbc9d
* Content: [What's new in Windows 10, version 1809](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-1809#registry-editor-improvements)
* Content Source: [windows/whats-new/whats-new-windows-10-version-1809.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/whats-new/whats-new-windows-10-version-1809.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **trudyha**

**Comment by e0i** [comment]
Hello, @windson  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
