### ISSUE TITLE
0xc0290904 not listed

### ISSUE THREAD

**Issue by juanheraclio** [MicrosoftDocs/windows-itpro-docs#2676]
Hi, I am having this error code in windows Hello but I did not find how to solve it.
Any idea?
Thank you?
Windows hello worked fine until yesterday...

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Errores de Windows Hello durante la creación de PIN (Windows 10)](https://docs.microsoft.com/es-es/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @juanheraclio  Thank you for submitting feedback.

In our understanding the error code that you have noted might actually have surfaced from other services rather than _Windows Hello_ itself.

Find below a quoted reply from our Content Developer:

DaniHalfin wrote:
> For error codes unlisted here, in most cases those are transient error codes
> being surfaced by other services in the Windows Hello dependency chain.

> We are working on something to improve the user experience in that regard,
> but that will not solve the issues you are experiencing.

> If we find a reoccurring error codes that isn't covered here and should be
> (meaning, in most cases, it is coming from Windows Hello and not other
> components) we'll make sure to add it to this page.

Also note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider consulting to _Feedback Hub_ for any of your suggestions, questions or feature requests to help Microsoft improve your experience. Find the link to _Feedback Hub_ below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

We are closing this issue but feel free to re-open it if you feel that we might have missed something.

Have a nice day.

**Comment by e0i** [comment]
@officedocsbot close
