### ISSUE TITLE
RDP Connection caused on Azure VM

### ISSUE THREAD

**Issue by shivakumarg06** [MicrosoftDocs/windows-itpro-docs#2677]
Hello Team,  

Based on the Documentation & Tool, I have executed the script & update the Local Security Policy on Azure VM, after applying the Script, I couldn't able to reconnect  with the Machine on RDP, 

what will be the solution/ is that a Security recommendation for connecting the VM from Public IP address? 

Note: I have fixed the issues, I would like to understand more.

**Comment by e0i** [comment]
Hello, @shivakumarg06  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close
