### ISSUE TITLE
0x801c044f not listed...

### ISSUE THREAD

**Issue by spankin** [MicrosoftDocs/windows-itpro-docs#2684]
Cause and mitigation please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by E14** [comment]
It seems the solution is "wait". It started working again before support was available.

**Comment by robertrenner** [comment]
samehere 0x801c044f

**Comment by jesoj** [comment]
We also got this error, and it seems to be something regarding MFA not working or maybe canceled by user

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @spankin @robertrenner @jesoj  Thank you for submitting feedback.

In our understanding the error code that you have noted might actually have surfaced from other services rather than _Windows Hello_ itself.

Find below a quoted reply from our Content Developer:

DaniHalfin wrote:
> For error codes unlisted here, in most cases those are transient error codes
> being surfaced by other services in the Windows Hello dependency chain.

> We are working on something to improve the user experience in that regard,
> but that will not solve the issues you are experiencing.

> If we find a reoccurring error codes that isn't covered here and should be
> (meaning, in most cases, it is coming from Windows Hello and not other
> components) we'll make sure to add it to this page.

Also note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider consulting to _Feedback Hub_ for any of your suggestions, questions or feature requests to help Microsoft improve your experience. Find the link to _Feedback Hub_ below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

We are closing this issue but feel free to re-open it if you feel that we might have missed something.

Have a nice day.

**Comment by e0i** [comment]
@officedocsbot close
