### ISSUE TITLE
Controlled Folder Access events stopped working (1123)

### ISSUE THREAD

**Issue by the123blackjack** [MicrosoftDocs/windows-itpro-docs#2703]
@rpenner55
 For me also the CFA has stopped generating events, on blocks, you could not imagine , how anyone could manage and allow without events as guidance, This is affecting both 1803 and 1809 both on the latest patch 171134.523.

This was working fine until the latest patch Tuesday 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8746dd40-7ee5-ee09-0924-d56e18f8e2b8
* Version Independent ID: 14fc90f5-5168-4354-d792-7ec6d79e9a50
* Content: [Turn on the protected folders feature in Windows 10](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/enable-controlled-folders-exploit-guard)
* Content Source: [windows/security/threat-protection/windows-defender-exploit-guard/enable-controlled-folders-exploit-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-exploit-guard/enable-controlled-folders-exploit-guard.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by Praful** [comment]
The CFA events and notifications have stopped for me too on both 1803 and 1809. I couldn't work out why a newly installed PowerShell 6 couldn't create directories and chased for a while before going back to the working PS 5.1.

**Comment by mt7479** [comment]
@the123blackjack Thanks for posting this. Events are also not created with KB4487017 applied.

**Comment by e0i** [comment]
Hello, @the123blackjack  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

You might also keep us informed about the resolution of your ticket so that we can ensure this documentation is up to date with relevant information.

Have a nice day.

**Comment by e0i** [comment]
@AndreaBarr _Recommended closure_
