### ISSUE TITLE
Extended Windows Update Logging

### ISSUE THREAD

**Issue by dfter** [MicrosoftDocs/windows-itpro-docs#2709]
Dear, 

Under windows 7 you could configure Extended Windows Update logging :
 see the registry keys at https://support.microsoft.com/en-us/help/902093/how-to-read-the-windowsupdate-log-file

How do you do this in Windows 10 ?

Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47692487-0a0b-3b1b-6d34-790046c7cbc3
* Version Independent ID: 0f66cafe-2bff-4323-b3fc-01014b904b3a
* Content: [Windows Update log files](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs)
* Content Source: [windows/deployment/update/windows-update-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-logs.md)
* Product: **w10**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by e0i** [comment]
Hello, @dfter thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
