### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by dg4u** [MicrosoftDocs/windows-itpro-docs#2710]
Under "Technical overview" the following sentence "When the operating system an Encrypted Hard Drive..." there is missing word which is probably "detects".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a32b71-a846-3997-2983-2da1fdaf6efc
* Version Independent ID: 13dec6ea-bb0c-9e1a-07c7-a4f39386de06
* Content: [Encrypted Hard Drive (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/encrypted-hard-drive)
* Content Source: [windows/security/information-protection/encrypted-hard-drive.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/encrypted-hard-drive.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
👍 I concur. Good point.
In my head, I tried out various other ideas, like "has found" or "runs from", but none of my ideas were nearly as likely as you suggestion for the described scenario.
Would you like to open a Pull Request for this change, or do you prefer me opening the PR?

**Comment by dg4u** [comment]
I don't understand how PR and GitHub works, so feel free to do whatever is required to correct the documentation.

**Comment by illfated** [comment]
Looking back at the text previous to the sentence with the missing word, it looks like the missing word could be "identifies". I will open a Pull Request with the suggestion "identifies" as the missing word, since the detection procedure is supposed to be like this:
- Identification
- Activation
- Configuration
- API
- BitLocker support

Feel free to reply, suggest or disprove my suggestion, either here or in the PR I will link back to this issue.
