### ISSUE TITLE
Easy Jump Link for Windows Home Subscribers

### ISSUE THREAD

**Issue by lmstearn** [MicrosoftDocs/windows-itpro-docs#2763]
This page (clicked from the Windows Defender block systray link) will want to have a section for Windows Home viewers who have no access to the GP editor.
Thus, on Home computers, link directly to a new _Confirm Block at First Sight is enabled on individual clients_ jump link.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by illfated** [comment]
Good idea. If anyone could suggest the appropriate text and where it should be placed, I could put it into a Pull Request to get it added (unless someone else wants to do both of those parts).

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello @lmstearn  Thank you for providing feedback.

Note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
