### ISSUE TITLE
Manual Data Refresh

### ISSUE THREAD

**Issue by monkeyskullfire** [MicrosoftDocs/windows-itpro-docs#2782]
How can the data refresh be triggered/forced by an admin?  It says in the document that data refresh happens automatically within 24 hours but how can an admin force it to happen on-demand?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d314758-3fa1-0d3d-829f-f74c4fabf7e0
* Version Independent ID: 3cc3212c-bde7-9566-ecd9-7417843d4b96
* Content: [Upgrade Readiness - Upgrade Overview (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-upgrade-overview)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-upgrade-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-upgrade-overview.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by yoohleah** [comment]
Same issue here.

**Comment by illfated** [comment]
Taking the risk of talking about stuff I know almost nothing about, but anyway;
Browsing through the documentation, it does not appear to be designed to be forced by manual interaction (MS tech specialists are welcome to contradict me here).

If I were to be thrown into a scenario where I would have to deploy and manage Upgrade Readiness and get ready to deploy Windows 10 on a large scale (large number of computers), I would presume that the tools would need to keep its own pace to monitor the progress, which would be a slow process requiring a lot of patience, especially because of the difference in how much patching, updating and security verification would be involved before the target computers would become ready for upgrading to Windows 10. The only things I presume I would be able to do to speed things up, would be manual updating and checking for no virus or malware on the target computers. Any other attempts to refresh the status of Upgrade Readiness would mostly be as fruitless as refreshing Windows Update several times in a row on the same computer after it has already stated that it is up to date. Chances are pretty low that the status will change within a short time. Hence I would find it less useful to refresh the monitoring software compared to checking the individual computers, especially those suspected to be slow to update or finish verifying security checks.

This is just my thoughts on a hypothetical scenario, but I would not be surprised if this is close to what can actually be done when using that software.

**Comment by monkeyskullfire** [comment]
> Taking the risk of talking about stuff I know almost nothing about, but anyway;
> Browsing through the documentation, it does not appear to be designed to be forced by manual interaction (MS tech specialists are welcome to contradict me here).
> 
> If I were to be thrown into a scenario where I would have to deploy and manage Upgrade Readiness and get ready to deploy Windows 10 on a large scale (large number of computers), I would presume that the tools would need to keep its own pace to monitor the progress, which would be a slow process requiring a lot of patience, especially because of the difference in how much patching, updating and security verification would be involved before the target computers would become ready for upgrading to Windows 10. The only things I presume I would be able to do to speed things up, would be manual updating and checking for no virus or malware on the target computers. Any other attempts to refresh the status of Upgrade Readiness would mostly be as fruitless as refreshing Windows Update several times in a row on the same computer after it has already stated that it is up to date. Chances are pretty low that the status will change within a short time. Hence I would find it less useful to refresh the monitoring software compared to checking the individual computers, especially those suspected to be slow to update or finish verifying security checks.
> 
> This is just my thoughts on a hypothetical scenario, but I would not be surprised if this is close to what can actually be done when using that software.

Hi illfated,
It sounds like you're referring to refreshing the data that machines put into Azure - which is not what I'm talking about.  I'm talking about refreshing the data that I update in Azure - when it says "User changes pending".  For example, when I go assign importance to applications I don't want to have to wait 24 hours before I can do more filtering and/or get updated results based on the changes I made within Azure.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@monkeyskullfire - thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
Nice. I like seeing the use of **officedocsbot** to save a bit of admin time. 👍

**Comment by mypil** [comment]
@officedocsbot close
