### ISSUE TITLE
View last scan result

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/windows-itpro-docs#2786]
How and where can you see the results of a full scan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b48087-97c2-e6c2-2080-e5fcdb662268
* Version Independent ID: 6f1caca8-c986-7364-bd2c-7975c9509ff6
* Content: [Review the results of Windows Defender AV scans](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/review-scan-results-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/review-scan-results-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/review-scan-results-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by illfated** [comment]
Sorry for not having the features available before replying, but what happens when you use any of the options under the listed suggestions?
- **Use Microsoft Intune to review scan results:**
- **Use Configuration Manager to review scan results:**
- **Use the Windows Security app to review scan results:**
- **Use PowerShell cmdlets to review scan results:**
- **Use Windows Management Instruction (WMI) to review scan results:**

**Comment by wbach82** [comment]
None of the options shows last full scan report

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @wbach82  thank you for providing feedback.

Note that the feedback section below documentation is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

**Comment by e0i** [comment]
@officedocsbot close

**Comment by wbach82** [comment]
Yes i know. This is about a documentation issue. In Intune device console you cannot see scan results from scheduled scans... documentation is wrong.

> Use Microsoft Intune to review scan results:

In Intune, go to Devices > All Devices and select the device you want to scan.

Click the scan results in Device actions status.
