### ISSUE TITLE
Link issue 

### ISSUE THREAD

**Issue by danjpadgett** [MicrosoftDocs/windows-itpro-docs#2789]
The hyperlink for this text "Hybrid Azure AD joined provisioning in a synchronous Certificate Trust deployment in a Federated environment"

does not go anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f170bfe-711d-f875-8d5f-a49d3d5113b2
* Version Independent ID: a75c9aa8-b47b-51dd-9b84-c63bb5c6b782
* Content: [How Windows Hello for Business works - Provisioning](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning#Hybrid-Azure-AD-joined-provisioning-in-a-synchronous-Certificate-Trust-deployment-in-a-Federated-environment)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md)
* Product: **w10**
* GitHub Login: @MikeStephens-MS
* Microsoft Alias: **mstephen**

**Comment by illfated** [comment]
Now this is weird. For me, all the internal page (anchor) links work in the Github page
(https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning.md),
but none of the page anchor links work in the public page
(https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-how-it-works-provisioning).

I have tested this using Microsoft Edge (Windows 10 Home 64-bit, Version 1809 (OS Build 17763.316)), Firefox 65.0.1 (64-bit) and Google Chrome Version 72.0.3626.119 (Official Build) (64-bit).
I could accept that Firefox & Chrome might block the linking on the public page due to ad-block addons, but I would expect that the links would work at least on Microsoft Edge without addons.

All the browsers can use the links on the Github page, though. Weird. I don't know why.

Clicking the anchor symbol after the chapter headlines works as expected: it adds the correct link in the address bar and makes that headline top of the visible frame of my browsers.

**Comment by illfated** [comment]
Oh. I think I may have found out why the URL text links don't work on the public site.
On Github, the links work even if they contain Upper-Case names in the #Anchor-Name part of the URLs,
whereas on the public page, only lowercase names in the #anchor-name part works.
Upper-Case doesn't seem to work for the anchor links.

If you click the anchor link symbol after the chapter headlines on the public page, you will see that they only contain the lowercase URLs.

**Now, the real question is:** Would you like me to open a Pull Request with the suggested changes to the Github contribution page, or do you want to test this in a VM yourself to be certain that this suggested find is the cause of this issue?

**Comment by mypil** [comment]
@danjpadgett - can you please check and respond to the answer/suggestion made by illfated? Thank you.

**Comment by danjpadgett** [comment]
The anchor links work in IE, not in Chrome or Edge. Given the size and complexity of this article all of these links should work.

**Comment by jdeckerms** [comment]
@illfated Thanks for figuring out what was causing the problem. I'm fixing the links, should be published by end of day.
