### ISSUE TITLE
Memory Integrity cant be turned on.

### ISSUE THREAD

**Issue by skarai** [MicrosoftDocs/windows-itpro-docs#2790]
Not every machine will allow Memory Integrity to be turned on - similar to UEFI-MAT this section deserves more explanation on how this works and what the interested user should pay attention to when shopping for new hardware. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c878c59f-38db-5fa0-7f0b-51899865817e
* Version Independent ID: 0b9e719f-3884-e1c6-4333-32bf9cfc9db7
* Content: [Memory integrity](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity)
* Content Source: [windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity.md)
* Product: **w10**
* GitHub Login: @iaanw
* Microsoft Alias: **iawilt**

**Comment by mypil** [comment]
@AndreaBarr - please assign this issue to me. Thank you,

**Comment by mypil** [comment]
@skarai - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @skarai ,
**this section deserves more explanation on how this works** - there is an article above the one you are talking about that provides more details - [Device Guard](https://docs.microsoft.com/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control)
**what the interested user should pay attention to when shopping for new hardware.** - there is an article that clarifies requirements - [Hardware qualifications](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/requirements-and-deployment-planning-guidelines-for-virtualization-based-protection-of-code-integrity)

as long as all three articles are in the same branch, wouldn't it be acceptable to leave it as is?

Thank you

![image](https://user-images.githubusercontent.com/48041687/53817078-90432d80-3f86-11e9-8f60-06d53c8c82c3.png)

**Comment by Geckojas** [comment]
I can't turn this on for a Surface Pro 6, I'm not sure what is stopping it.

**Comment by mypil** [comment]
@skarai - did the answer of @MaratMussabekov address your issue?

**Comment by mypil** [comment]
@skarai - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.

**Comment by ljflevy** [comment]
My memory integrity settings switch greys out when switched on, and loading sliding dots animation happens, but nothing else.  I refresh the memory integrity settings page during this, then the page is back to having the setting turned off.  
As a result, core isolation can't be turned on, and its settings page won't tell me if my hardware doesn't qualify for it.
Win10 Home build 18632.86

**Comment by illfated** [comment]
@ljflevy : The article says "Windows 10", but the intended target audience is business IT Pro where Windows 10 Pro is used in a domain configuration (or at least in a managed environment). I don't think it is supported on Windows 10 Home (but I could be mistaken). To put it simple, I would not bet money on it working on Windows 10 Home as such (unless you got it delivered as a complete solution for all types of Windows 10, including Home).

The article may not be clear enough for you to see that, but if you read the full context, it ought to be possible to notice.

**Comment by ljflevy** [comment]
Sorry i did not read carefully enough, and thank you for taking the time to
reply.

I did find notifications suggesting clearly that my os situation may not be
suitable for memory integrity core isolation, after I opened my
notifications bar, after trying and closing the core isolation settings.

**Comment by robmoss2k** [comment]
[Hardware qualifications](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/requirements-and-deployment-planning-guidelines-for-virtualization-based-protection-of-code-integrity) is a broken link. It makes it quite difficult to work out what the hardware requirements for support are.

**Comment by illfated** [comment]
The page has moved some time ago, either around 2019-08-24 or earlier, maybe due to general restructuring of the page directory order, maybe as a result of renaming some of the solutions from Windows to Microsoft ({name of technology here}).
## Baseline protections and additional qualifications for virtualization-based protection of code integrity
### docs.microsoft.com: 
- https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/requirements-and-deployment-planning-guidelines-for-virtualization-based-protection-of-code-integrity

### Github:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/device-guard/requirements-and-deployment-planning-guidelines-for-virtualization-based-protection-of-code-integrity.md

***
#### Defective link:
https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/requirements-and-deployment-planning-guidelines-for-virtualization-based-protection-of-code-integrity

**Comment by gspot3d** [comment]
I cant turn on core isolation after turning it off. Microsoft says I must find compatible drivers for my Lenovo ideapad 330 to resolve the issue. There are about 19 issues from Mediatek, Samsung, ZTE and Huawei. Microsoft also said i must not just delete them. Im not tech savvy please help.

**Comment by gspot3d** [comment]
Here is a screen shot.
![incompatible drivers](https://user-images.githubusercontent.com/68169143/102008824-f3f1b180-3d3b-11eb-8502-f8748676ae7c.jpg)

**Comment by illfated** [comment]
@gspot3d : Please note that this issue ticket was closed almost 2 years ago. Also, it looks like you need some form of technical support. Here is some advice I have picked up during my time spent here on GitHub, in particular from contributing to this and other MicrosoftDocs repositories:

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
