### ISSUE TITLE
Seems like a poorly planned idea

### ISSUE THREAD

**Issue by TonyBird1981** [MicrosoftDocs/windows-itpro-docs#2806]
We like many companies block access to Microsoft updates as we need to test aspects of them with programs that we're running and by removing the ability to use WSUS or SCCM to access these features it makes them inaccessible to us and I'm curious as to the reasoning behind this move? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d423c0e-fd99-9ad5-a11a-45237c2149fc
* Version Independent ID: f30e4101-7a8e-bfa9-a7c0-de7c36499cf5
* Content: [Windows 10 - How to make FoD and language packs available when you're using WSUS/SCCM](https://docs.microsoft.com/en-gb/windows/deployment/update/fod-and-lang-packs)
* Content Source: [windows/deployment/update/fod-and-lang-packs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/fod-and-lang-packs.md)
* Product: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by GeoSimos** [comment]
So true!

**Comment by e0i** [comment]
Hello @TonyBird1981  Thank you for providing feedback.

Note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider opening a product feedback ticket for any of your suggestions and questions to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
