### ISSUE TITLE
Dead Link for JPN translation document

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/windows-itpro-docs#2822]
The URL assigned in [Azure PowerShell コマンドレットを使用して、Virtual Machines および Cloud Services 向けの Microsoft マルウェア対策] is in Dead Link.
Please fix URL if possible.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ea8a5770-37e4-d118-4178-1bbc9f94550d
* Version Independent ID: 214c6852-b2cc-d0d5-c07a-9e662707aa23
* Content: [Windows Defender ウイルス対策の展開、管理、レポート](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus#fn3)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md](https://github.com/Microsoft/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md)
* Product: **w10**
* GitHub Login: @andreabichsel
* Microsoft Alias: **v-anbic**

**Comment by mypil** [comment]
@OfficeGlobal

**Comment by OfficeGlobal** [comment]
@mypil It's the source issue, the link "Microsoft Antimalware for Virtual Machines and Cloud Services with Azure PowerShell cmdlets" is not available in source article https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus#fn3

**Comment by mypil** [comment]
@andreabichsel - the URL for the source article (https://github.com/MicrosoftDocs/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md) is getting a 404 error. Can you please advise on how this can be fixed?

cc: @kenwith @AndreaBarr

**Comment by mypil** [comment]
@andreabichsel - I would like to follow up on this issue. Do you happen to know the correct URL for the source article? Please advise so we can create a PR to get this fixed. Thank you.

**Comment by andreabichsel** [comment]
I believe this PDF has the info: http://download.microsoft.com/download/F/A/E/FAE6F5D7-051D-49EF-A46D-1FAFAEFBB3F3/Microsoft%20Antimalware%20For%20Azure%20Cloud%20Services%20and%20Virtual%20Machines%20v2%20-%2010282014.pdf

**Comment by illfated** [comment]
The **https** version of that link should be just as valid (just in case https is preferred to http):
https://download.microsoft.com/download/F/A/E/FAE6F5D7-051D-49EF-A46D-1FAFAEFBB3F3/Microsoft%20Antimalware%20For%20Azure%20Cloud%20Services%20and%20Virtual%20Machines%20v2%20-%2010282014.pdf

**Comment by illfated** [comment]
By the way, @mypil - is there a branch named `live` in addition to `master` available to Microsoft employees, but hidden from other users? I am referring to your question about the link
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/live/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md

as opposed to the visible master branch page in this repository
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md

which corresponds to the online content
- https://docs.microsoft.com/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus

**Comment by mypil** [comment]
@illfated - I'm not sure about that. Perhaps, @andreabichsel or @kenwith have some information.

**Comment by andreabichsel** [comment]
My guess is that the link with "/live/" in it might be for localized content. I don't use that branch at all.

**Comment by illfated** [comment]
Fair enough, not a big deal, except for the conundrum of why the Japanese page used the `/live/` branch link
in the opening issue comment, instead of the `/master/` branch link.

From my point of view, the focus needs to be on where the correct documentation is located.
Maybe in one of the other repositories, like Azure or PowerShell?

https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azuresmps-4.0.0/Azure/Azure.md

https://docs.microsoft.com/powershell/module/servicemanagement/azure/set-azurevmmicrosoftantimalwareextension?view=azuresmps-4.0.0

I am uncertain how to continue from here, because the documentation in the originating page seems to indicate that the linked page with PowerShell cmdlets should list both **Virtual Machines** and **Cloud Services** cmdlets on the same page. 

Also, there is the original link structure to consider, is the likeness in a new link of any importance?
(thinking aloud, so to speak - if missing text could have played any role in the original links)

Overview: https://docs.microsoft.com/en-us/azure/security/azure-security-antimalware
new_link1: https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azuresmps-4.0.0/Azure/Get-AzureVMMicrosoftAntimalwareExtension.md
new_link2: https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/azuresmps-4.0.0/Azure/Get-AzureServiceAntimalwareConfig.md

dead link: https://docs.microsoft.com/powershell/servicemanagement/azure.antimalware/v3.4.0/azure.antimalware

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@illfated you are right, there is a private branch that no-one works in (most people don't even know it is there) -the  public and private repos are automatically synced but the repo admins have to merge from master to live through this extra layer because it was set up that way .(as I understand it)) About the links, I  will get back to you after doing some research. :smile:
