### ISSUE TITLE
0x801c004d Not Listed

### ISSUE THREAD

**Issue by GenericUser321** [MicrosoftDocs/windows-itpro-docs#2900]
This error code is not listed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-au/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by jdenicola67** [comment]
Same here, just got that.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @GenericUser321 , @jdenicola67  Thank you for submitting feedback.

In our understanding the error code that you have noted might actually have surfaced from other services rather than _Windows Hello_ itself.

Find below a quoted reply from our Content Developer:

DaniHalfin wrote:
> For error codes unlisted here, in most cases those are transient error codes
> being surfaced by other services in the Windows Hello dependency chain.

> We are working on something to improve the user experience in that regard,
> but that will not solve the issues you are experiencing.

> If we find a reoccurring error codes that isn't covered here and should be
> (meaning, in most cases, it is coming from Windows Hello and not other
> components) we'll make sure to add it to this page.

Also note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider consulting to _Feedback Hub_ for any of your suggestions, questions or feature requests to help Microsoft improve your experience. Find the link to _Feedback Hub_ below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

We are closing this issue but feel free to re-open it if you feel that we might have missed something.

Have a nice day.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by DirectDemo** [comment]
Idem with the new 1903

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-HelloForBusiness" Guid="{906b8a99-63ce-58d7-86ab-10989bbd5567}" /> 
  <EventID>7525</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>16</Task> 
  <Opcode>11</Opcode> 
  <Keywords>0x8000000000000002</Keywords> 
  <TimeCreated SystemTime="2019-07-16T15:42:48.120012500Z" /> 
  <EventRecordID>145</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="3900" ThreadID="9112" /> 
  <Channel>Microsoft-Windows-HelloForBusiness/Operational</Channel> 
  <Computer>PAM</Computer> 
  <Security UserID="S-1-5-21-2530811535-2135137420-3647824133-1001" /> 
  </System>
- <EventData>
  <Data Name="Error">0x801c004d</Data> 
  <Data Name="ProcessingTime">0</Data> 
  </EventData>
  </Event>

**Comment by jrjenk** [comment]
Searching for this error code, 0x801c004d in Bing and other popular search engines seems to mostly return articles referencing issues with Windows Hello. While this might be an issue from a Dependency as previously suggested, the error code should probably be mentioned in the "errors with unknown mitigation" section

**Comment by GriffReborn** [comment]
Also came here looking for a solution to this, and not finding the code in the MS article [Windows Hello errors during PIN creation](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation).  

For us, this feature was working until we updated to 1909.   We are now unable to set PIN.   This needs to be covered off by Microsoft in this article, as there's a clear link between setting up PIN, and this error.  

It's common enough for this article to exist and a number of other forum posts.    I've yet to see a post with a solution.  So I think it's down to MS to update the article with at least a clue where the problem lies (and you know, if it's not too much to ask, a solution)

**Comment by GriffReborn** [comment]
@e0i - there are too many other articles and search results pointing here. This needs to be open and the parent issue.  It shouldn't be closed until resolved.
> @officedocsbot close

**Comment by e0i** [comment]
@GriffReborn Thank you for following up with this issue. The case for this specific error code is under re-investigation.

**Comment by e0i** [comment]
@mapalko _Dani_ has informed that you can help us with this issue. The community is also eager to hear about `0x80070490`. Thank you.

**Comment by mapalko** [comment]
That error code maps to error not found. With just the error code it is difficult to map it to a specific component or issue.

**Comment by GitHubSachin** [comment]
What is the solution for 0x801c004d
I am still getting this error. pls post solution

**Comment by Vanguze** [comment]
Getting same error

**Comment by DaveWP** [comment]
Getting the same error. 

I have tried clearing the TPM workspace, cleared the NGC store, and reset the winbiodatabase to no avail.  I now find the following issues:

a. When I reset the NGC store (by renaming the file), the windows Hello environment looks OK, but when I attempt to set up a new PIN I get the error 0x801c004d and windows reports that the Windows Hello environment is not available
b) On the "Require Sign In", I have a red error message stating that "Windows Hello is preventing some options from being displayed".
c) As I am running Windows Home, I do not have access to gpedit.msc which is suggested in a number of places.

Environment
     I am running a local account on Windows 10 Home edition.  All available windows updates have been applied.

**Comment by Camalo1337** [comment]
Same problem here. Problems after restoring a backup to my PC. Now Hello isn't working.

**Comment by datphuquoc81** [comment]
Same problem here. Problems after restoring a backup to my laptop. Now Hello isn't working.

**Comment by e0i** [comment]
@mapalko Can you provide clarifications? Thank you.

**Comment by mapalko** [comment]
@Camalo1337 @datphuquoc81 @DaveWP have you opened a feedback hub item for this behavior? Have you tried running "certutil -deletehellocontainer" from cmd or powershell to try cleaning up state?

**Comment by azuntik** [comment]
> @Camalo1337 @datphuquoc81 @DaveWP have you opened a feedback hub item for this behavior? Have you tried running "certutil -deletehellocontainer" from cmd or powershell to try cleaning up state?

This solved the problem for me. Thank you!
