### ISSUE TITLE
IF you CHANGE a PRODUCT then YOU need to CHANGE the Documentation and step by steps

### ISSUE THREAD

**Issue by rzecchino** [MicrosoftDocs/windows-itpro-docs#2925]
PLEASE CREATE A STEP BY STEP THAT REFLECTS THE NEW METHOD.  We CANNOT wing it infront of customers and clients!  POST A STEP BY STEP ON SETTING UP UPGRADE READINESS FROM STEP 1 set up azure portal all the way through to ANALYZING the results!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24771310-237e-adf7-be33-59355a87f243
* Version Independent ID: e2792588-8318-98a2-a5bd-ff5cbba75e0e
* Content: [Get started with Upgrade Readiness (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started#feedback)
* Content Source: [windows/deployment/upgrade/upgrade-readiness-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-readiness-get-started.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by TokyoScarab** [comment]
@jaimeo I would love your input on this issue as one of the page contributors, thanks!

**Comment by zdvorak** [comment]
Hey @rzecchino,  

I've reviewed this page, and it looks like it's already been updated to reflect the onboarding changes that resulted from Log Analytics' move to the Azure portal.  

In terms of Analyzing results, this will be a process that is unique for each customer/workspace.  As a rule of thumb, we document what we've built so that you can get acquainted with the tool.  However, we're unable to document processes like data analysis as this will be heavily dependent upon the unique insights that you're seeing.  

If you find specific steps of the product that are not properly described or reflected in the docs, please let us know!

Thanks,
Zach

**Comment by TokyoScarab** [comment]
@rzecchino After spending some time looking into this and going through some other documentation, I can also confirm that @zdvorak 's comment is correct.  If you do happen to find something that you think could be improved or mentioned in the document to improve people's experiences using this, feel free to comment back with your suggestion and we'll be happy to re-open this issue and look at your suggestions and even add them if we think they are a good fit.  Thank you again for posting this and have a nice day!

**Comment by mypil** [comment]
@officedocsbot close
