### ISSUE TITLE
Event Collector stops processing

### ISSUE THREAD

**Issue by rewt1** [MicrosoftDocs/windows-itpro-docs#2928]
Dear All,
The documentation regarding advanced WEF usage is critically missing...
The only document that provides deeper information is:

https://community.softwaregrp.com/dcvta86296/attachments/dcvta86296/arcsight-discussions/24729/1/Protect2015-WindowsEventForwarding.pdf  (the author is now working @Microsoft :)

Multiple questions here and not treated in the documentation:
- What is the recommended approach regarding subscriptions ? I mean is there any impact running multiple subscription instead of a "big one"
- Is there size limits ?
- Will multiple subscription increase sockets / performances issues ?
- Are there recommended settings in WinRM/registry for large environments ? (as the only settings for this is in a HP doc  and not confirmed by MS!!!)
- Same for MaxItems/MaxLatency Time what kind of settings are the most valuables for large scale environments (+3k computers...)

Indeed in the actual documentation this is more "generalities" regarding performances...
How to measure the performances ?

etc...

All these questions should be considered as WEF is an enterprise grade solution.

Kind regards,

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rewt1 -  May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@rewt1 - I would like to follow up on this. May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by rewt1** [comment]
Hi @mypil, thank you for your interest !
I was talking about all the docs that are available by Micsrosoft, the main ones are : 
https://docs.microsoft.com/en-us/windows/desktop/wec/setting-up-a-source-initiated-subscription
https://docs.microsoft.com/en-us/windows/desktop/wec/windows-event-collector

Kind regards,

**Comment by mypil** [comment]
@rewt1 - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hello @rewt1 

I will try to answer most of these:

-  What is the recommended approach regarding subscriptions?
Yes, of course, you can log up to 5k events per second on any subscription or computer.
So if you want to have events for 3k+ and computers, there's no possible way you can dimension that into a single "big subscription" you'd need to have a bunch of servers for logging and also a bunch of people and time to query that.

- Is there size limits?
Size limits have not been updated on documentation because of the events are the same that in older Read windows vista (or newer)
https://support.microsoft.com/en-us/help/957662/recommended-settings-for-event-log-sizes-in-windows

And can be modified using GPO 
https://www.youtube.com/watch?v=qT62IZzyElw

Will multiple subscription increase sockets/performances issues?
Well, you have a single CPU and single Bios, a single RAM  on a computer or server. 
So increasing the number of subscriptions will divide the speed of the computer and will demand more and more resources.

For a 3k+ it's just nonsense, you will be getting so much information that you'd need to attach those to a Big Data database so you can actually query something, the whole idea of subscribing events collectors is to get a centralized spot for servers, not for workstations.

- Are there recommended settings in WinRM/registry for the large environment? (as the only settings for this is in a HP doc and not confirmed by MS!!!)
You will hardly get a simulation of 3k+ computers from Microsoft. We are a documenting team, not a technical team, and the cost of having a virtualized environment this big is not a realistic use of the "event collector". 

- Same for MaxItems/MaxLatency Time what kind of settings are the most valuables for large scale environments (+3k computers...)
the MaxItem And MaxLatency

- Indeed in the actual documentation, this is more "generalities" regarding performances...
Yes, the generalities are "guides" for admins, the implementation of such features and the dimensions of them are entirely the responsibility of the administrators.

- How to measure the performances?
The way has always been: Using Windows Resource Monitor
https://www.thewindowsclub.com/use-resource-monitor-windows-10
https://www.ghacks.net/2017/12/28/a-detailed-windows-resource-monitor-guide/

Make a run without charge, and then go incrementing the number of subscriptions, you can start doing a formal study of how it should be influenced based on the number of subscriptions and checking the performance on each stage.

All of these are technical questions, I don't consider that it would require any kind of updates of the documentation, because the nature of all the questions are a bit decontextualized of what the generalities on the article wanted to say.

**Comment by j0rt3g4** [comment]
@mypil  there's no PR on this one since the base of the questions is technical. So I'd recommend if they have an enterprise or premier subscription, contact them or a partner to help them to determine the technical answers

**Comment by mypil** [comment]
@rewt1 - From our understanding, the issue has been answered by @j0rt3g4. If you require technical support for this issue, the best option is for you to open a service ticket so this can get resolved ASAP. Based on outcome let us know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
