### ISSUE TITLE
0x801c0451 not listed

### ISSUE THREAD

**Issue by jonnydcakes** [MicrosoftDocs/windows-itpro-docs#2941]
0x801c0451 not listed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by joinimran** [comment]
@jonnydcakes Thank you for your feedback. Can you please share more details about the error code you have received.

**Comment by mypil** [comment]
@DaniHalfin - need your insights.. Is this request similar to issue #2409?

Please advise on how to proceed with this. Thank you.

**Comment by mypil** [comment]
@DaniHalfin - I would like to follow up on this. We need your insights.. Is this request similar to issue #2409?

Please advise on how to proceed with this. Thank you.

**Comment by jonnydcakes** [comment]
Hello - when I tried to add a PIN from the settings app, this is the error
message I received: 0x801c0451.

**Comment by DaniHalfin** [comment]
Hi everyone,
For any error code not listed in this topic, please file a problem through the feedback hub app.
Error codes that are unlisted in this topic are most likely transient and always too complex to be able to provide resolution through a help topic. 
Please report these issues through the feedback hub app, and reach out to us through our official support channels.

**Comment by DaniHalfin** [comment]
@mypil - My comment here applies to any issues where error code is unlisted. I'll work to formulate a note for this specific topic to reflect this information and prevent further issues being opened.

**Comment by nakosenk** [comment]
Since this and the other GitHub issue are the only results for error 0x801c0541 when searching online, here's what fixed it for our set up. The users were registered with an Azure MFA server set up on-premises which was configured only to allow authentication through the mobile app. These users, however, were receiving text messages for MFA when attempting to set up Windows Hello for Business. 

They had to register their mobile device in the Authenticator app, wait for the change to propagate, and then go to https://aka.ms/mfasetup and change their preferred method of verification to be notified through the mobile app. Once that change was made and they approved the mobile app they were able to get Windows Hello for Business to register the PIN.
