### ISSUE TITLE
Effectively Zero Options

### ISSUE THREAD

**Issue by PrinceMarkieD** [MicrosoftDocs/windows-itpro-docs#2951]
The 'Manual registration' workflow is the only viable workflow from the way this article reads. I have been struggling with consistency in AutoPilot for months now, and I am to understand that the device must not be currently on the internet when registered? The device must not have EVER been on the internet when registered? It is not clear. What this article describes is a scenario where a device must be in OOBE , and not connected to the Internet for Autopilot to work correctly. This leaves only one reasonably viable registration process, namely , the Partner side-loading through the portal before the hardware is received. I am I totally misunderstanding these options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243b015-5b5f-7a62-0d9d-767d729dc475
* Version Independent ID: ff8c0509-c075-8528-823f-c195ff4d2382
* Content: [Adding devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/add-devices#collecting-the-hardware-id-from-existing-devices-using-powershell)
* Content Source: [windows/deployment/windows-autopilot/add-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/add-devices.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@PrinceMarkieD - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @PrinceMarkieD ,
**The 'Manual registration' workflow is the only viable workflow from the way this article reads.** - there are two options:
1. Registration by OEM: in the article "Ideally, this would be performed by the OEM, reseller, or distributor from which the devices were purchased"
2. Manual registration: the rest of the article focused on it.

**The device must not have EVER been on the internet when registered?** - yes, it must not have ever been connected to the internet, otherwise, device will download blank profile. In this case, to add device to autopilot, you need put it back to OOBE state.

**This leaves only one reasonably viable registration process, namely , the Partner side-loading through the portal before the hardware is received.** - no, you can still load it manually, after receiving (you may need to reimage device)

So, to make long story short:
1. in case OEM didn't uploaded deviceid to autopilot, you can do it manually
2. collect device id and upload it before connecting device to the internet
3. if you already connected it to internet - you need to restart OOBE

Thank you

**Comment by PrinceMarkieD** [comment]
Thank you so much for the verification. This functionality is congruent
with what I understood to be the default behavior of auto-pilot. I think
that the article confuses this unintentionally. If it were stated this way:
"Autopilot OOBE will only take effect for a device that is
SysPrepped/Generalized. So if a device is already in use, and has been on
the internet the device will have to have the Windows 10 OS re-installed
fresh."
This leaves the question of will the device respect an autopilot profile
that has been uploaded from an internet active OS, if that OS is placed
into "Reset This PC" scenario.?
I find this article interesting because coincidentally I have always fresh
installed my devices just because it is FAR faster than "Reset This PC". I
now wonder if that means my AP profile would eventually break?
Also I do the same thing with VMware Workstation VMs. I save the state at
OOBE, and rapidly test Autopilot profile by going back to the OOBE save
state, and restarting the computer. I use the Same Auto-pilot profile but i
effectively "Reset" the PC because the snapshot I return to is just before
the computer boots into OOBE for the first time.

I wonder if that is a mistake lab situation. I will lay it out the way you
did for clarity; the two ways i test AutoPilot.


Physical Devices (when testing AutoPilot Zero touch deployment)
Vanilla Windows 10 Ent installed to device with TPM2.0.
* At the first language selection of OOBE, open Powershell.
*Rename the device so it gets into an Azure AD Group Dynamically (have not
found a more controllable dynamic method because ZTID is too broad)
*Use Auto-pilot script to save the CSV to the inserted WIn10 install USB.
Copy the CSV to technician station. Upload CSV to Intune etc etc.
* Reboot the test device
*AutoPilot works.
           * For subsequent provisioning test on PHYSICAL devices.
Re-install the Windows 10 OS to experience the AutoPilot OOBE again.

On Virtual Machines inside VMware Workstation on my Technician workstations
*Same process as above until you get to the "Reboot the Test Device" step.
* Shutdown the test device, and grab a snapshot of the VM before starting
it up again to continue OOBE"
*AutoPilot works as long as you do not expect to use the TPM2.0 dependent
function of Zero-touch Self-Deployment Preview (couldn't think of the name
above.)
          * For subsequent provisioning test "Roll back to the previous
snapshot" Delete the device from Intune.


Thank you for this good exchange, i know I am not the only person totally
confused by this article.

**Comment by MaratMussabekov** [comment]
Dear @PrinceMarkieD ,
**This leaves the question of will the device respect an autopilot profile that has been uploaded from an internet active OS, if that OS is placed into "Reset This PC" scenario.?** - no, after "Reset This PC" you can collect device hash and upload it too, the same as after fresh installation (because from the OS perspective, resetting is the same as reinstallation). Also from the article "the only way to clear the stored profile is to **re-install** the OS, reimage the PC, or run sysprep /generalize /oobe. "

**I now wonder if that means my AP profile would eventually break?** - could you please clarify, what do you mean by "break"? you can reset and reinstall your PC, that doesn't affect your AP account as it is stored in the cloud

**Also I do the same thing with VMware Workstation VMs. I save the state at OOBE, and rapidly test Autopilot profile by going back to the OOBE save state, and restarting the computer. I use the Same Auto-pilot profile but i effectively "Reset" the PC because the snapshot I return to is just before the computer boots into OOBE for the first time.**  - and what the result? which issue do you experience?

Also, which information do you think should be added/rewritten in this article to make it less confusing?

Thank you

**Comment by mypil** [comment]
@PrinceMarkieD - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by PrinceMarkieD** [comment]
Just make a flow chart that makes sense. If I gather the device hash from my pc RIGHT NOW, is it the same hash as if i gather it during the OOBE? You guys need to make it clear that people are expected to get this hash during a point when most normal users don't even know how to get to a command prompt.

**Comment by MaratMussabekov** [comment]
Dear @PrinceMarkieD ,
**If I gather the device hash from my pc RIGHT NOW, is it the same hash as if i gather it during the OOBE?** - yes, it is the same. More details here [Windows Autopilot FAQ](https://docs.microsoft.com/windows/deployment/windows-autopilot/autopilot-faq)

**most normal users don't even know how to get to a command prompt** - Could you please clarify?  Autopilot is a product designed to be administrated by IT Department, I am not sure which command that should be run by users you are talking about.

Thank you

**Comment by PrinceMarkieD** [comment]
Okay thank you. I think i can explain now what will make it more clear. Please make a step by step graphic, that explains to people who to reach the Autopilot OOBE. Starting from the Windows desktop. , and Starting with a Device that has never been powered on and connected to the internet. If you do this; it will not be confusing anymore. Thank you for this correspondence! this was amazing!

I have a new question now: Should i start a new thread?
