### ISSUE TITLE
Conflict in text

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windows-itpro-docs#2986]
There is a conflict in the document. You say:
"We do not recommend enabling this Group Policy setting because of the high number of events recorded."

In the settings table, you then recommend every computer in the domain have this policy enabled.
Additionally, your Windows 10 1809 baseline document recommends enabling this policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c93ec09a-25ee-93da-f0ce-3e6eb9870ffb
* Version Independent ID: 5ee9c8f8-5a41-5dad-1831-ed5c928bc775
* Content: [Audit Sensitive Privilege Use (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-sensitive-privilege-use)
* Content Source: [windows/security/threat-protection/auditing/audit-sensitive-privilege-use.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/auditing/audit-sensitive-privilege-use.md)
* Product: **w10**
* GitHub Login: @Mir0sh
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
I think you may have misread the text, although it is very easy to do so. Let me quote the paragraph:
> The use of two privileges, “Back up files and directories” and “Restore files and directories,” generate events only if the “[Audit: Audit the use of Backup and Restore privilege](https://technet.microsoft.com/library/jj852206.aspx)” Group Policy setting is enabled on the computer or device. We do not recommend enabling this Group Policy setting because of the high number of events recorded.

There are 2 privileges mentioned at the start,
- Back up files and directories
- Restore files and directories

The next part tells us that that they "generate events only if the
- “[Audit: Audit the use of Backup and Restore privilege](https://technet.microsoft.com/library/jj852206.aspx)” Group Policy setting

is enabled on the computer or device. We do not recommend enabling **this Group Policy setting** because of the high number of events recorded.
***
I could be wrong, but I am fairly sure that the table below refers to the general auditing of all other events except for the specific use of **Audit the use of Backup and Restore privilege**.

**Comment by SwiftOnSecurity** [comment]
@illfated you're totally right, sorry it's 2AM here and didn't have my thinking cap on. Please close this ticket. Appreciate your time.

**Comment by mypil** [comment]
@officedocsbot close
