### ISSUE TITLE
Autopilot Reset Question

### ISSUE THREAD

**Issue by rlawrimore** [MicrosoftDocs/windows-itpro-docs#3010]
To use Autopilot Reset, do the devices have to be enrolled in Autopilot Devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a662f1-c2aa-33ad-0e71-d0cbb288d053
* Version Independent ID: 196f1c8d-3179-c173-194f-08bf3a6f82ca
* Content: [Reset devices with remote Autopilot Reset (Preview)](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-reset-remote)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-reset-remote.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-reset-remote.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by illfated** [comment]
Judging by the linked documentation page, I would say "yes", because it looks obvious to me.
> To enable a device for a remote Windows Autopilot Reset, the device must be MDM managed, joined to Azure AD, and configured to use the [enrollment status page](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/enrollment-status).

> **[Windows Autopilot Enrollment Status page](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/enrollment-status)**
The Windows Autopilot Enrollment Status page displaying the status of the complete device configuration process. Incorporating feedback from customers, this provides information to the user to show that the device is being set up and can be configured to prevent access to the desktop until the configuration is complete.

Even so, I recommend verifying this by testing yourself (if possible) or wait for more feedback from other experienced users or one of the Docs team members.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by j0rt3g4** [comment]
Resolution of the issue #3010 using the PR #3191

**Comment by Neckross** [comment]
I tested on my lab, that feature for Autopilot Reset (preview) will stay grayed out UNLESS you reset the device using Autopilot (either using Fresh Reset or manually sysprep the device).

This should be added to documentation.

**Comment by illfated** [comment]
@Neckross : Do you have a suggestion for how it could be phrased (written) and if it can be added to the Pull Request #3191 by @j0rt3g4 ?

**Comment by j0rt3g4** [comment]
I've added a **rephase** into my sentence to add the comments from @Neckross. Hopefully, @nenonix  and @illfated  will get it reviewed and approved soon 👍 
#3191

**Comment by illfated** [comment]
@rlawrimore : The PR has been merged into the master branch of the docs here on Github. We hope you feel that your question has been answered. The changes will migrate to the docs.microsoft.com page within a few days, but if there is anything we have not covered so far, feel free to comment again to add more information to this issue. Otherwise, we hope you are happy with the information provided in the pull request, its following commit and this issue.

**Comment by mypil** [comment]
@officedocsbot close
