### ISSUE TITLE
Examples & SDK header files?

### ISSUE THREAD

**Issue by bmwilson1978** [MicrosoftDocs/windows-itpro-docs#3042]
Hi there - couple of items:

1. Are there any more detailed examples/source code available for creating a custom configuration service provider?
2. It appears the header files are missing from the latest Windows 10 SDK's.  I can't seem to find cmgrcsp.h etc.

Thanks
Bryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9251af-e49c-6dcd-db20-5851dd1350ee
* Version Independent ID: 446a77f7-a820-fdb1-c437-629e89bf17af
* Content: [IConfigServiceProvider2](https://docs.microsoft.com/en-us/windows/client-management/mdm/iconfigserviceprovider2)
* Content Source: [windows/client-management/mdm/iconfigserviceprovider2.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/iconfigserviceprovider2.md)
* Product: **w10**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @bmwilson1978  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
