### ISSUE TITLE
BITLOCKER PBA + Windows Hello 4 Business

### ISSUE THREAD

**Issue by binekkk** [MicrosoftDocs/windows-itpro-docs#3139]
Hi,
Is it possible to "merge" ONE PIN for Bitlocker Pre-Boot Authentication and Windows Hello 4 Business for Windows logon?

I can setup one PIN for BitLocker, and also PIN for logon into Computer/AD. I want to have 1 PIN connecting PBA and WH4B.

Maybe some 3th party devices/smart cards?

**Comment by e0i** [comment]
Hello, @- thank you for providing feedback.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly. The issues section of this repository is for product documentation problems only.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
