### ISSUE TITLE
The Windows 10 Release Information page cannot be viewed clearly when dark theme is enabled

### ISSUE THREAD

**Issue by sjetha-pason** [MicrosoftDocs/windows-itpro-docs#3142]
**Problem**
When viewing the Release Information page, the tabled content cannot be viewed clearly when Docs' dark theme is enabled.

**Steps to reproduce**
1. Visit https://docs.microsoft.com/en-us/windows/windows-10/release-information
2. Enable the dark theme

**Expected outcome**
All content can be viewed clearly

**Actual outcome**
The lower half of the page is too dark to read properly.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @sjetha-pason  thank you for providing feedback.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly. The issues section of this repository is for product documentation problems only.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by illfated** [comment]
@e0i : This issue was about the documentation page, although it sort of depends on the screen quality and ability to adjust brightness / contrast.

@sjetha-pason : I opened the page in dark mode and was able to read the whole page. But I admit that the lower half needs a certain amount of backlight from the physical screen to show enough to read.

**Comment by sjetha** [comment]
I think it should be considered a usability issue if it can't be clearly read at some brightness levels when the dark theme is enabled.

**Comment by e0i** [comment]
@officedocsbot reopen

**Comment by e0i** [comment]
@lizap Would it be possible to adjust the content theme to improve readability in Dark Mode? Please confirm.

**Comment by e0i** [comment]
Hello, @sjetha-pason

Thank you for taking the time to provide feedback and following-up.

We are investigating this issue and will follow up with updates.

Since this repository specializes in content and not design, also consider submitting this this usability feedback to [Microsoft Docs Site Feedback](https://github.com/MicrosoftDocs/feedback), where [similar issues](https://github.com/MicrosoftDocs/architecture-center/issues/1203#issuecomment-454950221) regarding dark mode have been submitted and resolved.

Thank you.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by gregvanl** [comment]
The text is also dim in High Contrast mode so I think this is an accessibility issue that needs to be addressed.
