### ISSUE TITLE
[LOC] Showing "*図 2. USB サム ドライブの選択*" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3159]
https://docs.microsoft.com/ja-jp/surface/microsoft-surface-data-eraser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a0e269-be9b-781a-b9b4-52b94e68618b
* Version Independent ID: 725c2d4a-5397-6c67-7605-93a8cd40cf08
* Content: [Microsoft Surface Data Eraser (Surface)](https://docs.microsoft.com/en-us/surface/microsoft-surface-data-eraser#feedback)
* Content Source: [devices/surface/microsoft-surface-data-eraser.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/microsoft-surface-data-eraser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @BRecords
* Microsoft Alias: **jdecker**

**Comment by mypil** [comment]
@officedocsbot assign @OfficeGlobal

**Comment by mypil** [comment]
@OfficeGlobal - Kindly assist with this Translation (Localization) issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dongmicro - Can you assist with this Translation (Localization) issue?

Thank you.

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Do you have any updates? Thanks.

cc: @AndreaBarr

**Comment by mypil** [comment]
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - I would like to follow up on this. Can you please assist with this Translation (Localization) issue? Thanks.

**Comment by Maruktruk** [comment]
Under investigation.

**Comment by illfated** [comment]
Oh. I think I can see why this is happening. This is about the image text `*Figure 2. USB thumb drive selection*` (under image 2 in the section [**How to create a Microsoft Surface Data Eraser USB stick**](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/microsoft-surface-data-eraser.md#how-to-create-a-microsoft-surface-data-eraser-usb-stick).

Right above the image, there is a note message. followed by the image and the affected figure text:

4.  Select the USB drive of your choice from the **USB Thumb Drive Selection** page as shown in Figure 2, and then click **Start** to begin the USB creation process. The drive you select will be formatted and any existing data on this drive will be lost.

  >[!NOTE]
  >If the Start button is disabled, check that your removable drive has a total capacity of at least 4 GB.
  
![dataeraser-usb-selection 1](https://user-images.githubusercontent.com/38162891/56441762-6bb0d400-62ee-11e9-9540-33d6d88645c8.png)

    *Figure 2. USB thumb drive selection*

To me, it looks like the Github indentation, along with the asterisks used to format the text as italics, puts the image text in a code block instead of showing it as formatted text, hence making the asterisks show up on the Github page. This looks like the note above the image, along with the following indentation, makes this happen instead of showing the text as regular formatted text.

The weird thing to me is that the format issue does not show up on the docs.microsoft.com page, neither the Japanese version nor the en-us version of the page, neither in MS Edge nor in Chrome.

I admit I am a little bit confused now, seeing that I can only reproduce it using Github, not the docs.microsoft.com page.

**Comment by mypil** [comment]
@Maruktruk @dongmicro - Any updates on this?

**Comment by illfated** [comment]
Looking forward to hear from you, @Maruktruk & @dongmicro.

**Comment by mypil** [comment]
@officedocsbot unassign @OfficeGlobal

@officedocsbot assign @dongmicro

**Comment by e0i** [comment]
Similar: #3394 #3453 #3452 #3451

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by illfated** [comment]
@e0i : Looking back at the pages now, this specific issue seems to be resolved, both for the Japanese and Github pages:
- https://docs.microsoft.com/ja-jp/surface/microsoft-surface-data-eraser#microsoft-surface-data-eraser-usb-%E3%82%B9%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E3%81%AE%E4%BD%9C%E6%88%90%E6%96%B9%E6%B3%95
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface/microsoft-surface-data-eraser.md#how-to-create-a-microsoft-surface-data-eraser-usb-stick

May I ask for you and @hyoshioka0128 to confirm that this is the case, testing several of your browsers as well?

If this issue really is solved, would you like to collect the remaining open linked issues in a different issue page?

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@officedocsbot close
This issue appears to be fixed.

**Comment by e0i** [comment]
@TinaMcN Thank you. Would you confirm that associated group of issues have also been fixed?

**Comment by TinaMcN** [comment]
@e0i thanks so much for doing that - much appreciated 👍
