### ISSUE TITLE
Documention says Server 2012 and above.  ATP portal lists Server 2008 R2 as option for onboarding?

### ISSUE THREAD

**Issue by Tower7Bro** [MicrosoftDocs/windows-itpro-docs#3208]
Hi,

When logged into the ATP portal under Onboarding.  The "Select O/S to start onboarding process:" one of the options in drop down is "Windows Server 2008 R2, 2012 R2, and 2016"

Why is Server 2008 R2 
![listofoptions](https://user-images.githubusercontent.com/49411810/55746884-e9303680-5a08-11e9-9161-662a3a57a9a0.png)
listed if it's not supported?  Is this new that 2008 is supported, or oversight that it's listed? 

Thanks!

**Comment by illfated** [comment]
Which documentation page is the one you refer to in "Documentation says Server 2012 and above." in the issue title?

About the screen shot, is it from the Azure ATP portal, or somewhere else?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Tower7Bro** [comment]
> Which documentation page is the one you refer to in "Documentation says Server 2012 and above." in the issue title?
> 
> About the screen shot, is it from the Azure ATP portal, or somewhere else?

At the top of the page where it says Applies To:  Server 2008 is not listed yet in the ATP portal under onboarding it's a choice.  Screenshot is from the onboarding section of ATP portal.

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/configure-server-endpoints-windows-defender-advanced-threat-protection

**Comment by illfated** [comment]
Thank you for adding the information. It is indeed puzzling to see 2008 R2 listed as an option, mostly because you hardly ever see client software supporting that server version these days, even if Windows Server 2008 & 2008 R2 still have got the rest of 2019 left before they will be removed from regular support (https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2).

Looking forward to see a proper answer to your question, provided by someone from the Microsoft Docs team.

**Comment by Malind19** [comment]
@mypil , It does not show Win Server 2008 R2 in the article. Shall I Add it there?

**Comment by mypil** [comment]
@Malind19 - Based on the feedback and your assessment, you may create a PR to add that information then we can let the doc owner review and get their approval to merge the content.

**Comment by Malind19** [comment]
@mypil Created PR https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3344

**Comment by illfated** [comment]
@Tower7Bro : The suggested amendment to the documentation page has been closed, due to the fact that the ATP Portal is in a preview phase and that the proper documentation is still being worked on.
(see https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3344#issuecomment-487666339 )
> Yes, confirmed that it is in preview. The documentation will be updated when it is officially available.

The conclusion is that this issue may be closed too, based on the feedback from the ATP team.

**Comment by mypil** [comment]
@officedocsbot close
