### ISSUE TITLE
Enterprise Mode scheme v2 seems to work on IE 11 running on Win 7 too

### ISSUE THREAD

**Issue by Darsstar** [MicrosoftDocs/windows-itpro-docs#323]
In the following files can be read that IE 11 on Windows 7 can not handle Enterprise Mode scheme v2, or only Windows 10 is mentioned.
* browsers/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode.md
* browsers/internet-explorer/ie11-deploy-guide/use-the-enterprise-mode-site-list-manager.md
* browsers/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance.md

However, my Windows 7 system running IE 11.0.9600.18816 seems to handle v2 just fine.
I'm guessing that information is outdated. Or I am wrong to one extent or another.

An official statement regarding the level of support of Enterprise Mode scheme v2 on Windows 7 & 8 would be nice.
Whether that is in the form of editing the relevant pages or a reply so a follow up pull request can be created is up to you guys and gals.

**Comment by eross-msft** [comment]
Hi @Darsstar 
You are correct, v2 is supported on Windows 10, Windows 8.1, and Windows 7. I only see the text missing from the browsers/internet-explorer/ie11-deploy-guide/use-the-enterprise-mode-site-list-manager.md topic, but please go ahead and make the changes in a pull request so that you get credit. Thanks!!

**Comment by eross-msft** [comment]
Closing this issue since there's now a pull request in place.
