### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by fredenocs** [MicrosoftDocs/windows-itpro-docs#3281]
I understand in the article states applies to Windows 10.

So this will not work on Windows 7?  It will only apply to W10, any version?

**Comment by jdeckerms** [comment]
@fredenocs What article are you asking about? Could you provide a URL?

**Comment by fredenocs** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit

Wow quick response.

**Comment by illfated** [comment]
Seeing that the **Reference** paragraph starts with the following:
> Beginning with Windows Server 2012 and Windows 8, Windows detects user-input inactivity of a sign-in (logon) session by using the security policy setting Interactive logon: Machine inactivity limit.

I would say that there was a change after Windows 7, starting with Windows 8, but completed in Windows 10. (I might be interpreting the page incorrectly.)

Even if you are able to make it work in Windows 7, I highly doubt it will be supported on Windows 7, unless the documentation says otherwise.

**Comment by illfated** [comment]
BTW, check out the existing issue on the page,
**screensaver name also required?** #2213
and its resolution in the Pull Request
**Details about screen saver** #3275

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@fredenocs - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by illfated. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
