### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by Tdiwestyguy** [MicrosoftDocs/windows-itpro-docs#3290]
I was a little lost on why this one article deviates from other CSPs, in that.. you list all Nodes and separately list the branches of the Nodes.  Sure they are replicated data sets, but for accuracy, it should be done. 

I know it may seem Tedious.. but really not to spell it out, to minutia, is skirting the reason documentation exists in the first place. 

I would suggest to actually represent the text, in the same format as the Visible Picture of the Nodes, and branches of URI paths, Underneath Each Node.

**Comment by illfated** [comment]
Please do not remove the automatically added information, because it is needed to trace the page you refer to when posting a question or suggestion for documentation improvements.
> Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

> ID: e0eabb49-13ec-054a-c6cc-bdd12bfec8b2
Version Independent ID: 0764f670-5d02-f47d-f583-09a047c630c5
Content: [RootCATrustedCertificates CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/rootcacertificates-csp)
Content Source: [windows/client-management/mdm/rootcacertificates-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/rootcacertificates-csp.md)
Product: w10
Technology: windows
GitHub Login: @MariciaAlforque
Microsoft Alias: maricia

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@Tdiwestyguy 

The issue has been noted and the document will be revised in the light of your feedback.

You will be kept posted on updates.

Thank you for providing feedback.

**Comment by illfated** [comment]
@Tdiwestyguy : Could you provide a small sample of what you suggest, just so I know where to start if I want to create a PR for this change? Or do you want to open a PR yourself (if yes, feel free to do so) for this change?

**Comment by e0i** [comment]
@Tdiwestyguy 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.
