### ISSUE TITLE
Ambiguous Section - "Create a device account using the Exchange Admin Center"

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/windows-itpro-docs#3295]
The "Create a device account using the Exchange Admin Center" section of this document implies that the Office 365 Exchange Online Admin Center can be used to add the account, even though the screenshot is of the Exchange 2103-or-higher EAC on-premises.

**Comment by illfated** [comment]
Looks like you posted directly on Github instead of from the related docs.microsoft.com page. Do you have the link for the page where you would like to see the improvements made?

**Comment by WillMartin58** [comment]
Interesting – I clicked the link on the doc that said View on GitHub, then posted my update there.  Here’s the doc’s link:  https://docs.microsoft.com/en-us/surface-hub/create-a-device-account-using-office-365

**Comment by illfated** [comment]
Very well, fair enough. Maybe I am misunderstanding your issue, because to me, it looks like the two sections are separated well enough by using the "Office 365 Admin Center" images in the first section, [**Create a device account using Office 365**](https://docs.microsoft.com/en-us/surface-hub/create-a-device-account-using-office-365#a-href-idcreate-device-acct-o365acreate-a-device-account-using-office-365), whereas the last section, [**Create a device account using the Exchange Admin Center**](https://docs.microsoft.com/en-us/surface-hub/create-a-device-account-using-office-365#a-href-idcreate-device-acct-eacacreate-a-device-account-using-the-exchange-admin-center) looks like it also has got the correct images for the Exchange Admin Center. From my point of view, it looks like you can choose to use either the first or the second section to achieve the goal of creating the desired account.

I might have misunderstood your issue completely, so I will wait for feedback from the Microsoft Docs team members or other users with personal experience in this topic.

**Comment by WillMartin58** [comment]
Actually, the upper solution will work if you don’t have an on-premises Active Directory that you are synching from, or if you only want the device account in the cloud.  However, the lower solution will only work if you have an on-premises Active Directory that you are synching from.  A customer read it wrong and tried to create the account using the lower solution, but had no on-premises Active Directory.

**Comment by illfated** [comment]
Thank you for pointing out the issue precisely.

Do you think it would suffice to add a note, similar to the one in the section [**Create a mobile device mailbox policy from the Exchange Admin Center**](https://docs.microsoft.com/en-us/surface-hub/create-a-device-account-using-office-365#a-href-idcreate-device-acct-exch-mbx-policyacreate-a-mobile-device-mailbox-policy-from-the-exchange-admin-center) , saying something similar to "**This method will only work if you are syncing from an on-premises Active Directory.**" ?

And if yes, where would the best logical placement be for this note? Right after the section header title, or after the 4 steps listed in the first paragraph? (or maybe even somewhere in between?)

**Comment by WillMartin58** [comment]
Yup – that’s what that lower section needs.

**Comment by illfated** [comment]
@mypil (or maybe @e0i ) -- please assign this issue ticket to the proper person (or if needed, request a ticket posted on the docs.microsoft.com page).
Please also note my PR linked above.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@illfated - Thank you for proactively helping to create the PR for this issue. 

I have tagged the other doc owners in this repo to help check and merge the content for PR #3306.
