### ISSUE TITLE
Error 0x80070005 

### ISSUE THREAD

**Issue by TyeStorm** [MicrosoftDocs/windows-itpro-docs#3378]
I have been trying to fix my updater for a while but I cannot seem to find a fix for the problem I have been having. I came here because this is the error code that I am receiving and I thought this would help. When I got to step six some of the inputs were working while others would just give me that error code. Can someone help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#feedback)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Did you try the suggested fixes on "The Windows Club" page [Fix Windows Update Install error 0x80070005](https://www.thewindowsclub.com/windows-update-install-error-0x80070005) ?

BTW, did you find that step 6 was unclear, or that it needs more clarification?

**Comment by illfated** [comment]
Oh. I think I have noticed a weakness in the **[Reset Windows Update components manually](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources#reset-windows-update-components-manually)** instruction set:
> 5. Type the following command at a command prompt, and then press ENTER:
`cd /d %windir%\system32`

The list of instructions should preferably start with
> 1. Open a Windows command prompt **as Administrator.** To open a command prompt as Administrator, click Start. Copy and paste (or type) the following command : `cmd`
Newer versions of Windows 10 contain the option "Run as administrator" on the right hand side of the Start menu, underneath the "Desktop app" in focus. For earlier versions of Windows where you don't see this feature, Right-Click the cmd app and select "Run as administrator" from your right-click menu.

If step 1 could be rewritten to assert that "Run as administrator" is used, we could get rid of the existing step 5 completely, because "Run as administrator" by default opens the CMD console to `%windir%\system32`.

@TyeStorm : Could you check if it works any better if you run the CMD console as Administrator, so your commands get full write access to its processes?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TyeStorm - We would like to follow up. Can you please respond to the query from illfated?

Thank you.

**Comment by mypil** [comment]
@officedocsbot close
