### ISSUE TITLE
Showing "種類を下スマート カード ログオン] * * 名前。" (extra asterisks appears) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3453]
https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#prepare-active-directory-certificate-authority

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [AADJ オンプレミス シングル サインオンのシングル サインオンの証明書の使用](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#prepare-active-directory-certificate-authority)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@dongmicro Would you follow-up with this localization issue?

Similar issues:

#3159  #3394 #3452 #3451

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by illfated** [comment]
I haven't quite figured out why the asterisks appear as they do in the Japanese version, but looking at the English (en-us) version of the page, it seems they need to be there as part of the explanatory text. I think this is exactly the same type of issue as in #3451 & #3452 , but I need to check it again and verify this before I can confirm that this is the case.

Excerpt from the en-us page version:
***
### Verify the onPremisesDistinguishedName attribute is synchronized
The easiest way to verify the onPremisesDistingushedNamne attribute is synchronized is to use Azure AD Graph Explorer.

1. Open a web browser and navigate to https://graphexplorer.azurewebsites.net/
2. Click **Login** and provide Azure credentials
3. In the Azure AD Graph Explorer URL, type <strong>https://graph.windows.net/myorganization/users/[userid], where **[userid]</strong> is the user principal name of user in Azure Active Directory.  Click **Go**
4. In the returned results, review the JSON data for the **onPremisesDistinguishedName** attribute.  Ensure the attribute has a value and the value is accurate for the given user.

   ![AADConnectOnPremDN](https://user-images.githubusercontent.com/38162891/62214159-c6a19f00-b3a4-11e9-9574-e3d5be4ec18c.png)
***

**Comment by illfated** [comment]
I have commented more in the English issue ticket #4589 (**Missing step to set the Subject Alternative Name in Create a SCEP Certificate Profile section?**), asking if the asterisks are needed at all or if they can be removed. This topic is unfortunately not within my experience or work area, so I have to rely on feedback from users who know this material to some extent already. Will post back here again as soon as there is a confirmed answer, one way or the other.

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by illfated** [comment]
@TinaMcN : As you can see, my PR #4626 to correct the **bold** marking in the page section https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert#create-and-assign-a-simple-certificate-enrollment-protocol-scep-certificate-profile has been merged into the source for the en-us version of the page. I can only suggest that you follow the development after the docs.microsoft.com page is updated to see when the next automated translation script procedure runs, to see if it solves this particular issue (and maybe one of the other related issues).

I was only able to find 1 more rogue asterisk ( `*` ) in the en-us version of this particular page (not sure if any issue is opened for that one on the ja-jp page), so I will keep looking around to see if I can locate any other pages where this particular type of issue happens because of a mix of HTML and MarkDown code inadvertently placed wrongly, causing asterisks to be reported from the Japanese pages.

**Comment by e0i** [comment]
Manually verified to be fixed.

**Comment by TinaMcN** [comment]
Thanks for checking @e0i Glad to see this one is fixed.
