### ISSUE TITLE
Broken link "発行元証明機関で新しい CRL 配布ポイントを構成します。"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3457]
https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base
![LINK_](https://user-images.githubusercontent.com/40815708/57059228-3abd9f80-6cef-11e9-964f-306dd8dce7b9.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 43c175ce-52a4-8b46-716f-106b4d55106c
* Version Independent ID: 374a7e9d-6e4f-f188-328b-4ca2651a9481
* Content: [Windows Hello for Business を使用して Azure AD に参加しているデバイスをオンプレミスのシングル サインオン用に構成する](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3458

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 この問題は、機械翻訳に使用されるツールに関連しています。 私はツールを担当するチームにエスカレートしました。 (Thank you for the feedback.  The issue is related to the tool used for machine translating.  I have escalated to the team who are responsible for the tool.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Thank you.

**Comment by TinaMcN** [comment]
私は人間の翻訳のためにこの記事を送った。 約3週間かかります。 (I sent this article to be human translated.  It should take approximately 3 weeks.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Corrected. 
Closed #3457.
Thanks.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.　Thanks.

**Comment by illfated** [comment]
OK, it took me a while to understand what is happening here.

Section: https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base#発行元証明機関の-crl-配布ポイントを構成する

発行元証明機関の CRL 配布ポイントを構成する
この一連の手順を使用して、ドメイン コントローラー証明書を発行して、http ベースの CRL 配布ポイントを含める証明機関を更新します。

次のような手順を実行します。

- インターネット インフォメーション サービスが CRL 配布ポイントをホストするように構成する
- 証明書失効リストをホストするファイル共有を準備する
- [発行元証明機関に新しい CRL 配布ポイントと公開場所を構成する](https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base#configure-the-new-crl-distribution-point-and-publishing-location-in-the-issuing-certificate-authority)
- CRL を公開する
- ドメイン コントローラー証明書を再発行する

The linked text above (only 1 link added instead of all 5) uses an ASCII-only link ID (# pointer), but the target section ID is in **kanji** and the link will therefore not respond to any action.

This is inconsistent and should be either ASCII on both ends or kanji on both ends, _not a combination_.

**Comment by illfated** [comment]
(ref. #3455 )

**Comment by TinaMcN** [comment]
そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by e0i** [comment]
See: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3459#issuecomment-654912262
Similar to the comment above, the `id` field seems to have both the translation and the original, while the relevant link still points to the link with the original hash ID.

cc @TinaMcN

**Comment by e0i** [comment]
See: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3459#issuecomment-654912262
Similar to the comment above, the `id` field seems to have both the translation and the original, while the relevant link still points to the link with the original hash ID.

cc @TinaMcN

**Comment by illfated** [comment]
@hyoshioka0128 : May I ask you to check the page links again, to see if any improvements can be found there?
- https://docs.microsoft.com/ja-jp/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-base

Thanks in advance for any feedback. 🙂

**Comment by hyoshioka0128** [comment]
@TinaMcN | @e0i | @illfated - Fixed. Thanks!
Closed #3457 .
