### ISSUE TITLE
toolkit be used to upgrade 500 pc's a once?

### ISSUE THREAD

**Issue by goingnova** [MicrosoftDocs/windows-itpro-docs#3510]
Can this toolkit be used to upgrade 500 pc's a once?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 042d10ec-8f56-909c-9f66-f4c1363373b9
* Version Independent ID: 3b72e026-16ea-e9bf-a48b-abb42382ddab
* Content: [Perform an in-place upgrade to Windows 10 with MDT (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit?ocid=tia-257835000#feedback)
* Content Source: [windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/upgrade-to-windows-10-with-the-microsoft-deployment-toolkit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @goingnova thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.

**Comment by e0i** [comment]
@officedocsbot close
