### ISSUE TITLE
SetupDiag – Dates are not localised

### ISSUE THREAD

**Issue by effleurager** [MicrosoftDocs/windows-itpro-docs#3623]
The output format of dates does not match the localisation settings of the machine it's run on.
```
SetupDiag v1.4.0.0
Copyright (©) Microsoft Corporation. All rights reserved.

Searching for setup logs, this can take a minute or more depending on the number and size of logs...please wait.
Found C:\$WINDOWS.~BT\Sources\Panther\setupact.log with update date 05/10/2019 23:18:56 to be the correct setup log.
```
```05/10/2019``` would be considered to be in the future outside of US territories. Dates should be localised according to system settings or standardised to ISO 8601, as done in the log files output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ad81361-15d8-0e95-9d5f-090dbf270f10
* Version Independent ID: c0c32397-d5d6-cce1-79fd-c310bec05240
* Content: [SetupDiag](https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag#release-notes)
* Content Source: [windows/deployment/upgrade/setupdiag.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/upgrade/setupdiag.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
I could be mistaken, but I presume the date format is hardcoded into the SetupDiag application. Therefore I also presume a new or updated version release is needed to support localized date formats.

You may want to contact the developers via the forum pages or Windows Feedback to call attention to your issue. This issue tracker is dedicated to working on improving the documentation pages on https://docs.microsoft.com/ .

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by illfated** [comment]
@effleurager : As a Scandinavian citizen, I completely agree with your assessment that the date format of the output from an application should comply with the localisation settings of the machine it runs on. My favourite date format is (for example) 2019-05-17 for use in file & folder names, making it easier to avoid date & time sorting issues for files & folders, because copy/save/update changes can sometimes compromise the original date of the file or folder.

I tried to find something about date format in the page you posted your issue on, but I could not find anything. Given that the documentation page does not deal with the date format, I recommend that you use other feedback tools to raise this issue with developers who are in the position to update the application with localisation formats support.

**Comment by effleurager** [comment]
As far as I'm aware these issues are mirrored internally at Microsoft, which might be why @e0i is assigned but nothing has been said from anyone representing Microsoft. Since there's no specific feedback tool available to me, I can only try Feedback Hub or Microsoft's forums.

Can anyone from Microsoft respond about this? Unless you are and I've just missed something, @illfated.

**Comment by illfated** [comment]
You have not missed anything, I am not affiliated with Microsoft. I am merely an avid Microsoft software user since 1991.
I also used to be a Microsoft Certified Product Specialist on Windows 3.1 + MS Office 4.2 (1995-1998).
These days, I am mostly a day-to-day computer support specialist, as well as a former IT repair technician.
I would merely like to point out that these pages are purely about improving the Microsoft Docs based on the software.
It is very unlikely that feedback on these pages can achieve anything else than Doc page modifications, when approved.

**Comment by ScottHendrix-MSFT** [comment]
SetupDiag is not localized, it is en-US only at this time.  Further, SetupDiag pulls the date/timestamps directly from the setup logs which are also not localized.  SetupDiag does not attempt to convert the date/timestamps of the log entries it parses.

You can always use the Feedback Hub to report feedback for SetupDiag, just be sure to mention it in the title of the Feedback and use the Windows Installation area when submitting Feedback.

**Comment by ScottHendrix-MSFT** [comment]
The best way to get help for SetupDiag is to submit Feedback via the Feedback Hub and include the word SetupDiag in the title.

As all upgrade/update logs are en-US only, the date format SetupDiag outputs should mirror that (for comparison purposes).  I have made a change to SetupDiag to use en-US only date/time formats, that fix should be coming out soon, with the next version publish.
