### ISSUE TITLE
[LOC]Showing "** 2.**" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3663]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1526c4cb-4584-7fc6-e633-a48e13dad7e8
* Version Independent ID: 13a88ed8-f43d-f658-cbe4-d148d5ffaa12
* Content: [コード整合性に対する仮想化ベースの保護を有効にする](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity)
* Content Source: [windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @e0i
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See #3159

**Comment by illfated** [comment]
Affected section on the Japanese page: https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity#requiredsecurityproperties

Weird issue. Looks like the translation script has singled out the ordinal 2. to add 1 space before it, making it the only place where the **bold** text formatting breaks.

This is about the 3 tables beneath https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity.md#requiredsecurityproperties

-- and as mentioned before, only `**2.**` gets singled out to have an additional blank in front of the number. None of the other numbers in the same table have been changed this way, neither have other appearances of `**2.**` in the document. That is odd. Then again, that is how bugs often appear, seemingly illogical until the root cause is found.

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot assign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by e0i** [comment]
The page has been moved to https://docs.microsoft.com/ja-jp/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity

**Comment by TinaMcN** [comment]
Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.
フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。

**Comment by TinaMcN** [comment]
@hyoshioka0128 元のリンクされたトピック (https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity) に新しい URL があるようです: https://docs.microsoft.com/ja-jp/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity

(The original linked topic (https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity) seems to have a new URL:  https://docs.microsoft.com/ja-jp/windows/security/threat-protection/device-guard/enable-virtualization-based-protection-of-code-integrity )


記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by illfated** [comment]
No asterisks appearing in the text what so ever.
This issue is clearly resolved.

**Comment by hyoshioka0128** [comment]
@TinaMcN  @illfated  - Fixed.
Cloesd #3663
