### ISSUE TITLE
Automate custom detection's

### ISSUE THREAD

**Issue by rstgermain** [MicrosoftDocs/windows-itpro-docs#3725]
Are there plans to let you set these to automatically run at certain intervals. For example if I make a custom detection for known malicious activity, I would want it to always run. Not have it be a one-off thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93d8d7cc-6b88-b07f-ad25-6439cc0292b1
* Version Independent ID: f2d25adc-f92e-dbac-4c2c-d678684f0de3
* Content: [Create custom detection rules in Windows Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/custom-detection-rules)
* Content Source: [windows/security/threat-protection/windows-defender-atp/custom-detection-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-atp/custom-detection-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @rstgermain  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
