### ISSUE TITLE
Microsoft Edge mode Kiosk

### ISSUE THREAD

**Issue by Moustique82** [MicrosoftDocs/windows-itpro-docs#3740]
Hello,
I tried to create a package with ICD for provisionning Win 10 to edge mode kiosk.
I test to configure the application with :
1) Classic Windows App
a. C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
b. %windir%\explorer microsoft-edge
c. Appsfolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge
2)Universal Windows App
AUMID : Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge

The package create the user but connect to a blackscreen and don t launch edge.

An idea ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Configurer un kiosque à application unique (Windows 10)](https://docs.microsoft.com/fr-fr/windows/configuration/kiosk-single-app#feedback)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Moustique82  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
