### ISSUE TITLE
License type misprint

### ISSUE THREAD

**Issue by StanislavMarimorich** [MicrosoftDocs/windows-itpro-docs#3763]
Please note that not "Office 365 Enterprise E3 and Office 365 Enterprise E5 include a Windows 10 Enterprise license", but Microsoft 365 E3 and Microsoft 365 E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3ecbc1-9c02-5681-7214-356be22ac7e8
* Version Independent ID: 73af82f6-079b-6c37-55c4-cb59e921457a
* Content: [Deploy Windows 10 Enterprise licenses](https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses#feedback)
* Content Source: [windows/deployment/deploy-enterprise-licenses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-enterprise-licenses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Good point. There has been some naming changes in the products during the last year.
- https://www.microsoft.com/en-us/microsoft-365/enterprise
- https://products.office.com/en-us/business/office-365-enterprise-e3-business-software#KEY_FEATURES

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @StanislavMarimorich 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by illfated** [comment]
@StanislavMarimorich : I am having trouble finding your quoted line
> Office 365 Enterprise E3 and Office 365 Enterprise E5 include a Windows 10 Enterprise license

within the searchable text on the page (https://docs.microsoft.com/en-us/windows/deployment/deploy-enterprise-licenses).
Is the text in one of the images, maybe with small print?
If you can help us narrow down where the wrong text is, it will be easier and quicker to correct.

**Comment by StanislavMarimorich** [comment]
It was at the top of the page in Note section. It looks like misprint is already corrected.

**Comment by illfated** [comment]
Yes, you may want to look at Pull Request https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3628 (based on issue https://github.com/MicrosoftDocs/windows-itpro-docs/issues/880) and see if that makes sense.

The files page containing the main changes (https://github.com/MicrosoftDocs/windows-itpro-docs/pull/3628/files) is probably easier to browse than the 15 separate commits merged from that PR, otherwise I would have linked directly to a master branch commit if all 15 PR commits had been squashed before merging into the `master` branch.

@e0i : You may close this issue, based on the feedback and looking at the page file history.

**Comment by e0i** [comment]
Closing the issue as it seems to be already resolved.

@StanislavMarimorich 

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
