### ISSUE TITLE
OEM App and group

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#3784]
I am working on a project with Autopilot kiosks - Lenovo adds an OEM start group and app into the start. My kiosk account, despite it being assigned access and have a custom start layout xml, still shows the Lenovo group / app in the start menu. How can we remove this?

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Niglb thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
