### ISSUE TITLE
Is this DevID will change if we format device

### ISSUE THREAD

**Issue by fijojosep** [MicrosoftDocs/windows-itpro-docs#3788]
Where this devID is stored? If device is formatted then this value will be changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b771bd46-01fc-7a0f-d58a-93758645f697
* Version Independent ID: 248d6831-0c01-fd2c-34f8-56175e6d9f2b
* Content: [DevInfo CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/devinfo-csp#feedback)
* Content Source: [windows/client-management/mdm/devinfo-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/devinfo-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MariciaAlforque
* Microsoft Alias: **maricia**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@fijojosep 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
