### ISSUE TITLE
How does one unenroll a device that was enrolled using the deployment script?

### ISSUE THREAD

**Issue by RNCRyan** [MicrosoftDocs/windows-itpro-docs#3801]
Hi, how does one unenroll a device that was enrolled using the deployment script?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4273a259-c3c7-dca7-6353-954068d740a7
* Version Independent ID: 1084ea77-95c4-4e4a-da6c-f4d8668f9ebf
* Content: [Enrolling devices in Windows Analytics (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-get-started#feedback)
* Content Source: [windows/deployment/update/windows-analytics-get-started.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-get-started.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@RNCRyan 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your question so that it gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
