### ISSUE TITLE
App Pool Identities

### ISSUE THREAD

**Issue by ewhitesides** [MicrosoftDocs/windows-itpro-docs#3907]
What is the impact of removing the various IIS APPPOOL accounts from this User Right?

It seems accounts are added by default when you install IIS or an application into IIS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d2543f-e772-44cd-f844-aae8b1456f74
* Version Independent ID: 8b300b78-863a-ee65-4f77-20250aed9792
* Content: [Generate security audits (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/generate-security-audits#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/generate-security-audits.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/security-policy-settings/generate-security-audits.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@ewhitesides 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
