### ISSUE TITLE
OEM who support white glove?

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#3914]
Hi,

Is there an official list of vendors who support the white glove provisioning method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b57d1-61b3-39d4-34ff-d6dcb858c250
* Version Independent ID: 42609104-815f-9e7a-39aa-38d92cc910c9
* Content: [Windows Autopilot for white glove deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/white-glove)
* Content Source: [windows/deployment/windows-autopilot/white-glove.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/white-glove.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@xNiklasJern 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by RAJU2529** [comment]
@xNiklasJern.   As per my knowledge, Dell, Lenovo, and  Acer are  adopted  windows autopilot

**Comment by e0i** [comment]
@officedocsbot close
