### ISSUE TITLE
Windows 10 IoT

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/windows-itpro-docs#3918]
Are there any information on if Autopilot will support Windows IoT (Enterprise) in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc999894-2a0a-bc87-7fd7-97df5f1fd04e
* Version Independent ID: ad68f62a-6bf0-5f5f-bb07-f64afe68fd10
* Content: [Windows Autopilot requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@xNiklasJern 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
