### ISSUE TITLE
Cannot add AD user to list of approved RDP users

### ISSUE THREAD

**Issue by leonbrag** [MicrosoftDocs/windows-itpro-docs#3926]
Azure VM is added to AAD, but following fails:

C:\Users\xxx>net localgroup "Remote Desktop Users" /add "AzureAD\user@test.onmicrosoft.com" 

**There is no such global user or group: AzureAD\user@test.onmicrosoft.com**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@leonbrag 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
