### ISSUE TITLE
Example of Code Integrity

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/windows-itpro-docs#3949]
The page https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/enable-virtualization-based-protection-of-code-integrity#enable-hvci-using-intune refers to AppLocker CSP to Enable virtualization-based protection of code integrity but at not times i could find an example on how to do it. Can we get one posted??

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa7dd86-8bcc-bb92-0a66-86e24701e5a4
* Version Independent ID: 277e194c-0fa3-7da6-1814-f6951e440df6
* Content: [AppLocker CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp)
* Content Source: [windows/client-management/mdm/applocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/applocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@schenardie  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@schenardie Did you get a chance to see AppLocker CSP document at https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp which has all the details and example listed in the doc.

Thanks

**Comment by schenardie** [comment]
Hi, yes i did. i do not see an example on how to deploy code integrity in it.

Can you point it out to me please if it is on the document?

**Comment by joinimran** [comment]
![image](https://user-images.githubusercontent.com/47118050/59182915-5e90c280-8b84-11e9-82d6-b79fb72d3620.png)

Please see this image, see if this portion helps. Otherwise, you have to open a support case with Microsoft Tech team so that your request can be escalated to the respective team.

Thanks.

@mypil , Please guide share the process to open a support ticket with Microsoft tech support team.

Thanks.

**Comment by schenardie** [comment]
So the documentation is unclear on how to enable Code Integrity and i need to open a support case??

Why do these features are documented then??
OK nvm close the issue then

**Comment by mypil** [comment]
@schenardie - Thank you for your response. Is there something within this article that you suggest to be added or edited? If yes, please share the appropriate text and where it should be placed, so we can have @joinimran  create a Pull Request to get it added.

Otherwise, if your issue is more of a feature request then for user feedback on product feature requests, you can submit via User Voice - **https://support.microsoft.com/en-za/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub.** 

Alternatively, if you require technical support then you can open a support ticket. Please follow this link to contact support for Windows 10 products: 
 **https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

Please understand that this site is a product documentation site and not a support nor a feature request site. I hope this gets you pointed in the right direction. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
