### ISSUE TITLE
Convert Hyper-V guests from generation 1 to generation 2

### ISSUE THREAD

**Issue by BWMerlin** [MicrosoftDocs/windows-itpro-docs#3960]
Is it possible to use MBR2GPT to convert a Hyper-V guest OS from gen 1 to gen 2 or is there more to it then simply converting the driver from MBR to GPT to upgrade to a gen 2 guest?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt#feedback)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by lindspea** [comment]
@BWMerlin thank you for reaching out.  I'll investigate with the team and get back to you shortly.

**Comment by lindspea** [comment]
@BWMerlin Thank you for reaching out. Unfortunately I'm not able to offer help in this regard, as it's not a doc related issue and not officially supported, but please let me know if there is anything else I can assist with.

**Comment by e0i** [comment]
@BWMerlin

As noted by *lindspea,* it has been found that the conversion in question is not officially supported.

Note that the issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
