### ISSUE TITLE
Locked in kiosk mode

### ISSUE THREAD

**Issue by MMmargarita** [MicrosoftDocs/windows-itpro-docs#3989]
Hi,
I enabled kiosk mode using the Settings instructions on Win10 enterprise version 1903.
I chose digital sign and selected Microsoft Edge. Then I restarted the device to enable it. 
My issue is getting out. When I press Cntl+Alt+Del, I don't have the option to log into another account. And if I reboot, it automatically logs back in on kiosk mode.

What other options do I have to sign out of assigned access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app#local)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @MMmargarita

Thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
