### ISSUE TITLE
Additional URLs to Whitelist

### ISSUE THREAD

**Issue by ewilborn** [MicrosoftDocs/windows-itpro-docs#3990]
I've found that whiteboard.microsoft.com also needs to be whitelisted. There is currently a certificate issue with the site as well, so SSL bypass may need to be utilized in some cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe78cdc5-d977-774d-3027-12a692212a55
* Version Independent ID: 8632de82-338f-aab7-cdf8-263726e83aea
* Content: [Set up and use Microsoft Whiteboard](https://docs.microsoft.com/en-us/surface-hub/whiteboard-collaboration#feedback)
* Content Source: [devices/surface-hub/whiteboard-collaboration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/whiteboard-collaboration.md)
* Product: **surface-hub**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by RAJU2529** [comment]
@ @ewilborn , I think , you add white list sites using internet options  under  all control panel.
under security tab , click on trusted sites .
add the full  address of the sites .
click Ok, ok . restart the windows

**Comment by ewilborn** [comment]
> 
> 
> @ @ewilborn , I think , you add white list sites using internet options under all control panel.
> under security tab , click on trusted sites .
> add the full address of the sites .
> click Ok, ok . restart the windows

@RAJU2529 - The whitelist I'm referring to is on a firewall or proxy for allowing communication

**Comment by illfated** [comment]
@ewilborn : if I have understood this issue correctly, are you saying that you would like to see the site name `whiteboard.microsoft.com` added to the list underneath the headline
[**Prerequisites for Whiteboard to Whiteboard collaboration (Microsoft Whiteboard 2016)**](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/whiteboard-collaboration.md#prerequisites-for-whiteboard-to-whiteboard-collaboration-microsoft-whiteboard-2016) , similar to this? :

To get Whiteboard to Whiteboard collaboration up and running, you’ll need to make sure your organization meets the following requirements:

- Office 365 with cloud-based Azure Active Directory (Azure AD) for all users
- OneDrive for Business deployed for all users who intend to collaborate
- Currently not utilizing Office 365 Germany or Office 365 operated by 21Vianet
- Surface Hub needs to be updated to Windows 10, version 1607 or newer
- Port 443 needs to be open since Whiteboard makes standard https requests
- Whiteboard.ms, **whiteboard.microsoft.com**, wbd.ms, *.onenote.com, and your company's SharePoint tenant domain URLs need to be whitelisted for proxies

**Comment by ewilborn** [comment]
> 
> 
> @ewilborn : if I have understood this issue correctly, are you saying that you would like to see the site name `whiteboard.microsoft.com` added to the list underneath the headline
> [**Prerequisites for Whiteboard to Whiteboard collaboration (Microsoft Whiteboard 2016)**](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/devices/surface-hub/whiteboard-collaboration.md#prerequisites-for-whiteboard-to-whiteboard-collaboration-microsoft-whiteboard-2016) , similar to this? :
> 
> To get Whiteboard to Whiteboard collaboration up and running, you’ll need to make sure your organization meets the following requirements:
> 
>     * Office 365 with cloud-based Azure Active Directory (Azure AD) for all users
> 
>     * OneDrive for Business deployed for all users who intend to collaborate
> 
>     * Currently not utilizing Office 365 Germany or Office 365 operated by 21Vianet
> 
>     * Surface Hub needs to be updated to Windows 10, version 1607 or newer
> 
>     * Port 443 needs to be open since Whiteboard makes standard https requests
> 
>     * Whiteboard.ms, **whiteboard.microsoft.com**, wbd.ms, *.onenote.com, and your company's SharePoint tenant domain URLs need to be whitelisted for proxies
> 
> 
> edit: BTW, are there obvious cases where the general domain `*.microsoft.com` would not be a practical addition to the whitelist?

Correct - that URL (or *.microsoft.com) should be added to the list as shown above. The full URL rather than a wildcard for Microsoft's domain is a better option in my opinion - whitelists should only be as large as they actually need to be.

**Comment by e0i** [comment]
Hello, @ewilborn 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by RAJU2529** [comment]
on my Windows 10, site mentioned 
**whiteboard.microsoft.com**   is opened in Microsoft  edge  browser.
But I could not Able to login, because access denied. reason is its azure services account is required.

**Comment by e0i** [comment]
@ewilborn 

Upon your feedback, We have updated the content with relevant changes accordingly. Thanks.

**Comment by e0i** [comment]
@officedocsbot close
