### ISSUE TITLE
corriger erreurs recovery manager

### ISSUE THREAD

**Issue by rossimonique** [MicrosoftDocs/windows-itpro-docs#4021]
VMware envoi des messages d;erreur  script SRA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5ab6b30-69ce-fbd4-b3e3-76222f1b67bd
* Version Independent ID: 28bdf6a5-075a-761b-c36e-beb945db6ae8
* Content: [Windows 10 application management](https://docs.microsoft.com/en-us/windows/application-management/#feedback)
* Content Source: [windows/application-management/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/application-management/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **elizapo**

**Comment by jvsam** [comment]
@officedocsbot assign jvsam

**Comment by jvsam** [comment]
Hi @rossimonique,  thank you for bringing this to our attention. We would love to help you but since this site is intended for product documentation, I would recommend [contacting Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) instead and opening a service ticket in your tenant so you can get your issue resolved ASAP. 

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date.

**NOTE: Using online translation tool:**
**Issue subject:**  correct recovery manager errors
**Description:** VMware sending SRA script error messages

**Comment by jvsam** [comment]
Hi @rossimonique just following up if you were you able to contact Windows 10 support for assistance? If so, we're very interested to know if you were able to resolve your issues. Again, if the resolution or information is something that can be incorporated to the existing documentation, please keep us informed and we will be happy to assist you in updating the contents of this document. Thank you.

**Comment by jvsam** [comment]
Hi again @rossimonique how are you? We haven't received any response from you, so for now, we will close this issue. However, feel free to re-open if you have suggestions to improve the quality of this documentation and we will submit them for review. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
