### ISSUE TITLE
Machine not onboarding

### ISSUE THREAD

**Issue by GlennMillerNZ** [MicrosoftDocs/windows-itpro-docs#4040]
I have followed this article exactly bu the "mdatp --health healthy" command keeps returning '1' (Not yet onboarded), nor can I see it in the machine list on the Defender portal.
How long does onboarding take?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f067243-d029-ec35-cb1d-cc271b00d0a1
* Version Independent ID: 121d2480-5bbc-9a8e-68a6-17f708dc21d4
* Content: [Installing Microsoft Defender ATP for Mac with JAMF](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-with-jamf)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-with-jamf.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-install-with-jamf.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @GlennMillerNZ , thank you for bringing this to you attention. We would love to help you but since this site is intended for product documentation, I would recommend contacting [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) instead and opening a service ticket in your tenant so you can get your issue resolved ASAP.

Also, have you already checked the [*Troubleshoot onboarding issues on the machine*](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#troubleshoot-onboarding-issues-on-the-machine) documentation? It may be of help.

Please keep us posted here on the resolution, information or improvements that can be called out in the docs. We want users to have the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful and up-to-date.

**Comment by GlennMillerNZ** [comment]
Hi jvsam. All of the information you've provided is Windows based. This is an Apple product... I will log a job through support. Thanks.

**Comment by jvsam** [comment]
Thank you for the feedback @GlennMillerNZ. 

P.S. If you get feedback from support and it's something that can be called out in the docs, please let us know.
