### ISSUE TITLE
This does not make sense

### ISSUE THREAD

**Issue by ejoepan1** [MicrosoftDocs/windows-itpro-docs#4042]
I'm using Windows Insider build 18917.  When looking through the settings&gt;windows security&gt;device performance and health&gt;device security&gt;core isolation details&gt;learn more,  I arrive at this page.  As a windows user seeking information on this feature this page should provide both a description of the feature and the MS recommendation for a the setting with cautions on what may happen if a non-recommended setting is selected.  BTW having to create a GitHub account to leave feedback is probably not what you really want Insiders or the general public to do. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c878c59f-38db-5fa0-7f0b-51899865817e
* Version Independent ID: 0b9e719f-3884-e1c6-4333-32bf9cfc9db7
* Content: [Memory integrity](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @ejoepan1 thank you for your feedback. [Memory integrity](https://support.microsoft.com/help/4096339/windows-10-device-protection-in-windows-defender-security-center#memoryintegrity) is a security feature of Core isolation. Following the steps you've followed, but using Windows 10 Home, clicking *Learn more* under the *Memory integrity setting* redirects me to this [support help article](https://support.microsoft.com/help/4096339/windows-10-device-protection-in-windows-defender-security-center#memoryintegrity) which provides general information about what it is for. In your case⁠—and perhaps because you're using Windows Insider build 18917⁠—you were redirected to the *Threat protection* documentation page which also provides information about [Memory integrity](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity). What I would do is to forward this to the Windows writing team so they can review and propose the best way on how your suggestion can be incorporated to the docs (https://docs.microsoft.com).

As regards to the use of Github, your feedback is noted. Several of the Microsoft documentation are open source and hosted on GitHub. The open source approach allows "*public-facing repos where users/contributors can make suggested changes via pull requests and also streamlines and improves communication between product engineers, content teams, and customers...*" So, you're not just leaving feedback, but you are also an active contributor who helps in ensuring the docs are accurate and up-to-date.

Again, thank you for engaging with the community!

**Comment by d00m3dd00d** [comment]
@ejoepan1 The instructions are a wreck everywhere, especially with a ton of articles referring to isolated user mode that no longer exists and other similar features. Here's something that might get you going:
-Update Windows to 1809 or 1903
-Make a Macrium recovery image, it's easy to wreck the OS after this.
-Download and run the dgreadinesstool on Microsoft's website
-Run DG_Readiness_Tool_v3.6.ps1 -capable with powershell, run it without the switch and understand the output. You can make your PC unbootable if you don't understand what you're about to do.
-Reboot
-Run DG_Readiness_Tool_v3.6.ps1 -capable again
-If everything comes back ok, run 'DG_Readiness_Tool_v3.6.ps1 -enable' 
-If anything fails, fix BIOS settings, ensure DEP is enabled, upgrade out of date hardware, etc -- your PC must meet Hyper-V and TPM 1.2 or 2.0 requirements (see hardware qualifications under this page).
-After rebooting, see 'Enable HVCI' section

**Comment by RAJU2529** [comment]
I am using memory integrity on windows 10 pro and on Windows 10 enterprise. Moreover memory integrity not available in all machines. It's depends upon processor capabilities and bios.

**Comment by RogerW2** [comment]
I always enable this feature in every build without a problem but fails to start on Insider Build 18922 with error "Memory Integrity Can't Be Started".
Memory diagnostics OK. Feedback https://aka.ms/AA5djme
Please advise, thanks in advance.

**Comment by RogerW2** [comment]
Sorry, forgot to mention that screenshots can be found here:
https://answers.microsoft.com/en-us/insider/forum/all/build-18922-device-security-memory-integrity-cant/8d5bfdea-c211-4b12-b872-dd544674a436

**Comment by RAJU2529** [comment]
I seen the screenshots. some device system drivers are blocking the features.
I would recommend to uninstall those visible drivers, Then try re enable

**Comment by RogerW2** [comment]
Thanks for your reply. I've tried uninstalling those "drivers" by clicking those buttons, they disappear, then when I try to enable memory integrity the error pops and those "drivers" show up again to be uninstalled.
Any other suggestion?

**Comment by RAJU2529** [comment]
list the drivers  and note down on paper.
boot the Windows into safe mode.  
go to  C:\windows\system32\drivers \

find the drivers and cut and copy to desktop folder.

boot the Windows into normal mode.
try to En enable

**Comment by RogerW2** [comment]
@RAJU2529
I fixed it by taking ownership of those files and deleting them. I don't know what they were, the signature was from DevGuru Co. LTD but I don't have any of their software installed, go figure. Thanks again!

**Comment by RAJU2529** [comment]
@RogerW2 .DId you able to enable memory integration successfully.

**Comment by RogerW2** [comment]
Yes and I saved the files just in case I need to restore them. Cheers!

**Comment by RAJU2529** [comment]
@RogerW2. I am very happy that your issues has been solved from my little ideas..
Keep posting if you have any further queries.

**Comment by RogerW2** [comment]
Indeed it was your first reply that led me to delete those files but, by your second reply everything was deleted and the issue fixed already. You still got credit at the linked page none the less. Cheers!

**Comment by jvsam** [comment]
Circling back to this issue. It appears that your issue is already *resolved* @RogerW2, at least based on your updates here and also in this [community Q & A](https://answers.microsoft.com/insider/forum/all/build-18922-device-security-memory-integrity-cant/8d5bfdea-c211-4b12-b872-dd544674a436). 

>As a windows user seeking information on this feature this page should provide both a description of the feature and the MS recommendation for a the setting with cautions on what may happen if a non-recommended setting is selected.

As for your suggestion, we will post an update here if improvements on this documentation have been submitted for review. Thank you again for your feedback.

**Comment by lindspea** [comment]
@ejoepan1 Thank you for reaching out to help improve MS Docs.  I work on the writing/editing side to improve/correct MS articles. Please could you confirm which part of the article in 'Memory Integrity' you are referring to. Please could you let me know if @d00m3dd00d suggestion works for you and I can have it added to the relevant article.

**Comment by ejoepan1** [comment]
Lindsay,

I am complaining that I was directed from Windows 10 Insider Edition 18922 to a GITHUB link when I was trying to get information on Memory Integrity in the Windows 10 Settings.  My point is that routing normal consumers to GitHub and requiring them to set up a GitHub account to get “More Information” on a Windows Setting is not a great User Experience.

Joe

**Comment by lindspea** [comment]
@ejoepan1 Apologies, thanks for clearing that up. I've done some more research and hopefully this link will help.  https://support.microsoft.com/help/4096339/windows-10-device-protection-in-windows-defender-security-center. Please let me know if you need any further assistance.

**Comment by ejoepan1** [comment]
Lindsay,

Look at the link you sent me and you will see this:
[cid:image001.png@01D533DB.36D3EB10]

In the Windows Insider Edition build 18932, clicking on the “Learn more” link under the highlighted Memory integrity take you to this link on GitHub
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/memory-integrity

[cid:image002.png@01D533DB.36D3EB10]

Not the link you sent me, which is much more applicable, and this is why I created the feedback.

BTW this Windows Insider Team has not addressed this issue yet.  I’ve submitted feedback at https://aka.ms/AA5ionf

Joe

**Comment by jvsam** [comment]
Hi again @ejoepan1, the suggested update to this documentation via Pull Request (PR) #4359 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
