### ISSUE TITLE
Windows 10 version 1903 - Spotlight not working.

### ISSUE THREAD

**Issue by oshada97** [MicrosoftDocs/windows-itpro-docs#4184]
I tried many ways.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by illfated** [comment]
@oshada97 : I am using Windows 10 1903 both on my Home computer and my office computer (Windows 10 Pro). Spotlight works on both of them, so I think you may have configured your Windows installation to block the feature. The best way to ensure that it works is to allow all types of Telemetry on your computer to enable the feature.

Also please note: That feature is probably better suited for the Support Forum pages, seeing that there are many pages around the internet on how to fix a broken configuration for the Spotlight feature. You may want to search (Bing or Google) to find the necessary pages containing solutions on how to re-enable the feature if you have managed to disable it during or after the installation of your Windows 10 OS.

**Comment by mypil** [comment]
@oshada97 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:  
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by illfated** [comment]
@oshada97 : Please also note that this issue tracker is intended to improve on the documentation in https://docs.microsoft.com/windows/#pivot=it-pro (ordinary users are mostly only interested in https://docs.microsoft.com/windows/windows-10/), but if you have found one of the Microsoft Docs pages to be unhelpful to your problem, please tell us which page could be improved to solve those types of issues.

**Comment by oshada97** [comment]
@illfated   @mypil  its pleasure to tell you , after putting password for windows 10 ,then it works.
Thanks for helping on this issue :heart:

**Comment by illfated** [comment]
Oh. Right. Very well. That is also something that tends to make Spotlight or other features not behave as expected. Logging in, then out and back in again can in many cases help by triggering background communication with both internet related services and also some account related settings. The login/logout detail is mentioned at least in a couple of pages I read to reactivate an otherwise blocked Spotlight feature on my own computer.

**Comment by oshada97** [comment]
Its ok @illfated  . I think this will help some people to resolve their issue.

**Comment by oshada97** [comment]
windows light 1903 feature update will solve issues.

**Comment by illfated** [comment]
Glad to hear that. On Windows 10 Pro, I had to delete all the files in the **Spotlight cache folder content** after updating to 1903 to make it advance beyond the default image. Then again, I think that was because I had disabled some of the Microsoft Telemetry settings while modifying Windows 10 privacy settings and that I had to adapt to the changes I had made. After I cleared out the Spotlight cache folder contents, rebooted, logged out and then in again a few times, I got it back to a working state.

**Comment by oshada97** [comment]
**C:\Users\username\AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets**

path is this for your work.

**Comment by illfated** [comment]
Yes, I know. I have made notes on my own computers, but it is good that you have taken notes too, so you can continue learn more about it for future use.

**Comment by oshada97** [comment]
yes i will.Thanks for cooperation.:blush:

**Comment by mypil** [comment]
@officedocsbot close
