### ISSUE TITLE
Error Code 0x801c03f3 not listed for MDM errors during autopilot

### ISSUE THREAD

**Issue by FabianNiesen** [MicrosoftDocs/windows-itpro-docs#4245]
I get a error during White Glove with autopilot. It seams related to MDM, but nothing in the lists with the MDM error codes.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@FabianNiesen - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for Windows 10 products:
**https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by greg-lindsay** [comment]
If possible, obtain logs using the following command
Mdmdiagnosticstool.exe -area Autopilot;TPM -cab c:\autopilot.cab

In general you’ll get that error if Azure AD can’t find an AAD device object for the device that you are trying to deploy.  Typically this happens when you manually delete that object – don’t do that, it will break white glove and self-deploying mode.

To fix it, remove the device from AAD, Intune, and Autopilot, then re-register it with Autopilot (which will recreate the AAD device object).

**Comment by billgatesfan** [comment]
As a colleague and myself ran into this issue today on 2 different machines, here my 2 cents after my investigations :

- I don't think FabianNiesen seeked for assistance... He was more into "please document this undocumented error", which I can understand since only 2 occurrences on Google reference this error, and this Github issue is one of them. It would be great to have this documented properly at https://docs.microsoft.com/en-us/mem/intune/enrollment/troubleshoot-windows-enrollment-errors.

- I don't know what was the status of the AAD object of my colleague in AAD, but deleting the Autopilot object, and re-importing the hash did the job for him. Means we did not deleted any AAD object that was associated with that Autopilot object, prior to hit the issue.

- We used both self-deployment mode, but no white-glove.

- Thanks to the output provided by `Mdmdiagnosticstool.exe -area Autopilot;TPM -cab c:\autopilot.cab`, in my case, the `Microsoft-Windows-ModernDeployment-Diagnostics-Provider/Autopilot event log` showed 10 attempts of following : 

> AutopilotManager began device enrollment with internal state 0.
AutopilotManager began device enrollment phase AADConfigure.
AutopilotManager completed device enrollment phase AADConfigure.  HRESULT = 0x0
AutopilotManager began device enrollment phase AADEnroll.
AutopilotManager failed during device enrollment phase AADEnroll.  HRESULT = 0x801C03F3
Autopilot device enrollment failed with error HRESULT = 0x801C03F3. Waiting 120000 milliseconds then retrying.
Current attempt 9 of 10.

- My Autopilot object was (incorrectly like sometimes...) associated with its on-prem "computer object" counterpart, instead of creating a new AAD object, like when you manually upload a CSV hash. Note : we use SCCM Co-mgmt with Hybrid AAD join.

The "onprem" AAD object showed following properties :

       {
            "accountEnabled": true,
            "deviceId": "8e95blahblah",
            "deviceObjectVersion": 2,
            "deviceOSVersion": "10.0.18363.778",
            "deviceTrustType": "ServerAd",
            "dirSyncEnabled": null,
            "displayName": "THEONPREMNAME",
            "isCompliant": false,
            "isManaged": true,
            "deviceSystemMetadata": [
                {
                    "key": "AutoPilot",
                    "value": "True"
                },
                {
                    "key": "RegistrationAuthTime",
                    "value": "123456"
                },
                {
                    "key": "CreationTime",
                    "value": "10/10/2018 5:46:25 AM"
                },
                {
                    "key": "RegistrationAuthority",
                    "value": "ADRS"
                },
                {
                    "key": "RegistrationAuthMethods",
                    "value": "[\"wia\"]"
                }
            ],
            "status": "Enabled",
            "trustTypeDisplayValue": "Hybrid Azure AD joined",
            "creationTimeStamp": "2018-10-10T05:46:25Z"
        }

I would love to know if @FabianNiesen is also using Hybrid AAD join or SCCM Co-mgmt, to know if we are almost in same scenario.

@greg-lindsay : yes, removing all the stuff in Intune and re-uploading the hash, will magically fix the issue (this is the usual Intune support engineer magic answer, as they can't provide any RCA...). But please notice that in our case, the problem was probably caused again by an Autopilot entry created in Intune, and incorrectly associated with an old "on-prem" AAD object, which failed probably to be updated/overwritten during OOBE phase, as it is a   "deviceTrustType": "ServerAd", and not deviceTrustType: "AzureAd" like it is usually with real new AAD devices.

**Comment by FabianNiesen** [comment]
Yes, you got it @billgatesfan just a bit of documentation was what i meant by It seams related to MDM, but nothing in the lists with the MDM error codes.
It could been Hybrid, I do not remember.

**Comment by mavhc** [comment]
I've just got the same error after enabling hybrid join. Currently in AAD Devices page I have machines with join type "Azure AD registered", from computers where users have logged into O365
