### ISSUE TITLE
Sufficient details are already mentioned 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#4254]
I read this article just Now. Authors are contributed their points exactly.  highlight of this article are
added Microsoft language extension link 
supported language list 

Thanks to the authors 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47bd063-dbf5-f628-3a13-4602583fb750
* Version Independent ID: 9dad7d24-7e1b-73ec-819b-9760a23f33db
* Content: [Microsoft Edge for IT Pros](https://docs.microsoft.com/en-in/microsoft-edge/deploy/about-microsoft-edge#minimum-system-requirements)
* Content Source: [browsers/edge/about-microsoft-edge.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/about-microsoft-edge.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @RAJU2529 that's good to hear! Thank you so much for taking the time to acknowledge the Microsoft authors' hard work. And since the docs are considered *continuous work in progress*, please continue to send feedback on how to make the docs better.

We will now close this issue. Thank you again for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
