### ISSUE TITLE
Question regarding Update Compliance Delivery Optimization dashboard accuracy

### ISSUE THREAD

**Issue by hammondjx** [MicrosoftDocs/windows-itpro-docs#4260]
With the current known issues with the "Device Configuration" blade of the DO dashboard - does this also impact the Content Distribution % and Content Distribution GB statistics? Just trying to understand if what I am seeing for BW SAV% can be trusted and shared with my customers.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @hammondjx, we would love to assist you, however, this site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. 

If you have issues or questions with the [Delivery Optimization in Update Compliance](https://docs.microsoft.com/windows/deployment/update/update-compliance-delivery-optimization) or to follow-up on the status of the known issues and their impact (*e.g. if the issues impact Content Distribution (%) blade, etc.*) , please contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) so that you will get immediate assistance. 

And please, do keep us posted here on the resolution or any relevant information from the support team  that can be called out in the docs. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation.

**Comment by jvsam** [comment]
Hi again @hammondjx, we haven't heard or received any updates from you, but we are hoping you were able to contact Windows 10 support. For now we will close this issue, however, feel free to re-open it if you have suggestions to improve the quality of this documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
