### ISSUE TITLE
Misleading Wording

### ISSUE THREAD

**Issue by Travia21** [MicrosoftDocs/windows-itpro-docs#4264]
Consider rewording the first paragraph. The wording initially makes AppLocker seem like it is strictly a whitelist, then contradicts that with the next paragraph defining blacklist functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11bb6d4-8f7f-9495-5fa4-c12b8c7cfdc9
* Version Independent ID: e84769bb-bc68-9f11-32c1-fa3be3bc3a8b
* Content: [Understanding AppLocker allow and deny actions on rules (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/understanding-applocker-allow-and-deny-actions-on-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/understanding-applocker-allow-and-deny-actions-on-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/understanding-applocker-allow-and-deny-actions-on-rules.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Travia21 thank you for your feedback. I would assume you are pertaining to the *Allow action versus deny action on rules* section where the first paragraph describes the behavior of the *Allowed* list, and the second paragraph segued to the *Deny* list. This is the reason why we have this Github site, to make it easier to get feedback. It would also help if you can tell us the exact messaging or information you seek or share ideas of what to add or edit, e.g. *will it be preferable and easier for users if we separate the information through sub-headings? Or just revise the current heading?* The more details you can provide, the more helpful it will be so that we will know what specific improvements we can suggest in this documentation. Looking forward to hearing from you. 

Nevertheless, I will forward your suggestion to the Windows writing team for review. Thanks for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by Travia21** [comment]
"Unlike Software Restriction Policies (SRP), each AppLocker rule collection functions as an allowed list of files. Only the files that are listed within the rule collection are allowed to run."

Assuming that were the only line read on this page, a user would get the impression AppLocker can only default block, allow by exception (granted, that's probably it's ideal use case). However, AppLocker has the ability to block by exception, as is stated in the next paragraph.

I am suggesting revising the wording in the first sentence to clarify that rule collections can function as more than an allowed list of files. Perhaps using the phrase, "...in a block by default, allow by exception configuration, each AppLocker rule collection..."

**Comment by jvsam** [comment]
> I am suggesting revising the wording in the first sentence to clarify that rule collections can function as more than an allowed list of files. Perhaps using the phrase, "...in a block by default, allow by exception configuration, each AppLocker rule collection..."

Thank you for providing more information @Travia21, that helps a lot. I've also informed the Windows writing team about this so it will surely be taken into consideration. We will let you know once the amendments have been submitted for review. Your contribution is appreciated!

**Comment by jvsam** [comment]
Hi again @Travia21, hope all is well. The suggested update to this documentation via Pull Request (PR) #4344 has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
