### ISSUE TITLE
..."In the following task sequence?"

### ISSUE THREAD

**Issue by rikirikrdo** [MicrosoftDocs/windows-itpro-docs#4266]
where is the actual sample task sequence? I don't see it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c3977f-3b78-1d8e-ad8f-50538ad1934f
* Version Independent ID: 46b9ab6d-7a30-4dab-70fa-e1c97cc3ec3e
* Content: [Set up MDT for BitLocker (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker#feedback)
* Content Source: [windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @rikirikrdo thanks for your question. You can downloaded the sample task sequence from here https://blogs.technet.microsoft.com/deploymentguys/2010/12/22/check-to-see-if-the-tpm-is-enabled/, as stated in the documentation.

> In this task sequence, we are using a sample script (ZTICheckforTPM.wsf) from the Deployment Guys web page to check the status on the TPM chip. **You can download this script from the Deployment Guys Blog post**, [Check to see if the TPM is enabled](https://go.microsoft.com/fwlink/p/?LinkId=619549).

We understand why this part, "*in the following task sequence*", may be confusing. Thank you for your feedback. 

@nenonix we need your expertise here please. Do we need to propose update since it appears *following* is used as a substantive adjective (*personally, I am not really sure about it :-)*) or will it suffice? Of course, we want it less confusing and easier for users to understand. Thank you in advance for your input.

**Comment by nenonix** [comment]
@jvsam; not confusing to me, as that sentence is followed by a list of five actions in a task sequence

**Comment by jvsam** [comment]
Hi @nenonix, appreciate your input. Can you please open a pull request to suggest that messaging? Thank you.

**Comment by jvsam** [comment]
Hi @rikirikrdo we'd like to inform you that the suggested update to this documentation (See pull request #4362) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!
