### ISSUE TITLE
翻訳(Japanese Translation)

### ISSUE THREAD

**Issue by maz2000** [MicrosoftDocs/windows-itpro-docs#4270]
グループ Id のソースを選択するの説明が以下のようになっています。
1 = 広告サイト
原文は1 = AD Siteですので

1 = ADサイト
が正しいと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: df445cda-3b0a-2ad7-e3cc-23e159013530
* Version Independent ID: a6bb5f97-d350-f7b7-77f7-b0093322289d
* Content: [配信最適化リファレンス](https://docs.microsoft.com/ja-jp/windows/deployment/update/waas-delivery-optimization-reference#feedback)
* Content Source: [windows/deployment/update/waas-delivery-optimization-reference.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-delivery-optimization-reference.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
(machine translated text from original issue post)

> The explanation of selecting the source of group Id is as follows.
> 1 = Advertising site
> Since the original text is 1 = AD Site
>
> 1 = AD site
> I think that is correct.

I may have misunderstood the above translation,
are you simply saying that you agree with the page text?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by maz2000** [comment]
yes. You are correct.

2019年6月27日(木) 16:18 Trond B. Krokli <notifications@github.com>:

**Comment by illfated** [comment]
Thank you for confirming.
That aside, it looks like there is some sort of translation misunderstanding.
"AD" is NOT the same as "advertising".
- AD ≠ ads, announcements or ad sites.
- AD = Authenticated Domain

Based on this apparent misunderstanding, I recommend spelling AD as "Authenticated Domain" instead of using initials, to avoid confusion and mistranslations.

**Comment by jvsam** [comment]
Thank you @maz2000. The docs are considered *continuous work in progress*, so please continue to send feedback to help improve the quality of the technical documentation of Microsoft Docs.

Since there is evidently an issue with the machine translation, I will get this over to the Windows writing team for review and to suggest replacing the abbreviations with complete words. 

@illfated nice catch. Thanks. Hi @dongmicro, do you have another advice? Thanks.

**Comment by jvsam** [comment]
Hi again @maz2000, we'd like to inform you that the suggested update to this documentation (See pull request #4380) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
