### ISSUE TITLE
Why there are some update udid can not find by sync MU? But I can get it from my enrolled device.

### ISSUE THREAD

**Issue by wfnyah** [MicrosoftDocs/windows-itpro-docs#4327]
suhc as 662b9834-63fe-43cd-b57b-8ea62da33001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24796ccb-a3a7-c8c5-829d-ede6e06ff7c4
* Version Independent ID: 1282c601-0457-f28a-7ad1-c373739d7004
* Content: [Mobile device management MDM for device updates](https://docs.microsoft.com/en-us/windows/client-management/mdm/device-update-management#feedback)
* Content Source: [windows/client-management/mdm/device-update-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/device-update-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> Why there are some update udid can not find by sync MU? But I can get it from my enrolled device

Hi @wfnyah thank you for opening this issue, but can you please provide more information? Is your device able to get updates from Microsoft Update or it's not syncing at all? We're happy to assist you with your concern, however, this Github site is intended to help improve the quality of the technical documentation. If it's a product or feature issue and doesn't pertain to the content of this documentation, I recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance, otherwise, we'll wait for more information from you.

**Comment by jvsam** [comment]
Hi again @wfnyah, I just want to follow-up if you were able to contact Windows 10 Support regarding your concern? Let us know if the resolution is something that can be called out in the docs. If your issue is related to the content of this documentation, please provide more information. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date. Thank you.

**Comment by wfnyah** [comment]
Hi @jvsam, sorry for I response too slow. I have open a ticket .Here is this link https://answers.microsoft.com/en-us/windows/forum/windows_10-update/why-there-are-some-update-udid-can-not-find-by/92b2cec6-53cd-45eb-8179-cac078999c19?tm=1563413791484.
Thanks!

**Comment by jvsam** [comment]
Hi @wfnyah no worries. I hope you'll find the resolution soon. For now, we will close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. You can also tag me here if there's new information from support or the community that needs to be incorporated in this doc. Thanks again for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by Kilika** [comment]
Hello,

i've got the same problem. My client reports some UpdateIdentity.UpdateId 's (which are detected via wuapi). But it look's like that these Id's are not used to find an Update on WSUS oder https://www.catalog.update.microsoft.com/.

## Client scan
```ps
$session = (New-Object -ComObject 'Microsoft.Update.Session')
$history = $session.QueryHistory("",0,50)
```
![grafik](https://user-images.githubusercontent.com/10596892/134631722-da889cbe-dabf-4f43-aabd-46b221bc3a22.png)

## Scan with an ms-wsusss implementation and also check id on microsoft update catalog 
_used endpoint: https://sws.update.microsoft.com_

![grafik](https://user-images.githubusercontent.com/10596892/134631789-4c258a8b-57a2-461f-b1df-81b27ae705a2.png)
