### ISSUE TITLE
Testing | Google drive

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#4342]
Hello,

We do have WIP deployed and working on fine-tuning,

Our test was:
1. Get Dropbox personal account
2. Ge GoogleDrive personal account
3. Copy WIP protected file to folder of Dropbox/GoogleDrive
4. Check sync behavior

In result we see:
1. Dropbox stop sync, explained here that it works only for Dropbox Business: https://help.dropbox.com/accounts-billing/security/windows-information-protection

2. But GoogleDrive could sync file, so protected file, copied to GoogleDrive folder and it is synced to GoogleDrive,
the most problematic is that after it is synced, if try use "non-managed" PC and go to Google Account @Drive location, can download that file that was synced. 
Any explanation regards GoogleDrive please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91b024a-9642-3823-360b-d657d2f1492b
* Version Independent ID: 0540cef6-7c8b-2b7d-f10a-4fb9729c1d5d
* Content: [Testing scenarios for Windows Information Protection (WIP) (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip)
* Content Source: [windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/windows-information-protection/testing-scenarios-for-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@lightupdifire . I think you should contact Google drive support.
Please visit below site for information.

**https://gsuite.google.com/intl/en_in/driveforwork/?driveforwork-work-without-limits_activeEl=all-your-work&driveforwork-safe-secure-reliable_activeEl=reliable-cloud-storage&driveforwork-ease-and-power_activeEl=no-training-wheels-needed&driveforwork-built-for-teams_activeEl=easy-to-share&driveforwork-do-more-with-google_activeEl=a-powerful-business-tool-suite**

**Comment by jvsam** [comment]
Hi @lightupdifire have you checked the [Limitations while using Windows Information Protection (WIP)](https://docs.microsoft.com/windows/security/information-protection/windows-information-protection/limitations-with-wip) article? Is the issue you're encountering not related to anything in there, for instance "*WIP is designed for use by a single user per device*?" I agree with @RAJU2529 that it might be good to contact Google Support since you are using one of their apps. If you believe the WIP feature is the issue, you also have the option to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) by opening a service ticket in your tenant. 

Also, please be informed that this Github site is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. If you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review. Thank you so much.

**Comment by lightupdifire** [comment]
Hello @jvsam,
I found solution myself and I would advise to add in document:
"If used silent configuration, please add in Protected Apps the Google Drive and set option as Deny"
Google Drive details:
Publisher=O=GOOGLE LLC, L=MOUNTAIN VIEW, S=CA, C=US
File=GOOGLEDRIVESYNC.EXE

Then if files are WIP protected, they will not sync by Gdrive.

**Comment by illfated** [comment]
@lightupdifire : Closing your issue is OK if you don't want anything more to be done about it, but from what you wrote, it looks like we should at least evaluate if your suggestion can be accepted as additional information in the Docs pages.

**Comment by lightupdifire** [comment]
Hello @illfated 
Yes, sorry, quite busy with multiple things, indeed I want to have better documentation, could help a lot for people who try setup same.

**Comment by jvsam** [comment]
Thanks for the additional information @lightupdifire. From your testing, you've added GDrive app on your protected apps list so that encrypted files can sync to the cloud and then under *Action* you set it to *Deny*, though if it's set to *Allowed*, I would assume you can download but still maintain the encryption locally. Anyway, I will get this over to the Windows content writing team for testing and also to take note of the behaviors specifically for Gdrive and suggest adding that to one of the scenarios. We really appreciate your feedback and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by lightupdifire** [comment]
Hello @jvsam ,
Our goal was to Deny sync WIP protected files, we use Silent mode in WIP as we don't want to bother employees with messages.
When used Silent mode and you have Gdrive, if you copy WIP protected file to Gdrive folder, then it will silently remove protection and upload file to Gdrive.
This not happening with Dropbox, Dropbox is already blocking sync WIP protected files without any settings.
Then to have similar setup to Dropbox, we did add Gdrive to Protected app list with Action = Deny.
Now if we copy WIP protected file to Gdrive folder, it will not sync, same as Dropbox.

**Comment by jvsam** [comment]
Awesome, thanks for the clarification @lightupdifire, much appreciated! @joinimran already created a pull request (refer: #4493) to suggest that scenario. We'll keep you posted with updates.

**Comment by jvsam** [comment]
Hi again @lightupdifire, we'd like to inform you that the suggested update to this documentation to include the *Google Drive sync scenario* (See pull request #4493) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
