### ISSUE TITLE
"Settings > Connected sources > Windows telemetry" Does not exist

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/windows-itpro-docs#4392]
The first troubleshooting step here is to navigate to this path, but this path does not exist in Log Analytics. The closest is "Advanced Settings &gt; Connected Sources", but then there is no option for Window telemetry. It appears the Windows telemetry screen has been moved somewhere else, but this document not updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20e3377-fdbc-ac87-239e-7184db24a685
* Version Independent ID: 0464da82-efa4-b147-bba9-d6802cf9d273
* Content: [Frequently asked questions and troubleshooting Windows Analytics](https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-faq-troubleshooting#feedback)
* Content Source: [windows/deployment/update/windows-analytics-FAQ-troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-analytics-FAQ-troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @cameron-interactive thank you for bringing this to our attention. Is the [Telemetry component enabled or set on your Windows 10](https://docs.microsoft.com/windows/privacy/configure-windows-diagnostic-data-in-your-organization), e.g. via group policy, etc.? I don't know your sysinfo so I am unable to search for resources that may be helpful for you. I would recommend that you check or ask the [Windows Analytics](https://techcommunity.microsoft.com/t5/Windows-Analytics/ct-p/WindowsAnalytics) Tech community as there may be other reasons why certain options are not available. You also have an option to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) for immediate assistance.

This Github site is intended to help improve the quality of the technical documentation so please keep us posted here on the resolution or any relevant information you may find that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. 

Thanks for being part of the Microsoft Docs community! We look forward to hearing from you.

**Comment by cameron-interactive** [comment]
We've enabled telemetry on a test device, yes. But that's not what I'm asking about, I'm talking about the documentation here, it tells us to open screens that do not exist. Again, there is no "Settings", it's either "Advanced Settings" or something else? Then, in there, there is no option for "Telemetry", so that can't be the right spot for it. The documentation needs to be updated to match what the Azure portal actually displays now.

**Comment by jvsam** [comment]
>The documentation needs to be updated to match what the Azure portal actually displays now.

@cameron-interactive that helps a lot. Thanks for clarifying this for us. I will get this over to the Windows content writing team to investigate the navigation steps and propose the updates accordingly. We really appreciate your feedback and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by joinimran** [comment]
> We've enabled telemetry on a test device, yes. But that's not what I'm asking about, I'm talking about the documentation here, it tells us to open screens that do not exist. Again, there is no "Settings", it's either "Advanced Settings" or something else? Then, in there, there is no option for "Telemetry", so that can't be the right spot for it. The documentation needs to be updated to match what the Azure portal actually displays now.

Can you please share the information from where and how you have activated these services? Where this lies so that we can update the document accordingly.

**Comment by cameron-interactive** [comment]
> > We've enabled telemetry on a test device, yes. But that's not what I'm asking about, I'm talking about the documentation here, it tells us to open screens that do not exist. Again, there is no "Settings", it's either "Advanced Settings" or something else? Then, in there, there is no option for "Telemetry", so that can't be the right spot for it. The documentation needs to be updated to match what the Azure portal actually displays now.
> 
> @cameron-interactive
> Can you please share the information from where and how you have activated these services? Where this lies so that we can update the document accordingly.

No, I can't as I can't find these screens listed... This is why I was referring to and logging issues with the documentation to begin with as the screens in my portal don't match what was listed.

**Comment by joinimran** [comment]
@cameron-interactive In this case, I would recommend you to open a support case with Microsoft Azure support team to better help you on this. 

@jvsam Please guide user how a user can contact and open a support case with Microsoft Azure support team.

Regards,
Imran.

**Comment by jvsam** [comment]
Hi @cameron-interactive we appreciate your patience on this matter. Since the [OMS portal has been deprecated](https://docs.microsoft.com/azure/azure-monitor/platform/oms-portal-transition) and you are using Azure portal, some of the experiences are not same, for example, viewing your log analytics data by following *Settings > Connected sources > Windows telemetry* steps are not applicable in the Azure portal. Log analytics data are available through [Azure Monitor](https://docs.microsoft.com/azure/azure-monitor/overview) and you will have to create a [Log Analytics workspace in the Azure portal](https://docs.microsoft.com/azure/azure-monitor/learn/quick-create-workspace) first. And then you can add [monitoring solutions](https://docs.microsoft.com/azure/azure-monitor/insights/solutions) from your workspace. When you install a solution, you must select [Log Analytics workspace](https://docs.microsoft.com/azure/azure-monitor/platform/manage-access) where the solution will be installed and where its data will be collected. Go to your **Log Analytics workspaces > Solutions** and if you haven't added Windows Analytics solutions (Upgrade Readiness, Update Compliance, and Device Health) yet, add [Windows Analytics in the Azure Portal](https://docs.microsoft.com/windows/deployment/update/windows-analytics-azure-portal).

I've tested this and was able to add Windows Analytics and can see *Upgrade Readiness* from the dashboard. 

![image](https://user-images.githubusercontent.com/18371314/62834786-f1da8880-bc05-11e9-8322-033a649c7071.png)

More information in adding [Upgrade Readiness solution to your Azure subscription](https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-get-started) and running the [Upgrade Readiness deployment script](https://docs.microsoft.com/windows/deployment/upgrade/upgrade-readiness-deployment-script) to troubleshoot data sharing issues. 

@joinimran thanks for creating a pull request with updates (#4665) but can we add a note with the correct steps in the Azure portal, including relevant links? The existing steps are still applicable for the OMS portal, if I am not mistaken. Thank you so much!

**Comment by jvsam** [comment]
Hello again @cameron-interactive, thank you for your patience. I just want to inform you that there's already a suggested update to this documentation (see PR #4687) based on your feedback. PRs are normally reviewed/merged in the order of submission but once approved, they will be displayed here at docs.microsoft.com site in the next scheduled publishing run. I will let you know once the PR has been approved and merged.

**Comment by jvsam** [comment]
Hi @cameron-interactive, apologies if it took long but the good news is, the pull request has been approved and merged (see #4687). Thank you again for your feedback. Soon, the updates will reflect here at docs.microsoft.com site. 

We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation. Thank you for your being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot assign

**Comment by jvsam** [comment]
@officedocsbot close
