### ISSUE TITLE
avoid malware suggestions

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/windows-itpro-docs#4425]
Why no mention of not using old binary / 2003 file formats, use the new 2007 X-file formats.
No mention of not using RTF format

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dea73d5-6cf6-3b6d-b1cd-14a67672d55e
* Version Independent ID: 1db9d496-4942-01e6-4550-1a5cb6a770e5
* Content: [Prevent malware infection](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/prevent-malware-infection)
* Content Source: [windows/security/threat-protection/intelligence/prevent-malware-infection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/intelligence/prevent-malware-infection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **levinec**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Ronsss we always strive to improve the quality of the technical documentation of Microsoft Docs so thank you for your feedback. Though it will help a lot if you can provide more details, for instance, what exactly are you looking for or do you have specific suggestions when it comes to messaging? Do you want us to add, perhaps under *Other safety tips*, another tip that states *"be careful about opening old binary, 2003 file formats and RTF formats?"* And when you say *2003 file formats*, are you pertaining to old office file formats? Is that not *somewhat* addressed in this [Macro malware](https://docs.microsoft.com/windows/security/threat-protection/intelligence/macro-malware#feedback) doc where you've also provided the same suggestion? Or under [Fileless threats > Execution and injection](https://docs.microsoft.com/windows/security/threat-protection/intelligence/fileless-threats#execution-and-injection). The more information you can give us, the more helpful it will be so that we will know what improvements to suggest to this documentation. Thanks for understanding and we look forward to hearing from you.

**Comment by Ronsss** [comment]
Sorry, I've lost the context (I submitted 2 similar comments). What was the original article (link) that this comment submitted on?  Might be useful to automatically include in all of your replies (?).
.
Somewhere in the original article I commented on I thought it would be appropriate to mention that ALL of the old "Binary" / 2003 and earlier file formats are not secure because they allow macros to be included. Because people are used to thinking in terms of files and specific file types. The mentions I've seen tend to say "documents".  Maybe that could be covered by a link to this page you referenced (https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/fileless-threats#execution-and-injection)

<snip>
Is that not somewhat addressed in this Macro malware<https://docs.microsoft.com/windows/security/threat-protection/intelligence/macro-malware#feedback> doc where you've also provided the same suggestion?
</snip>
Your "somewhat" is what I take issue with.  The reason someone is reading pages like this is that they are looking for specific guidance.

On this macro malware page they talk about not opening files. It would help if that page could be more specific.  The old 2003 / binary file types, DOC XLS (others as appropriate allow macros to be embedded. So they are definitely a bad file types to avoid opening.  On the other hand a new x-file type as an attachment is not going to have a macro virus in it, .

On the Macro Malware page another strategy is to return the email with potential malware bearing file type and ask the sender to resend the attachment in an appropriate file type.

Another strategy is to have your File Options > Trust Center > File Block settings set to either completely block opening vulnerable file types or to open them with warnings and in protected mode. I haven't come across a mention of it yet.

<snip>
Don’t open suspicious emails or suspicious attachments.
</snip>
This statement assumes the reader is knowledgeable about what is suspicious. But the reader is looking for information, for guidance. Be specific, define what makes an email or attachment "suspicious". Potentially, that could be a link to another detailed page... Unknown sender, obscured hyperlinks, list file types vulnerable to containing malware (DOC, RTF, ZIP containing vulnerable file types)

****************

One point I'm trying to make is that all of these related pages are very generic, application agnostic for the most part (a little Office specific when mentioning Trust Center) . How about creating new page(s) / new section that is Office application specific. How to avoid malware in Outlook. How to avoid Malware in Word (which can tie back to Outlook). I was looking for mention of the Trust Center File Block feature, but I didn't find it.


On Sat, Jul 13, 2019 at 2:15 PM Jo <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @Ronsss<https://github.com/Ronsss> we always strive to improve the quality of the technical documentation of Microsoft Docs so thank you for your feedback. Though it will help a lot if you can provide more details, for instance, what exactly are you looking for or do you have specific suggestions when it comes to messaging? Do you want us to add, perhaps under Other safety tips, another tip that states "be careful about opening old binary, 2003 file formats and RTF formats?" And when you say 2003 file formats, are you pertaining to old office file formats? Is that not somewhat addressed in this Macro malware<https://docs.microsoft.com/windows/security/threat-protection/intelligence/macro-malware#feedback> doc where you've also provided the same suggestion? Or under Fileless threats > Execution and injection<https://docs.microsoft.com/windows/security/threat-protection/intelligence/fileless-threats#execution-and-injection>. The more information you can give us, the more helpful it will be so that we will know what improvements to suggest to this documentation. Thanks for understanding and we look forward to hearing from you.

**Comment by jvsam** [comment]
Hi @Ronsss the other issue you've opened is #4426 and we have suggested updates to the documentation as per your feedback. It's also linked to this issue (*I am not sure if automatically appending it to the notification email is supported by Github since you haven't seen it in the email thread*). 

![image](https://user-images.githubusercontent.com/18371314/61596898-f0e1a880-abbd-11e9-94d7-a858851e85c3.png)

All right, let me list your suggestions.

1. Suggestions: 

> Somewhere in the original article I commented on I thought it would be appropriate to mention that ALL of the old "Binary" / 2003 and earlier file formats are not secure because they allow macros to be included. Because people are used to thinking in terms of files and specific file types. The mentions I've seen tend to say "documents". 

**Content:** https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/prevent-malware-infection
**Next step:** I will forward this to the Windows content writing team for review.

2. Suggestions:

> a. On this macro malware page they talk about not opening files. It would help if that page could be more specific.  The old 2003 / binary file types, DOC XLS (others as appropriate allow macros to be embedded. So they are definitely a bad file types to avoid opening.  On the other hand a new x-file type as an attachment is not going to have a macro virus in it.
> b. On the Macro Malware page another strategy is to return the email with potential malware bearing file type and ask the sender to resend the attachment in an appropriate file type.
> c. Another strategy is to have your File Options > Trust Center > File Block settings set to either completely block opening vulnerable file types or to open them with warnings and in protected mode. I haven't come across a mention of it yet.

**Content:** https://docs.microsoft.com/windows/security/threat-protection/intelligence/macro-malware
**Next step:** Please open a Github issue on the *Macro malware* content page. **NOTE**: *You can tag me so I can assign the issue to myself and track its progress.*

3. Others:

> One point I'm trying to make is that all of these related pages are very generic, application agnostic for the most part (a little Office specific when mentioning Trust Center) . How about creating new page(s) / new section that is Office application specific. How to avoid malware in Outlook. How to avoid Malware in Word (which can tie back to Outlook). I was looking for mention of the Trust Center File Block feature, but I didn't find it.

We really appreciate all your feedback @Ronsss. For the new topic contents, I am tagging @levinec for review and consideration. Thank you so much.

**Comment by jvsam** [comment]
Hello @Ronsss, we really appreciate your patience and thank you again for sharing your feedback. Please be informed that the pull request (See PR #5724) that contains suggestions based from your feedback has been approved and merged. This documentation will be updated in the next scheduled publishing run. We will now close this issue, thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
