### ISSUE TITLE
Install-ProvisioningPackage -LogsFolder <string> error

### ISSUE THREAD

**Issue by staynik** [MicrosoftDocs/windows-itpro-docs#4504]
When I used Install-ProvisioningPackage -LogsFolder &lt;string&gt; it comes up saying -LogsFolder is not valid, even though that is what is listed on this page. Instead, it wants me to use -LogsDirectoryPath. I did confirm -LogsDirectoryPath worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9d3111-a801-5fbd-51fd-182c9fcde05d
* Version Independent ID: b6515ca3-15f5-5a24-0aea-612c0f5867ab
* Content: [PowerShell cmdlets for provisioning Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-powershell#feedback)
* Content Source: [windows/configuration/provisioning-packages/provisioning-powershell.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-powershell.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
@staynik : Thank you for posting this issue. Could you also confirm which Windows 10 version you used, or maybe you have tested on more than one version?

**Comment by staynik** [comment]
I have just tried this on 1903
________________________________

**Comment by illfated** [comment]
Should be interesting to see if someone using 1709/1803/1809 could confirm or counter-argue this issue, just to narrow this down to whether the documentation is completely off, regarding that parameter, or if it needs specific updating for 1903.

**Comment by jvsam** [comment]
Hi @staynik thanks for your feedback. Perhaps that is why *Install-ProvisioningPackage* Cmdlet is not listed because it uses -LogsDirectoryPath as a parameter? Can you please confirm if this will work for you for 1903, https://docs.microsoft.com/powershell/module/provisioning/install-provisioningpackage?view=win10-ps? A [community contribution](https://techcommunity.microsoft.com/t5/Windows-10/Install-Provisioning-Package-with-PowerShell-in-Windows-10-1703/td-p/60187) suggests the same Cmdlet for 1703. Like what @illfated have said, we want to identify if there are inaccuracies in this documentation or maybe it's intended for 1703 only. 

Let me also check with the Windows content writing team. Your patience is appreciated!

**Comment by illfated** [comment]
Oh. Good point. I didn't notice until now that `Install-ProvisioningPackage` is not listed on the related page (https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-powershell) at all. And just as you said, Jo, it does look like it is described in detail on the page https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage?view=win10-ps instead.

Could it be that this is only a simple misunderstanding?

**Comment by illfated** [comment]
Oh, and by the way, @staynik , if you have got time, maybe you could suggest improvements to the [`Install-ProvisioningPackage`](https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage?view=win10-ps) page via the issue ticket #247 (**General content missing. Too much "add here"-s**) ?

**Comment by jvsam** [comment]
Hi @staynik this documentation, it would appear, is specific to PowerShell cmdlets that work for Windows 10, version 1703. There may be more changes (*and maybe testing*) if we will request for it to be expanded to include other [provisioning related cmdlets](https://docs.microsoft.com/powershell/module/provisioning). Do you have specific suggestions to this page? Please let us know, otherwise, we will close this issue. Thank you again.

**Comment by jvsam** [comment]
Hi again @staynik, we will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation. Please consider as well opening an issue on this page and suggest improvements https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage. Thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
