### ISSUE TITLE
Newcomer to using Device Security & Core Isolation

### ISSUE THREAD

**Issue by Cyberchipz** [MicrosoftDocs/windows-itpro-docs#4507]
I'm here, from a link provided in the Core Isolation settings in my Windows Pro machine.
I've got an extensive background in development, programming, and standard network security (policy, various troubleshooting, etc.)  But, I'm completely new to device security and core isolation.  I'm always looking for better was to protect my machine and ultimately help others, family, etc..  

I'm just looking a for more in-depth understanding of how to implement this (newly found by me) security feature.  I promise to be light with contributors time; I very highly prize the support, information or assistance I get from these repositories.  That said..

Initially any links to information on using the feature would be greatly appreciated.  I've read the few related closed cases listed. I'm seeing that it's recommended to make an image of my machine first, and check and confirm compatibility with my devices I use before turning on this feature.  And information on doing that would be a great start for now.  I can handle making an image; but as far as ensuring my devices (drivers?) are compatible, or able to handle the requirements of implementation, not quite sure.  Right now I only know they work, and I use them.

I'm not sure what to do or look for to implement this.   I've noticed that my motherboard supports Hyper-V, which having created and used a virtual machine a few times, and find the isolation and protection to be beneficial for this old White Hat. I do have reasons to want to ensure I'm better protected than most. I'm 65 and trying to keep my toe in on security (active brain exercises?!), again, saw something mentioned on Hyper-V; but not sure how it would be related; except perhaps, creating a more secure image.  Very appealing.

 Anyway, this looks like areas I'd like to explore; anything deemed a requirement, any pointers or links to information would be appreciated on using this core feature for Defense.  Please be gentle ;-)

So far, reading closed issues on the linked page in Core Isolation has been my only experience on this subject, as far as I know at this time. (I'm patient) So, thank you... again!  If we could start with _confirming_, like any major change, that I should/must start with a good backup and image of my machine would be welcome.

So, it looks like obtaining Macrium for that image; that and reading information i get directed to, until I can budget the imaging software (around 1 to 2 months) will be my path. 

As a side question, would I be legally able to create a Hyper-V copy using the existing license on this machine.  Windows 10 Pro?  I do have hopes of _one day_ putting a honey pot at the front door. ;-) 

Apologies, hope this isn't TL;DR!

**Comment by illfated** [comment]
Fair enough, your post may be a little bit long to read, but that is not really an issue here. I can see that the style of your post is quite common for anyone wanting to ask questions in a social forum, instead of contacting Microsoft Support directly.

What I would like to suggest, is for you to consider posting this in one or more Microsoft forums instead of the issue tracker for the Microsoft Docs pages. This issue tracker has been made available to Github users mostly to improve the quality and content of the Windows IT Pro pages on docs.microsoft.com . Sure enough, questions posted in these pages do get replied to once in a while or every so often, as long as the question or requested answer can be narrowed down and connected to a docs.microsoft.com page for the topic in question. Your post, on the other hand, looks a lot more like material for a discussion on a broader spectrum, or at least with feedback from multiple experienced users and technical experts.

@e0i / @jvsam / @mypil : Could you recommend some forums for this type of question?

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @Cyberchipz I agree with @illfated. And your willingness to learn and explore new tech is commendable. We also want to make sure that we point you to the right community where you can interact with other Windows enthusiasts. Here's one of the communities where you can start:

https://techcommunity.microsoft.com/t5/Microsoft-Defender-Advanced/ct-p/MicrosoftDefenderAdvanced

A list of communities that you may want to check as well as you progress with your learning goals https://techcommunity.microsoft.com/t5/Communities/ct-p/communities

You might also be interested with the [Windows Insider Program](https://insider.windows.com/en-us/) and here's the Tech Community for it, https://techcommunity.microsoft.com/t5/Windows-Insider-Program/bd-p/WindowsInsiderProgram

And in the future, if you have suggestions related to Microsoft Docs or ideas to make the technical documentation better for users, you can create a GitHub issue directly from a content page. 

![image](https://user-images.githubusercontent.com/18371314/61583023-0c2db480-aae7-11e9-9c85-cea3f6724b78.png)

For now, we will close this issue. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
