### ISSUE TITLE
Upgrading to Windows 10 Enterprise with Office 365 E3

### ISSUE THREAD

**Issue by Jcweb35** [MicrosoftDocs/windows-itpro-docs#4603]
Our small non-profit purchased 5 365 E3 licenses for use of the office staff and the ability to upgrade to Windows 10.

All of our systems are currently running Windows 7 :-(,  

Cannot find a download link for Win 10 on Office 365 admin.  How do we upgrade each system to Win 10 Enterprise?

**Comment by illfated** [comment]
If all your Windows 7 versions are Windows 7 Professional or Windows 7 Ultimate, it will be necessary to first upgrade them to Windows 10 Professional before applying the Enterprise licenses. I think this should still be possible, because I did upgrade my company's old Windows 7 Ultimate computer to Windows 10 Professional a few months ago.

**Comment by Jcweb35** [comment]
Thanks.  I'll try that.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @Jcweb35 this Micrcosoft [Windows 10 upgrade paths](https://docs.microsoft.com/windows/deployment/upgrade/windows-10-upgrade-paths) doc can help. As you can see on the table, you cannot upgrade directly to Windows 10 Enterprise if you are using Windows 7 Home. However, for Pro, it seems it's possible. Since you have M365 subscription, there may be additional steps that you need to perform beforehand. Please check this discussion at the [Tech Community](https://techcommunity.microsoft.com/t5/Microsoft-365/M365-upgrade-windows-7-to-Windows-10/m-p/326450#M2370), where you can also participate and ask questions.

For Windows 7 Pro, it says [here](https://docs.microsoft.com/microsoft-365/business/upgrade-to-windows-pro-creators-update) that "*If you have Windows devices running Windows 7 Pro, Windows 8 Pro, or Windows 8.1 Pro, your Microsoft 365 Business subscription entitles you to a Windows 10 upgrade - you don't require a Product Key*." 

And here's another important information to consider:

> Windows 7 required you to redeploy the operating system using a full wipe-and-load process if you wanted to change from Windows 7 Professional to Windows 10 Enterprise. More details [Windows 10 Subscription Activation](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation).

@illfated for the *Upgrade Paths* perhaps it's different in this case because of the E5 subscription? If the doc is not accurate, please propose an amendment if time permits? Thank you.

**Comment by illfated** [comment]
Thank you for the tip and the links, I have not had the opportunity to test upgrading to Enterprise versions myself. My comment above was mostly based on previous feedback in other issue pages where Windows 10 Pro was a necessary step in the process. Those could have been related to Windows 10 Home, I don't remember that part in detail.

**Comment by jvsam** [comment]
All right, thanks for the clarification @illfated.

Hi again @Jcweb35, we hope the information we've provided helped. If you encounter difficulties upgrading, you can open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance or start a conversation at the [Microsoft Tech community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers. We will now close this issue. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
