### ISSUE TITLE
Table issue in the German version 

### ISSUE THREAD

**Issue by d-Rickyy-b** [MicrosoftDocs/windows-itpro-docs#4604]
In the German version, the table is broken where the pipe character `|` should be. That leads to the parameter description disappearing.

![grafik](https://user-images.githubusercontent.com/5798157/62326849-5fbcdc80-b4af-11e9-8f34-e3992b612b7c.png)

Comparison to the English version:
![grafik](https://user-images.githubusercontent.com/5798157/62327086-f7bac600-b4af-11e9-9131-83aa72e7e890.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f25443de-57f4-c8f2-fecb-f58714467894
* Version Independent ID: 1d783d00-ae0d-3eea-9a32-b42dd32e73c2
* Content: [Verwenden der Befehlszeile zum Verwalten von Windows Defender Antivirus](https://docs.microsoft.com/de-de/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Difficult to say why it happens in the German version, because the Github source for the German page is not available to ordinary users.
Could be a spacing issue or just simply a machine translation issue, which might have removed the extra table cell delimiting pipe character.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @d-Rickyy-b. Your feedback to improve the quality of the localized documentation is very much appreciated!

@dongmicro please see the feedback from a community user. Thanks.

**Comment by jvsam** [comment]
@officedocsbot assign @dongmicro

**Comment by d-Rickyy-b** [comment]
Thanks a lot. I want to send out some kudos to the seamless integration of GitHub issues into your documentation. It couldn't be easier to report issues. Microsoft is on a lovely way - I like where everything is going. Keep up the good work 😊 .

**Comment by jvsam** [comment]
@officedocsbot assign @TinaMcN

**Comment by jvsam** [comment]
You're very much welcome @d-Rickyy-b and thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@d-Rickyy-b thanks for reporting it.  It appears to be an issue with the Machine Translation tool. I've reported it to the tool owners but it will likely be a while before it's fixed.  The same issue occurs for other languages too.

**Comment by illfated** [comment]
To me, it seems like the raw table content uses the escape character (backslash) a lot, to make sure the parameter divider pipe (functioning as "or" between the arguments is kept from being used as a cell divider for the table. I wonder if it would be helpful to surround the command arguments with back ticks to mark them as code, to see if that might mitigate the issue when being translated.

Current table on Github (en-us):

| Command                                                                                                 | Description                                                                                            |
|:--------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------|
| \-? **or** -h                                                                                           | Displays all available options for this tool                                                           |
| \-Scan [-ScanType #] [-File \<path> [-DisableRemediation] [-BootSectorScan]] [-Timeout \<days>] [-Cancel] | Scans for malicious software                                                                           |
| \-Trace [-Grouping #] [-Level #]                                                                        | Starts diagnostic tracing                                                                              |
| \-GetFiles                                                                                              | Collects support information                                                                           |
| \-GetFilesDiagTrack                                                                                     | Same as Getfiles but outputs to temporary DiagTrack folder                                             |
| \-RemoveDefinitions [-All]                                                                              | Restores the installed Security intelligence  to a previous backup copy or to the original default set |
| \-RemoveDefinitions [-DynamicSignatures]                                                                | Removes only the dynamically downloaded Security intelligence                                          |
| \-RemoveDefinitions [-Engine]                                                                           | Restores the previous installed engine                                                                 |
| \-SignatureUpdate [-UNC \| -MMPC]                                                                       | Checks for new Security intelligence updates                                                           |
| \-Restore  [-ListAll \| [[-Name \<name>] [-All] \| [-FilePath \<filePath>]] [-Path \<path>]]               | Restores or lists quarantined item(s)                                                                  |
| \-AddDynamicSignature [-Path]                                                                           | Loads dynamic Security intelligence                                                                    |
| \-ListAllDynamicSignatures                                                                              | Lists the loaded dynamic Security intelligence                                                         |
| \-RemoveDynamicSignature [-SignatureSetID]                                                              | Removes dynamic Security intelligence                                                                  |
| \-CheckExclusion -path \<path>                                                                           | Checks whether a path is excluded                                                                      |

Same table after adding back ticks (code markers):

| Command                                                                                                  | Description                                                                                           |
|:-------------------------------------------------------------------------------------------------------- |:------------------------------------------------------------------------------------------------------|
| `-?` **or** `-h`                                                                                         | Displays all available options for this tool                                                          |
| `-Scan [-ScanType #] [-File <path> [-DisableRemediation] [-BootSectorScan]] [-Timeout <days>] [-Cancel]` | Scans for malicious software                                                                          |
| `-Trace [-Grouping #] [-Level #]`                                                                        | Starts diagnostic tracing                                                                             |
| `-GetFiles`                                                                                              | Collects support information                                                                          |
| `-GetFilesDiagTrack`                                                                                     | Same as `-Getfiles` but outputs to temporary DiagTrack folder                                         |
| `-RemoveDefinitions [-All]`                                                                              | Restores the installed Security intelligence to a previous backup copy or to the original default set |
| `-RemoveDefinitions [-DynamicSignatures]`                                                                | Removes only the dynamically downloaded Security intelligence                                         |
| `-RemoveDefinitions [-Engine]`                                                                           | Restores the previous installed engine                                                                |
| `-SignatureUpdate [-UNC \| -MMPC]`                                                                       | Checks for new Security intelligence updates                                                          |
| `-Restore  [-ListAll \| [[-Name <name>] [-All] \| [-FilePath <filePath>]] [-Path <path>]]`               | Restores or lists quarantined item(s)                                                                 |
| `-AddDynamicSignature [-Path]`                                                                           | Loads dynamic Security intelligence                                                                   |
| `-ListAllDynamicSignatures`                                                                              | Lists the loaded dynamic Security intelligence                                                        |
| `-RemoveDynamicSignature [-SignatureSetID]`                                                              | Removes dynamic Security intelligence                                                                 |
| `-CheckExclusion -path <path>`                                                                           | Checks whether a path is excluded                                                                     |

Please note: I had to keep the backslash escape character in front of the argument pipe dividers, even between the back tick code tags, to keep MarkDown from interpreting them as cell dividers.

I suspect that the machine translation tool to somehow inserts a space after the backslash, making the pipe divider ( `|` ) appear as a cell divider again, and that this might be the cause of this issue.

@d-Rickyy-b : Should some of the arguments, like `-Bauteile` appear as valid command arguments in their translated form, instead of `-ListAll`?

**Comment by d-Rickyy-b** [comment]
@TinaMcN thank you for the info. Looking forward to a solution :)

@illfated I actually doubt that `-Bauteile` should be a valid command argument. On the one hand it's not the correct translation for `-ListAll` (Bauteile [plural] means somehting like components), oh the other hand I don't think command line parameters should be translated, should they? I did not find the parameter `-Bauteile` working which confirmes my assumption.

I also thought about the issue being related to something with the pipe character being somehow altered which leads to the broken table.

**Comment by illfated** [comment]
Very well, thanks for confirming that parts of the table actually gets translated (and incorrectly translated as well) when it should not.

I still think it would be useful to add the code back ticks to try to keep as much of the code intact, without being translated, therefore not affected by character replacement or wrong spacing.

**Comment by illfated** [comment]
You can also see the translation tool affecting the table in the French version:
https://docs.microsoft.com/fr-fr/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus

**Comment by illfated** [comment]
Well, the PR is now merged into the [`MicrosoftDocs:public`](https://github.com/MicrosoftDocs/windows-itpro-docs/tree/public) branch.

Just waiting for the migration to the docs.microsoft.com site to see the results on the Machine Translated pages a few hours after that.

**Comment by jvsam** [comment]
Hello @d-Rickyy-b thank you again for your feedback. We will now close this issue since it has been resolved and there is already a pending update which will be displayed here at docs.microsoft.com in the next scheduled publishing run.

Please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation. Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
