### ISSUE TITLE
Different behavior with O365 and a local AD with SSO

### ISSUE THREAD

**Issue by AlexAftanas** [MicrosoftDocs/windows-itpro-docs#4609]
When on a on-premises AD and the user is using O365 and you set the minimum password age setting to 1 or more then as an administrator you reset a password in AD and check "must change password at next logon" the behavior is different than what is listed on this page.

The behavior is that a user authenticating through O365 still is limited by the minimum password age setting.  In other words the O365 user will need to wait a day before resetting the password if the minimum password age is 1 day.  Even if the admin checks the "must change password at next logon" when resetting the password.

Again this behavior is when there is a on-premises AD using SSO with O365 and the user is logging in through O365.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @AlexAftanas happy to help, however, can you please point us to the correct documentation where you are seeing the discrepancy? Are you pertaining to this information that is available [here](https://docs.microsoft.com/office365/admin/manage/set-password-expiration-policy?view=o365-worldwide), perhaps?

> People who only use the Outlook app won't be forced to reset their Office 365 password until it expires in the cache. This can be several days after the actual expiration date. There's no workaround for this at the admin level.

Or this warning for Azure AD's password writeback? A common issue for some users who [can't sign in to Office 365, Azure, or Microsoft Intune because that option is enabled](https://support.microsoft.com/help/2855271/how-to-troubleshoot-password-synchronization-when-using-an-azure-ad-sy)?

> Use of the checkbox "User must change password at next logon" in on-premises Active Directory administrative tools like Active Directory Users and Computers or the Active Directory Administrative Center is not supported. When changing a password on-premises do not check this option.

If not, we recommend going directly to the actual content page and submit the feedback from there. This new feedback system at docs.microsoft.com leverages the GitHub platform so we can easily track it and if there are amendments to be made, we can easily create a pull request and submit it for review. 

![image](https://user-images.githubusercontent.com/18371314/62408036-dbce2780-b576-11e9-9ab2-ab5b223da1da.png)

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@AlexAftanas I will now close this issue since you have already opened #4611 from the actual content page. We will track that instead. Thank you again.

**Comment by jvsam** [comment]
@officedocsbot close
