### ISSUE TITLE
Markup escaping issues?

### ISSUE THREAD

**Issue by countingpine** [MicrosoftDocs/windows-itpro-docs#4631]
Hi.
There are some double backslashes in commands, e.g. 'ren c:\\boot\\bcd bcd.old', in Methods 3/4
Also there are two missing filename parameters under Method 4, e.g. 'attrib-s -h -r'

(While I'm here, there's some inconsistency with the attribute ordering, I'd suggest alphabetical, i.e. '-h -r -s'.  There's also capitalisation inconsistencies with commands like bootrec/bcdedit.)

(Also while I'm here, why is Notepad's file dialog enlisted for copying/renaming files?  Maybe that's not worth looking at in this issue though.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems#feedback)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@countingpine - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by illfated** [comment]
@countingpine : I plan to open a Pull Request for the main issue you have outlined above, hopefully this evening.

At first, I thought that maybe your comment about the double backslashes could have something to do with the command being tested and copied from a PowerShell console or have anything at all to do with a folder path containing spaces or special characters, but that does not seem to be the case here. All I can hope for, is a potential correction feedback when I open the pull request containing removal of the secondary backslash at each occurrence.

Regarding your suggestion to reorder the attribute parameters for the `attrib` command, they are ordered logically instead of alphabetically. As a long-time MS-DOS user since 1990, I would like to point out that the logical order of the `attrib` command parameters are:
```
-a (Archive)
-r (Read-only)
-s (System)
-h (Hidden)
```
I am going to suggest a reordering of the parameters in the Pull Request based on the listed order above, though, because writing the `-r` parameter at the end of the command reminds me too much of the `/r` (Recursive) parameter, which `-r` does not mean at all. Example:
```
attrib -r -s -h bootmgr
```

**Comment by illfated** [comment]
Oh, and by the way: Double backslash is not a big problem, because the cmd command interpreter will normally ignore redundant backslashes.
- https://stackoverflow.com/questions/21078804/double-backslash-in-cmd-directory-handling/21080688
