### ISSUE TITLE
Is this new key suppose to override this setting?

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/windows-itpro-docs#4645]
System/Internet Communication Management/Internet Communication settings 
     Policy Setting:  Turn off access to all Windows Update features = Enabled  

Should having this new option Enabled allow Optional Features to install?  It seems to allow them from the old style Control Panel Add Feature area but not the newer Windows 10 &gt; Apps &gt; Add Optional Features area.  Was looking to allow FoD from MS but leave Win Updates to WSUS but this key doesn't seem to let us do that by itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d423c0e-fd99-9ad5-a11a-45237c2149fc
* Version Independent ID: f30e4101-7a8e-bfa9-a7c0-de7c36499cf5
* Content: [Windows 10 - How to make FoD and language packs available when you're using WSUS/SCCM](https://docs.microsoft.com/en-us/windows/deployment/update/fod-and-lang-packs)
* Content Source: [windows/deployment/update/fod-and-lang-packs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/fod-and-lang-packs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi again @mattsmacblog, seems this issue is related to the other one that you've created (refer: #4637). Have you had a chance to check the resources? I've provided several reference links that may help you. You can also check the [scenario table here](https://blogs.technet.microsoft.com/swisspfe/2018/04/13/win10-updates-store-gpos-dualscandisabled-sup-wsus/). Of course, the last option is to contact [Windows 10 support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) to get immediate assistance. Please let us know if there is anything in this documentation that needs improvement so we can submit the feedback for review. Thank you.

**Comment by mattsmacblog** [comment]
Thanks @jvsam I've read a bunch of the resources sadly most are now pretty out of date, 1803, 1809 and 1903 have added a lot of new GP settings and behaviours...  Just be good to include on this page as of 1903 this new setting doesn't have precedence over the "Turn off access to all Windows Update features = Enabled" setting to clarify it for people...

**Comment by jvsam** [comment]
Hi @mattsmacblog were you able to confirm from Support if that's the case? It would be good if we have that information.

>  Just be good to include on this page as of 1903 this new setting doesn't have precedence over the "Turn off access to all Windows Update features = Enabled" setting to clarify it for people...

Hi @greg-lindsay hope all is well. Can you please provide some insights on this? Your help is appreciated.

**Comment by jvsam** [comment]
Hello again @mattatmsft. I know it's been a while since this issue was opened so thank you for your patience. I just wanted to follow up if you've found the answer to your question or if you have contacted Windows 10 support? It would be great if you can share relevant information with us so we can determine if it's something that can be incorporated into this documentation. 

Hello again @greg-lindsay, are you still the owner of this doc or is it now @jaimeo? I just want to follow up if you have any information about this. So far, I haven't found anything concrete other than forum conversations, which appear to suggest that if the policy setting *"Turn off access to all Windows Update features"* is enabled on 1903, it will block, e.g. downloading of FOD if you are on a Windows domain environment even if the setting *"Specify settings for optional component installation and component repair"* is enabled. Or what will be the right combination of getting the updates? Thank you, looking forward to your feedback or any information that can shed some light on this issue.

> Should having this new option Enabled allow Optional Features to install? It seems to allow them from the old style Control Panel Add Feature area but not the newer Windows 10 > Apps > Add Optional Features area. Was looking to allow FoD from MS but leave Win Updates to WSUS but this key doesn't seem to let us do that by itself.

Related issue: #4637

**Comment by jvsam** [comment]
Hi again @mattsmacblog, I just want to follow-up if you had a chance to contact Support and confirm your assessment?

> Just be good to include on this page as of 1903 this new setting doesn't have precedence over the "Turn off access to all Windows Update features = Enabled" setting to clarify it for people...

It would be good to know and if yes, we can assist in creating a pull request with the suggestion. Have you also tested it? Please keep us posted here, thank you.

**Comment by jvsam** [comment]
Hello again @mattsmacblog, we haven't heard or received any updates from you. We are hoping that you were able to contact support or have engaged with the community to find the answer to your question. For now, we will close this issue, however, feel free to re-open if you find relevant information that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close
