### ISSUE TITLE
Must have proxy servers as neutral for WDAG

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/windows-itpro-docs#4668]
Hostnames and aliases for proxy servers must be included in the "Domains categorized as both work and personal" policy (aka "neutral"). That's an important note left out of the documentation for that policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a8c802-79ca-1593-c045-2ed150e9ce40
* Version Independent ID: 3dabd613-2eee-7c65-6f30-6746c8fb5bdf
* Content: [Configure the Group Policy settings for Windows Defender Application Guard (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard)
* Content Source: [windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback @iadgovuser1. To clarify, you are suggesting to add, e.g. a note on the *Domains categorized as both work and personal* description that this can include *hostnames and proxy servers? And are you pertaining to both local and internet proxies?* We appreciate the clarification.

Hi @ManikaDhiman how are you? For the WDAG policy, do we have available information in the [NetworkIsolation/NeutralResources CSP](https://docs.microsoft.com/windows/client-management/mdm/policy-csp-networkisolation#networkisolation-neutralresources) on how we can define or correctly add hostnames and proxy servers, if supported of course? Is it an IP address, port number like *server:port* format? (see [proxies using symbolic names](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-guard/faq-wd-app-guard)). Thank you in advance for your continued assistance. 

**NOTE**: An interesting reference read, see [Network](https://techcommunity.microsoft.com/t5/Data-Center-Security/PAW-deployment-guide/ba-p/372296) section.

**Comment by iadgovuser1** [comment]
@jvsam The product group told us that proxy servers must be included in the neutral policy. We were initially using the DNS alias name for the proxy server, but had to use the actual hostname (FQDN). We were cautious and included both the hostname (FQDN) and alias (FQDN). The documentation doesn't mention this anywhere. Whatever proxy you point WinInet (browsers) and WinHTTP (services) to use need to be in the neutral policy.

**Comment by jvsam** [comment]
> The product group told us that **proxy servers** must be included in the neutral policy. 

Thanks for that additional information @iadgovuser1. For the above, I will request the Windows content writing team to review and to suggest adding that to this documentation. I cannot confirm the proper format though, if *Hostname/Alias* and *FQDN* format are acceptable. Did they work for you when you've added them?

Hi again @ManikaDhiman, any information regarding the format? Sorry if I tagged you, I assumed you may have an idea since you own the CSPs? Appreciate the help!

**Comment by iadgovuser1** [comment]
@jvsam We ended up using FQDN and entering the proxy server's host (A) record FQDN and alias (CNAME) record FQDN. I'm not sure if both are required. Maybe only the A record is required.

**Comment by jvsam** [comment]
Thanks for that additional information @iadgovuser1. Just to confirm, does the Application Guard work with that setting in place? I haven't received any confirmation yet on the proper format. I am curious, did you add the domain name in the A record and the IP address of the proxy server in the record's address?

**Comment by iadgovuser1** [comment]
@jvsam 

As far as I know the format is always going to be FQDN regardless of whether the A or CNAME record of the proxy server is used. I think a simple statement of **Proxy servers must be a neutral resource listed in the "Domains categorized as both work and personal" policy.** would likely suffice.

**Comment by jvsam** [comment]
Noted on that. Thanks you @iadgovuser1.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, is this issue resolved? From the comments above, it seems updates are required in windows/security/threat-protection/windows-defender-application-guard/configure-wd-app-guard.md.

**Comment by jvsam** [comment]
Yes, it is @ManikaDhiman. Thank you for the follow-up.

Hello again @iadgovuser1, we appreciate your patience. Your suggested update to this documentation to include a note regarding proxy servers (see pull request #4979) has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue since it's considered—albeit with pending updates⁠— *resolved*. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
