### ISSUE TITLE
Autopilot Reset in Intune for Education is coming soon

### ISSUE THREAD

**Issue by ChrisMSNT** [MicrosoftDocs/windows-itpro-docs#4695]
This article is outdated. Autopilot reset is already in Intune for Education.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 687baa4b-2e3b-e632-403f-546f7e1bbaf3
* Version Independent ID: eabccfdc-45ec-339d-a4c2-537f1387608d
* Content: [Reset devices with Autopilot Reset](https://docs.microsoft.com/en-us/education/windows/autopilot-reset)
* Content Source: [education/windows/autopilot-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/education/windows/autopilot-reset.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @ChrisMSNT thank you so much for bringing this to our attention. I will get this over to the Windows content writing team to suggest adding the instructions for the [Remote Autopilot Reset in Intune for Education](https://docs.microsoft.com/intune-education/autopilot-reset) (*For Windows 10, version 1809 and later*). The information on this documentation is still applicable in resetting devices with local *Windows Autopilot Reset* which can be performed by IT Admins, specifically for Windows 10, version 1709 and later versions.

We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated! Thank you again for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello again @ChrisMSNT, we appreciate your patience. There's already a suggested update to this documentation to remove the *"coming soon"* contents related to [Autopilot Reset in Intune for Education](https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/Introducing-Remote-Autopilot-Reset-in-Intune-for-Education/ba-p/332539), please see pull request (PR) #4981. Since the PR has been approved and merged, expect that it will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue since it's considered—albeit with pending updates⁠— *resolved*. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
