### ISSUE TITLE
Offboarding OMA-URI missing?

### ISSUE THREAD

**Issue by richard-irwin** [MicrosoftDocs/windows-itpro-docs#4712]
Step 3 of the offboarding process references a "following supported OMA-URI", but that seems to be missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc98378-18c5-81bf-769e-d76d26852c91
* Version Independent ID: dd542381-071b-e583-f082-976e8fd91019
* Content: [Onboard Windows 10 machines using Mobile Device Management tools](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-mdm#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-mdm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/configure-endpoints-mdm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> Step 3 of the offboarding process references a "following supported OMA-URI", but that seems to be missing.

Thank you for bringing this to our attention @richard-irwin. I understand that you are looking for the OMA-URI settings, right? For your reference, here's the [WindowsAdvancedThreatProtection CSP](https://docs.microsoft.com/windows/client-management/mdm/windowsadvancedthreatprotection-csp) (see *offboarding* blob) and details in [creating/adding custom settings](https://docs.microsoft.com/intune/custom-settings-windows-10).

Hello @mjcaparas, hope all is well. Can you please confirm the Offboarding OMA-URI settings in Microsoft Intune? Is this accurate?

OMA-URI: ./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/Offboarding
Date type: String
Value: [*Copy and paste the value from the content of the WindowsDefenderATP_valid_until_YYYY-MM-DD.offboarding file*]

We appreciate your assistance. Thank you.

**Comment by mjcaparas** [comment]
@jvsam - that looks about right. Thanks!

**Comment by jvsam** [comment]
That's great @mjcaparas, thank you very much for the confirmation. We will create a pull request to suggest adding the OMA-URI settings and will submit them to you for review and merging. 

@richard-irwin, we really appreciate your feedback. Thank you.

**Comment by jvsam** [comment]
Hello again @richard-irwin, we appreciate your patience. The suggested update to this documentation to include the supported OMA-URI settings (see pull request #4982) has been approved and merged. The content updates will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue since it's considered—albeit with pending updates—*resolved*. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
