### ISSUE TITLE
ICONES DESACTIVESS

### ISSUE THREAD

**Issue by ahvanco** [MicrosoftDocs/windows-itpro-docs#4718]
Bonjour,
il y a 3 ou 4 jours, windows 10 me demande de redémarrer pour résoudre un problème d'erreur de disque. Cela m'est déjà arrivé plusieurs fois et après une pseudo réparation du disque, puis un ou des démarrages avortés se traduisant par une réparation automatique, je me retrouve à chaque fois avec une réinstallation complète. Donc, je passe outre à chaque démarrage et la machine semble fonctionner. Malheureusement, une grande partie des icones est devenues inactive, le menu de bouton droit sur l'icone de démarrage ne présente plus que le choix bureau bureau ou arrêt...
Les procédures DSIM /SFC n'ont rien donné. Je me prépare à formater !
je reconnais que mes machines datent un peu...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 00912925-8922-8c5e-fc36-d00fb992114c
* Version Independent ID: 1dd2bc12-d31b-dcd8-a2fb-c279adfa81a5
* Content: [Résoudre les erreurs du menu Démarrer](https://docs.microsoft.com/fr-fr/windows/configuration/start-layout-troubleshoot#feedback)
* Content Source: [windows/configuration/start-layout-troubleshoot.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/start-layout-troubleshoot.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by ahvanco** [comment]
tdlrecover.exe et sysfer.dll  n'existent apparemment plus, mais c'est surtout le catastrophique problème des réparations automatiques de Windows10 que je voudrais pouvoir éviter...

**Comment by jvsam** [comment]
I am sorry to hear that @ahvanco. Please be informed that this Github site is intended to help improve the quality of the technical documentation through user contributions and feedback, and since your issue appears to be product related, I recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. You can also visit the [Technet forums](https://social.technet.microsoft.com/Forums/home) and the [Tech Community](https://techcommunity.microsoft.com/t5/Communities/ct-p/communities) where you can ask questions and interact with other users, experts and also Microsoft engineers.

Please keep us posted here on the resolution or information that can be called out in the docs. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. Thank you.

**Online translation (Bing):** 
*Hello, 3 or 4 days ago, windows 10 asks me to restart to fix a disk error problem. This has already happened to me several times and after a pseudo repair of the disc, then one or more aborted starts resulting in an automatic repair, I find myself each time with a complete reinstallation. So I skip every boot and the machine seems to work. Unfortunately, a lot of the icons have become inactive, the right button menu on the boot icon only presents the choice office or stop ...
The DSIM/SFC procedures did not work. I'm getting ready to format!
I recognize that my machines date a little ...*

**Comment by jvsam** [comment]
Hello @ahvanco, we didn’t hear back from you. Were you able to contact support? We hope your issue has been resolved. Now, if you have suggestions related to this documentation or ideas to make it better for users, please let us know here and we will submit them for review, otherwise, we can now close this issue. Thank you.

**Comment by jvsam** [comment]
Hello again @ahvanco, we will now close this issue, however, feel free to re-open if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
