### ISSUE TITLE
Kiosk mode section isn't anchored 

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/windows-itpro-docs#4733]
Please make the kiosk mode heading have an anchor so that it can be directly linked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd1e023-65ae-0e1d-b031-c02f5fb1daf8
* Version Independent ID: 8053b30a-82b6-404e-5daa-2110fb56c20b
* Content: [Prepare a device for kiosk configuration (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-prepare)
* Content Source: [windows/configuration/kiosk-prepare.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/kiosk-prepare.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@lanatmwan : I can only assume you are talking about the incorrectly formatted line
```
## Testing your kiosk in a virtual machine (VM)
```
because it is preceded by the invisible HTML tag
```
<span id="test-vm" />
```
which should either be removed or at least separated from the heading by adding a blank line in front of it, to make it work as a section heading like this:
## Testing your kiosk in a virtual machine (VM)
... and thereby automatically become linked in the link menu on the right hand side.

If you can confirm that this is the line you are interested in seeing, it should be an easy task to resolve that issue.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lanatmwan - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@lanatmwan - Does your issue fit what @illfated described on his comment above? Please confirm.

Thank you.

**Comment by v-tbert** [comment]
Yes, that is the change I was suggesting. That particular nugget of information is quite important for testing.

**Comment by illfated** [comment]
Thank you. I will have the fix ready shortly, linking it back here when it is uploaded.

**Comment by illfated** [comment]
There you go, Pull Request #4745 ready for copy review & other suggested improvements.
