### ISSUE TITLE
Hardware-based isolation link

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/windows-itpro-docs#4738]
The link only refences to Application Buard - no mention of System Guard...?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dcaddick - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@dcaddick - We would like to follow up on this. May we know which Microsoft document link you used in reference to this issue? Please share it with us so we can make the necessary changes to improve the MS document for accuracy.

**Comment by illfated** [comment]
@dcaddick : Please see https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/overview-hardware-based-isolation for links to both.
Please also answer the question of where you found this issue, because we don't know which page you refer to where the link is supposed to be (or if it needs to be corrected).

**Comment by mypil** [comment]
@dcaddick - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue. 

Please feel free to open a new issue if there is a particular area of the docs that we can improve or make better and kindly link it to the specific MS doc. Thank you.
