### ISSUE TITLE
ConfigureKioskResetAfterIdleTimeout - MultiApp

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/windows-itpro-docs#4754]
Will ConfigureKioskResetAfterIdleTimeout be supported in MultiApp deployment anytime? I successfully set the setting but it does nothing in a multiple configuration. I have public kiosks and would like the Edge session to reset after a given time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f840fa14-a379-d297-c3f7-ada05ec299d6
* Version Independent ID: 81396f7b-7506-43cd-fd9a-4066719a6eb2
* Content: [Deploy Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/microsoft-edge/deploy/microsoft-edge-kiosk-mode-deploy)
* Content Source: [browsers/edge/microsoft-edge-kiosk-mode-deploy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/microsoft-edge-kiosk-mode-deploy.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Niglb  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
