### ISSUE TITLE
HTTP:// vs HTTPS://

### ISSUE THREAD

**Issue by CCDFischer** [MicrosoftDocs/windows-itpro-docs#4769]
Every instance of mentioning not using protocols gives the example https:// or https://, one of these should surly be http://

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd25175-8d39-ba5a-6483-79d021b5d116
* Version Independent ID: 30f683a5-02f3-3f43-577c-d6c2c2bf74a6
* Content: [Enterprise Mode schema v.2 guidance (Internet Explorer 11 for IT Pros)](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance)
* Content Source: [browsers/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance.md)
* Product: **ie11**
* Technology: **internet-explorer**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by illfated** [comment]
I agree, it looks silly to say the least, seeing https://contoso.com mentioned 2 times in the same sentence, as if they were different to each other. Same goes for every double mention of https:// later down on the page. What is the recommended order here, is it **http** first, then **https** ?

- "[ ... ] automatically applies to both http://contoso.com and https://contoso.com." ?

**Comment by jvsam** [comment]
Thanks for bringing this to our attention @CCDFischer! Your feedback is much appreciated. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date.

@illfated, if time permits, would you mind creating a pull request to correct one of the protocols so they won't appear redundant? Please let me know, otherwise, I can ask someone from the content writing team. So far, I've see 3 instances. Also, *http* normally precedes *https* and personally, I don't think the placement in the sentence will be an issue unless it changes the context, no? As always, thank you!

**Comment by illfated** [comment]
Thank you for asking. Sorry I was a bit occupied during the last 24 hours, but it should be an easy enough task to create a PR to solve the mentioned redundancy.

**Comment by jvsam** [comment]
This is great, thank you @illfated!

**Comment by jvsam** [comment]
Hi @CCDFischer just a quick update. The changes are now displayed here at docs.microsoft.com and you can verify by visiting this URL: https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/enterprise-mode-schema-version-2-guidance. Thanks again for your feedback and thanks too for fixing this @illfated!
