### ISSUE TITLE
loadstate parameter /progress the log file name should be loadlog.log

### ISSUE THREAD

**Issue by alghaden** [MicrosoftDocs/windows-itpro-docs#4777]
misstypo
loadstate /i:migapp.xml /i:migdocs.xml \server\share\migration\mystore /progress:prog.log /l:scanlog.log
it should be
loadstate /i:migapp.xml /i:migdocs.xml \server\share\migration\mystore /progress:prog.log /l:loadlog.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560b9a5d-d642-cd87-4d42-8fe4e4bab7c6
* Version Independent ID: ee572330-99ec-89a5-1830-cb8478b1e758
* Content: [LoadState Syntax (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-loadstate-syntax#feedback)
* Content Source: [windows/deployment/usmt/usmt-loadstate-syntax.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/usmt/usmt-loadstate-syntax.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention, @alghaden. I will get this over to the Windows content writing team to correct the log filename as it currently shows */l:scanlog.log* which is for the [*ScanState*](https://docs.microsoft.com/windows/deployment/usmt/usmt-scanstate-syntax) syntax, not the one for *LoadState* (*/l:load.log*). We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated!

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Hello again @alghaden, we appreciate your patience. We'd like to inform you that the requested amendment to this documentation (see pull request #4983) has been approved and merged. The content update will be displayed here at docs.microsoft.com in the next scheduled publishing run. We will now close this issue since it's considered—albeit with pending updates—*resolved*. Feel free to re-open or create another issue through the doc's *feedback feature*, if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
