### ISSUE TITLE
Licensing requirements needs updating? 

### ISSUE THREAD

**Issue by AlexJPawlak** [MicrosoftDocs/windows-itpro-docs#4778]
With recent add-on of M365 Security addon to existing Office365 E3 customers and others the article might need update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13006cbf-ad22-e75a-bf3a-2a6d0b92f088
* Version Independent ID: c9a7a12f-2ef5-b5fa-b515-41ecce5fecd1
* Content: [Troubleshoot Microsoft Defender ATP onboarding issues](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#licensing-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for bringing this to our attention @AlexJPawlak. We appreciate you taking the time to share your feedback to improve the quality of this documentation.

Hello @mjcaparas, since Office 365 Advanced Threat Protection (ATP) is now included in Office 365 Enterprise E5, Office 365 Education A5 and can be purchased as an [add-on to certain subscriptions](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#licensing-requirements), can we add the following in the list of [supported licensing requirements](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/troubleshoot-onboarding#licensing-requirements)?

- Office 365 Enterprise E5
- Office 365 Education A5
- Advanced Threat Protection (ATP) Plan 1 or ATP Plan 2 subscription (See: [Feature availability across Advanced Threat Protection (ATP) plans](https://docs.microsoft.com/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans). )

Kindly confirm if the content of this doc (*onboarding issues*) is applicable to the above plans and we can create a pull request to add the information and submit it for your review. Thank you in advance for your assistance.

**Comment by jvsam** [comment]
Hello again @mjcaparas, just following up if you had the chance to review this issue and the request. Can you please confirm if we can include the following in the list of supported licensing requirements? Thank you very much.

> Office 365 Enterprise E5
Office 365 Education A5
Advanced Threat Protection (ATP) Plan 1 or ATP Plan 2 subscription

**Comment by mjcaparas** [comment]
Checking with team.

**Comment by jvsam** [comment]
Thanks @mjcaparas for looking into this.

**Comment by jvsam** [comment]
Hello again @mjcaparas, just following up if you have heard from the product team? Did they confirm the inclusion of the new subscriptions, in addition to the *Microsoft Volume Licensing* plans? Looking forward to your feedback.

**Comment by mjcaparas** [comment]
Office 365 is seperate from Microsoft 365 E5. Office 365 ATP is also a separate product. So no, I confirm that the content of this doc (onboarding issues) is not applicable to the mentioned plans. 

For more information on licensing, there's a great resource here: https://github.com/AaronDinnage/Licensing

**Comment by jvsam** [comment]
Thank you for the confirmation @mjcaparas, and that's a great resource. Much appreciated. 

Hello @AlexJPawlak, to reiterate the confirmation from the doc author:

> Office 365 is seperate from Microsoft 365 E5. Office 365 ATP is also a separate product. So no, I confirm that the content of this doc (onboarding issues) is not applicable to the mentioned plans.

Again, thank you for your feedback. Please continue to send ideas or suggestions to improve the quality of the Microsoft documentation. Thanks for being part of the Microsoft Docs community!
