### ISSUE TITLE
Set-mppreference is configured with dead URL.

### ISSUE THREAD

**Issue by rjbutt** [MicrosoftDocs/windows-itpro-docs#4831]
Team,

URL redirection for Set-MPPreference is configured to point to a URL that doesn't exist. It should be pointing to "https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps". Currently it's pointing to "https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference.md" that gives you 404 error message of page doesn't exist.  Please see highlighted in attached screenshot. Thank you for all the hardwork :)

![Issue](https://user-images.githubusercontent.com/17909567/64079315-2943ce80-ccb4-11e9-8b82-2c23e25b0093.jpg)

**Comment by illfated** [comment]
Would be nice to know which page this is about, in addition to what is wrong on the page.
Where did you find this?

**Comment by jvsam** [comment]
assign @jvsam

**Comment by illfated** [comment]
OK, I found it after some searching, using internet search engines:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-antivirus/deploy-manage-report-windows-defender-antivirus.md

**Comment by illfated** [comment]
To be specific, the page is currently pointing to
- https://technet.microsoft.com/itpro/powershell/windows/defender/set-mppreference.md

which also does not exist, but the http server tries to find it in the docs.microsoft.com hierarchy anyway, instead of reporting the technet.microsoft.com page as the dead link.

Anyway, if you remove the `.md` extension from that link, at least the server finds the correct page,
https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps

**Comment by illfated** [comment]
The source links are a bit odd, because they vary from pointing to TechNet and MSDN without actually being linked to any of those pages, but simply using MarkDown code brackets like in Wikipedia. Note that the following link, [Update-MpSignature](https://technet.microsoft.com/itpro/powershell/windows/defender/update-mpsignature) [] still works, but mostly because the following brackets are separated from the bracketed link text with 1 space character.

The raw cell content looks like this:
`Use the [Set-MpPreference][] and [Update-MpSignature] [] cmdlets available in the Defender module`

A possible solution could be to remove both sets of empty brackets from that line, in addition to adding a period ( `.` ) at the end of the sentence for readability.
