### ISSUE TITLE
AutoPilot Hybrid Join with Tenant Restrictions

### ISSUE THREAD

**Issue by maxchenz** [MicrosoftDocs/windows-itpro-docs#4853]
We have tenant restrictions in place on our Corporate Network. How can we get AutoPilot to work when we have to have a trusted internal root certificate on our machines before we can get to Azure AD services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2be263b-5134-0e2d-ad25-101e55aeb85a
* Version Independent ID: 43593283-afe8-80d0-38d5-1be447cd50b4
* Content: [Windows Autopilot support](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/autopilot-faq)
* Content Source: [windows/deployment/windows-autopilot/autopilot-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/autopilot-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello, @maxchenz  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
