### ISSUE TITLE
legacy terms being used

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windows-itpro-docs#4872]
Enterprise Cloud Suite no longer exists.  It's now referred to as M365.

And On-Prem Azure MFA Server is no longer an option for customers, so it shouldn't be included in the planning documentation.  Since it's still a supported product, it should be kept in the troubleshooting documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5739fab2-c6db-a7a9-b0e7-2bf4b85912a7
* Version Independent ID: 82c58053-c1d7-d938-1b0f-f3f7f70ada3b
* Content: [Planning a Windows Hello for Business Deployment](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-planning-guide)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-planning-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/hello-for-business/hello-planning-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @poortom1004 thank you for your feedback. The note on this doc that lists different pricing plans/options where Azure Multi-Factor Authentication is available is accurate. It says bundled with:

1. [Azure Active Directory Premium](https://azure.microsoft.com/pricing/details/active-directory/), this includes Free, Office 365 apps edition, Premium P1, and Premium P2.
2. [Enterprise Mobility Suite](https://www.microsoft.com/en-us/microsoft-365/enterprise-mobility-security), this is M365's *Identity & access management* feature.
3. [Enterprise Cloud Suite](https://www.microsoft.com/licensing/licensing-programs/enterprise) is for organizations with 500* or more users or devices and is available via the Enterprise Agreement.

More information [here](https://azure.microsoft.com/pricing/details/multi-factor-authentication/). 

> And On-Prem Azure MFA Server is no longer an option for customers, so it shouldn't be included in the planning documentation. 

For the above, it still is for [existing customers who have activated MFA Server prior to July 1, 2019](https://docs.microsoft.com/azure/active-directory/authentication/howto-mfaserver-deploy) but not for new deployments. This documentation is still relevant to customers using MFA Server. 

Hi @mapalko, if you are not busy, can you please let us know if there is an ongoing update or a plan to update this documentation or the doc set since it heavily references Azure MFA server? We appreciate any information you can provide us. Thank you.

**Comment by mapalko** [comment]
Changes we made to update the on-prem deployment guides which fully rely on on-prem MFA server. The planning guide and other documents were not updated, but should be updated to no longer recommend on-prem MFA server because it cannot be enabled for new deployments.

**Comment by jvsam** [comment]
> Changes we made to update the on-prem deployment guides which fully rely on on-prem MFA server. The planning guide and other documents were not updated, but should be updated to no longer recommend on-prem MFA server because it cannot be enabled for new deployments.

@mapalko is it ok then to add the same *[Important and warning notes](https://docs.microsoft.com/azure/active-directory/authentication/howto-mfaserver-deploy)* here?

How about @poortom1004's question with regard to terminology? The same terms are reflected [here](https://azure.microsoft.com/pricing/details/multi-factor-authentication/). 

Thank you again!

**Comment by jvsam** [comment]
Hello again @mapalko, we'll create a PR and suggest adding the warning note, similar to what's on the Azure doc and submit it for your review and approval. Thank you again.

**Comment by jvsam** [comment]
Hello again @poortom1004, thank you for your patience. Please be informed that the suggested update to this documentation to include the on-prem MFA server warning (See pull request #5022), has been approved and merged. It will be displayed here at docs.microsoft.com in the next scheduled publishing run. 

As for the terms used on this doc, there is no change as of this time, and there are still several contents across the Microsoft site where those terms are used (*please see the links that I've provided*). We also can't guarantee the accuracy of the information from external resources. However, rest assured that if there will be updates, the doc author will surely update this document as well. 

We will now close this issue, but please continue to send your feedback and suggestions to improve the quality of the Microsoft documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
