### ISSUE TITLE
「モバイルデバイス管理 (MDM) を使用して AppLocker のポリシーを管理する」セクションが空っぽです

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [MicrosoftDocs/windows-itpro-docs#4894]
MDM を使用した場合の方法について、見出しのみで内容の掲載がありません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c1906d52-45c5-aa31-877d-38a2794dcb16
* Version Independent ID: fee4f9d4-d574-d404-0d40-09f2bad98f47
* Content: [AppLocker のポリシーを管理する (Windows 10)](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/windows-defender-application-control/applocker/maintain-applocker-policies#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/applocker/maintain-applocker-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/maintain-applocker-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@ShintakuNobuhiro - このフィードバックを送信していただきありがとうございます。[Thank you for submitting your feedback.]

これを調査のために転送します。[We will forward this for investigation.]

**Comment by mypil** [comment]
@TinaMcN  - Can you please assist with this new localization issue?

Thank you.

**Comment by illfated** [comment]
Please note that the same is true for the EN-US version of this document:
docs.microsoft.com (en-us):
- https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/applocker/maintain-applocker-policies#maintaining-applocker-policies-by-using-mobile-device-management-mdm
***
## Maintaining AppLocker policies by using Mobile Device Management (MDM)

## Maintaining AppLocker policies by using Group Policy
***
Github/MicrosoftDocs/windows-itpro-docs (master branch):
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/threat-protection/windows-defender-application-control/applocker/maintain-applocker-policies.md#bkmk-applkr-use-mdm
***
## <a href="" id="bkmk-applkr-use-mdm"></a>Maintaining AppLocker policies by using Mobile Device Management (MDM)



## <a href="" id="bkmk-applkr-use-gp"></a>Maintaining AppLocker policies by using Group Policy
***
This looks like a general documentation issue, instead of being a translation issue.

**Comment by mypil** [comment]
@TinaMcN - Do you have any updates on this? Thanks.

**Comment by illfated** [comment]
Meanwhile, I would like to note that there has not been any page comment regarding the US English version of the page, regarding the lack of information for that specific section ( **Maintaining AppLocker policies by using Mobile Device Management (MDM)** ). Could we perhaps ask the current author & manager Daniel Simpson what might have caused this missing information in that section in the first place?

**Comment by TinaMcN** [comment]
@mypil this appears to be an issue in the source (English) content as @illfated mentioned.  I agree with @illfated's suggestion to ask the author to fix the English content first.  Then we'll pick up the update for the localized content.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@ShintakuNobuhiro - 我々の理解から、問題はマージされたコミットhttps://github.com/MicrosoftDocs/windows-itpro-docs/commit/28005be79521aefef05a268c4acb54f7403dc020#diff-ddee9f659034cd6ddf3c4f5cd6358e34 に基づいて解決されました。解決されていないと思われた場合は、この問題を再度開いてください。

[From our understanding, the issue has been resolved based on the merged commit. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!]

ドキュメントをより良くするためにあなたの貢献をありがとう!非常に感謝!
