### ISSUE TITLE
Disable Device Guard not possible

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MicrosoftDocs/windows-itpro-docs#4917]
Running Device Guard on a Virtual Maschine in Hyper-V. After disabling Device Guard, using Step 1-7, include Set-VMSecurity .... DG is still active . RuleSet does still apply. 

/comment
Even after removing Hyper-V optionalfeature from the machine 
... just read: no longer needed since 1607 :-(  Please update all How Tos, like:
https://blogs.technet.microsoft.com/ash/2016/03/02/windows-10-device-guard-and-credential-guard-demystified/
./comment

Additionally changes 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\SystemGuard
Enabled and Managed to "0"

Update, functional way:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/identity-protection/credential-guard/credential-guard-manage.md
DG_Readiness_Tool_v3.6.ps1 -Disable -AutoReboot 

Conclusion, there is a difference in your step by step guide and the ps1 script ? Will take a look at it ...

**Comment by e0i** [comment]
Hello, @gruppenrichtlinien  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
