### ISSUE TITLE
DG_Readiness_Tool_v3.6.ps1 - Error in function PrintToolVersion

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MicrosoftDocs/windows-itpro-docs#4924]
Version mismatch in Text, non critical, but irritating.
-> Readiness Tool Version 3.4 Release.

**Comment by illfated** [comment]
@gruppenrichtlinien : Sorry for the delayed reply, but could you link the page you are talking about?

**Comment by gruppenrichtlinien** [comment]
See the Text inside the output of the DG_Readiness_Tool_v3.6.ps1, it is still reporting 3.4

**Comment by illfated** [comment]
Sure, but I would still like to know which page we are talking about, because https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/dg_readiness_tool shows version 3.7 .

I am pretty sure I am looking at the wrong page, but that is the first Windows related page (not Office) I found by searching for `DG_Readiness_Tool` from the search bar.

**Comment by gruppenrichtlinien** [comment]
Then, the page is updated, it was version 3.6

**Comment by illfated** [comment]
Fair enough, it was updated 2019-09-18 -- 6 days after you opened this ticket.
Do you consider your issue solved, or are there any other pages with the old error?

**Comment by e0i** [comment]
Closing as the Readiness Tool Version is 3.7 in the referenced article. Thank you for letting us know of the outdated content.
