### ISSUE TITLE
snapshot vs 'reset this pc'

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windows-itpro-docs#4927]
This article talks about using hyper-v so that we can use snapshots, and then we have instructions for taking a snapshot - but, then we're told to use the 'reset this pc' feature within windows 10, which is very slow. why wouldn't we just use the snapshot we were instructed to take? We should just revert to that snapshot instead, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc63299-cc1c-e031-deb7-915914b8f94e
* Version Independent ID: 356eaba5-16b0-952f-fc19-c8d5be5feb5f
* Content: [Demonstrate Autopilot deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm#capture-the-hardware-id)
* Content Source: [windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/demonstrate-deployment-on-vm.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
I'm not sure that restoring a snapshot would work. There is a cache on the client that needs to be cleared, which is created when the client first boots up and connects to the Internet. 

On first boot and connecting to the Internet the client basically asks the Autopilot service if this particular host is configured. If it isn't (which it won't be because we haven't added the hardware ID to Autopilot yet) then the client caches a "I have no Autopilot config" response.  From that point on, the client will not accept any Autopilot config because it believes it has none.

The only way to ensure it has the proper response is to connect to the Internet for the first time AFTER you have added the device's hardware ID. You could do this by disabling the Internet connection while getting the hardware ID, then re-enabling the Internet connection after you have added this ID in the cloud, but you can also just reset the device.  Anyway, this is my understanding. I could be wrong about some of this.

**Comment by Mike-Crowley** [comment]
@greg-lindsay that explains the behavior I've witnessed too; unfortunately. But if this is the case, the advice above to take a snapshot should probably be removed.

**Comment by greg-lindsay** [comment]
Well the snapshot is still useful if (for example) you want to change Autopilot/ESP settings then go back and restore the snapshot and reset the PC again to see your new settings take effect.

**Comment by e0i** [comment]
Hello @Mike-Crowley,

The issue is being closed since your question seems to be answered by the document author.

Thank you for taking the time to provide feedback.
