### ISSUE TITLE
Fix it?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windows-itpro-docs#4930]
"The steps in step 4 are also performed by the "Aggressive" mode of the Fix it Solution above."

There is no Fix it Solution above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@lizap 

The issue seems to have stemmed from the following commit,

[[183af3b ] Merged PR 11421: New Windows Update overview content from CSS ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/183af3b873be75f8f29f6e39c98c669ed5ee3c18#diff-e31aa55e77816943ac0f5a51e2eb78aaR52)

 Would you be able to shed light on the missing, "Fix it Solution"? Let us know whether we could aid with coming up with a PR if necessary. Thanks.

**Comment by illfated** [comment]
Unless there is any ongoing work on a content update to add the "Fix it" Solution to this page soon™, I volunteer to create a PR to modify the relevant text and remove the irrelevant parts of the text. I noticed that there are some minor grammar issues in the text too, so a general grammar/readability review of the page would be useful as well.

**Comment by illfated** [comment]
(ref. #9104, #9216, #9237, #9287, #9304, #9315)

**Comment by e0i** [comment]
Fixed via https://github.com/MicrosoftDocs/windows-itpro-docs/commit/15e9a411fce64546f8572b29691f782b3f4badb1#diff-fc5cd38a44f9cd55d877749fbddbe9dabdf373fbf2348b20aba9581b44062630

See: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9315#issuecomment-800640519
