### ISSUE TITLE
Doc bug in "Configure Windows diagnostic data in your organization" article

### ISSUE THREAD

**Issue by amirsc3** [MicrosoftDocs/windows-itpro-docs#4936]
The article may have the wrong URL listed in the "ENDPOINTS" section:
https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints

![image](https://user-images.githubusercontent.com/42802974/64885904-dda70280-d66d-11e9-9e2c-0023a8da97ab.png)

"Settings - win.data.microsoft.com" is mentioned 3 times in this section.
I believe it should be:
"Settings - settings-win.data.microsoft.com"

**Comment by jvsam** [comment]
Hi @DaniHalfin can you please confirm if the suggestion is correct? Is yes, do you want us to create a pull request to correct the *settings* details? Thank you.

**Comment by illfated** [comment]
The issue ticket author has got a valid point. `settings-win.data.microsoft.com` is a valid node, whereas `win.data.microsoft.com` is not:
```ini
Microsoft Windows [Version 10.0.18362.356]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>tracert win.data.microsoft.com
Unable to resolve target system name win.data.microsoft.com.

C:\WINDOWS\system32>tracert settings-win.data.microsoft.com

Tracing route to settingsfd-geo.trafficmanager.net [52.156.204.185]
over a maximum of 30 hops:

  1    19 ms     6 ms     2 ms  192.168.0.1
```
Looking closer at [the table referenced above](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization#endpoints), it appears to be a malformed formatting issue with the text. I am fairly certain it should have been formatted differently to keep the name intact. Example:

***
### Endpoints

The Microsoft Data Management Service routes data back to our secure cloud storage. Only Microsoft personnel with a valid business justification are permitted access.

The following table defines the endpoints for Connected User Experiences and Telemetry component:

Windows release | Endpoint
--- | ---
Windows 10, versions 1703 or later, with the 2018-09 cumulative update installed| **Diagnostics data** - v10c.vortex-win.data.microsoft.com</br></br>**Functional** - v20.vortex-win.data.microsoft.com</br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country, for example:</br>**de**.vortex-win.data.microsoft.com</br>settings-win.data.microsoft.com
Windows 10, versions 1803 or later, without the 2018-09 cumulative update installed | **Diagnostics data** - v10.events.data.microsoft.com</br></br>**Functional** - v20.vortex-win.data.microsoft.com</br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country, for example:</br>**de**.vortex-win.data.microsoft.com</br>settings-win.data.microsoft.com
Windows 10, version 1709 or earlier | **Diagnostics data** - v10.vortex-win.data.microsoft.com</br></br>**Functional** - v20.vortex-win.data.microsoft.com</br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country, for example:</br>**de**.vortex-win.data.microsoft.com</br>settings-win.data.microsoft.com
***
I must admit that I find it bothersome seeing a hyphen (instead of colon) used as a delimiter or pointer between some of the descriptions (Diagnostics data, Functional) and their following URLs which also contain a hyphen.

**Comment by illfated** [comment]
@jvsam : From your point of view, does it look like the **bold** text is supposed to be some form of heading or category before the descriptive information? If that is the case, I could suggest something like this:

Windows release | Endpoint
--- | ---
Windows 10, versions 1703 or later, with the 2018-09 cumulative update installed| **Diagnostics data** - v10c.vortex-win.data.microsoft.com</br></br>**Functional** - v20.vortex-win.data.microsoft.com</br></br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country, for example:</br>**de**.vortex-win.data.microsoft.com</br></br>**Settings:** settings-win.data.microsoft.com

**Comment by jvsam** [comment]
@illfated, I can't say I am very familiar with the topic, but I agree with you that may probably be a category (on one doc the heading is *area*), but @amirsc3 is right, if it is, then the endpoint is *settings-win.data.microsoft.com*, which also reflects on several [docs](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints). 

![image](https://user-images.githubusercontent.com/18371314/65383720-02753700-dd4c-11e9-9a58-2635fa803913.png)

From an external resource (I can't guarantee its accuracy!), it says 'The UTC client connects to settings-win.data.microsoft.com, provides its device ID (a randomly generated Globally Unique ID that is not associated with any personal information), and a few other configuration details, **and downloads a settings file**.'

See texts in **bold**. I checked my data stored in %ProgramData%\Microsoft\Diagnosis and I see downloaded setting files inside the **DownloadedSettings** folder. I would recommend that you go ahead and create a PR with the corrections. If there are issues, it will be declined or we will get feedback anyway. Better be proactive, no? :)

**Comment by illfated** [comment]
Very well, fair enough. :-) I will post a PR shortly, suggesting the aforementioned table changes.

**Comment by illfated** [comment]
I have proposed the following:

| Windows release                                                                     | Endpoint                                                                            |
| ----------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| Windows 10, versions 1703 or later, with the 2018-09 cumulative update installed    | **Diagnostics data:** v10c.vortex-win.data.microsoft.com</br></br>**Functional:** v20.vortex-win.data.microsoft.com</br></br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country,</br>for example: **de**.vortex-win.data.microsoft.com</br></br>**Settings:** settings-win.data.microsoft.com |
| Windows 10, versions 1803 or later, without the 2018-09 cumulative update installed | **Diagnostics data:** v10.events.data.microsoft.com</br></br>**Functional:** v20.vortex-win.data.microsoft.com</br></br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country,</br>for example: **de**.vortex-win.data.microsoft.com</br></br>**Settings:** settings-win.data.microsoft.com      |
| Windows 10, version 1709 or earlier                                                 | **Diagnostics data:** v10.vortex-win.data.microsoft.com</br></br>**Functional:** v20.vortex-win.data.microsoft.com</br></br>**Microsoft Defender Advanced Threat Protection** is country specific and the prefix changes by country,</br>for example: **de**.vortex-win.data.microsoft.com</br></br>**Settings:** settings-win.data.microsoft.com  |

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam
