### ISSUE TITLE
Please add May 2019 Servicing link

### ISSUE THREAD

**Issue by philschwan** [MicrosoftDocs/windows-itpro-docs#4944]
Please update the servicing links with the May 2019 release for Win10 1903 support :)

**Comment by mypil** [comment]
@philschwan - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by philschwan** [comment]
Sure. Here's the URL:
https://support.microsoft.com/en-us/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack

Thanks,
Phil

**Comment by illfated** [comment]
Well, that link points to https://support.microsoft.com/ (which we do not have access to editing from here). 
Do you mean that the page you linked contains information which should be available on one of the docs.microsoft.com pages, but currently is not present on that other page?

**Comment by philschwan** [comment]
Yes, the link I provided is information that should be available on the
docs.microsoft.com page that I submitted this feedback from. I assumed it
would actually include the original article in the submission.

To clarify, this is the page on the Docs site that needs modified:
https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations

The "Service releases" section near the end should include a link to the
May 2019 release at the following address:
https://support.microsoft.com/en-us/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack

Hope that clarifies. Thanks!

**Comment by illfated** [comment]
Yes, that helps a lot. The page and section https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations#service-releases is the relevant part in need of the update you requested.

After making a Pull Request and getting it merged, the section could look like this:

## Service releases 

- [April 2016 hotfix](https://support.microsoft.com/help/3144445/april-2016-hotfix-rollup-for-microsoft-desktop-optimization-pack)
- [September 2016](https://support.microsoft.com/ms-my/help/3168628/september-2016-servicing-release-for-microsoft-desktop-optimization-pa)
- [December 2016](https://support.microsoft.com/help/3198158/december-2016-servicing-release-for-microsoft-desktop-optimization-pac)
- [March 2017](https://support.microsoft.com/en-ie/help/4014009/march-2017-servicing-release-for-microsoft-desktop-optimization-pack) 
- [June 2017](https://support.microsoft.com/af-za/help/4018510/june-2017-servicing-release-for-microsoft-desktop-optimization-pack)
- [September 2017](https://support.microsoft.com/en-ie/help/4041137/september-2017-servicing-release-for-microsoft-desktop-optimization)
- [March 2018](https://support.microsoft.com/help/4074878/march-2018-servicing-release-for-microsoft-desktop-optimization-pack)
- [July 2018](https://support.microsoft.com/help/4340040/july-2018-servicing-release-for-microsoft-desktop-optimization-pack)
- [May 2019](https://support.microsoft.com/help/4505175/may-2019-servicing-release-for-microsoft-desktop-optimization-pack)

***
I can only presume you clicked through to Github instead of writing the issue text on the docs.microsoft.com page, hence missing the information which would have been provided with your post, if it had been posted on the docs.microsoft.com page.

**Comment by philschwan** [comment]
Correct. Thanks.

-Phil
