### ISSUE TITLE
Can't login to Remote Desktop and File Sharing fails when 2FA enabled

### ISSUE THREAD

**Issue by AmirHossein** [MicrosoftDocs/windows-itpro-docs#4958]
Authentication for Remote Desktop and File Sharing in Local Network always fails when 2FA enabled, Both devices are Windows 10 1903 and joined to Azure AD. I tried it with Surface Pro 4, Surface Book, PC and multiple Office365 accounts.
It will be solved as soon as 2FA disables.
https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc

**Comment by e0i** [comment]
Hello, @AmirHossein  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
