### ISSUE TITLE
WDAC Event Logs for blocked COM objects

### ISSUE THREAD

**Issue by HC-7** [MicrosoftDocs/windows-itpro-docs#4960]
Hi,

I have a question about the way to obtain the GUID of blocked COM objects:

In my Windows 10 LTSB 2016 and Windows Server 2016 systems, there are no block events under Application and Service Logs > Microsoft > Windows > AppLocker > MSI and Script. 
Even if certain elements are blocked by WDAC. 
The latest cumulative updates are installed, as described on this page.

Adding the GUID to the WDAC Policy and allowing the COM objects works fine on these systems.
Is there another way to obtain the GUID of COM objects that are blocked by WDAC?
Is there any configuration required to create the log entries?

On a comparable system with Windows 10 LTSC 2019, the GUID is logged in the event log as described.

Thank you.

**Comment by e0i** [comment]
@HC-7 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
