### ISSUE TITLE
"Windows Update for Business" の日本語訳 - japanese transration

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/windows-itpro-docs#5017]
"Windows Update for Business" が、場所によって「企業向け windows Update」、「ビジネス向けの Windows Update」、「一般法人向け Windows Update」の 3 種類の言葉に翻訳されてしまっているため、なんの話をしているのかわかりづらい。
-----------
企業向け windows Update では、IT 管理者は、これらのシステムを Windows Update service に直接接続することにより、組織内の Windows 10 デバイスを常に最新のセキュリティ防御と Windows 機能で最新の状態に保つことができます。 グループポリシーまたは Microsoft Intune などの MDM ソリューションを使用して、windows 10 デバイスの更新方法とタイミングを制御するビジネス設定の Windows Update を構成することができます。

特に、ビジネス向けの Windows Update によって、更新プログラムの提供とエクスペリエンスを制御できるようになり、組織全体で更新プログラムをロールアウトする前に、システムのサブセットの信頼性とパフォーマンスのテストを行うことができます。組織内のユーザー。

注意

一般法人向け Windows Update を使用するには、デバイスが Windows Update サービスにアクセスできるようにする必要があります。
---------

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2056993d-a700-fba6-8982-e645b182eeea
* Version Independent ID: fb38a86a-cdf6-6fc2-8eb6-fd54f1599f55
* Content: [Windows Update for Business を使った更新プログラムの展開 (Windows 10)](https://docs.microsoft.com/ja-jp/windows/deployment/update/waas-manage-updates-wufb#feedback)
* Content Source: [windows/deployment/update/waas-manage-updates-wufb.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-manage-updates-wufb.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
(online machine translation:) ["Windows Update for Business" translates into three different words, depending on the location: Windows Update for Business, Windows Update for Business, and Windows Update for Business It's hard to understand what you're talking about because you've been made.]

(I presume that the end of the sentence was poorly translated, but I had no other option than to use an online translator.)

@TinaMcN : I presume this document needs manual translation for consistent use of the correct translation of "Windows Update for Business" in Japanese.

**Comment by mypil** [comment]
@takeakitake - フィードバックを送信していただきありがとうございます。

この問題は、調査のためにWin10 ITPro執筆チームに伝えます。

ドキュメントを報告して改善していただきありがとうございます。

[Thank you for submitting your feedback.

This issue will be communicated to the Win10 ITPro writing team for investigation.

Thank you for reporting and improving the documentation.]

**Comment by mypil** [comment]
@TinaMcN - Can you please assist with this new translation/localization issue?

Thank you.

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 製品名の過剰ローカリゼーションは、機械翻訳ツールの既知の問題です。  この問題は調査中です。  その間、私はこのトピックを人間翻訳に切り替えました。 翻訳には約3週間かかります。
(Thank you for the feedback.  Over-localization of product names is an known issue with the machine translation tool.   The issue is being investigated.   In the meantime I have switched this topic to be human translated.  It will take approximately 3 weeks to be translated.)

**Comment by mypil** [comment]
@TinaMcN - We would like to follow up on the status. Do you an update whether this issue has been fixed?

Thank you.

**Comment by TinaMcN** [comment]
@takeakitake 記事は現在、人間が翻訳されています。 問題が解決したことを確認してください。 フィードバックをありがとう。
(The article is now human translated.  Please verify that the issue is fixed.  Thanks again for the feedback.)

**Comment by mypil** [comment]
@takeakitake - 私たちの理解から、問題は解決されました。 解決されていないと思われる場合は、この問題を再度開いてください。

ドキュメントの改善にご協力いただきありがとうございます！

(From our understanding, the problem was solved. If you think this has not been resolved, please reopen this issue.

Thank you for helping us improve the documentation!)
