### ISSUE TITLE
Link to Windows Analytics Upgrade Readiness broken

### ISSUE THREAD

**Issue by gcmlpfaltaher** [MicrosoftDocs/windows-itpro-docs#5039]
Link just takes users to the main Windows For Business page.  Did you mean to point users here: https://docs.microsoft.com/en-us/windows/deployment/upgrade/upgrade-readiness-get-started

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34937b5e-eda3-9c93-c31b-0701ea61198a
* Version Independent ID: 36f54d9f-503d-ea0a-bff2-3441571f8d44
* Content: [Quick guide to Windows as a service (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/update/waas-quick-start)
* Content Source: [windows/deployment/update/waas-quick-start.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/waas-quick-start.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
That's where the PM wanted it to go at one time. But it should be corrected. There some additional things to change on that topic as well, so I'll do that. Thanks.

**Comment by e0i** [comment]
@gcmlpfaltaher 

This issue has been addressed by the document author with the following commit and content has been updated according to your feedback.

[[6cd745c ] corrected link; fixed some language and terms ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/6cd745c49b5f6cd4d326887c0eccead4da07d043#diff-efc002e74ae4b7fbd5f284af4b615944)

We are thus closing this issue since it seems to be resolved. 

Thank you for taking the time to provide feedback.

**Comment by illfated** [comment]
For those of you who stumble upon this at a later time, see the simplified changes in the Rich Text Diff view:
https://github.com/MicrosoftDocs/windows-itpro-docs/commit/6cd745c49b5f6cd4d326887c0eccead4da07d043?short_path=efc002e#diff-efc002e74ae4b7fbd5f284af4b615944
