### ISSUE TITLE
Surface Hub 2S

### ISSUE THREAD

**Issue by Jonny2026** [MicrosoftDocs/windows-itpro-docs#5043]
Is this guide also working for Surface Hub 2S devices? I'm asking cazse I had a few articles that worked with surface hub (1. Gen) but not with 2. Gen devices.

Thanks for your answer

**Comment by Jonny2026** [comment]
I'm refering to this article:

https://docs.microsoft.com/de-de/surface-hub/hybrid-deployment-surface-hub-device-accounts#exchange-lokal

**Comment by e0i** [comment]
@Jonny2026 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
