### ISSUE TITLE
Set DisableLockdownOfStartPages to 0 (not configured) is most restrictive and not (not configured)

### ISSUE THREAD

**Issue by alokshan** [MicrosoftDocs/windows-itpro-docs#5050]
Tip: If you want to make changes to this policy:

Set DisableLockdownOfStartPages to 0 (not configured). 

Setting DisableLockdownOfStartPages  to 0 is most restrictive setting, its is not (not configured)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd200806-fa21-1384-e489-be8fe923c666
* Version Independent ID: 9b68cddb-aa39-5269-9a70-dfe6c2ce1ff7
* Content: [Policy CSP - Browser](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-browser#browser-configureopenmicrosoftedgewith)
* Content Source: [windows/client-management/mdm/policy-csp-browser.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/policy-csp-browser.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for the feedback @alokshan. Much appreciated. 

Hello @ManikaDhiman, under *Browser/DisableLockdownOfStartPages*, it indicates that the *Most restricted value is 0*. However, in the tip section, it says *Set DisableLockdownOfStartPages to 0 (not configured).* Should it just be 0 or not configured? Thanks for the clarification.

**Comment by ManikaDhiman** [comment]
Hi @jvsam, I've reached out to the product team to confirm this. I will update the content as soon as I hear from them. Thanks!

**Comment by ManikaDhiman** [comment]
Hi @alokshan, @jvsam, 
Here's the response from the product team:
If DisableLockdownOfStartPages is set to 1 (enabled) then changing ConfigureOpenEdgeWith will not take effect. They will need to first set DisableLockdownOfStartPages to 0 (disabled) or ‘Not configured’ it before modifying ConfigureOpenEdgeWith. The reason 0 is indicated as the most restricted value is because when set to 0, the end user cannot override the IT admins configuration. Also the value 0 (disabled) has the same behavior as when the setting is not configured.

There was a typo in the default value of DisableLockdownOfStartPages. I updated the default value to 0 instead of 1. The changes will be merged with live docs soon.

Hope this helps. Thanks!

**Comment by jvsam** [comment]
> Hope this helps. Thanks!

Absolutely, thank you so much @ManikaDhiman. Also, I can see that the update on the DisableLockdownOfStartPages's default value is now reflecting on live.

@alokshan, we hope the information provided clarified this issue for you. Thank you again for your feedback. We always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date.

**Comment by jvsam** [comment]
Hi again @alokshan, we will now close this issue, but feel free to re-open or create another issue via the *feedback feature* if you have other suggestions or ideas to improve the quality of this documentation.

Thank you for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
