### ISSUE TITLE
why aren't all error codes listed? why are these log files so useless when troubleshooting update errors? why are update quality so horrible?

### ISSUE THREAD

**Issue by seamonkey420** [MicrosoftDocs/windows-itpro-docs#5083]
why is it that none of the error codes we get in the real world ever are trackable on this site?  what is error code 0x800f0986 mean? no one knows, not even microsoft it appears. how does htis error in my log help me resolve this update error? it doesn't, just lead me down a loop of 'mvp' microsoft posers telling us to run sfcscan or dism check health that has may fixed 1 of 1million problems.  better error code documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47692487-0a0b-3b1b-6d34-790046c7cbc3
* Version Independent ID: 0f66cafe-2bff-4323-b3fc-01014b904b3a
* Content: [Windows Update log files](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-logs#feedback)
* Content Source: [windows/deployment/update/windows-update-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-logs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by mypil** [comment]
@seamonkey420  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@greg-lindsay - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by greg-lindsay** [comment]
I understand the frustration with error codes. We've attempted to provide as many codes here as possible and to provide solutions. If you are having trouble with Windows upgrade, we are focusing most of our efforts on developing the Setupdiag tool, which can parse through long and complex log files and summarize what went wrong. This tool has undergone several updates and supports a wide variety of possible errors. See https://docs.microsoft.com/en-us/windows/deployment/upgrade/setupdiag

That said, an error code of 0x800f0986 is often reported to be a problem caused by file access. For example, you are trying to update a file that is currently open or in use by another app. Be sure to try the quick fixes listed on this site before anything else. See https://docs.microsoft.com/en-us/windows/deployment/upgrade/quick-fixes - in particular use the Windows Update troubleshooter.

**Comment by piotr-cz** [comment]
@seamonkey420 
I feel with you. There are no resources out there for **0x800f0986** error.

I've tried everything described in Windows support > [Fix Windows Update errors](https://support.microsoft.com/en-us/help/10164/fix-windows-update-errors) and only the _In-place Upgrade_ helped.
