### ISSUE TITLE
Features supported by Windows Defender and SCEP

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#5091]
Can you please confirm it will support all features that is provided by Windows Defender on old version of Windows running SCEP clients like smart screening, controlled folder access etc? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
@mzafzal1 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
