### ISSUE TITLE
Do we need to assign licenses individually?

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#5092]
What is the procedure for assigning the ATP license on machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2748359b-273d-7faa-6a63-7a6ebea450d2
* Version Independent ID: f4885da5-9a83-13aa-789e-1751db586404
* Content: [Validate licensing provisioning and complete Microsoft Defender ATP set up](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/licensing)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/licensing.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/licensing.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Hello, @mzafzal1  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
