### ISSUE TITLE
Detailed graph

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#5099]
Our core purpose for purchasing the Defender ATP is to have the complete information in graphical view from where the virus is generated and prevail into our systems like if the virus received through Email the graph will show us the detail that the virus received through email and then moved to other systems. Similarly, if it received through IE the graph will provide the details that the virus was received through browsing. I couldn't find anything like that in the documents. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81afe8a2-3504-d628-4228-28118c2416d4
* Version Independent ID: 8d0bedb0-3142-941f-8067-77d499c90d41
* Content: [Microsoft Defender Advanced Threat Protection portal overview](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/portal-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/portal-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/portal-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Hello, @mzafzal1  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
