### ISSUE TITLE
Can I manage Windows 7 ESU using VMAT?

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/windows-itpro-docs#5103]
Can I manage Windows 7 ESU using VMAT?
and support proxy scenarios?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: db3d4459-a57d-a227-a9ee-47a9d25fd8e1
* Version Independent ID: 43374c7a-f5d7-8168-6a0d-285f8fb29693
* Content: [ボリュームライセンス認証管理ツール (VAMT) テクニカルリファレンス (Windows 10)](https://docs.microsoft.com/ja-jp/windows/deployment/volume-activation/volume-activation-management-tool)
* Content Source: [windows/deployment/volume-activation/volume-activation-management-tool.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/volume-activation/volume-activation-management-tool.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
@TomoharuMisawa 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
