### ISSUE TITLE
Adding exclusions Link

### ISSUE THREAD

**Issue by redog** [MicrosoftDocs/windows-itpro-docs#5105]
404 Link on Adding Exclusions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6fd4c46-8ba2-4a67-47bb-8fe1b9064b11
* Version Independent ID: ca04d6c8-6943-4b7f-dd59-521b4511d3d5
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
Thank you for pointing out the broken link. I am looking into that issue now, trying to find out what can be done to fix the link.

Non-working section ([adding exclusions](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/enable-attack-surface-reduction#exclude-files-and-folders-from-asr-rules) is the broken link):

> You can use [audit mode](audit-windows-defender.md) to evaluate how attack surface reduction rules would impact your organization if they were enabled. It's best to run all rules in audit mode first so you can understand their impact on your line-of-business applications. Many line-of-business applications are written with limited security concerns, and they may perform tasks similar to malware. By monitoring audit data and [adding exclusions](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/enable-attack-surface-reduction#exclude-files-and-folders-from-asr-rules) for necessary applications, you can deploy attack surface reduction rules without impacting productivity.

Bad link:
https://docs.microsoft.com/windows/security/threat-protection/windows-defender-exploit-guard/enable-attack-surface-reduction#exclude-files-and-folders-from-asr-rules
Working link:
https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction#exclude-files-and-folders-from-asr-rules
Corresponding Github page:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction.md#exclude-files-and-folders-from-asr-rules

Please notice the change from `windows-defender-exploit-guard` to `microsoft-defender-atp` as the directory where it can be found now.

The change causing this broken link is sort of documented on the Github page https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md :
**martyav** moved attack surface topics to mdatp dir  ae43d72 on Aug 21

I am a bit miffed by the use of docs.microsoft.com links on the Github source page, because the ideal solution would be to point the Github page links to other Github source pages, and the migration process should convert the Github links to docs.microsoft.com links (given that the linked pages exist on Github).
