### ISSUE TITLE
TVM update cycle

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/windows-itpro-docs#5107]
It would be great if the documentation could include some information about the update cycle , i.e. how often does TVM assess the information on the local system and process it in the MDATP backend. 

Example: When a machine has an older version of Software XYZ that has vulnerabilities, the software is then patched, how long does it take to see this change in the TVM console?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e827de-5cf9-4506-880f-908d454f5807
* Version Independent ID: a9da7cb9-222f-084a-7a1a-36730cf0e669
* Content: [Weaknesses](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-weaknesses)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-weaknesses.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-weaknesses.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @alexverboon, thank you for your feedback. As you know, we always strive to give users the best Windows 10 experience by ensuring that contents of the Microsoft Docs are useful, accurate and up-to-date.  

> ...how often does TVM assess the information on the local system and process it in the MDATP backend.

As per the available information, Threat & Vulnerability Management (TVM) "*uses the same agentless built-in Microsoft Defender ATP sensors..*", hence, devices onboarded to Microsoft Defender ATP automatically report and push vulnerability and security configuration data to the Threat & Vulnerability Management dashboard.

Furthermore, it's emphasized [here](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory#how-it-works)—and in the *Weaknesses* doc—that "*In the field of discovery, we are leveraging the same set of signals in Microsoft Defender ATP's endpoint detection and response that's responsible for detection, for vulnerability assessment. Since it is real-time, in a matter of minutes, you will see vulnerability information as they get discovered. The engine automatically grabs information from multiple security feeds. In fact, you'll will see if a particular application is connected to a live campaign. It also provides a link to a Threat Analytics report soon as it's available.*"

> When a machine has an older version of Software XYZ that has vulnerabilities, the software is then patched, how long does it take to see this change in the TVM console?

Actually, the [Scenarios](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/threat-and-vuln-mgt-scenarios) doc explains it well. It depends on your IT Administrator. When the remediation task is submitted and then accepted, you can view the status of the remediation request on the *Remediation* tab. Once completed (in your example, a patch has been deployed), the IT Administrator will select Complete Task and this action updates the security task status in both Intune and ATP. Here's a [workflow](https://docs.microsoft.com/intune/protect/atp-manage-vulnerabilities) for more information.

Basically, the information is already on this doc set. Is there a specific messaging that you would like to add, Alex?

**Comment by jvsam** [comment]
Hello again @alexverboon, just following up if you have other suggestions related to this doc? So far, the information you seek is already available and if you're okay with the content, we can consider this issue resolved. Thanks.

**Comment by jvsam** [comment]
Hello again @alexverboon, we haven't heard from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have suggestions related to this documentation or ideas to make it better for users. Thank you.

**Comment by jvsam** [comment]
@officedocsbot close

**Comment by alexverboon** [comment]
> Hello again @alexverboon, we haven't heard from you but we hope the information we've provided helped. We will now close this issue, however, feel free to re-open if you have suggestions related to this documentation or ideas to make it better for users. Thank you.

Hello sorry I forgot to follow up on this; my question isn’t really answered; let me rephrase. 

I have software ABC version 1.0 installed
TVM finds a vulnerability 
I update the software
When will I see the updated status in TVM? That I have now version 1.1 installed as it does seem to take awhile.
