### ISSUE TITLE
Values for Server 2019

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windows-itpro-docs#5115]
Please update for filter values for Server 2019 family

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7937ded2-6bd7-e34e-08a8-5e7f6e9ffe4c
* Version Independent ID: b4313161-be46-059c-6a6c-1af2a90252f6
* Content: [Create WMI Filters for the GPO (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo)
* Content Source: [windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/create-wmi-filters-for-the-gpo.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Good point. I can only offer to create a PR to add the information, but I am not familiar or experienced with this topic, so I would need to have the information pointed out to me. (Looking forward to any follow-up from the Microsoft Docs team members.)

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you for your feedback @pyoungberg. Although, looking at the theme, the deployment guide, including all the [procedures](https://docs.microsoft.com/windows/security/threat-protection/windows-firewall/procedures-used-in-this-guide) used in it are intended for Windows 10 & Windows Server 2016 OS. 

What do you think @illfated? Will adding 2019 information—if we have the information—fit since the content will deviate from the applicable OS?

Anyway, there's an interesting discussion in the Tech Community regarding Windows Server 2019 [WMI Filters or Security Group Filtering](https://techcommunity.microsoft.com/t5/Windows-Server-for-IT-Pro/Server-2019-WMI-Filters-or-Security-Group-Filtering/m-p/773601), with sample filter but for Windows Server 2019 Domain Controllers only. Found a lot of external resources like [this](https://teamengr.com/2019/08/28/windows-server-2016-versus-2019-wmi-filtering/), though we cannot guarantee the accuracy. There is a [TechNet article](https://social.technet.microsoft.com/wiki/contents/articles/31701.windows-sample-wmi-filter-strings.aspx) but it does not have 2019 specifically, but have sample strings that target Desktop OS and 64 Bit. Have you tested WMI filter for server 2019 @pyoungberg? It helps to confirm.

**Comment by illfated** [comment]
Given that the Windows Server 2019 WMI Filters content is very different (or quite different) from the Windows Server 2016 WMI Filters content, I prefer to see what the document author would say about this. I do not know enough about this content to tell if this page is the right place to add Windows Server 2019 WMI Filters content or if it belongs on a separate page for Windows Server 2019.

**Comment by pyoungberg** [comment]
Haven't tested as the documentation out there was spotty. Was hoping for an authoritative answer. I'd assume you could just post or link to a list of Windows 10 releases w/ version numbers we the users could sort out the rest.

**Comment by illfated** [comment]
Thank you for your feedback, I hope it will be useful enough for the maintainers of this page & topic.

@Dansimp : Could we have a comment from you regarding future plans or actions regarding documentation of Windows Server 2019 WMI Filters for GPO?

**Comment by jvsam** [comment]
Thanks @pyoungberg [is this](https://docs.microsoft.com/windows-server/get-started/windows-server-release-info) what you are looking for?

Thanks @illfated. @Dansimp can you provide some insights on this one please?

**Comment by pyoungberg** [comment]
> Thanks @pyoungberg is this what you are looking for?
> Thanks @illfated. @Dansimp can you provide some insights on this one please?

Yup thanks I can make a filter with that!

**Comment by jvsam** [comment]
That's great @pyoungberg, any update? If you can share your filters here, it would help other users who are also looking for the same information. Looking forward to hearing from you.

**Comment by pyoungberg** [comment]
I don't have a need for this anymore in my env so I wasn't able to test, but if I did write one it'd probably be like this:
`#Windows 2016 LTSB
SELECT * from Win32_OperatingSystem WHERE Version > "10.0.00000" AND Version < "10.0.17763" AND ProductType="1"

#Windows 2019 LTSB
SELECT * from Win32_OperatingSystem WHERE Version > "10.0.17762" AND ProductType="1"`

**Comment by jvsam** [comment]
Thank you @pyoungberg for sharing that information. I am sure other users who'll stumble upon this thread—which is available on the feedback section of the doc content page—will find it useful. 

We will now close this issue and thank you again for your feedback and for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
