### ISSUE TITLE
Time.windows.com

### ISSUE THREAD

**Issue by Rkendall75** [MicrosoftDocs/windows-itpro-docs#5143]
The article states Allow access to all hosts via port 80 (HTTP), 443 (HTTPS), and 123 (UDP/NTP) I believe the only one that requires 123 is time.windows.com not all hosts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The http ports are used to determine if the client is online and able to access the Internet.  It does a test to verify that it can access www.msftconnecttest.com. See https://docs.microsoft.com/windows/privacy/manage-windows-1809-endpoints

**Comment by Rkendall75** [comment]
I don’t disagree, but its not true that we need port 123 open for all the listed ports as the article says. We need 443/80 for everything and port 123 for a single URL.

Thanks
Robert

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by e0i** [comment]
@greg-lindsay Would it be feasible to state in the document to limit allow access to 123 (UDP/NTP) only for a single domain (_time.windows.com_) as suggested? We would like to aid with relevant content updates if necessary. Thanks.

**Comment by illfated** [comment]
Maybe the proposed change is appropriate for Windows Autopilot and American or western countries with large enterprise deployments. To me, it looks slightly different, because I don't use Windows Autopilot and I also only manage a small business amount of computers. My specific case is for all the computers I manage, I quickly change time.windows.com to my local national (and trustworthy) NTP servers, like ntp.online.no in Oslo, Norway (and maybe no.pool.ntp.org). That makes it practical for me to allow more than 1 NTP server to pass the firewall (likely something like 5). In my own network, the NTP and SNTP ports are open for traffic in general, so any NTP server will work. On the other hand, allowing all addresses has caused some minor attack attempts to be reported in the firewall, from Chinese or Russian NTP servers.

**Comment by illfated** [comment]
> The article states Allow access to all hosts via port 80 (HTTP), 443 (HTTPS), and 123 (UDP/NTP) I believe the only one that requires 123 is time.windows.com not all hosts.
> 

I wonder if this is an indirect suggestion that the document phrasing seems to be too liberal. What @Rkendall75 also said, is that in his opinion, only one address is needed for the NTP port (UDP/NTP 123), but that seems to be too strict in my opinion. Since I don't have personal experience with Filtering or Firewall rules to allow only a small number of addresses, I don't have a useful suggestion for what would be a middle ground between those two opposite points. I also presume it is quite difficult to predict a reduced number of addresses to allow through the Firewall, even more so when it comes to determining what is a good solution for Windows Autopilot. Knowing that it is close to unpredictable which addresses (IP or DNS) will be preferred in environments beyond the United States, also taking into account that NTP server names might change over time, I don't know what could be a practical solution to implement for a change in the current document ("Your Mileage May Vary").

**Comment by Rkendall75** [comment]
Exactly my comment was that the only host that needs 123 is whatever your time server is none of the other endpoints need that port opened.

Thanks
Robert

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by illfated** [comment]
@e0i : Should we ask the document author for a final comment on this, whether it should be updated or not?

**Comment by e0i** [comment]
We haven't got feedback from Greg as commented above. The best way to get relevant feedback, in this case, is to come up with a PR with mentioned suggestions so I'm passing this to a contributor for that. Thank you for the discussion.

**Comment by VLG17** [comment]
@Rkendall75 @illfated In my opinion this is addressed a bit further in the article:

> **In environments that have more restrictive Internet access**, or for those that require authentication before internet access can be obtained, additional configuration may be required to allow access to the required services

![image](https://user-images.githubusercontent.com/41186174/86243007-44ba8700-bbae-11ea-8d24-124f7f4d755e.png)

The sentence you are referring to in the beginning of the article refers to a less restrictive environment (which also exists), and then it goes further to talk about what you need to do for more restrictive environments. If you find that this is not explicit enough, what wording would you see appropriate for the first sentence?

> Allow access to all hosts via port 80 (HTTP), 443 (HTTPS), and 123 (UDP/NTP).

**Comment by illfated** [comment]
@VLG17 : Thank you for the practical feedback. Good & fair point.

I think the current phrasing/wording is OK as it is, based on your summary of what is actually already present in the document page. Giving access to only 1 NTP host (time.windows.com) on restricted networks, or access to all NTP hosts (UDP/123 completely open) on non-restricted networks. In my opinion, it is very difficult to find a middle ground between those two, because everyone and their mother has an opinion on how many and which NTP servers to allow.

**Comment by e0i** [comment]
@VLG17 Right to the point!. Thank you for providing this detail that is too easy to look over.
