### ISSUE TITLE
Resetting bitlocker passwords after use

### ISSUE THREAD

**Issue by Oldfield007** [MicrosoftDocs/windows-itpro-docs#5145]
Am I reading this correctly - if you use your recovery key MS recommends that you should reset it? https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-recovery-guide-plan#resetting-recovery-passwords  If this is correct why?

**Comment by e0i** [comment]
@Oldfield007 

The issues section of this repository is intended for problems relating to documentation content only.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by Oldfield007** [comment]
Thank you and noted. I will follow up with the other link.  The only reason I choose the doc section was because there was no reasin given to why you need to re-do a password after using the number sequence.

Thank you

Regards
Greg
0421057542 

    On Tuesday, 15 October 2019, 08:31:04 am AEDT, Onur <notifications@github.com> wrote:  
 
 
@Oldfield007

The issues section of this repository is intended for problems relating to documentation content only.

Please open a support ticket via the link below so that that your question gets answered quickly.

Windows 10 Support

Thank you.
