### ISSUE TITLE
How to Set up UWP Application of Win32 Conversion in Kiosk Mode

### ISSUE THREAD

**Issue by yowang** [MicrosoftDocs/windows-itpro-docs#5146]
We can use Windows settings to set a UWP application to run in a Kiosk mode. We find that UWP applications converted by DesktopAppConverter from Win32 application cannot be set as a Kiosk mode in the Windows settings.
We don't want to use MDM or any other way to set up a Kiosk mode. Does Microsoft plan to fix this problem? When can you solve this problem?

**Comment by yowang** [comment]
@e0i  Any update for this issue?

**Comment by e0i** [comment]
@yowang 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
