### ISSUE TITLE
Specifying the parameter '-ID' is required to back up recovery information

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/windows-itpro-docs#5159]
"For example, to back up all of the recovery information for the C: drive to AD DS, you would use the following command from an elevated command prompt: manage-bde -protectors -adbackup C:"

nope:
"ERROR: Specifying the parameter '-ID' is required to back up recovery information."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c1a2e9d-0121-2b6d-3c0d-7548286c2c72
* Version Independent ID: 9d520385-fe81-b512-8bd4-e77ad6ef4cc4
* Content: [BitLocker and Active Directory Domain Services (AD DS) FAQ (Windows 10)](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-and-adds-faq#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-and-adds-faq.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/bitlocker-and-adds-faq.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @rafalfitt, thank you for bringing this to our attention. We would love to help you with your concern, however, this Github site is intended to help improve the quality of the technical documentation through user contributions and feedback. We recommend that you open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. 

Other support resources include the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. You may want to check the following posts as well:

- [Unable to Force BitLocker\TPM info to AD using Manage-BDE](https://social.technet.microsoft.com/Forums/office/en-US/71f8180b-36e5-4b1a-a7b8-2d39a2c1ef8a/unable-to-force-bitlockertpm-info-to-ad-using-managebde?forum=w7itprosecurity) (*This is an old post and for Win 7, but please check the latest comment*)
- [Saving BitLocker to AD on Windows 10](https://social.technet.microsoft.com/Forums/en-US/5f847f61-8772-4054-9ea3-76fb8e8b8720/saving-bitlocker-to-ad-on-windows-10?forum=win10itprosecurity)

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by rafalfitt** [comment]
@jvsam, ??

"this Github site is intended to help improve the quality of the technical documentation through user contributions and feedback."

So I am reporting that the syntax is different from your doc sample and  you reply with some autoreply crap answer without even reading my issue?? How is it useful?

Once more:
the documentation suggests that using "manage-bde -protectors -adbackup C:" you can back up all of the recovery information for the C: drive to AD DS.
But when I tried to use this exact command, I got error "ERROR: Specifying the parameter '-ID' is required to back up recovery information."
![2019-10-20 190016](https://user-images.githubusercontent.com/36852431/67163150-ecb75980-f36b-11e9-8a19-d6e3187c77e4.png)

**Comment by illfated** [comment]
This looks very much like a document improvement suggestion to me. I presume this is about the command in the section 
https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-and-adds-faq#what-if-bitlocker-is-enabled-on-a-computer-before-the-computer-has-joined-the-domain
, but I also looked at the scenario described in https://social.technet.microsoft.com/Forums/en-US/5f847f61-8772-4054-9ea3-76fb8e8b8720/saving-bitlocker-to-ad-on-windows-10?forum=win10itprosecurity and I am curious about whether it should also be noted that for the original encryption command needs to include the switch `-RecoveryPassword` in order to create the required "Numerical Password:" ID.

@rafalfitt : Any suggestions for exactly what we need to add, and where, on the related document page?

**Comment by rafalfitt** [comment]
@illfated
Yes, you are right.
A Powershell script sample would be nice to have, for example:
$BitLocker = Get-BitLockerVolume -MountPoint c: ; $RecoveryID = $BitLocker.KeyProtector | Where-Object { $_.KeyProtectorType -match 'RecoveryPassword' }; Backup-BitLockerKeyProtector -MountPoint c: -KeyProtectorID $RecoveryID.KeyProtectorID

**Comment by illfated** [comment]
Very well, I presume it needs some MarkDown code formatting to be able to show up as code on its individual lines, like this:
```PowerShell
$BitLocker = Get-BitLockerVolume -MountPoint c: ;
$RecoveryID = $BitLocker.KeyProtector | Where-Object { $_.KeyProtectorType -match 'RecoveryPassword' };

Backup-BitLockerKeyProtector -MountPoint c: -KeyProtectorID $RecoveryID.KeyProtectorID
```

**Comment by rafalfitt** [comment]
yes, sure, it was my Powershell on-liner ;-)

even better: hard-coded c: should be replaced by $env:SystemDrive

**Comment by illfated** [comment]
Fair enough. Also please keep in mind that we will need to place the extra information so it does not get cluttered or confusing to the readers.

**Comment by jvsam** [comment]
> So I am reporting that the syntax is different from your doc sample and you reply with some autoreply crap answer without even reading my issue?? How is it useful?

Hello again @rafalfitt, thank you so much for the clarification. For us to better understand your issue,  it is recommended that you provide as much information as you can. You've provided an error without enough context, hence I've provided support resources. I understand that you must have been frustrated, but kindly refrain from using inappropriate words. 

> the documentation suggests that using "manage-bde -protectors -adbackup C:" you can back up all of the recovery information for the C: drive to AD DS. But when I tried to use this exact command, I got error "ERROR: Specifying the parameter '-ID' is required to back up recovery information."

Your follow-up message is better. But again, it is a matter of identifying if this is an issue with a Microsoft feature or product, or an issue with the accuracy of the documentation. Which what you have clarified.

> A Powershell script sample would be nice to have, for example:
$BitLocker = Get-BitLockerVolume -MountPoint c: ; $RecoveryID = $BitLocker.KeyProtector | Where-Object { $_.KeyProtectorType -match 'RecoveryPassword' }; Backup-BitLockerKeyProtector -MountPoint c: -KeyProtectorID $RecoveryID.KeyProtectorID

@illfated thank you for your assistance and in helping clarify this matter. Since you understand the request better now, do you want to create a PR so it can be reviewed? Otherwise, I can forward it to the content writing team.

**Comment by illfated** [comment]
Sure, I think I should be able to write a PR to suggest an improved paragraph with a full code sample, to back up all of the recovery information for the SystemDrive drive to AD DS. I will have a PR available for review shortly.
