### ISSUE TITLE
Incorrect content image

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/windows-itpro-docs#5163]
The https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app#set-up-a-kiosk-in-local-settings section where the content image specifies privacy with a yellow box around the item is not an option in my build 1909 / 18363.418.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f49c3f-ba5c-49e9-fad2-88cac155920a
* Version Independent ID: dc5e1f7e-61a8-bf2c-34b8-4046d024f4c2
* Content: [Set up a single-app kiosk (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app#set-up-a-kiosk-in-local-settings)
* Content Source: [windows/configuration/kiosk-single-app.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/configuration/kiosk-single-app.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
> ...option in my build 1909 / 18363.418.

Hi @awentzel, thanks for bringing this to our attention. We would love to help you with your concern, however, this Github site is intended to help improve the quality of the technical documentation through user contributions and feedback. Since 18363.418 is a Windows 10 Insider Preview build, we recommend that you post your question through the [Windows Insider Forum](https://answers.microsoft.com/en-us/insider?OCID=WIP_r_Welcome3_Body_InsidersForum) and get help from the community. More support options available [here](https://insider.windows.com/en-us/how-to-overview/#how-to-get-support).

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by illfated** [comment]
@awentzel : Please notify us again when Windows 10 version 1909 goes live and replaces 1903 as the current supported version.

**Comment by jvsam** [comment]
Hello again @awentzel, we hope that the information we've provided helped. We will now close this issue, thank you for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
