### ISSUE TITLE
Not returning values

### ISSUE THREAD

**Issue by redforce123** [MicrosoftDocs/windows-itpro-docs#5173]
Some of the Ips that I send to api.securitycenter  is not returning any values nor it gives any error,What could be the reason behind it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e975e6-ad08-1f45-7503-d63b8949bb0a
* Version Independent ID: 0306852c-5c3a-183b-e4af-cbde734114ec
* Content: [Find machines by internal IP API](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/find-machines-by-ip#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/find-machines-by-ip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/find-machines-by-ip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @redforce123, apologies for the inconvenience. We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. If you have feedback, suggestions related to this documentation, or ideas to make it better for users, please let us know and we will submit it for review.

What we recommend regarding your issue is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community.

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi @redforce123, we hope you were able to contact support to resolve your concern. We will now close this issue, and again, if you have feedback or suggestions to help improve the quality of the technical documentation of the Microsoft Docs, please use the doc's feedback feature to easily track content improvement requests. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
