### ISSUE TITLE
Can we audit one specific security group?

### ISSUE THREAD

**Issue by rbassilian** [MicrosoftDocs/windows-itpro-docs#5196]
How can we further lock this down so we can trigger when a specific security group gets a membership change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223d88e1-3d6f-aede-77bb-b4299ba5157e
* Version Independent ID: 9ab2553f-02ba-fa30-4d24-0a6ab4c292ee
* Content: [Audit Security Group Management (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-security-group-management#feedback)
* Content Source: [windows/security/threat-protection/auditing/audit-security-group-management.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/audit-security-group-management.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by rbassilian** [comment]
Figured it out.  At least on a basic level, this triggers any event that affects the specific group.  Still not sure how to do multiple conditions, but this is good enough for now.
<QueryList>
  <Query Id="0" Path="Security">
    <Select Path="Security">*[EventData[Data[@Name='TargetUserName'] and (Data='<_groupname_>')]]</Select>
  </Query>
</QueryList>

**Comment by RAJU2529** [comment]
@rbassilian. Your question is complecated. Only experienced users can give exact solution. Keep waiting for correct answer

**Comment by e0i** [comment]
Hello, @rbassilian

The issue is being closed as it seems that you have found the answer that you are looking for.

However, Please note that the issues section of this repository is intended for documentation problems only.

Should you have any similar questions in the future, please consider opening a product support ticket here: [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thank you.
