### ISSUE TITLE
Where are the Autopilot profiles located?

### ISSUE THREAD

**Issue by ivanko021** [MicrosoftDocs/windows-itpro-docs#5198]
This page has a link that has another link to the following page - https://docs.microsoft.com/en-us/intune/enrollment/enrollment-autopilot Here you can find information about "Creating an Autopilot deployment profile". However none of the fields in this profile correspond to the Autopilot Profiles referred to in this page. Where can I find the Autopilot profiles from this page?

**Comment by RAJU2529** [comment]
@ivanko021. I don't know whether is correct or not.i think 
each auto pilot profiles have formats. So search that particular formats through out the C drives

**Comment by ivanko021** [comment]
@RAJU2529 I would like to clarify my question. I want to know where in the Azure/Intune interface I can find the Autopilot profile settings outlined in this doc:
https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/profiles

**Comment by e0i** [comment]
@ivanko021 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
