### ISSUE TITLE
Saving Firewall Log to a different location

### ISSUE THREAD

**Issue by samsig01** [MicrosoftDocs/windows-itpro-docs#5255]
How would I specify changing the location of the firewall log file to point to a central logging server instead of the default path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3621dedd-460e-2afd-e6d6-ac7a5d0d6911
* Version Independent ID: 298b96a7-17d2-6c1f-a2d1-81c24ad80e81
* Content: [Configure the Windows Defender Firewall Log (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log#feedback)
* Content Source: [windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-firewall/configure-the-windows-firewall-log.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@samsig01 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
