### ISSUE TITLE
Additional info on 0xC1900101 - 0x4000D

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-itpro-docs#5317]
If the machine bugchecked (BSOD) with error 0xEF (CRITICAL_PROCESS_DIED) and rolled back, returning setup exit code 0xC1900101 - 0x4000D, it may be because of a malformed registry value in the "HKLM:\SOFTWARE\Microsoft\Ole" key.
If the data of value MachineLaunchRestriction is abnormally large (in my observed cases, larger than 65535/FFFF), a critical service will crash in the SECOND_BOOT phase (around 80-90% of total progress), resulting in bugcheck 0xEF.

Resolution procedure as instructed by Microsoft support is to delete the MachineLaunchRestriction registry value and attempt the upgrade again. In my case, this gives successful upgrades.
This value does not seem to regenerate on reboot, but it does regenerate (with normal data) on successful upgrades.

Please include this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 528014e0-02e5-2d77-a229-4895731bb872
* Version Independent ID: 4f46b620-e345-c9e4-70fa-ae4f5a8e48b9
* Content: [Resolution procedures - Windows IT Pro](https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolution-procedures)
* Content Source: [windows/deployment/upgrade/resolution-procedures.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/resolution-procedures.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@KasJensen. In my windows 10 insider enterprise preview, i observed the following registry values

![upload](https://user-images.githubusercontent.com/3296790/67961779-2c125f80-fc22-11e9-92ce-1bbe80629d6f.JPG)

**Comment by KasJensen** [comment]
Hi @RAJU2529. This is primarily an issue on Windows 7 machines. On searching for "MachineLaunchRestriction", you get a variety of forums point to various DCOM errors, and some claim the malformed value was caused by an old Windows 7 bug. As it's regenerated upon upgrade to Windows 10, it makes sense that yours looks just fine. I have no sources to verify that claim.

I ran a CMScript on my machines to get the size of this value. Results: https://i.imgur.com/MpG6hGD.png. As you can see, this only affects Windows 7 machines. Here is what the 65564b large value looks like on a Windows 7 machine: https://i.imgur.com/wJkdMku.mp4.

It was a community member who contacted Microsoft support with a crash dump, the engineer instructed him to delete that value to get a successful upgrade. He tested it, it worked. He then told others in the community on reddit. I think it's only fair to include it in the documentation.
