### ISSUE TITLE
Delete Profile Not Working for Onedrive Synced Profiles

### ISSUE THREAD

**Issue by brockettc** [MicrosoftDocs/windows-itpro-docs#5324]
When a profile has it's onedrive synced to the machine the user profile folder and all of their onedrive contents remain after the autodeletion/maintenance occurs. 

Everything else gets deleted, but the onedrive folder remains inside the user folder. So the user folder remains as well.

**Comment by RAJU2529** [comment]
@brockettc. Sir will you mention the content source , from where you read

**Comment by brockettc** [comment]
@RAJU2529 https://docs.microsoft.com/en-us/windows/configuration/set-up-shared-or-guest-pc

AccountManagement:DeletionPolicy

**Comment by e0i** [comment]
Hello, @brockettc thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
