### ISSUE TITLE
adfssvc - what is it?

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/windows-itpro-docs#5352]
Regarding this step - "In the Enter the object names to select text box, type adfssvc. Click OK." Some readers may have skipped over the device registration configuration page because it was already configured before they started with WHFB. In that case, the adfssvc account is introduced here for the first time. It's somewhat obvious that this is the ADFS service account, but it may be worth adding a blurb to the effect like "substitute the name of the ADFS service account in your ADFS deployment for adfssvc."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d7753d-30e1-db13-429a-c0b4eaf2c9c5
* Version Independent ID: 5be668ea-fc9d-0fb5-585d-4f5d5575b416
* Content: [Configuring Hybrid Windows Hello for Business - Active Directory Federation Services (ADFS)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-whfb-settings-adfs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
I do not have access to any ADFS server scenario to test this on, so I would have to wait for a reply from the document author.

Just as an educated guess, based on standard Active Directory browser usage experience, I think typing **adfssvc** and clicking OK should produce the correct service name and context, for example [BUILTIN\SYSTEM] or a similar context combination for the individual service, because the first time you click OK it should produce the correct name & context (if the base name is valid), and the second time you click OK it will enter that information into the object browser.

**Comment by mypil** [comment]
@robmacf  - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robmacf - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/07482859580142079f9f710114fe01235e2dd2d4. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
