### ISSUE TITLE
How do I get the remaining days left for the Maximum password age to expire?

### ISSUE THREAD

**Issue by jgoc** [MicrosoftDocs/windows-itpro-docs#5359]
I need it for monitoring and informing the users their `Maximum password age`'s remaining days.

**Comment by e0i** [comment]
@jgoc 

The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
