### ISSUE TITLE
Actual demand in the enterprise environment

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#5360]
Each port should be supported for control, such as turning off a USB, SD card slot, shutting down Bluetooth separately, AND NFC.
These needs are the real focus of enterprises, should increase support to improve competitiveness to meet user needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507f76f4-8665-4e41-8981-8c68a9b61cb3
* Version Independent ID: 2cf4cee5-62ea-584b-9ee7-07eca2f15922
* Content: [Intune management of Surface UEFI settings](https://docs.microsoft.com/en-us/surface/surface-manage-dfci-guide)
* Content Source: [devices/surface/surface-manage-dfci-guide.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/surface-manage-dfci-guide.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @goxia 

The issues section of this repository is intended for documentation and content related issues.

Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thank you.
