### ISSUE TITLE
USBC-only Requirement for newer hardware?

### ISSUE THREAD

**Issue by dashoffma** [MicrosoftDocs/windows-itpro-docs#5379]
Do the new Surface Pro 7 and Surface laptop 2 require the "Surface USB-C to Ethernet and USB 3.0 Adapter" [5921303] to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd6c1f5-529c-4b6a-6d70-6a091df10f3e
* Version Independent ID: df97fced-4167-f5d8-8643-50cbb1ba69e4
* Content: [Ethernet adapters and Surface deployment (Surface)](https://docs.microsoft.com/en-us/surface/ethernet-adapters-and-surface-device-deployment)
* Content Source: [devices/surface/ethernet-adapters-and-surface-device-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/ethernet-adapters-and-surface-device-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@dashoffma. Good question. I think Experts will update the article very soon

**Comment by e0i** [comment]
@dashoffma 

The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
