### ISSUE TITLE
LDAP will be faded out, but LDAPS instead?

### ISSUE THREAD

**Issue by earth0102** [MicrosoftDocs/windows-itpro-docs#5386]
In another word, LDAP will not be in use anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5db8802-afa2-017d-d898-46653a641ba7
* Version Independent ID: 23f9dca4-94a1-0803-e038-cf80bce83fc0
* Content: [Domain controller LDAP server signing requirements (Windows 10)](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hello @earth0102, thank you for your question. Just to clarify, is this a feedback regarding the accuracy of this documentation? If yes, it will help if we know what specific improvements you are suggesting or what you think needs clarification. Otherwise, if you are asking if LDAP is supported, I would presume it may be related to this statement or the suggested [Best Practices](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-controller-ldap-server-signing-requirements#best-practices)?

> *Client device that do not support LDAP signing cannot run LDAP queries against the domain controllers.*

Yes, clients that do not support LDAP signing, as mentioned in this doc, will be unable to execute LDAP queries against the domain controllers. If you need more technical details, I encourage you to [contact Windows Support](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10). There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community.

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation. Our main goal here is to ensure users have the best Windows 10 experience by providing useful, accurate and up-to-date documentation. 

*Important* - This Github site is used as a feedback system and is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback.

**Comment by jvsam** [comment]
By the way @earth0102, these are link resources that may help:

- [2020 LDAP channel binding and LDAP signing requirement for Windows](https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows)
- [ADV190023 | Microsoft Guidance for Enabling LDAP Channel Binding and LDAP Signing](https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023)
- [Understanding LDAP Security Processing](https://blogs.technet.microsoft.com/askds/2009/09/21/understanding-ldap-security-processing/)

Thank you.

**Comment by jvsam** [comment]
Hello again @earth0102, we haven't heard or received any updates from you. We are hoping that the information we shared helped. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
