### ISSUE TITLE
Missing error code: 0x80090016

### ISSUE THREAD

**Issue by azscloudpro** [MicrosoftDocs/windows-itpro-docs#5390]
Having big troubles with a AAD joined Windows 10 machine and setting a PIN code, throws error 0x80090016 tried unjoining and re-joining many times but doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4f9133-887f-17a6-95fc-3712de8a3fa1
* Version Independent ID: 09d34ce8-1590-8202-3e70-e6299dadbb65
* Content: [Windows Hello errors during PIN creation (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-errors-during-pin-creation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @redforce123, apologies for the inconvenience. We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. If you have feedback, suggestions related to this documentation, or ideas to make it better for users, please let us know and we will submit it for review.

What we recommend regarding your issue is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community.

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by illfated** [comment]
@azscloudpro : On one hand, the reason for the error codes missing on this page has often been explained as intermittent or unclear errors without a constant reason or solution. This error code hex value is also used by several other applications or software solutions, both on Windows Servers and Windows 10.

If you are able to produce a useful error message consistent, it could be helpful to report that error message here, in case it can be used to add the entry in the table.

In the meanwhile, I am fairly sure that a web search will be a faster way to find a solution, like this page:
- https://www.thewindowsclub.com/error-code-0x80090016-for-pin-and-microsoft-store

What that page says about Windows Hello PIN error 0x80090016 and its cause, it seems to be the corruption of the contents of the NGC folder. The NGC folder is responsible for storing certain files which are crucial for the system’s security. The most probable reason behind the corruption of the folder is when a third-party software modifies the files. Other than this, third-party software products induce certain background processes which could cause this error.

**Comment by jvsam** [comment]
Hi again @azscloudpro, we hope you were able to contact Windows 10 Support to resolve your concern, or checked the information provided by @illfated. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
