### ISSUE TITLE
Error on ADFS

### ISSUE THREAD

**Issue by AlexeiKlimenko** [MicrosoftDocs/windows-itpro-docs#5392]
On adfs error is registred:

"Failed to download Windows Hello key receipt public issuer certificates. Url: none.. 

Additional Data 
Exception details: 
System.InvalidOperationException: Invalid or missing tenant information in Active Directory. Make sure you have configured the Service Connection Point (SCP) here: CN=62a0ff2e-97b9-4513-943f-0d221bd30080,CN=Device Registration Configuration,CN=Services,CN=Configuration,(forest-dn)."

Via ADSI edit we configured Keywords but there is no any info about msDS-IssuerCertificates -> the corresponding CN=DeviceRegistrationService is missed under "CN=62a0ff2e-97b9-4513-943f-0d221bd30080,CN=Device Registration Configuration,CN=Services,CN=Configuration..."

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by AlexeiKlimenko** [comment]
Do we run Initialize-ADDeviceRegistration if we're using on-premise only?

**Comment by jvsam** [comment]
Hi @AlexeiKlimenko, apologies for the inconvenience. We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. If you have feedback, suggestions related to this documentation, or ideas to make it better for users, you can open an issue on a specific content page by using the feedback feature so it can easily be tracked.

What we recommend regarding your issue is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community.

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
Hi again @AlexeiKlimenko, we haven't heard or received any updates from you. We are hoping that you were able to contact Windows 10 Support to resolve your concern. We will now close this issue, however, feel free to re-open if you have suggestions or ideas to improve the quality of this documentation.

Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
