### ISSUE TITLE
Tuple and OEM registration takes 2 or 3 days

### ISSUE THREAD

**Issue by Dud3z** [MicrosoftDocs/windows-itpro-docs#5427]
Hi,

i tried to add Devices at different customer Tenants via Partner Center and tuple. I had to wait at least 2 days for the Device to show up in the device enrollment console. in this 2 days of waiting there was not even a little sign of the device. If i tried to upload regular csv files in intunes it says that the device is already registered. Same with OEM registration, i ordered a DELL Latitude 7400 and tried the OEM registration process. If i try to upload a regular hwhash in intune it tells me that its allready assigned. Right now the customer is sitting infront of his new Notebook but is not allowed to use it since it is kind of added but not completely. Is this behaviour by feature or for what reason its that slow?

**Comment by RAJU2529** [comment]
@Dud3z. From which content you are taking about

**Comment by e0i** [comment]
Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

The issues section of this repository is intended for documentation feedback.

Feel free to re-open this ticket if you feel that documentation also needs to be updated.
