### ISSUE TITLE
One-handed Start gesture doesn't list that users need to be on current build.

### ISSUE THREAD

**Issue by evmill** [MicrosoftDocs/windows-itpro-docs#5430]
This is a new feature that only works after updating. I believe there should be something that indicates to users that if this interaction isn't working that they should try updating their device. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb17525-36a9-d993-b774-24fdd800fa0e
* Version Independent ID: c3ec4304-6217-5341-47cf-774070496c73
* Content: [Getting around HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens2-basic-usage#one-handed-start-gesture)
* Content Source: [devices/hololens/hololens2-basic-usage.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens2-basic-usage.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by scooley** [comment]
@e0i - can this be resolved fixed?

@DaniHalfin - what can I do to become a maintainer so we can use this for issue tracking too?

**Comment by e0i** [comment]
@evmill 

This issue has been addressed with the following commit and content has been updated according to your feedback.

[[c3d09ab ] CAT Auto Pulish for Windows Release Messages - 20191115191333 (#1564) ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c3d09ab5230109f0617caf1f2ad6970c9820f82c#diff-88d88b985986996a7ceb461876b5eeb7)

We are thus closing this issue since it seems to be resolved. 

Thank you for taking the time to provide feedback.

**Comment by evmill** [comment]
@scooley
"You must update to the November 2019 update (build 18363) or later."
would be better identified as
"You must update to the November 2019 update (build 10.0.18363.1039) or later."
because the current ARC build could also be identified using the current statement and would not have this feature.
