### ISSUE TITLE
Connect-AutopilotIntune' is not recognized

### ISSUE THREAD

**Issue by mustafafarooq** [MicrosoftDocs/windows-itpro-docs#5443]
In the step 3 of Create the JSON file i am receiving this error, has it changed or something ?

PS C:\WINDOWS\system32&gt; Connect-AutopilotIntune -user admin@example.onmicrosoft.com
Connect-AutopilotIntune : The term 'Connect-AutopilotIntune' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ Connect-AutopilotIntune -user admin@example.onmicrosoft.com
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-AutopilotIntune:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bfe927-f7b7-608b-8537-5c2274ccdced
* Version Independent ID: 5dd9abca-92d9-fbb2-6796-d1f6b9ab3c8b
* Content: [Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/existing-devices#feedback)
* Content Source: [windows/deployment/windows-autopilot/existing-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/existing-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by CyclopsHelpdesk** [comment]
Hi

Connect-MSGraph should be used instead.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @mustafafarooq, our apologies for the inconvenience. We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. What we recommend is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to get immediate assistance. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can post your question and get help from the community. You may also want to check this:

[The term is not recognized" error when you try to run Azure Active Directory for Windows PowerShell cmdlets](https://support.microsoft.com/en-us/help/2669552/the-term-cmdlet-name-is-not-recognized-error-when-you-try-to-run-azure)

Kindly keep us informed if you find any relevant information that can be incorporated into this documentation. 

@CyclopsHelpdesk could you please clarify your comment? Do you mean instead of using *Connect-AutopilotIntune*, use *Connect-MSGraph*? Is this a workaround when you get that error? Thanks for the information.

**Comment by redog** [comment]
I'm seeing this error also. The error is raised at step 3 of the "Create the JSON file" section .

Using Connect-MSGraph instead does indeed work.

**Comment by mustafafarooq** [comment]
My concern was if the cmdlet doesnt exist as the error indicates, then what is it doing here in the documentation.

**Comment by Jamin79** [comment]
Hi, I'm trying to get this working. I've seen that I now have to connect with MSGraph, however when I try to run the following command:

Get-AutopilotProfile | ConvertTo-AutopilotConfigurationJSON

I get the below error:

ConvertTo-AutopilotConfigurationJSON : The term 'Get-Organization' is not recognized as the name of a cmdlet, function,
 script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is c
orrect and try again.
At line:1 char:24
+ Get-AutopilotProfile | ConvertTo-AutopilotConfigurationJSON
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-Organization:String) [ConvertTo-AutoPilotConfigurationJSON], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,ConvertTo-AutoPilotConfigurationJSON

I can't find where that "Get-Organization" command is supposed to come from. What am I missing?

**Comment by phalore** [comment]
Try making the dir first c:\Autopilot then it should run.

**Comment by Jamin79** [comment]
Actually, the problem was that the command ConvertTo-AutopilotConfigurationJSON isn't in the older version of the module. I ended up installing the older version because Install-Module WindowsAutopilotIntune -Force didn't actually install anything. Took forever to find the correct install path for the latest version, but once that was installed everything worked.

**Comment by jvsam** [comment]
Hi @Jamin79, with what you've experienced so far, does it mean the information (specifically the instructions) in the documentation is still accurate? As per the discussion, using *Connect-MSGraph* instead of *Connect-AutopilotIntune* works (as confirmed by @CyclopsHelpdesk and @redog). If there is missing information or amendments should be made based on empirical data, please let us know.  Thank you.

**Comment by kennethvs** [comment]
For Reference: https://oofhours.com/2019/11/02/whats-new-with-the-windowsautopilotintune-powershell-module/

Connect-MSGraph should now be used instead of Connect-AutoPilotIntune

**Comment by jvsam** [comment]
Thank you for that additional information @kennethvs. Let me get this over to the Windows content writing team for review.

**Comment by illfated** [comment]
(ref. #5772 )

**Comment by e0i** [comment]
@mustafafarooq 

With the help of your feedback, the content has been updated with relevant changes accordingly. Thanks.

**Comment by Naures1981** [comment]
Coonect-MGGraph is correct
