### ISSUE TITLE
ARM-based processors

### ISSUE THREAD

**Issue by thetechguy86** [MicrosoftDocs/windows-itpro-docs#5450]
Does Windows Defender ATP support ARM-based processors? Can it be used on a Microsoft Surface Pro X?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@thetechguy86. All Android  OS running in the smart phones  will be manufacturered ARM chips, so that meass windows defender ATP is supported.

**Comment by thetechguy86** [comment]
I opened a case with Microsoft Technical support and they are stating Windows Defender ATP is not supported on ARM-based processors.

**Comment by jvsam** [comment]
Thank you for sharing @thetechguy86! This is valuable information that can help other users since feedback or issues shared through the Microsoft Docs are public. I also recommend periodically checking the [What's new in Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/whats-new-in-microsoft-defender-atp) content page to keep abreast of the new feature enhancements and capabilities (*including those in preview*). There is a good news though, users of Windows 10 19H2 will have Windows Defender Credential Guard enabled for ARM64 devices  for additional protection against credential theft for enterprises. More information available on [Microsoft's blog](https://blogs.windows.com/windowsexperience/2019/08/19/announcing-windows-10-insider-preview-build-18362-10014-18362-10015-19h2/). 

Since Windows 10 for ARM does not support MDATP yet, I encourage you to submit this on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub) (*Feedback Hub*). This way, your feedback goes directly to the Microsoft product team and I assure you, they would love to hear what you think. If there's already a request, suggestion or feedback similar to yours, you can add your vote to the request. Thank you!

**NOTE:** We're not sure exactly what has been communicated by Windows Support with regard to ARM. If it's something that you believe needs to be called out in the docs, let us know and provide more information. Please be informed that this GitHub-based feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs through user contributions and feedback. We are always looking forward to suggestions and ideas to make the docs better for users.

**Comment by jvsam** [comment]
Hi again @thetechguy86, we hope the information we've provided helped. We will now close this issue, and again, please let us know if you have feedback or suggestions to help improve the quality of the Microsoft Docs technical documentation. Thanks for being part of the Microsoft Docs community!

**Comment by jvsam** [comment]
@officedocsbot close
