### ISSUE TITLE
Automatic exclusions for OS before 2016

### ISSUE THREAD

**Issue by samsig01** [MicrosoftDocs/windows-itpro-docs#5486]
The documentation references the automatic exclusions for server 2016 and newer but does not reference how automatic exclusions are handled for earlier OS's that are still supported by WD-ATP.  Such as 2008 R2 SP1 and 2012 R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9b6379-e575-9819-eca1-a0952f66b655
* Version Independent ID: 34d81602-ffa2-5be6-67ef-b42b3b6f17ee
* Content: [Configure Windows Defender Antivirus exclusions on Windows Server 2016](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-server-exclusions-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
As suggested in the article title, the subject already pertains to _Server 2016_. This might be intentional due to the fact that 2008 is at the end of its support lifecycle.

See: [End of support for Windows Server 2008 and Windows Server 2008 R2](https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2)
