### ISSUE TITLE
Needs updating for windows 10?

### ISSUE THREAD

**Issue by opoplawski** [MicrosoftDocs/windows-itpro-docs#5511]
The requirements table does not list windows 10 in the column headings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132e8bfa-12ba-2ae0-7745-545bcfd909f1
* Version Independent ID: 984c17f4-04a4-bf30-3a9e-3af49209f0bb
* Content: [Certificate Requirements and Enumeration (Windows 10)](https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration#feedback)
* Content Source: [windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @opoplawski, let me get this over to the Windows content writing team for review. We really appreciate your feedback and thank you for being part of the Microsoft Docs Community and for helping improve the quality of the technical documentation!

**Comment by jvsam** [comment]
Hi again @opoplawski , we really appreciate your patience and thank you again for sharing your feedback. We will now close this issue since it has been resolved and updates are now displayed here at docs.microsoft.com. Please continue to send your feedback and suggestions to help improve the quality of the technical documentation of Microsoft Docs. Thank you for being part of the community!

**Comment by jvsam** [comment]
@officedocsbot close
