### ISSUE TITLE
Windows Restricted Traffic Limited Functionality Baseline - Updates for 1909?

### ISSUE THREAD

**Issue by epon** [MicrosoftDocs/windows-itpro-docs#5524]
Hi,

Are there any updates to the Windows Restricted Traffic Limited Functionality Baseline specifically for version 1909? The baseline currently only covers up to 1903. Are the LGPO/auto-install scripts for 1903 suitable for use on 1909?

Regards.

**Comment by mypil** [comment]
@epon - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by epon** [comment]
https://docs.microsoft.com/en-gb/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services

**Comment by epon** [comment]
Note that none of the documentation regarding managing connections from Windows OS components currently refers to 1909. I was just wanting to know if there are planned updates to any of this.

**Comment by mypil** [comment]
@medgarmedgar - Can you please share your insights on this issue? 

This is for the below doc:

Content: [Manage connections from Windows 10 operating system components to Microsoft services](https://docs.microsoft.com/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services)

Content Source: /[windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services.md)


Thank you!

cc: @kenwith

**Comment by medgarmedgar** [comment]
Answers are below. 

#1
Q: Are there any updates to the Windows Restricted Traffic Limited Functionality Baseline specifically for version 1909? The baseline currently only covers up to 1903. 
A: No, there are no specific updates for 1909.  In our testing the 1903 settings fully worked and prevented egress traffic. 

#2 
Q: Are the LGPO/auto-install scripts for 1903 suitable for use on 1909?
A: Yes, the 1903 scripts can be used on 1909. 

#3 
Q: I was just wanting to know if there are planned updates to any of this.
A: There are no planned updates specific to 1909 since the 1903 settings work on 1909.

**Comment by epon** [comment]
Thanks for the clarification!
