### ISSUE TITLE
Erreur 404

### ISSUE THREAD

**Issue by Efflamm** [MicrosoftDocs/windows-itpro-docs#5562]
Lien invalide :
https://www.kingston.com/us/usb/bootable/ikw700

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 93868b54-1342-6a97-ea84-ab75066c837b
* Version Independent ID: 8ee0f61c-67cd-9df6-a8e9-b854d8134587
* Content: [Présentation de la fonctionnalité Windows to Go (Windows 10)](https://docs.microsoft.com/fr-fr/windows/deployment/planning/windows-to-go-overview#feedback)
* Content Source: [windows/deployment/planning/windows-to-go-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-to-go-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by RAJU2529** [comment]
@jvsam. afternoon I will create PR

**Comment by illfated** [comment]
@Efflamm : Où avez-vous trouvé ce lien invalide?
Dans quelle section ou paragraphe se trouve-t-il?

**Comment by illfated** [comment]
Aha, je vois. La section IronKey entière souffre de problèmes de format de liaison, mais l'erreur 404 réelle est la première ligne de lien. Voir l'exemple de texte copié ci-dessous:

>  /!\ Avertissement
>
> L’utilisation d’un lecteur USB qui n’a pas été certifié n’est pas prise en charge.

> **Espace de travail IronKeyhttp://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w700.htmlW700 ()** ⬅️ 
> Espace de travail IronKeyhttp://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w500.htmlW500 ()
> Espace de travail IronKeyhttp://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w300.htmlW300 ()
> Espace de travail DataTraveler Kingston pour Windows tohttp://www.kingston.com/wtg/Go ()

**Comment by illfated** [comment]
The en-us page looks something like the following:
(Please note, I have added the fwlinks in parentheses at the end of the rows.)
***
/!\ Warning

Using a USB drive that has not been certified is not supported.

- IronKey Workspace W700 (http://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w700.html) | (https://go.microsoft.com/fwlink/p/?LinkId=618714)
- IronKey Workspace W500 (http://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w500.html) | (https://go.microsoft.com/fwlink/p/?LinkId=618717)
- IronKey Workspace W300 (http://www.ironkey.com/windows-to-go-drives/ironkey-workspace-w300.html) | (https://go.microsoft.com/fwlink/p/?LinkId=618718)
- Kingston DataTraveler Workspace for Windows To Go (http://www.kingston.com/wtg/) | (https://go.microsoft.com/fwlink/p/?LinkId=618719)
***
The "good" news is that the 404 error is caused by the W700 model being discontinued on the Kingston site, so that issue needs to be dealt with internally, I think. Alternatively, the link can be removed entirely, unless there is a consolidating page for the discontinued models 32GB/64GB/128GB (see table below):

https://www.kingston.com/en/memory/search/partnumber?partId=IKW700

## Results for Kingston Part Number(Discontinued )

| Kingston Part Number | Description |
| --- | --- |
| [IKW700/32GB](https://www.kingston.com/en/memory/search/discontinuedmodels?partId=IKW700%2F32GB)  |  32GB IronKey Workspace W700 Certified for Windows To Go |
| [IKW700/64GB](https://www.kingston.com/en/memory/search/discontinuedmodels?partId=IKW700%2F64GB)  |  64GB IronKey Workspace W700 Certified for Windows To Go |
| [IKW700/128GB](https://www.kingston.com/en/memory/search/discontinuedmodels?partId=IKW700%2F128GB)  |  128GB IronKey Workspace W700 Certified for Windows To Go |

(the table is repeated below, in reverse order, as Results for Distributor Part Number(Discontinued ) )
***
The only real translation issue on this Fr-Fr page is that the formatting seems to become broken for links, specifically in the Kingston section referred to above.

**Comment by illfated** [comment]
@jvsam : What course of action do you recommend, regarding the discontinued model W700 and its broken link?

@TinaMcN : Would it be useful to contact the MT technicians to check if this formatting issue is specific to the French page or if it is a general filter issue?

**Comment by jvsam** [comment]
@illfated, from the update on PR #5566, the fwlink needs to be corrected. IronKey Workspace W500, W300 and Kingston DataTraveler all points to this [page](https://www.kingston.com/us/support/technical/products?model=dtws) (DataTraveler Workspace+B2:M22). Also, there is a regional redirect so the country code is automatic depending on your location. Anyway, the link to the IronKey Workspace W700 goes to https://www.kingston.com/us/usb/bootable/ikw700 which is currently a 404 page (and even if you remove the country code, or replace it with another country or language code, it's still 404). I will recommend creating a new PR and update the fwlink link (not sure if that can be done via the PR?) to be the same as the other links. Can you create a new one and explain the scenario?

**Comment by illfated** [comment]
OK, so if I understand you correctly, you suggest a change to something similar to this:
***
> [!WARNING] Using a USB drive that has not been certified is not supported.
- IronKey Workspace W700 (https://www.kingston.com/support/technical/products?model=dtws)
- IronKey Workspace W500 (https://www.kingston.com/support/technical/products?model=dtws)
- IronKey Workspace W300 (https://www.kingston.com/support/technical/products?model=dtws)
- Kingston DataTraveler Workspace for Windows To Go (http://www.kingston.com/wtg/)
- Spyrus Portable Workplace (http://www.spyruswtg.com/)
We recommend that you run the Spyrus Deployment Suite for Windows To Go to provision the Spyrus Portable Workplace.
***
(The only change is the links in parentheses after W700, W500, and W300.)

**Comment by TinaMcN** [comment]
@illfated I had already reported a bug with spacing issues like this to the machine translation tool team.   I shared this example with them also.
