### ISSUE TITLE
This WAAS

### ISSUE THREAD

**Issue by kenmac311** [MicrosoftDocs/windows-itpro-docs#5563]
This has become similar to the ones who create widgets and then put up a blog for users to help themselves, because the producer will not support or stand by their own product. The bureaucrat cry about involving the public is to either to transfer their responsibility to others, or to exploit those users for money.   So often is the advice(?) to call support.  But who is the support and how much will it cost me?  Much too often the customer is transferred to a contractor company, many of whom one cannot understand and most often does not know how to help the user.  I do not like Apple products or the way they operate, but it is no wonder why they are eating your lunch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4e47c9-b470-be67-acc3-6a763746b854
* Version Independent ID: fdfb6514-3340-54a2-7743-9ce46b91c5e3
* Content: [Windows 10](https://docs.microsoft.com/en-us/windows/windows-10/#feedback)
* Content Source: [windows/hub/index.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/hub/index.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @kenmac311, I am very sorry to hear that you are not happy with Microsoft products. Can you please share more information so we can assist you or get to the bottom of this? This GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. Do you have any concerns, feedback or suggestions related to this documentation? If so, please let us know and we will submit it for review. Otherwise, please provide more information so we can further assist you. Thank you.

**Comment by illfated** [comment]
@kenmac311 : May we also know in which capacity your statement is made, from your perspective as an end user; if it is based on home usage or business usage, only for yourself or as part of a group or an organization?

**Comment by denisebmsft** [comment]
Closing this issue out. Thank you @jvsam and @illfated for helping with this!
