### ISSUE TITLE
drvload loading keyboard drivers is not support laptop 2

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windows-itpro-docs#5679]
Includes the laptop2 and 3 models, but its driver conflicts cannot be fully imported, and the drvload load driver is planned, but the drive for the laptop2 is found to be unsupported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b195b1b-81bf-310e-3ff4-e520826e7e94
* Version Independent ID: fb399be5-9fb5-a3f9-f912-ed3fde235f05
* Content: [How to enable the Surface Laptop keyboard during MDT deployment (Surface) - Surface](https://docs.microsoft.com/en-us/surface/enable-surface-keyboard-for-windows-pe-deployment)
* Content Source: [devices/surface/enable-surface-keyboard-for-windows-pe-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/enable-surface-keyboard-for-windows-pe-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Hi @goxia, thank you for bringing this to our attention. To clarify, are you saying that you cannot install the [Surface Laptop 2 Drivers and Firmware](https://www.microsoft.com/en-us/download/details.aspx?id=57515) update successfully? And you are using Windows 10 since it's a requirement, right? We would love to help you with your concern, however, this GitHub-based documentation feedback system is intended to help improve the quality of the technical documentation of Microsoft Docs. What we recommend is to open a [service/support ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10) in your tenant to report this issue. There are also other support resources that you can explore like the [Microsoft Tech Community](https://techcommunity.microsoft.com/) or the [Technet forums](https://social.technet.microsoft.com/Forums/home) where you can collaborate and discuss this issue with the community.  Thank you.

**IMPORTANT**: Surface [update history](https://support.microsoft.com/en-us/help/4036283/surface-surface-update-history) for your reference. See [Download drivers and firmware for Surface](https://support.microsoft.com/en-us/help/4023482/surface-download-drivers-and-firmware), as well.

**Comment by goxia** [comment]
Hi @jvsam , What I want to mean is that I want to be able to support both laptop2 and 3 keyboards in the Windows PE, but in fact their drivers can't be added to a single Windows PE at the same time.

**Comment by illfated** [comment]
Thank you for clarifying. Unfortunately, I do not have access to any Surface device, so it would be helpful if you could confirm if you are looking for this issue to be resolved in the software, or if you think this issue needs to be documented in the article, or both.

Regardless, I think this should be commented on by the document author @Teresa-Motiv or the contributor @CoveMiner .

**Comment by goxia** [comment]
@illfated , Thanks a lot.
This requirement can be prevalent in the enterprise, and if you can include it in the article, it will help users understand and avoid problems in advance.

**Comment by illfated** [comment]
Sounds like a good idea to add a note regarding this issue in the document. I am thinking something similar to the following text:
> [!NOTE]
> It is currently not supported to add Surface Laptop 2 and Surface Laptop 3 keyboard drivers in the same Windows PE boot instance due to driver conflict.

Feel free to suggest a different phrasing if the one above can be misunderstood or is open to different interpretations. If you also have a good suggestion for a good place in the article to place this note, that would be very helpful too. Thanks in advance. 👍

**Comment by goxia** [comment]
@illfated , Thanks. I think this has been very helpful to users, hope that the future can have a perfect solution.

**Comment by greg-lindsay** [comment]
Looks like the note was added to the topic, so closing this issue.
