### ISSUE TITLE
Please include next logic next steps

### ISSUE THREAD

**Issue by Axilla-the-HUN** [MicrosoftDocs/windows-itpro-docs#5681]
Related Topics should be - How to import ADMX templates into Group Policy, linked to a step by step guide - using images - how to import. My suggestion would be adding some images to your documentation, we can use graphics on the web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3e60ec-cf61-c34b-db79-74b13e3ee867
* Version Independent ID: fc5079f7-a563-c627-3a3e-eb84a99e4fd3
* Content: [New policies for Windows 10 (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10#feedback)
* Content Source: [windows/client-management/new-policies-for-windows-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/new-policies-for-windows-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
Thank you @Axilla-the-HUN. I will get this over to the Windows content writing for review and consideration. For now, adding a link to another content page under the same topic (and Doc set) will help. The topic *"Understanding ADMX-backed policies"* contains We always strive to improve the quality of the technical documentation of Microsoft Docs so your feedback is appreciated!

Thank you for being part of the Microsoft Docs Community!

**Comment by jvsam** [comment]
Thank you @Axilla-the-HUN. I will forward your suggestion to the Windows content writing team for review and consideration since this might be an entirely new topic or content and can't be handled via the normal feedback process here in Github. Anyway, MS authors do check issues opened by the community so I am sure your feedback is noted. Also, please note that there are topics in the same doc set that provide information in deploying the templates, for example, the [Manage the Settings app with Group Policy](https://docs.microsoft.com/en-us/windows/client-management/manage-settings-app-with-group-policy) topic which links to the [How to create and manage the Central Store for Group Policy Administrative Templates in Windows](https://support.microsoft.com/help/3087759/how-to-create-and-manage-the-central-store-for-group-policy-administra) page. 

There is also the [Step-By-Step: Managing Windows 10 with Administrative ADMX templates](https://techcommunity.microsoft.com/t5/ITOps-Talk-Blog/Step-By-Step-Managing-Windows-10-with-Administrative-ADMX/ba-p/842926) blog article that is available in the Tech Community. 

I also encourage you to submit any feedback regarding content creation on [UserVoice](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Again, thank you for your feedback and for being part of the Microsoft Docs Community!
