### ISSUE TITLE
Include documentation about wuauclt /reportnow

### ISSUE THREAD

**Issue by javierlarota** [MicrosoftDocs/windows-itpro-docs#5686]
Great article, it would be great if you include documentation on how the WU Client or the UpdateAgent reports Update status back to WSUS. `wuauclt /reportnow` seems to be not very reliable, or at least there is not documentation on how that works in Windows 10. 

Some times devices do not report their patch status, and `wuauclt /reportnow` does not do anything, it would be nice if we understand how that works, so we can better troubleshoot issues.

Thanks,

--Javier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc8a7ec-75d7-894c-9499-cbb4c3807ea7
* Version Independent ID: a4c97095-7c09-1bff-690d-90c8cdeee6c2
* Content: [Get started with Windows Update - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-overview#feedback)
* Content Source: [windows/deployment/update/windows-update-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by jaimeo** [comment]
Thanks for that suggestion! We're undertaking a big overhaul of all this info in January, so I'll add this to that list.

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by jvsam** [comment]
@officedocsbot assign @jaimeo

**Comment by nam31** [comment]
@javierlarota  Please look into these links which might help you: 
https://docs.microsoft.com/en-us/troubleshoot/mem/configmgr/troubleshoot-issues-with-wsus-client-agents
https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus

If you still think documentation is completely missing. Please share your feedback here 

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.
