### ISSUE TITLE
Subcategory Table

### ISSUE THREAD

**Issue by thelonelyprogrammer** [MicrosoftDocs/windows-itpro-docs#5706]
The first row in the table (Audit Credential Validation, etc.) should not be in bold since the values are not a header but just values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea5ca36-d3ce-725c-c47a-ff28da011a8b
* Version Independent ID: cd2257e0-e907-0332-55c1-2d18eb7cf853
* Content: [4912(S) Per User Audit Policy was changed. (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4912#feedback)
* Content Source: [windows/security/threat-protection/auditing/event-4912.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/auditing/event-4912.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@thelonelyprogrammer . For me table is good.

**Comment by joinimran** [comment]
@thelonelyprogrammer Thank you for your feedback here but as per Github writing styles this 1st row in the table will always be bold.

See https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

Thanks.

**Comment by illfated** [comment]
Looks like we need to add an empty 1st row then, to make the table only show the list content.

**Comment by illfated** [comment]
|    |   
-- | -- | --
Audit Credential Validation | Audit Process Termination | Audit Other Logon/Logoff Events
Audit Kerberos Authentication Service | Audit RPC Events | Audit Special Logon
Audit Kerberos Service Ticket Operations | Audit Detailed Directory Service Replication | Audit Application Generated
Audit Other Logon/Logoff Events | Audit Directory Service Access | Audit Certification Services
Audit Application Group Management | Audit Directory Service Changes | Audit Detailed File Share
Audit Computer Account Management | Audit Directory Service Replication | Audit File Share
Audit Distribution Group Management | Audit Account Lockout | Audit File System
Audit Other Account Management Events | Audit IPsec Extended Mode | Audit Filtering Platform Connection
Audit Security Group Management | Audit IPsec Main Mode | Audit Filtering Platform Packet Drop
Audit User Account Management | Audit IPsec Quick Mode | Audit Handle Manipulation
Audit DPAPI Activity | Audit Logoff | Audit Kernel Object
Audit Process Creation | Audit Logon | Audit IPsec Driver
Audit Other Object Access Events | Audit Filtering Platform Policy Change | Audit Other System Events
Audit Registry | Audit MPSSVC Rule-Level Policy Change | Audit Security State Change
Audit SAM | Audit Other Policy Change Events | Audit Security System Extension
Audit Policy Change | Audit Non-Sensitive Privilege Use | Audit System Integrity
Audit Authentication Policy Change | Audit Sensitive Privilege Use | Audit PNP Activity
Audit Authorization Policy Change | Audit Other Privilege Use Events |  
Group Membership | Audit Network Policy Server |  

This empty title row can be achieved using Alt+255 as a substitute for any single visible character, which would otherwise be shown as a column heading.

**Comment by illfated** [comment]
See also https://stackoverflow.com/questions/17536216/create-a-table-without-a-header-in-markdown for details on various support or hacks for header-less tables.

**Comment by illfated** [comment]
There is also the option to add the word "value" 3 times to fill up the first row, just in case the empty row option breaks the page:

value | value | value
-- | -- | --
Audit Credential Validation | Audit Process Termination | Audit Other Logon/Logoff Events
Audit Kerberos Authentication Service | Audit RPC Events | Audit Special Logon

**[ ... ]**

**Comment by joinimran** [comment]
I like @illfated idea to place mark them as values. Additionally, @illfated is right, Group Membership should be Audit Group Membership. I have made the necessary adjustments in the PR.

**Comment by mypil** [comment]
@thelonelyprogrammer -  From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/643823da2714a189852db5304ee5456a5d9e0135. 


Thank you for your contribution to make the docs better! Much appreciated!
