### ISSUE TITLE
Missing 100.79.67 release notes

### ISSUE THREAD

**Issue by annerajb** [MicrosoftDocs/windows-itpro-docs#5738]
Where can I find 100.79.67 release notes / changes? they are not on the app neither on this website this is for Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 287292d6-355f-5ad8-b29d-3fcc4b2604ca
* Version Independent ID: 1bcc491b-3736-6a85-3551-7aade2ff5f8a
* Content: [What's new in Microsoft Defender Advanced Threat Protection for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-whatsnew.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by annerajb** [comment]
New version out 100.80.42 and no release notes or list of changes included.

**Comment by annerajb** [comment]
Any release notes for 100.83.73

**Comment by annerajb** [comment]
Thanks you can close i see the new ones have been added

**Comment by annerajb** [comment]
Any idea what changed on 100.85.54

**Comment by nam31** [comment]
@annerajb Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.
