### ISSUE TITLE
Microsoft Teams Mode settings is incorrect in Japanese page.

### ISSUE THREAD

**Issue by Satoshi-Mori** [MicrosoftDocs/windows-itpro-docs#5746]
English page:
https://docs.microsoft.com/en-us/surface-hub/surface-hub-2s-manage-intune

![image](https://user-images.githubusercontent.com/46014661/71427512-d1b2ee00-26fc-11ea-94ee-228063ab4961.png)

Japanese page:
https://docs.microsoft.com/ja-jp/surface-hub/surface-hub-2s-manage-intune

![image](https://user-images.githubusercontent.com/46014661/71427532-19397a00-26fd-11ea-9401-15c4c44ba674.png)

**Comment by RAJU2529** [comment]
@illfated . There is no edit option on Japanese page

**Comment by illfated** [comment]
Yes, I know. So far, only the en-us pages have been opened for community editing, because it is much easier for Microsoft Docs team managers to verify that suggested changes (pull requests) in English are correct, compared to any other languages covered by automatic translation.

There are 2 options when it comes to issues with translated pages: either
1. Wait for this issue ticket to become assigned to one of the MS Docs team members and possibly a suggestion from @TinaMcN to have the page manually translated due to Machine Translation issues, or
2. Research the /en-us/ version of the page to see if we can find a cause for the current translation problem, maybe suggest a PR change if we find that something in the English text can be improved to avoid this Machine Translation issue.

Seeing that this issue does not occur on the /en-us/ page, I recommend that we use option 1 for now.

(in theory, there is a chance that using MarkDown back ticks (code tags) around the affected string on the /en-us/ page could block the translation tool from converting the end part of the string, but I am uncertain if this is the recommended solution here.)

**Comment by illfated** [comment]
Alternate option, in case it can be accepted to use monospaced font for the string value:

Name | Description | OMA-URI | Type | Value
-- | -- | -- | -- | --
Teams App ID | App name | ./Vendor/MSFT/SurfaceHub/Properties/VtcAppPackageId | String | `Microsoft.MicrosoftTeamsforSurfaceHub_8wekyb3d8bbwe!Teams`
Teams App Mode | Teams mode | ./Vendor/MSFT/SurfaceHub/Properties/SurfaceHubMeetingMode | Integer | 0 or 1 or 2

***


名前 | 説明 | OMA-URI | 型 | 値
-- | -- | -- | -- | --
Teams アプリ ID | アプリ名 | ./Vendor/MSFT/SurfaceHub/Properties/VtcAppPackageId | String | `Microsoft.MicrosoftTeamsforSurfaceHub_8wekyb3d8bbwe!Teams`
Teams アプリモード | Teams モード | ./Vendor/MSFT/SurfaceHub/Properties/SurfaceHubMeetingMode | 整数 | 0または1または2

**Comment by TinaMcN** [comment]
@Satoshi-Mori thank you for reporting this issue.  The Japanese article is machine translated and the MT tool sometimes overtranslates items like this.   I sent the article to be human translated, it will take approx. 3 weeks.

**Comment by Satoshi-Mori** [comment]
Hi, Thank you for your cooperation.
I understand it will take 3 week to fix document.
Best Regards,
Satoshi Mori

**Comment by e0i** [comment]
Manually verified to be fixed. Thanks.
