### ISSUE TITLE
Surface Hub - ActiveSync disabled (room Type)

### ISSUE THREAD

**Issue by Systech2017** [MicrosoftDocs/windows-itpro-docs#5813]
Hello Smart boys,

I am trying to create a SH account.
1. create a Room MBX - enabled it
2. convert to regular MBx
3. assign Policy created 
4. convert back to room Mbx

when try to connect from Surface Hub device, we got error that connection failed.
Activesync is disabled on that account (Room)
I enabled it when back to regular set-casmailbox...

But after a certain time, activesync is back to false .

Where is my mistake?
Thx all.

**Comment by e0i** [comment]
Hello, @Systech2017

The issues section of this repository is intended for defects in the documentation itself.

Please consider opening a product support ticket by the following link below for your problem so that it gets addressed quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
