### ISSUE TITLE
Exchange 2016 - Archiving issue

### ISSUE THREAD

**Issue by Systech2017** [MicrosoftDocs/windows-itpro-docs#5814]
Hello,

When MBx and Archive Mbx are on different servers same dag, All archive mails are moved to the dumpster of the archives Mbx. I need MFCMapi to find them.

I can see the Prt_Retention flag on the MBx - Policy is working fine when both MBx and Archive MBx are on same server (different DB also)

Any hint where where i can look into?
Thx.

**Comment by e0i** [comment]
@Systech2017,

The issues section of this repository is intended for product documentation issues only.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

The issues section of this repository is intended for defects in the documentation itself.

Please consider opening a product support ticket by the following link below for your problem so that it gets addressed quickly.

Thank you.
