### ISSUE TITLE
bad color choice for table headers - dark & high contrast themes

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/windows-itpro-docs#5819]
multiple tables in this article (e.g.  in section https://docs.microsoft.com/en-us/windows/deployment/windows-10-poc#in-this-guide) are using header's colors that does not render well in dark & high contrast themes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5fb2354-bc61-a5f7-3e73-456588847923
* Version Independent ID: 1825f737-8689-29b7-1ea2-b7a4d0c337fa
* Content: [Configure a test lab to deploy Windows 10 - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-poc?source=docs)
* Content Source: [windows/deployment/windows-10-poc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-poc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
I confirm this issue. The light blue table headers contain (normal) black text when the page is shown using the Light theme, but when switching to the Dark theme, the text is reversed to white on the same light blue background color, which is less than ideal to read for users without an extraordinary good eyesight (20/20 vision).

The recommended solution is to remove the background color and use only the page colors, only to be changed in the CSS for the site, instead of having colors defined anywhere in the individual page.

I can provide a PR to remove the light blue color, making the table title row follow the default page colors (black text on white background when using the Light theme, or white text on black background when using the Dark theme.

**Comment by RAJU2529** [comment]
I also confirmed

**Comment by illfated** [comment]
Thank you. I will do so.

**Comment by greg-lindsay** [comment]
Although I agree that the color isn't ideal for dark theme, this doesn't markedly compromise usability since the data inside the table is easily readable.  The color improves clarity for the light theme. So on balance it's a bit of a wash, except that the light them is much more frequently used (it is the default).  

I would argue that we should leave this alone. I like the appearance on the light theme, and users that prefer the dark them can still read the content, even though it is slightly difficult.

Alternatively, we can find a color that works on both themes, such as a light grey.  I'd rather not remove the color from the header entirely.

**Comment by shivtorov** [comment]
@greg-lindsay, I think this is the 1st article I see on docs.microsoft.com to use some custom colors. I don't think this is a good idea. All articles should use the same consistent style unless there is a very very strong reason for a custom design for a page element.

**Comment by shivtorov** [comment]
ouch, I see multiple articles in this repo are using some hard-coded custom colors and other hard-coded style changes :(

related: #5810

**Comment by greg-lindsay** [comment]
I'm not necessarily in agreement that it is important to downgrade formatting of tables so that it matches a bland styling present in other pages.  I don't want to make a huge issue of this, but I'd prefer that we leave this alone and not start making changes to fix things that aren't technical issues. The table renders fine with a colored header and I personally feel that it makes it more readable for most users. The choice of color does have some consequences for the dark theme and I can see a reason to adapt to this.

**Comment by greg-lindsay** [comment]
I found a fix and I'm pushing out a change to these docs so that dark theme doesn't have any issues.
