### ISSUE TITLE
download pdf link error

### ISSUE THREAD

**Issue by thiagobeier** [MicrosoftDocs/windows-itpro-docs#5880]
when the download pdf is loaded (you can access the PDF) and try the link https://www.youtube.com/embed/4k4hc5nchbe on page 7 under windows autopilot walkthrough ERROR: Video unavailable This video is unavailable. and at this current page the link for the walkthrough it's different (https://youtu.be/KYVptkpsOqs) the one generated on the PDF file 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aafc065-6ee6-e3cf-31ba-ab3dd277fb23
* Version Independent ID: 35d3102e-4ff7-9408-8dbd-513b7dfff5c0
* Content: [Windows Autopilot requirements - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements#feedback)
* Content Source: [windows/deployment/windows-autopilot/windows-autopilot-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/windows-autopilot-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
i create new PR  to  enable  video picture display on website

**Comment by RAJU2529** [comment]
@e0i , @illfated , Please review PR   #5946

**Comment by illfated** [comment]
https://www.youtube-nocookie.com/embed/KYVptkpsOqs works just fine for me, what is the problem?

**Comment by illfated** [comment]
https://youtu.be/KYVptkpsOqs works fine too, I don't see the problem or need for any changes in the page.

**Comment by illfated** [comment]
Oh. I see. @RAJU2529 : it looks like you have misunderstood the problem. The issue is _not_ the embedded video.
The problem seems to be inside some kind of Adobe Acrobat PDF file somewhere, but I can't find the PDF.

**Comment by illfated** [comment]
Correction: I found the PDF download link now. It is on your **bottom left on the page** (bottom of the CSS TOC index) where this issue was reported from, https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/windows-autopilot-requirements .

Direct link to the PDF file: https://opdhsblobprod04.blob.core.windows.net/contents/d0d41f25ce48460387a79ace64acad6b/589def0b5dfd0fccf1d7f1b4170edab5?sv=2015-04-05&sr=b&sig=KssaOkJtTJrlQTcq%2BlqGUIUTTw8Yqj3rk%2F%2Fgik4WdtM%3D&st=2020-01-28T14%3A39%3A51Z&se=2020-01-29T14%3A49%3A51Z&sp=r

**See upload below for the specific content of page 7:**
- [Windows Autopilot page 7.pdf](https://github.com/MicrosoftDocs/windows-itpro-docs/files/4122983/Windows.Autopilot.page.7.pdf)

**Comment by illfated** [comment]
The PDF says that the YouTube video link is supposed to be https://www.youtube.com/embed/4k4hc5nchbe , but that link does not work (removed or blocked). Heck, even https://www.youtube.com/watch?v=4k4hc5nchbe is not available due to incorrect link name.

**Comment by e0i** [comment]
@thiagobeier The content has been updated by community contributor @RAJU2529 according to your feedback. Thank you all, for your contributions.
