### ISSUE TITLE
1909 missing

### ISSUE THREAD

**Issue by beerisgood** [MicrosoftDocs/windows-itpro-docs#5930]
Where are the infos for build 1909?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611b03b8-c215-0f34-c739-7f4bc7fcf51e
* Version Independent ID: 695ca891-bf89-82df-a9a8-90e598512c96
* Content: [Windows 10, version 1903, connection endpoints for non-Enterprise editions - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions#feedback)
* Content Source: [windows/privacy/windows-endpoints-1903-non-enterprise-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/windows-endpoints-1903-non-enterprise-editions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @MikeEdgar
* Microsoft Alias: **v-medgar**

**Comment by RAJU2529** [comment]
might be the same as 1903

**Comment by beerisgood** [comment]
Problem still not fixed.

**Comment by illfated** [comment]
Looks like the 1909 page for **Enterprise** is missing too, so there is probably a long list of things to verify before publishing those 2 pages.

See also issue ticket [**Multiple small updates**](https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5899) **#5899** for details.

**Comment by medgarmedgar** [comment]
We didn't publish the docs for 1909 since it was an incremental update to 1903 and no new egress traffic was discovered.

**Comment by beerisgood** [comment]
Fair enough but this should then written somewhere as we users doesn't know the changes.

**Comment by illfated** [comment]
You mean something like "For 1909, see 1903." ?

**Comment by beerisgood** [comment]
> 
> 
> You mean something like "For 1909, see 1903." ?

For example, yes :)

**Comment by medgarmedgar** [comment]
Sorry, I see now that this question is about the lack of 1909 "raw" traffic article and not the Restricted Traffic settings main article. Let me address these various points:

1. There was not 1909 "raw" traffic endpoint article created since there were no new endpoints discovered.  So, the 1903 "raw" traffic article is applicable to the 1909 release as well.  The primary reason for this is that the 1909 release was primarily 1903 with some KBs and some limited but net new features (that didn't generate any new "raw" traffic).  By "raw" I mean the device is in it's default configuration, and hasn't been configured for Restricted Traffic in any way.

2. Yes, the 1903 settings can be used on 1909 devices. 

3. Yes, it would have been better to explicitly state in the 1903 'raw" traffic article that it is also applicable to 1909.  I will take this as an update to do.

4. Also, a note should be added to the "main" article that the downloadable 1903 script/settings can be used on 1909 devices. The readme in the .zip downloadable file should also state this, even though, the "main" article does state that the settings listed are applicable to "1607 and newer". 

By "main article" I mean this one: 
https://docs.microsoft.com/en-us/windows/privacy/manage-connections-from-windows-operating-system-components-to-microsoft-services

**Comment by illfated** [comment]
Thank you very much for the authoritative reply comment. I haven't looked into how the page can be updated, but I may do so in a few days' time.

**Comment by e0i** [comment]
@medgarmedgar

Your comments and suggestions are being passed to and independent contributor for revisions. Thank you.
