### ISSUE TITLE
Variations between Windows Versions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#5960]
How do these features vary for the different release versions of Windows 10? i.e, what should we expect to get or not get when an endpoint is running 1909 vs 1803?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a64c5-bdea-ae9f-578e-a785bca20d23
* Version Independent ID: b521d32a-cf9f-8b6a-0411-fd77537673e1
* Content: [Overview of endpoint detection and response capabilities - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/overview-endpoint-detection-response.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MaratMussabekov** [comment]
Hello @DeanGross ,
some of the response actions depend on the Windows version, more details are in the appropriate articles: 
[Take response actions on a machine](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/respond-machine-alerts)
[Take response actions on a file](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/respond-file-alerts)

Live response is available [since 1903](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/live-response)

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
