### ISSUE TITLE
Standalone package SCCM OSD deployment information

### ISSUE THREAD

**Issue by randomman87** [MicrosoftDocs/windows-itpro-docs#5999]
The Surface UEFI Configurator states it is deployable but throws a 1603 error when deployed in a task sequence. From TechNet forum search this appears to be because the task sequence runs it as the SYSTEM account. Some clarification on how to install this during SCCM OSD Task Sequence would be nice.

**Comment by e0i** [comment]
Hello, @randomman87 

thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
