### ISSUE TITLE
What defines machine inactivity?

### ISSUE THREAD

**Issue by mbenford21** [MicrosoftDocs/windows-itpro-docs#6007]
I have users with this policy set.  However, the time limit passes and the screen does not lock.  What determines when the inactivity period starts?

**Comment by denisebmsft** [comment]
Hello @mbenford21, can you tell us which article your question is about? It will help us route this to the correct writer. Thanks!

**Comment by e0i** [comment]
Hello, @mbenford21  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
