### ISSUE TITLE
When will the new Edge Chromium browser be supported?

### ISSUE THREAD

**Issue by avbski12** [MicrosoftDocs/windows-itpro-docs#6044]
As an enlightened app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @avbski12 thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
