### ISSUE TITLE
Support for Adobe Reader

### ISSUE THREAD

**Issue by avbski12** [MicrosoftDocs/windows-itpro-docs#6045]
Will Adobe Acrobat Reader ever be an enlightened app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ed0150-0172-f3ad-3c7f-3a7141efbe64
* Version Independent ID: 6a978d2b-a0ff-1052-ce00-06f02f30cfa1
* Content: [List of enlightened Microsoft apps for use with Windows Information Protection (WIP) (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip#feedback)
* Content Source: [windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/enlightened-microsoft-apps-and-wip.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@avbski12 

The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
