### ISSUE TITLE
how to convert PowerButtonTimestamp to a datetime object

### ISSUE THREAD

**Issue by ricofox959** [MicrosoftDocs/windows-itpro-docs#6046]
Any tips on how to convert PowerButtonTimestamp to a DateTime object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da13b68-67f7-a360-4e63-078dc0d275d5
* Version Independent ID: 55998351-042c-ce92-841f-5023e3cff5af
* Content: [Advanced troubleshooting for Event ID 41 - ](https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-event-id-41-restart)
* Content Source: [windows/client-management/troubleshoot-event-id-41-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/troubleshoot-event-id-41-restart.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by e0i** [comment]
Hello, @ricofox959  thank you for providing feedback.

Note that the feedback section you have submitted this feedback from is intended for product documentation issues only.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks again.
