### ISSUE TITLE
Is it slash or back-slash?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windows-itpro-docs#6082]
I keep seeing documentation casually flip between slash / and back-slash \ for URI segment separation. Why the inconsistency?

Or are these trying to teach us they are interchangeable? So I can write a URI as
.\Device\vendor\MSFT/Policy/Config/AppVirtualization/WhatSoEverILike ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d3e3340-f744-af16-bfd2-3964d585e1e1
* Version Independent ID: dd074932-c941-ce52-29ce-1ec637fda651
* Content: [Understanding ADMX-backed policies - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies)
* Content Source: [windows/client-management/mdm/understanding-admx-backed-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/understanding-admx-backed-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looking at the origin of the page here on GitHub, https://github.com/MicrosoftDocs/windows-itpro-docs/commit/18332f30c4e062bbf34d2f98ac4af57511275b01#diff-de48785b7f39aee16f534acabf2adff8 (commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/18332f30c4e062bbf34d2f98ac4af57511275b01), it looks like the originating document had this impractical duplicity too.

Browsing different web pages concerning the URI general format, there seems to be a standard to use (forward) slash throughout as URI segment separators, whereas referenced Registry keys and UNC file paths use backslash. See also some useful comments in https://stackoverflow.com/questions/1589930/so-what-is-the-right-direction-of-the-paths-slash-or-under-windows as well as noting that the document RFC (Request for Comments) 1738 classifies backslash ( ` \ ` ) as an unsafe character because it might be translated during network transport. Also note that backslash is often used as an escape character in many coding languages, as well as being used as a comment separation character.

**Comment by icelava** [comment]
I believe the LocURI element being string data should not interfere with a programming language's use of \ as an escape character since it's not typed out literal in source code. Unless there're further processing rules I'm not aware of in SyncML or OMA that defines \ with special meaning.

**Comment by illfated** [comment]
Fair enough. I can only refer to external documentation, so it would be nice to hear from one of the authors or technical writers regarding this content, whether it should be kept more consistent by using only the slash character as as URI segment separator, except for in file/UNC paths & registry strings.

@e0i or @mypil : may I ask for this question to be passed to one of the team members who knows this topic and to confirm the correct type of URI segment separator?

**Comment by e0i** [comment]
@JohanFreelancer9 @nenonix 

Looping in so that maybe you can answer this question in terms of Style Guide and documentation standards. Thank you.

**Comment by JohanFreelancer9** [comment]
@e0i Unfortunately I cannot be of much help. I am not aware of any clear standards and the Style Guide is also not very helpful. Like @illfated, I can also only refer to external documentation.

**Comment by e0i** [comment]
Closing via merged PR #6805. Thank you for the feedback.
