### ISSUE TITLE
[LOC] "両面" needs to be replaced with "2" (re-open issue: #4047)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#6128]
re-open issue: #4047

ja-jp:https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/includes/do-not-sync-include
do-not-sync-include_j
![59576280-2e07d600-90fa-11e9-983d-dde4a0d05d7c_2](https://user-images.githubusercontent.com/40815708/75435024-c5197300-5995-11ea-8bd1-81a2914c6c22.png)

en-us:https://docs.microsoft.com/en-us/microsoft-edge/deploy/includes/do-not-sync-include
do-not-sync-include_e
![59576288-33652080-90fa-11e9-8d38-cd36cb068594_2](https://user-images.githubusercontent.com/40815708/75435040-cba7ea80-5995-11ea-8ae6-c6ec0ee204d1.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 50bec5eb-91c4-370c-afeb-eb20fa884b49
* Version Independent ID: 929bbc78-a013-f04e-9a32-19f3f120c2ad
* Content: [サポートされる値](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/includes/do-not-sync-include)
* Content Source: [browsers/edge/includes/do-not-sync-include.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/includes/do-not-sync-include.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by illfated** [comment]
@hyoshioka0128 : As @TinaMcN mentioned in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/4047#issuecomment-594700546 , this issue seems to be resolved in https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/includes/do-not-sync-include (may I ask you please to confirm this as well?).

If you are happy with the changes, you are of course free to close this issue ticket as well, at your discretion.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #6128.
Thanks.
