### ISSUE TITLE
mbr2gpt fails to detect OS if WinRE disabled

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/windows-itpro-docs#6182]
If WinRE is disabled on the machine, mbr2gpt will fail to find the OS partition, even if the disk is specified. 

There is an excellent write up of the issue here: https://medium.com/@revanmj/one-way-to-fix-mbr2gpt-cannot-find-os-partition-33631dfd9f5e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73c22f0-cb0d-e34b-29d8-06829b86784f
* Version Independent ID: 083115ed-f1be-e962-5b0e-5079dec37353
* Content: [MBR2GPT - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/mbr-to-gpt#feedback)
* Content Source: [windows/deployment/mbr-to-gpt.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/mbr-to-gpt.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
Hello, @iUnknwn  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
