### ISSUE TITLE
Provider GUID for FIDO2 security keys

### ISSUE THREAD

**Issue by MaximeRastello** [MicrosoftDocs/windows-itpro-docs#6189]
Having Multifactor Unlock enabled prevents the use of security keys for authentication on Hybrid Azure AD Join devices (preview).
Could you please update the documentation to include the correct GUID for security keys?
Here it is: {F8A1793B-7873-4046-B2A7-1F318747F427}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f8c2ce-8edb-60d3-ebf9-bdb625bf66dc
* Version Independent ID: ee1ed0a8-b05c-c499-6504-40b5b298c53b
* Content: [Multifactor Unlock - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock)
* Content Source: [windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/feature-multifactor-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
@MaximeRastello is your feedback that you want security keys to work with the Multifactor unlock feature or that multifactor unlock breaks logon with security keys with DJ++? I am confused because you asked to add the security key cred prov GUID to the multifactor unlock documentation which implies it should be listed as a configurable option. Today these two features are completely separate.

**Comment by Matt-C22** [comment]
@MaximeRastello You can't use it under the first unlock factor or even second. It is a separate sign-in feature, which satisfies both unlock factors, meaning you won't need to use anything else other than your FIDO2 PIN and have your security key plugged in.

However, what I've achieved in my deployments, I've used the same Device Configuration Profile that has the OMA URIs for both multifactor unlock (this article) and also FIDO2.

To be able to use it, you will need first to deploy the feature using this article:
https://docs.microsoft.com/bs-latn-ba/azure/active-directory/authentication/howto-authentication-passwordless-security-key#prepare-devices-for-preview

After which you can deploy the sign-in option via Intune:
https://docs.microsoft.com/bs-latn-ba/azure/active-directory/authentication/howto-authentication-passwordless-security-key-windows#enable-security-keys-for-windows-sign-in

During the deployment phase via Intune, instead of using a new Profile, just add the OMA-uri and its value under the same profile configured for W10 multi-factor unlock.

Cheers

**Comment by mypil** [comment]
@MaximeRastello - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by mapalko and Matt-C22 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mortyobnoxious** [comment]
@MaximeRastello Hi, how is it being a racist?
https://twitter.com/emrahsamdan/status/1322613752525692931
