### ISSUE TITLE
How to apply license

### ISSUE THREAD

**Issue by infinitedreams9586** [MicrosoftDocs/windows-itpro-docs#621]
How to apply Office License using this CSP ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86aba37-9069-3d7c-28ec-45116320c0b9
* Version Independent ID: 613681db-84f0-6eed-4826-fa11be9ceb49
* Content: [Office CSP](https://docs.microsoft.com/en-us/windows/client-management/mdm/office-csp)
* Content Source: [windows/client-management/mdm/office-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/client-management/mdm/office-csp.md)
* Service: **unspecified**
* GitHub Login: @nickbrower
* Microsoft Alias: **maricia**

**Comment by shortpatti** [comment]
@MariciaAlforque -- Can you take a look at this issue?

**Comment by Tulkku** [comment]
How do I use this with Microsoft Intune?

**Comment by egallagh** [comment]
@infinitedreams9586 Licensing of Office 365 applications is performed within the Office 365 admin portal and licenses are then associated with user accounts. In order to have an installed Office 365 application suites become activated in association with one of the licenses, the suite needs to be associated with a user account by entering the user credentials (Office 365 ID and password) of the user. When an Office 365 application is started on a system where the Office 365 suite has not been activated, the Office application with prompt for the user credentials for activation.

**Comment by egallagh** [comment]
@Tulkku The configuration service provider pertains only to Office 365 and not to Intune.

**Comment by mypil** [comment]
@infinitedreams9586 and @Tulkku - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
