### ISSUE TITLE
Please add to 365 business

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/windows-itpro-docs#6215]
365 business security postures suffers from the absence of this feature as a no or low cost add to normal 365 business licensing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
Hello, @gkens 

The issues section of this repository is intended for documentation and content related issues.

Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thank you.
