### ISSUE TITLE
Volume?

### ISSUE THREAD

**Issue by tom1stein** [MicrosoftDocs/windows-itpro-docs#6238]
Das Wort "Volume" bedeutet hier mitnichten "Lautstärke", sondern "Laufwerk" oder "Datenträger". Die vorhandene Übersetzung als Lautstärke ist eine Lachnummer.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f6b62a2-d4bf-f680-3cb8-f67769ab27c4
* Version Independent ID: 17c6e5c3-36cf-4bc8-5ff2-5a9527471012
* Content: [BitLocker-grundlegende Bereitstellung (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/de-de/windows/security/information-protection/bitlocker/bitlocker-basic-deployment#feedback)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-basic-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-basic-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
@TinaMcN Seems to be a localization issue via the Bing translation:

> The word "volume" here does not mean "volume" but "drive" or "disk". The existing translation as volume is a laughing stock.

**Comment by TinaMcN** [comment]
@tom1stein Vielen Dank, dass Sie das Problem gemeldet haben, das durch ein Problem mit maschineller Übersetzung verursacht wird.  Wir werden den Artikel Mensch übersetzt bekommen.  Ich werde den Fehler auch dem Team für maschinelles Übersetzungstool melden.  (Thank you for reporting the issue which is caused by a machine translation problem.  We will get the article human translated.  I will also report the bug to the machine translation tool team.)   @OfficeGlobal, please human translate the article.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by e0i** [comment]
@OfficeGlobal Any updates on this?

**Comment by TinaMcN** [comment]
@tom1stein Der Artikel wird nun von einem Menschen übersetzt.  Können Sie bitte überprüfen, ob das Problem jetzt behoben ist?

**Comment by illfated** [comment]
The document seems to be correctly updated, there are no more occurrences of "Lautstärke". 
Words used in this document are either "Laufwerk" or "Datenträger" in various forms (standalone or compound words).
