### ISSUE TITLE
There is no edit option in French article

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6272]
I want to replace the incorrect word to correct word.
But I failed to do so. because there is no EDIT option in french translated article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ae3a36-8282-abf0-a355-0fa02ff21308
* Version Independent ID: da7bb5f7-78a4-594f-7a7d-db096928a89e
* Content: [Configure security policy settings (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings)
* Content Source: [windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
@RAJU2529 : That is entirely correct. The link button [Edit This Document] is only available on the English (en-us) pages. This is by design and is intentional.  Microsoft has decided not to give us ordinary users access to the localized material just yet.

You may ask "Why?" and I completely understand you. I also asked why a couple of years ago.
One reason is that many of the localized pages are translated by Machine Translation, and therefore do not contain static page content for editing.
If you would like to see a non-English page corrected, you report it directly from the correct language page
(for example, in this instance, https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings).

Please also note the text at the top of the page when you visit the French page:
- **( i ) Certaines parties de cette rubrique sont traduites automatiquement.**

**Comment by illfated** [comment]
Just in case I wrote too much in my previous comment (TL;DR):
Go to the French page, open a ticket at the bottom of the page 
(https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings#feedback)
and post a new ticket there to tell Microsoft Docs about it.

The localization team will take care of it.

**Comment by illfated** [comment]
#please-close

**Comment by RAJU2529** [comment]
@illfated . i already commented in french article yesterday itself. I think, one of the  team member  told to give  a feedback in english article ,so that the  translator can see the feedback he might fix it , so  i wrote here.

**Comment by illfated** [comment]
OK, very well. Fair enough. I did not know that this ticket was recommended by the team. It looks like there is some kind of trouble to view any of the existing feedback tickets in the French page, so I guess it is OK to keep this ticket open until further notice.

Would you be able to tell me about the sentence in the French article where you found the incorrect word?

**Comment by RAJU2529** [comment]
@illfated . Here is the french article site address

**https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings**

actually  secpol.msc   is  given gap between .  and msc 
below paragraph 
Pour ouvrir la stratégie de sécurité locale, dans l’écran d' Accueil , tapez **secpol. msc**, puis appuyez sur entrée.

**Comment by illfated** [comment]
Yes, I think we have seen something similar before, also regarding French & German pages. The direct link to the section you are reporting is as follows:
https://docs.microsoft.com/fr-fr/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings#pour-configurer-un-paramètre-à-laide-de-la-console-de-stratégie-de-sécurité-localeto-configure-a-setting-using-the-local-security-policy-console
***

## Pour configurer un paramètre à l’aide de la console de stratégie de sécurité locale
1. Pour ouvrir la stratégie de sécurité locale, dans l’écran d' **Accueil** , tapez **secpol. msc**, puis appuyez sur entrée.
2. Sous paramètres de sécurité de l’arborescence de la console, effectuez l’une des opérations suivantes:

***
But the problem is much bigger than the word you noticed. There are quite a few spacing issues throughout the page, both excessive (wrongly inserted) and lack of spacing (missing space between words). There are also some odd formatting, like some phrases consisting of 2 words, but only the second word is formatted in **bold**, instead of the whole phrase.

@TinaMcN : Would you mind taking a look at this, unless you are preoccupied in these trying times?
I see now that @RAJU2529 had to report this French page issue here, because it looks like there is 
a loading issue for the Feedback section at the end of the French version of the page.

**Comment by TinaMcN** [comment]
@OfficeGlobal please human translate this page and ensure the space in "secpol. msc" is removed.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by illfated** [comment]
Thank you for the update. @OfficeGlobal : Have you noticed the other spacing issues in the page as well, or do you prefer that we provide samples of those translation-related spacing issues?

**Comment by e0i** [comment]
Manually confirmed to be fixed. Thank you, all.

**Comment by illfated** [comment]
Sure, the specific issue is fixed, **secpol.msc** . I presume you need new tickets for the remaining spacing issues.

**Comment by TinaMcN** [comment]
@OfficeGlobal can you please check again this French article.   There are 3 instances of this text segment where I believe there should be a space between "utilisateur" and "ou".   Please check the whole article for any missing or extra spaces.
![image](https://user-images.githubusercontent.com/53281468/81597905-4a001000-937b-11ea-879f-df00d8416f88.png)
