### ISSUE TITLE
Just now created PR 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6286]
Author please review my PR #6285

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb5cd998-7919-6eb6-8198-0c3e90d76c56
* Version Independent ID: 4e9c7668-62f6-912d-5354-bff400f591ac
* Content: [Microsoft Security Compliance Toolkit 1.0 Guide - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-configuration-framework/security-compliance-toolkit-10)
* Content Source: [windows/security/threat-protection/windows-security-configuration-framework/security-compliance-toolkit-10.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-security-configuration-framework/security-compliance-toolkit-10.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@illfated .@e0i  . Please review PR #6285 .

**https://github.com/MicrosoftDocs/windows-itpro-docs/pull/6285**

**Comment by illfated** [comment]
Thank you for properly starting a new issue ticket to reference your PR with your recommended changes to this document.  That in itself is the proper way to go about unreported issues, especially if you are going to create a pull request to resolve the issue at hand.

What I am hoping for you to learn more about, as you progress in your work here in these Microsoft repositories, is to discover that there is a format and code style (although not broadcast or published particularly well for all users to be discovered. This is more of a general code style that you may need to learn as time goes by and you see what others use to describe their issue tickets and pull requests.

Anyway, since I have already suggested an improvement to your PR title, I would like to suggest an improvement to this issue ticket title as well.

Suggestion:

**Microsoft Security Compliance Toolkit 1.0 : versions missing in the Security Baselines lists**

**Comment by e0i** [comment]
@RAJU2529 Please do not create blank issues to draw attention to Pull Requests.
