### ISSUE TITLE
Endpoint list is different from the /en-us version

### ISSUE THREAD

**Issue by brutesquad** [MicrosoftDocs/windows-itpro-docs#6348]
On this page, under Windows 10 Education,  it lists:
insiderppe.cloudapp.net/windows-app-web-link    as an endpoint

The US-EN  version of this page does not list this link as a valid endpoint:
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1809-non-enterprise-editions

The domain  insiderppe.cloudapp.net  does not seem to resolve, so I assume the ga-ie version is incorrect?

---
#### Sonraí doiciméid

⚠ *Ná cuir an rannán seo in eagar. Tá sé riachtanach le haghaidh docs.microsoft.com ➟ nascadh fadhbanna GitHub.*

* ID: a536a609-8ee6-5ac4-9fd1-d8d459fedfd9
* Version Independent ID: ac6433b8-548c-4876-088f-088eea5c48e1
* Content: [Windows 10, leagan 1809, críochphointí naisc um eagráin neamh-Enterprise - Windows Privacy](https://docs.microsoft.com/ga-ie/windows/privacy/windows-endpoints-1809-non-enterprise-editions#feedback)
* Content Source: [windows/privacy/windows-endpoints-1809-non-enterprise-editions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/windows-endpoints-1809-non-enterprise-editions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@brutesquad - Thank you for submitting feedback.

I will get this issue over to the Win10 ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TinaMcN - This appears to be a Translation/Localization issue since the en-us version of the Doc (https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1809-non-enterprise-editions) shows _maps.windows.com/windows-app-web-link_ as the endpoint for the Link to Maps application as shown below:

![image](https://user-images.githubusercontent.com/47188252/77831209-90234c00-710c-11ea-83b0-b9077ce2ab96.png)

But the (ga-ie) version shows _insiderppe.cloudapp.net/windows-app-web-link_ for the same Description as shown below:

![image](https://user-images.githubusercontent.com/47188252/77831231-b34dfb80-710c-11ea-8af3-f5ea23cf91c8.png)


Can you please share your insights on how we could resolve this issue? 

Thank you.

cc: @kenwith

**Comment by TinaMcN** [comment]
@brutesquad thank you for reporting this (go raibh maith agat).  @OfficeGlobal, this issue is tracked in bug#14169 which I know you are already working on.  Please let us know when the Irish page is fixed.

**Comment by OfficeGlobal** [comment]
@brutesquad , @TinaMcN the issue was fixed and article republished

**Comment by mypil** [comment]
@brutesquad - From our understanding, the issue has been resolved.


Thank you for your contribution to make the docs better! Much appreciated!
