### ISSUE TITLE
Inactive machine list

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/windows-itpro-docs#6369]
How to remove machines that are inactive from the list? We have deleted the machine from our environment and it is now listed in inactive machines list. How to remove them so that it will not appear in Defender ATP portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e07681-222a-ca3c-20f3-c98dabd935fa
* Version Independent ID: 6a9262d1-911f-bd4b-5366-7e6a0e31ca13
* Content: [Fix unhealthy sensors in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/fix-unhealthy-sensors)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/fix-unhealthy-sensors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/fix-unhealthy-sensors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
