### ISSUE TITLE
Title name is different.

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6382]
Title name is different from the article website address.
In site address, says microsoft compatible security keys.
But the article described about what is microsoft security key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacf4c87-5c77-1d03-0c60-bc608fabe2f8
* Version Independent ID: 70d65968-6f5e-8013-0b0b-6d5d660969e0
* Content: [Microsoft-compatible security key - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
@mapalko : The page this issue is opened from, **Microsoft-compatible security key - Microsoft 365 Security** (https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key) does not seem to have a highlighted link in the index page on the left, in addition to having a page title different from the HTML title text:
- Title visible on the page: **What is a Microsoft-compatible security key?**
- HTML page title: **Microsoft-compatible security key - Microsoft 365 Security**

Is this set of pages (including the Windows Hello for Business page index on the left) a work in progress?

**Comment by joinimran** [comment]
Hello @RAJU2529 - Thank you for your feedback. As per my investigation, this is not necessary to add words like what, is, a, and any more other like these in the URL. The content is same and full SEO optimized so we are good with this. There are thousands of other pages having same pattren.

@e0i FYI please.

**Comment by RAJU2529** [comment]
@joinimran. Thanks for your reply. I keep waiting for  others users feedback also

**Comment by illfated** [comment]
@RAJU2529 : I presume that the comment from Imran Habib is meant to tell us that many, many pages use the same pattern as this page, that there is a difference between the page title and the tab title ("website address"), which should be OK in the MS Docs pages. The conclusion I draw from his comment is that this is not an issue we need to do anything about, unless the Microsoft Documentation team decides to implement a more strict rule regarding the similarity between the page title and the page URL name. I also presume this means that this ticket is OK to close, unless you can provide any documentation showing that it needs to be changed.

**Comment by RAJU2529** [comment]
@illfated . @joinimran . Thanks for the feedback. I am closing this issue
