### ISSUE TITLE
Emulator 2 and DirectX 12

### ISSUE THREAD

**Issue by IvanGitH** [MicrosoftDocs/windows-itpro-docs#6414]
The emulator does not run the native DirectX 12 template App !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91011c3c-a047-926b-058b-dad6c68de528
* Version Independent ID: a1254343-5378-fdab-ba8f-202358a28ff4
* Content: [HoloLens release notes](https://docs.microsoft.com/en-us/hololens/hololens-release-notes)
* Content Source: [devices/hololens/hololens-release-notes.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/hololens/hololens-release-notes.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by e0i** [comment]
The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
