### ISSUE TITLE
Auto MDM Enroll: Device Credential (0x1), Failed (Unknown Win32 Error code: 0x80180001)

### ISSUE THREAD

**Issue by PaulEstevesAtPEX** [MicrosoftDocs/windows-itpro-docs#6437]
When looking in the DeviceManagement-Enterprise-Diagnostics-Provider Admin event viewer logs I find Event ID 76:
Auto MDM Enroll: Device Credential (0x1), Failed (Unknown Win32 Error code: 0x80180001)

This is for a hybrid AD environment on a locally joined machine that does show the Azure Devices as 'Hybrid Azure AD joined'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.
