### ISSUE TITLE
Support for Windows Server 2016  and 2019

### ISSUE THREAD

**Issue by VAnjan12** [MicrosoftDocs/windows-itpro-docs#6453]
Hello,

will this Web Content Filtering supports Windows Server operating systems like 2016 and 2019?

Thanks in Advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
While I don't know the specific answer to your question, since I am not a Microsoft employee and not familiar with all the details of Microsoft Defender ATP, I would still like to question your scenario if you expose a Windows Server 2016 or 2019 to the plethora of threats from personal browser usage on a server computer. Based on my general understanding of the server role, I would assume that the main goal of Microsoft Defender ATP is to provide a threat protection for domain member computers with regular users logged in to Windows 10. I would also assume that it is the responsibility of local administrator(s) to protect and manage servers to avoid personal browser usage on the server(s).

Could you describe your scenario where it would be practical to manage servers as if they were domain computers by applying policies and threat mitigation on the same level as the regular computers?

**Comment by SteveBurkettNZ** [comment]
@illfated;  How about RDS/terminal servers.

**Comment by illfated** [comment]
OK, fair enough. I have not worked in that kind of scenario, so my mind did not go there.
Maybe we could ask the current author where to look for some practical answers.
@e0i : Would you be so kind as to forward the question to someone who could point us in the right direction?

**Comment by levinec** [comment]
Hi @VAnjan12. The short answer is yes, Web Content Filtering will work in Windows Server operating systems, but only through the Microsoft Edge browser, **not** through third-party browsers such as Firefox or Chrome.

Web Content Filtering uses the Network Protection client to perform blocks for third-party browsers like Firefox and Chrome. The Network Protection client doesn’t support blocking in Windows Server, so Web Content Filtering will not work with third-party browsers in Windows Server.

In Microsoft Edge, blocking is performed through SmartScreen, which will support all web protection features (including Web Content Filtering).  If you require Web Content Filtering on your server, you can limit users to Microsoft Edge.
