### ISSUE TITLE
Caveat

### ISSUE THREAD

**Issue by konrag** [MicrosoftDocs/windows-itpro-docs#647]
I was unfamiliar with setting up DFSR so this guide was a big help. However, I was having lots of weird issues with the read-only site afterward. I kept thinking that my Bootstrap and CustomSettings were incorrect, but it was actually because DFSR wasn't replicating some files. That turned out to be because deduplication was enabled on that drive and was reparsing files and DFSR was ignoring them...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb440d06-32d1-c982-7736-0588cb4d8718
* Version Independent ID: 37cfa729-ee6d-3af4-dbbd-547797e37397
* Content: [Build a distributed environment for Windows 10 deployment (Windows 10)](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment)
* Content Source: [windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/build-a-distributed-environment-for-windows-10-deployment.md)
* Service: **unspecified**
* GitHub Login: @mtniehaus
* Microsoft Alias: **greglin**

**Comment by DaniHalfin** [comment]
Hi @konrag, thanks for bringing this to our attention. We're now looking at possible ways to highlight DFS-R use cases in more detail for this topic. 
We'll update when we have something to share.

**Comment by nedpyle** [comment]
Hi. DFSR supports replicating with (Windows Server) deduplicated files - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc773238(v%3dws.10). Can you explain a bit more about what you are seeing and where it intersects with DFSR.

I am going to warn you know that troubleshooting this is likely to need a support case, so I will answer as far as I can, but if we start needing a few GB of logs to look at, you will be redirected. :) 

- Ned

**Comment by nedpyle** [comment]
No worries. I’ll chat with some MDT folks here and see if they have seen anything similar. If you run into this again in the meantime don’t hesitate to let me know.

NP | PM

**Comment by Aenea42** [comment]
Hello all,

I stumbled into this post after a lot of searching to solve my own DFS issues (that are exactly the same as konrag explained above).
Considering that he is unable to troubleshoot this issue further, maybe I can provide the needed troubleshooting information. If you are still interested in troubleshooting this issue of course?

I have 2 file servers (2012R2) in different sites (with dedup active on both servers) and konrag explained the problem to the letter.
fsutil usn readdata returnes 0x620 (REPARSE_POINT, SPARSE_FILE, and ARCHIVE)
fsutil usn readdata returnes reparse tag of 0x80000013
In Event Log is DFSR Event ID 4406 logged (The DFS Replication service encountered an unsupported reparse point in a replicated folder. This reparse point will not be replicated because the replication of this type of reparse point is not supported by the DFS Replication service.)

Does anyone have any idea where to look further?
Similar to konrag, I used up all my DFS knowledge at this point, which is 90% based on Ned's blog posts anyway. :)

Best regards,
Aenea
