### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ddebald** [MicrosoftDocs/windows-itpro-docs#6475]
I'm backing up my projects to an external drive and "time remaining" is MORE THAN A DAY.  Every couple of seconds I get a notification that my administrator requires a security scan of this item (typical MS notification...what item? but that's another rant) and the file copy stalls.  Block at first sight is a good idea but you really ought to work out the kinks before dropping it onto my PC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus#feedback)
* Content Source: [windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-antivirus/configure-block-at-first-sight-windows-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
@ddebald : Looks like you should try a different approach for your backup methods, unless you prefer to disable the feature. If you want the feature enabled, and if it interferes with your current backup method (which I presume is manual file/folder copy in the Windows UI), I suggest looking for some dedicated backup software to avoid having every byte scanned before being written to the backup media. Whether the backup solution uses protocol tunneling or virtualized methods like sandboxing or memory separation, whatever works for you is your choice.

Anyway, your comment looks more directed towards developers than improving the documentation pages. I suggest using the Feedback Hub or similar to address the developers.

**Comment by e0i** [comment]
It seems that your question has been answered by the community and the issue is being marked as resolved. 

Please note that the issues section of this repository is intended for documentation feedback.

Should you have any further issues similar to this one, please consider opening a ticket here:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Feel free to re-open this issue if you feel that there are further suggestions to improve the documentation itself.

Thank you, and stay healthy.
