### ISSUE TITLE
Biometrics Assurance.

### ISSUE THREAD

**Issue by BartJocque** [MicrosoftDocs/windows-itpro-docs#6493]
Hello,
Do the published biometric assurance levels remain unchanged after the findings of Talos' Security group ? ( https://arstechnica.com/information-technology/2020/04/attackers-can-bypass-fingerprint-authentication-with-an-80-success-rate/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c4b7fc-8a91-5d34-d483-f644c248ad30
* Version Independent ID: 1f14bf28-71e0-121d-7890-c2d3b921c106
* Content: [Windows Hello biometrics in the enterprise (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise#feedback)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-biometrics-in-enterprise.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by nam31** [comment]
@BartJocque  

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

The issues section of this repository is being used to track problems related to the documentation articles.

Thank you.
