### ISSUE TITLE
What is meant by Work Protection

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windows-itpro-docs#6518]
Please provide a technical description of the type of protection that is meant by the phrase "the device enforces work protection for any file with the label". Is this encryption or something else? What happens when a General label is applied that does not require protection? Please provide additional details about what WIP does for the various Sensitivity Label settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561d91d8-458d-bc0c-45af-c0a9ccacee93
* Version Independent ID: 7c1fd8f1-74b6-f7d4-fcb0-0e41a0d6ff42
* Content: [How Windows Information Protection (WIP) protects files with a sensitivity label (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels)
* Content Source: [windows/security/information-protection/windows-information-protection/how-wip-works-with-labels.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/how-wip-works-with-labels.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@DeanGross . I think restricting certain users for accessing files and folders 
applying policies to the machine and to users  by using the group policy editor
configuring security policies through secpol.msc.

**Comment by e0i** [comment]
@DeanGross Passing this to an independent contributor for investigation. Thank you.

**Comment by VLG17** [comment]
@DeanGross I could not find the mentioned sentence "the device enforces work protection for any file with the label" in the article you linked. I think that certain article might have been taken down in the meantime, because i cannot find any reference to it online.

Anyway, keeping in mind we are talking about Sensitivity Labels, i would say that work protection = encryption, content marking and oversharing protection (similar to AIP).

WIP is limited to specific endpoints, labels are not. If a document with a specific Sensitivity Label (with or without encryption) leaves your organisation, it will still inherit that Sensitivity Label and when opened, it will ask for what you have configured it to request. WIP does not do that or know how to do that, it will just guard the endpoint.

> What happens when a General label is applied that does not require protection? Please provide additional details about what WIP does for the various Sensitivity Label settings.

WIP uses EFS (Encrypting File System) encryption and Sensitivity labels use the Azure Rights Management service (Azure RMS) from Azure Information Protection. So one does not affect the other.
