### ISSUE TITLE
Redirect Exploit protection "Evaluation Package" link directly to right site

### ISSUE THREAD

**Issue by beerisgood** [MicrosoftDocs/windows-itpro-docs#6531]
The link on top "Evaluation Package" redirect to [Windows Defender Testground](https://demo.wd.microsoft.com/?ocid=cx-wddocs-testground) but it should directly redirect to [Exploit Protection](https://demo.wd.microsoft.com/Page/EP)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6713d1-d4da-6e3b-88b7-89879f0140f8
* Version Independent ID: 9f460ef5-ed19-9c74-fbc9-560724655b83
* Content: [Import, export, and deploy exploit protection configurations - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/import-export-exploit-protection-emet-xml)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/import-export-exploit-protection-emet-xml.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/import-export-exploit-protection-emet-xml.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by illfated** [comment]
That is a fair point, we would not want users to get sidetracked to visit other pages and maybe forget why they went to the currently linked page. I agree with your conclusion.

The XML file name on the page in question (https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/import-export-exploit-protection-emet-xml) seems to be incorrectly referenced, I think I will add the suggestion to correct that one as well:
> The Evaluation Package contains a sample configuration file (name ProcessMitigation-Selfhost-v4.xml that you can use to see how the XML structure looks.

The actual file name is simply `ProcessMitigation.xml` so I will suggest to use that name instead.

**Comment by beerisgood** [comment]
I also wonder if the "ProcessMitigation.xml" is up2date (new Chromium-Edge for example)

**Comment by illfated** [comment]
No idea. I only find time enough to follow up on these issue ticket pages and their reported pages. I am uncertain, because looking at the end-of-life date for EMET (July 31, 2018) and the up-to-date information regarding Microsoft Defender ATP, it is difficult to keep track so long as my daytime job does not offer much need for upscaled IT work. I only hope the page author may find time to shed some light on your question.

**Comment by illfated** [comment]
To sum up: There were 6 separate issues to resolve in that page:
1. https://aka.ms/mp7z2w `=>` https://demo.wd.microsoft.com/Page/EP
2. https://go.microsoft.com/fwlink/p/?linkid=2069559 `=>` `microsoft-defender-advanced-threat-protection.md` ("Applies to" text link, previously pointed to Windows 10 editions comparison PDF)
3. `ProcessMitigation-Selfhost-v4.xml` `=>` `ProcessMitigation.xml` (Selfhost v4)
4. https://technet.microsoft.com/library/cc731212.aspx `=>` https://docs.microsoft.com/previous-versions/windows/desktop/gpmc/group-policy-management-console-portal (permanent MSDN redirect, also pointed to an outdated Windows 8, Windows Server 2008 R2, Windows Server 2012 page)
5. https://msdn.microsoft.com/library/ee663280(v=vs.85).aspx `=>` https://docs.microsoft.com/en-us/windows/win32/srvnodes/group-policy (permanent redirect from MSDN, also landed 1 level above the correct page)
6. https://technet.microsoft.com/security/jj653751 `=>` https://support.microsoft.com/en-us/help/2458544/the-enhanced-mitigation-experience-toolkit (the outdated technet link redirects to https://www.microsoft.com/en-us/msrc?rtc=1 (**Microsoft Security Response Center**))

I notice that I got slightly stressed going back and forth between my PR and this ticket, so I had to make 2 supplemental corrections because of details I overlooked during my main PR commit edit session.
