### ISSUE TITLE
Windows 10 1909

### ISSUE THREAD

**Issue by holoholo808** [MicrosoftDocs/windows-itpro-docs#6545]
- Windows 10 1909
- All Networks - Network location - User can change location

When I change the network location from public to private, the UAC message appears. Bug or is there another setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27f2e95-068a-6568-113d-66b378a2f6fe
* Version Independent ID: 6c13ead4-d350-d64c-7d29-3a7e4358d9ea
* Content: [Network List Manager policies (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-list-manager-policies#feedback)
* Content Source: [windows/security/threat-protection/security-policy-settings/network-list-manager-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/network-list-manager-policies.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Depending on the computer Windows 10 edition and your existing user access level, I would not in general consider it to be a bug, unless your user account belongs to a computer administrator group. Notice that changing the network location to Private means that you are considering your local network to be safer than a public network connection and are therefore willing to set Windows Firewall to use less protection against local network access to your computer OS.

Could you provide a bit more details regarding your setup, configuration or scenario, so we may better understand under which circumstances this happens?

**Comment by holoholo808** [comment]
Sure, it's Windows 10 1909 Enterprise. The Users are Domain integrated users, not members of the administrators local group. 

I understand what happens we configured the firewall through group policies. We set a firewall setting we don't really like to enable in the public profile, private could be ok. I thought, sounds nice, then when the user need it he can change it by himself with the network profile...

**Comment by illfated** [comment]
OK, very well. We may want to ask one of the technical writers for more specific feedback or reference pointers to relevant documentation where this is described in detail.

For the moment being, I suggest that you may consider this UAC message to be just the way Windows 10 reacts to change. Unless this message is considered a problem and that you have previously had a working solution where this was not happening, I would advise to see this as a confirmation that you are doing something correct and that a missing UAC prompt can be seen as a security breach or security flaw on those computers where the dialog box does not appear.

**Comment by holoholo808** [comment]
I have also tested it on the Windows 10 1709 build, there it worked as a domain user without policy.

With Windows 10 1909 it doesn't work with or without policy anymore. So this policy doesn't really make sense. If I have to be an administrator for this change I don't need this policy. I have already the right for this change.

**Comment by illfated** [comment]
Fair enough, I see your point. Since I don't have access to any Enterprise licensed computers, I would recommend asking for feedback from someone in the know of this specific policy in the Enterprise scenario, in case that would be helpful to your question(s).

@mypil or @denisebmsft : Would you be able to forward the questions above to anyone in the team, or do you know of any specific forum for this topic?

**Comment by VLG17** [comment]
@holoholo808 Could you help with a few details so i understand this issue better?

> When I change the network location from public to private, the UAC message appears.

What UAC message? Could you share a printscreen?


> I have also tested it on the Windows 10 1709 build, there it worked as a domain user without policy.

What does it mean that it worked? You did not get the UAC pop-up when changing the network location from public to private?


> With Windows 10 1909 it doesn't work with or without policy anymore. So this policy doesn't really make sense

What do you mean with it doesn't work? Althoug you set the network location via policy, it does not stick, or what?

Thanks in advance for providing these answers in order to narrow down the issue.

Please also keep in mind that our goal is to identify if we need to change anything with the documentation that you've linked. Although we can do a best effort, the goal of solving a technical issue falls under the responsability of support.

**Comment by nam31** [comment]
@holoholo808 Please let us know if you still have any question regarding the issue you have raised initially.

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
