### ISSUE TITLE
Embedded Video is broken

### ISSUE THREAD

**Issue by jrjenk** [MicrosoftDocs/windows-itpro-docs#6560]
The embedded overview video appears to be leading a page that no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa7a534-0c88-a3b6-5b27-81d735779fad
* Version Independent ID: cf641b62-a2b2-54fb-d885-15c5d7200215
* Content: [Access the Microsoft Defender Advanced Threat Protection APIs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/apis-intro#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/apis-intro.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/apis-intro.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Hmm, that is odd. I have no problem at all playing that video. Could your issue be caused by one of your browser addons or a firewall issue at your end?
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/apis-intro

https://www.microsoft.com/en-us/videoplayer/embed/RE4d73M

[![Microsoft Defender ATP APIs](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/images/next-generation-windows-security-vision.png?raw=true)](https://www.microsoft.com/en-us/videoplayer/embed/RE4d73M)

Maybe the video breaks if you view the page through a localized page, which aims to translate the page from English (en-us) to your own locale?

**Comment by jrjenk** [comment]
Well, it seems it works for me now, so maybe it was a temporary issue.  What was odd was I was seeing a Microsoft generated 'Page not found' error, not a normal browser error like the URL was bad.  I was using Google Chrome at the time so perhaps there was a missing update or something and it has since been patched.  Thanks for taking a look.
