### ISSUE TITLE
Calling this API return 404 as not found

### ISSUE THREAD

**Issue by MrKragh** [MicrosoftDocs/windows-itpro-docs#6573]
Calling this API currently returns 404 (not found).
My URL and request are correct, if I for instance change the last part of the endpoint to "/alerts" I get the alerts for the correct machine.
I know that there is software installed that are listable (as they're presented in the software list on the webportal).
Any guess on how this could be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 966fa534-25be-a5e5-be9f-b63c1d1c4d9f
* Version Independent ID: 05efaf9b-d5cb-eaba-6cfb-a0f10ed22c8a
* Content: [Get installed software - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-installed-software#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/get-installed-software.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/get-installed-software.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thank you.
