### ISSUE TITLE
Recommend adding trouble shooting/verification steps to verify data connection 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#6620]
Need to add additional section that describes how user can verify data is being sent to event hub , one possible option would be to link to this tool with description of viewing events using https://github.com/paolosalvatori/ServiceBusExplorer or other similar tool. Or other quick method to check events are reaching event hub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1d8755-e166-b930-39c6-a5bff6e05720
* Version Independent ID: 0b23fb74-ed0b-b6ee-9d0c-8c73b614ee95
* Content: [Stream Microsoft Defender Advanced Threat Protection events to Azure Event Hubs - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-event-hub#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/raw-data-export-event-hub.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-event-hub.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by Reeced40** [comment]
@bledMS82 thank you for pointing this out. It looks like the article has been updated in the interim. Please check and let me know if you think anything else should be added.

**Comment by illfated** [comment]
@Reeced40 : if you look at the file history or blame view, you will notice that only 2 updates were made to this document since the ticket got opened:
- `[!INCLUDE Microsoft 365 Defender rebranding]` (the 'important' light blue note blob before "Applies to" at the top of the page)
- `machine -> device` / `Machine -> Device` (2 words changed in an unrelated sentence)

File history & blame view source:
- https://github.com/MicrosoftDocs/windows-itpro-docs/commits/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-event-hub.md
- https://github.com/MicrosoftDocs/windows-itpro-docs/blame/public/windows/security/threat-protection/microsoft-defender-atp/raw-data-export-event-hub.md

Based on this fact, I would recommend keeping the ticket open until a decision is reached for how to proceed with this issue and specific issue feedback is provided.

**Comment by bledMS82** [comment]
A section should be added for basic troubleshooting of the connection and verification that the setup was configured correctly .

**Comment by illfated** [comment]
> A section should be added for basic troubleshooting of the connection and verification that the setup was configured correctly .

Fair point. Feel free to suggest any similar examples you know of, if you feel like you got ideas about how it could look.

**Comment by bledMS82** [comment]
Some of the info from the Event Hub Docs would most likely be relevant and able to be linked or listed here ? Might need small modifications if it is meant for only Defender , 
https://docs.microsoft.com/en-us/azure/event-hubs/troubleshooting-guide

**Comment by illfated** [comment]
Thank you for the idea. Looks like something worth considering. It may take quite some time before I can get around to provide any preliminary work on it, I have a few cases already I need to finish before I can dig into this one. Hope one of the tech writers on the MS Docs team could have a look at this, maybe even the topic author or someone in their group.

F.Y.I. / disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I simply contribute in my spare time.

**Comment by illfated** [comment]
(ref. #8681 )

**Comment by illfated** [comment]
(also ref. closing commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/fcec01f319747143785c9850bd7171223c04a042)

**Comment by illfated** [comment]
#please-close

**Comment by nam31** [comment]
Closing via #8681 
Thanks
