### ISSUE TITLE
Add list of "common system folders" 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/windows-itpro-docs#6645]
In the line "The protected folders include common system folders" there is no explanation of what folders these are , please include link or list in doc 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a78241-106e-4b06-8c19-998d67617456
* Version Independent ID: bc47935a-7d45-120d-3c1e-dd0e1431ab7c
* Content: [Prevent ransomware and threats from encrypting and changing files - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/controlled-folders)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/controlled-folders.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/controlled-folders.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@bledMS82 . Recently i executing some files which are in continued in system32 folder.
i accessed below files, but controlled folder access is blocked to access
1. Chkdsk.exe 
2. Systeminfo.exe
3. Msconfig.exe

**Comment by beerisgood** [comment]
> @bledMS82 . Recently i executing some files which are in continued in system32 folder.
> i accessed below files, but controlled folder access is blocked to access
> 
> 1. Chkdsk.exe
> 2. Systeminfo.exe
> 3. Msconfig.exe

Is this expected behaviour? In my opinion windows internal processes should be whitelisted

**Comment by RAJU2529** [comment]
@beerisgood . It was blocked the accessing the files. .
Really i want to execute those flles, soi allowed in controlled folder access

**Comment by MaratMussabekov** [comment]
Dear @Sirkkuw, 
The list of default folders protected by protected folder access wasn't published anywhere in docs, all I found is that user libraries and "common system folders" are listed.
Could you please advise, which system folders are protected by default?

Thank you

**Comment by mypil** [comment]
@denisebmsft - Can you please share your insights on this issue?

Thank you.

**Comment by denisebmsft** [comment]
Hello @mypil, i have this on my list and will follow up soon. Thank you!

**Comment by denisebmsft** [comment]
For organizations, the specific list of folders is determined by how the security operations team has configured controlled folder access. If you look at this video (https://www.youtube.com/watch?v=byOQrERKxDg), and especially at 2:28 where controlled folder access is defined, you can get an idea of which folders are included or excluded. Also, you can see your protected folders list by opening the Windows Security app, selecting **Virus & threat protection**, and then selecting **Manage ransomware protection**, and then selecting **Protected folders**. If you cannot see that, it is probably because of how your security team has configured settings for your organization. I will update this article accordingly. Hope this helps!

**Comment by MaratMussabekov** [comment]
Hello @denisebmsft ,
Thank you for the information, but it seems like there are some other folders protected by default, not only the folders included by security team.
In the original article it states: "The protected folders include **common system folders**, and you can add **additional folders.** ". As I understand, folders added as it is shown at 2:28 of the video are **additional folders**, am I correct?
Also, in other [article](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/customize-controlled-folders#protect-additional-folders): "Controlled folder access applies to a number of **system folders** and default locations, such as Documents, Pictures, Movies, and Desktop. You can add **additional folders** to be protected, but you can't remove the default folders in the default list."
I believe the caller requested the list of these system folders.
Thank you

**Comment by denisebmsft** [comment]
Greetings! Thank you @bledMS82 for posting your feedback. And thank you @RAJU2529 and @MaratMussabekov for your help. I finally got the article updated a little earlier this month. It looks like this issue is now resolved, and I'm closing it. Please let me know if anything else is needed, and Happy New Year!

**Comment by illfated** [comment]
> Greetings!

A friend of mine used to reply "Do you come here bearing gifts?" when someone said "Greetings!" to him, because he was fed up with some of his friends using that greeting phrase all the time, just to reference their geek/nerd status of roleplaying typical fiction/fantasy roleplaying games. 😄
