### ISSUE TITLE
Qualified multitenant hoster link is broken

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/windows-itpro-docs#6648]
the link for "qualified multitenant hoster." says, "page cannot be found" also I believe multi-tenant is a hyphenated word.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Thank you for reporting that broken link, which turns out to be another exception from the general rule of using localizable links, instead of having /en-us/ as part of the link. The usual suspects are the Windows Server OS download pages and some non-localized software pages. As a note to myself, the actual link is this one:
- https://www.microsoft.com/en-us/CloudandHosting/licensing_sca.aspx

Page title (in the image & in the meta-reference above the image): **Qualified Multitenant Hoster Program**

I will open a PR to have that link text & URL corrected.

**Comment by illfated** [comment]
Hmm, looks like I won't be making any suggested change to the word "multitenant", seeing that the www.microsoft.com page does not split the word by hyphen or space (although the page does use the QMTH initials as if it was referring to a "Multi Tenant" or "Multi-Tenant"). Oh well.

**Comment by illfated** [comment]
There you go, PR #6649 is now ready for review. Feel free to comment or suggest further improvements.

**Comment by jonwbstr** [comment]
Yeah I saw that after opening the ticket as well. Curious but it is what it
is. Thanks!
