### ISSUE TITLE
Microsoft Management Agent Fast Deployment Guide?

### ISSUE THREAD

**Issue by peterhuerlimann** [MicrosoftDocs/windows-itpro-docs#6662]
Hi,

Where can I find the "Microsoft Management Agent Fast Deployment Guide" mentioned above?

Kind regards,
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2748359b-273d-7faa-6a63-7a6ebea450d2
* Version Independent ID: f4885da5-9a83-13aa-789e-1751db586404
* Content: [Set up Microsoft Defender ATP deployment - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/production-deployment#feedback)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/production-deployment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/production-deployment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.

Thank you.
