### ISSUE TITLE
How to remove pre-boot PIN and usb key from bitlocker?

### ISSUE THREAD

**Issue by yonathanluiz** [MicrosoftDocs/windows-itpro-docs#6663]
![5fb90a8e-86e1-42f3-b5ad-094bf65a47f1](https://user-images.githubusercontent.com/64906019/81296933-0179e700-9049-11ea-9e43-c3c22aabbce0.jpg)

I need to remove this dependency from the pre-startup, users cannot access the bitlocker keys for security reasons, and I can't disable the bitlocker, does anyone know how to help me?

**Comment by beerisgood** [comment]
What? Why the user can't access the recovery keys? It doesn't make sense to say "because of security reasons".

So you can't login to windows now?

**Comment by yonathanluiz** [comment]
It is a company security procedure, they cannot access security keys, many of them delete files when they are fired

**Comment by denisebmsft** [comment]
Hello @yonathanluiz. This doesn't appear to be a documentation issue. Please correct me if I am wrong. And if documentation does need to be updated, can you tell us which article(s)?

**Comment by yonathanluiz** [comment]
It's a BITLOCKER problem!

**Comment by RAJU2529** [comment]
@yonathanluiz . Its possible  before restarted the BitLocker  drive, You should have enabled some configurations via  group policy editor 
Conputer configuartion\Administrative templates\Bitlocker Drive Encryption\Operating system drives\Require additional authentication at startup 

![Capture4](https://user-images.githubusercontent.com/3296790/81321404-30777380-90b0-11ea-8dcf-116682dfc3d3.JPG)

**Comment by e0i** [comment]
Hello, @yonathanluiz, Thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.
