### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6676]
**Consumer applications for S mode** link does not exist.
**S mode devices** link does not exist
so please update new link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693c3223-df7f-9fbb-ce68-d3fb1ec04d53
* Version Independent ID: 2e2a1281-750a-63f6-f412-c466f44d03c9
* Content: [Windows 10 Pro in S mode - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/s-mode)
* Content Source: [windows/deployment/s-mode.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/s-mode.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
Both these links work fine.

**Comment by illfated** [comment]
Please note: The link [Consumer applications for S mode](https://www.microsoft.com/windows/s-mode) seems to work as intended (I have not tested other languages than Norwegian and English) ...

... but the link **S mode devices** (https://www.microsoft.com/windows/view-all-devices) only works in EN-US environments, not in other languages. I believe this link needs to get its EN-US locale specific directory pointer back, because it might have been removed at some point, breaking it for other languages than **en-us** specific OS or browsers.

The link https://www.microsoft.com/en-us/windows/view-all-devices works just fine, but the page is _definitely_ not language agnostic.

**Comment by illfated** [comment]
Yeah, it is evident in the file history: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5bde60c9d7091f610fd0c95f036e7a1cffcb3cb2 removed too many /en-us/ directory pointers.
- (https://github.com/MicrosoftDocs/windows-itpro-docs/commit/5bde60c9d7091f610fd0c95f036e7a1cffcb3cb2#diff-dffbd7542ee3841047935906e688331c)

(The commit page is showing 236 changed files, so be warned before scrolling on a slow computer.)

**Comment by illfated** [comment]
(ref. #6679 )

**Comment by illfated** [comment]
@RAJU2529 : As you can see, my PR change has been committed to the public branch and should be available on the public page in a few days' time.

PR: #6679 // commit: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9538f5c5de6226d9b3cf40e228625350be33d617
