### ISSUE TITLE
User & Machine activity

### ISSUE THREAD

**Issue by exchameed** [MicrosoftDocs/windows-itpro-docs#6712]
Will it possible to pull user/machine level web activity for the certain range of period once the feature is enabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17ef5983-b696-87da-5bb5-337454ab3b3a
* Version Independent ID: 54e202f2-ea8f-b7db-a38e-24b05c724fdd
* Content: [Monitoring web browsing security in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-protection-monitoring)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-protection-monitoring.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-protection-monitoring.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
