### ISSUE TITLE
Enhanced PIN support

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/windows-itpro-docs#6739]
My client is used to using Enhanced startup PINs in Windows 7. Now they are upgrading to Autopilot/Intune managed AAD-joined devices I can't find a setting to enable Enhanced/alpahnumeric PINs. Is thi spossible or on the roadmap? If not it would be good to clarify that in the docs

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05802f-9d0f-9aeb-3c8e-8b92f1284202
* Version Independent ID: 1fd9efc2-8946-75e4-27f3-95ac43a9d987
* Content: [BitLocker CSP - Windows Client Management](https://docs.microsoft.com/en-gb/windows/client-management/mdm/bitlocker-csp)
* Content Source: [windows/client-management/mdm/bitlocker-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/bitlocker-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @lomayor
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
**I can't find a setting to enable Enhanced/alpahnumeric PINs. Is thi spossible** - as I answered in https://github.com/MicrosoftDocs/windows-itpro-docs/issues/6738, it is not possible
**or on the roadmap?** - This feature was not announced, however, as you can see, new features are added in each new Windows 10 release, so may be in one of the future releases it would be added.
**If not it would be good to clarify that in the docs** - I don't think this info would look consistent in the Bitlocker CSP article, since these articles are focused on features that could be done using CSP, rather than things that couldn't be done.
Thank you

**Comment by mypil** [comment]
@thommck  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
