### ISSUE TITLE
Very low quality text.

### ISSUE THREAD

**Issue by rmpv1920** [MicrosoftDocs/windows-itpro-docs#6794]
I believe better quality text could be provided by Microsoft than the one present on this docs.
Examples:
BIOS Phase - Method 1- It says (point 3) "select NEXT -> Command Prompt" and immediatly follows (point 4) "Afeter startup reapir select shutdown". Beats me how opening a command prompt could repair my startup!
On method 3 - "If you receive BCD-related errors" doa "bootrec /scanos" and "restart to check whether the problem is fixed". Again beats me how a simple listing command option (such as /scanos) can fix whatever error I had previously.
There's more...
On method 4 - "Run the attrib command to unhide the file: attrib -r -s -h". I'm afraid this command just throws an error, wherever you type it, because it's mandatory to tell the file target.
It's just creepy how bad this text is. I'm a teacher at high school and I would FAIL any student of mine that would deliver such nonsense.
Sleep well.

[Escreva aqui os seus comentários]

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems - Windows Client Management](https://docs.microsoft.com/pt-pt/windows/client-management/advanced-troubleshooting-boot-problems)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
As a former dedicated computer support agent, I would like to mention that some of the necessary work is done automatically in the background. In particular, this is true for **Method 1: Startup Repair tool** (https://docs.microsoft.com/pt-pt/windows/client-management/advanced-troubleshooting-boot-problems#method-1-startup-repair-tool).

The reason why this step suggests to choose the Command Prompt option as your startup selection, is to run the Startup Repair Tool in the background and not attempt to start the full GUI desktop, to avoid any form of stop errors during the full GUI desktop completion process.
***
**Method 3: Fix BCD errors** (https://docs.microsoft.com/pt-pt/windows/client-management/advanced-troubleshooting-boot-problems#method-3-fix-bcd-errors):
- See https://support.microsoft.com/en-us/help/927392/use-bootrec-exe-in-the-windows-re-to-troubleshoot-startup-issues for more information about what the Bootrec.exe does in the Windows Recovery Environment does in the background. 

Maybe your issues have been outside the scope of this tool, so that might be a reason why it did not work in your case(s).
***
> On method 4 - "Run the attrib command to unhide the file: attrib -r -s -h". I'm afraid this command just throws an error, wherever you type it, because it's mandatory to tell the file target. [ ... ]

If you either get an error when trying to run the `attrib` command or have to specify the path to `attrib.exe`, it is possible that your computer problem includes missing startup files where the path environment variable is set, including the path to `C:\Windows\system32\`.
***
I am not trying to say that your suggestion is incorrect, I am trying to say that troubleshooting Windows startup (boot) problems can be quite varied and cumbersome to write for, particularly when it comes to some of the variations that may occur between some of the OEM brands who may include some of their own diagnostic tools in the startup.

Sure, feel free to suggest improvements to the current documentation. We other contributors may be able to help if you have questions about how to get the improvements added to the current documentation.

**Comment by RAJU2529** [comment]
@rmpv1920 .I also read this article,. In method 4, you must change to system reserved partition before entering attrib command.

More those methods works in windows 7  BIOS based computers

**Comment by e0i** [comment]
Closing via the answer provided by the community above. Thank you for the discussion.
