### ISSUE TITLE
Guest account

### ISSUE THREAD

**Issue by gabeluci** [MicrosoftDocs/windows-itpro-docs#6810]
The documentation of the Guest accounts says:

> The Guest account cannot be deleted or disabled

But in reality, it *can* be disabled, no? (assuming it was previously enabled)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e22ab2d-6274-c576-1093-a8bf33cec0cd
* Version Independent ID: b4f8e3d3-d83a-8bb7-1b38-8b544484b424
* Content: [Active Directory Accounts (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-accounts)
* Content Source: [windows/security/identity-protection/access-control/active-directory-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/access-control/active-directory-accounts.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
**Applies to**
-   Windows Server 2016

From the section https://docs.microsoft.com/windows/security/identity-protection/access-control/active-directory-accounts#guest-account
> The Guest account is a default local account has limited access to the computer and is disabled by default.
> The Guest account cannot be deleted or disabled, and the account name cannot be changed.
***
Just tested the enable/disable part on my production Windows Server 2016 Standard, Version 1607 (OS Build 14393.3686) Active Directory Domain Controller (VM).

1. Guest account did not seem to be disabled by default, but I can't be 100% certain of this, because I wasn't present when the server was installed. I just have had most time doing the general OS & user admin.
2. It is very simple to disable & enable & disable the account again, as many times as you wish. Nothing stopped me from switching between the states.

![Active Directory Users](https://user-images.githubusercontent.com/38162891/82930783-37462780-9f86-11ea-96df-0b955e618fc3.PNG)

**Comment by RAJU2529** [comment]
@illfated . I was able to renamed built-in Administrator account and  Guest account successfully on windows 10 1809, 1903  and 1909

**Comment by gabeluci** [comment]
This article isn't talking about the Administrator and Guest accounts on Windows 10. It's talking about those accounts in Active Directory.

**Comment by illfated** [comment]
Yes, I know. I hope I was able to provide at least some insight into the minor Active Directory user list I have got access to at work.

**Comment by gabeluci** [comment]
My comment was directed @RAJU2529. Sorry, I should have said that :)

**Comment by illfated** [comment]
That is OK, I understood as much. I was just a bit curious whether or not my comment & image post was of any help at all.

**Comment by gabeluci** [comment]
Your findings do at least confirm what I suspected, that this documentation has errors.

**Comment by illfated** [comment]
OK, fair enough. I suspect as much too. I would just feel more qualified to say that it is true if I had access to install & run a test ADFS to confirm even more clearly that this is the case in a default AD setup.
