### ISSUE TITLE
Surface Data Eraser is not working on Surface Book 3 (Commercial)

### ISSUE THREAD

**Issue by AlexHileman** [MicrosoftDocs/windows-itpro-docs#6845]
The SoftwareLicenseTerms text file is not displaying after booting to USB, and does not progress whatsoever. I've tried remaking the tool, adjusting UEFI settings, etc. Nothing appears to work.

Device Specs:
15" i7/32GB/512GB Quadro

**Comment by e0i** [comment]
The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
