### ISSUE TITLE
we can hide by using registry key

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#6871]
In windows 10 editions ,we can alse hide firewall & protection app by creating new key under windows registry here is the key
**reg.exe add"HKLM\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Firewall and network protection" /v UILockdown  /t REG_DWORD /d 1**
i confirmed after testing on my windows 10 laptop

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4c88cdf-2bf7-8abe-de14-6dba6a8daf07
* Version Independent ID: cda1e59c-ef42-f140-6c37-51e23dec8631
* Content: [Firewall and network protection in the Windows Security app - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-security-center/wdsc-firewall-network-protection)
* Content Source: [windows/security/threat-protection/windows-defender-security-center/wdsc-firewall-network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-security-center/wdsc-firewall-network-protection.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Sure, but I am fairly certain that the target audience for this article is IT professionals who need to deploy the solution to many more computers than they have got time to visit individually or manage remotely one by one. I also seem to remember that this can not be done via Microsoft Intune or Windows Autopilot, unless this is something configured in a preconfigured image (which I am somewhat doubtful of, given the sentence "This can only be done in Group Policy." on the page.

Perhaps this could be done via Microsoft Endpoint Configuration manager in a PowerShell script to run the registry key change, but I do not know if it is possible to mass distribute this kind of solution, also because of the same sentence.

This would have to be confirmed by the technical writer team, I suppose.

**Comment by RAJU2529** [comment]
@illfated.  I have  examined the .admx file, each and every file is mentioned registry key.  Moreover this registry key is solved some problems from users in Microsoft community

**Comment by illfated** [comment]
Very well. I have no doubt that your research is good and that your results are correct. I am merely thinking that it might not be what the general IT pro audience is looking for, based on previous experience from other issues where some users have argued that they are looking for solutions to deploy in a bigger environment where they don't have time to visit each individual computer personally. I may very well be mistaken, so if that is the case, I hope your research results are useful enough to be considered as applicable to this document. Please disregard any notions that I am negative to your suggestions. I will leave it for others to decide if this is usable in the documentation, since my personal experience is too limited for the general audience.

**Comment by nam31** [comment]
Thank you for providing feedback.				
				
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub.](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) You might find others have made a similar request that you can add to, or you can open a new one.				
				
Thank you for your contribution to make the docs better! Much appreciated!
