### ISSUE TITLE
Unable to set Approved Update Time

### ISSUE THREAD

**Issue by PriyaKOMA** [MicrosoftDocs/windows-itpro-docs#6877]
The protocol says 
ApprovedUpdates/Approved Update Guid/ApprovedTime
Specifies the time the update gets approved.
Supported operations are Get and Add.
However, on adding the ApprovedTime the protocol returns 418 always and sets another time. If setting of approved time is not supported the documentation needs to be modified.

**Comment by denisebmsft** [comment]
Hello @PriyaKOMA, can you please tell us to which article(s) your feedback applies? This information will help us route the issue correctly. Thank you!

**Comment by PriyaKOMA** [comment]
Hello,
My feedback is related to **https://docs.microsoft.com/en-us/windows/client-management/mdm/update-csp**
ApprovedUpdates/Approved Update Guid/ApprovedTime
Specifies the time the update gets approved.
Supported operations are Get and Add.

The Approved Time does not accept user defined time. Always returns 418 for ADD operation.

**Comment by PriyaKOMA** [comment]
Hello,
Any update on this issue?

**Comment by lindspea** [comment]
@Dansimp could you please assist here?

**Comment by lindspea** [comment]
@denisebmsft @Dansimp please could you assist.

**Comment by nam31** [comment]
Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
