### ISSUE TITLE
Unable to fetch metadata for update IDs having revision number 1

### ISSUE THREAD

**Issue by PriyaKOMA** [MicrosoftDocs/windows-itpro-docs#6883]
Hi,

The endpoint on fetching for updates through OMADM returns a list of updates. Some updates have an update ID but revision number as 1. These updateids fail to get the metadata using WSUS Server Server Sync Protocol. How to fetch metadata for these updateIDs.

**Comment by denisebmsft** [comment]
Hello @PriyaKOMA. Thank you for submitting this question. Can you tell us to which article(s) your issue applies so that we can route it to the correct writer/team?

**Comment by PriyaKOMA** [comment]
Hello, 
I was referring to
https://docs.microsoft.com/en-us/windows/client-management/mdm/device-update-management
WSUS-Server Server Protocol the only way to get metadata as for some update ids with revision number 1, the server - server protocol fails.

**Comment by e0i** [comment]
@PriyaKOMA 

The issues section of this repository is intended for product documentation issues.

Please consider opening a product support ticket by the following link below for your problem.

Here is a related community discussion that seems to be related to your feedback that you might find useful: https://social.technet.microsoft.com/forums/en-US/9cc1efb0-9d96-4674-93f4-ed027ed90e6a/mdt-2010-cannot-find-path-ds001operating-systems-because-it-does-not-exist

For any further support queries, please refer to [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10).

Thank you.

**Comment by joinimran** [comment]
@PriyaKOMA - There is a note section describing the required details. Please ensure that S2S sync is enabled as it can only fetch the information using S2S sync.

The note section has more details on this. If you are having any issue after enabling S2S sync, I would suggest you to contact MS support team.

Thanks
Imran.

@e0i - FYI&A Please.
