### ISSUE TITLE
Work with Surface Book too?

### ISSUE THREAD

**Issue by jon-au** [MicrosoftDocs/windows-itpro-docs#6888]
I have my Surface Book on charge while at work (I present on the road regularly so need portability). I notice the battery limit feature only works on the Clipboard section and not the base. 

Is there a way to limit the Base battery too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a767ea0-4095-7a35-3828-4b3a17a0ea26
* Version Independent ID: 4ca4088c-1e98-c725-d46b-94cecfa123f2
* Content: [Battery Limit setting (Surface) - Surface](https://docs.microsoft.com/en-us/surface/battery-limit)
* Content Source: [devices/surface/battery-limit.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/devices/surface/battery-limit.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @CoveMiner
* Microsoft Alias: **greglin**

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
