### ISSUE TITLE
US GOVT Request URLs

### ISSUE THREAD

**Issue by ITOpsReborn** [MicrosoftDocs/windows-itpro-docs#6966]
Is there any available documentation of the URLs for pulling alerts in GOVT cloud tenant? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b835bf35-1614-2d8d-13ab-176c6d839047
* Version Independent ID: ed4653f3-e393-dd42-5960-87888c08ba40
* Content: [Pull Microsoft Defender ATP detections using REST API - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api#request)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/pull-alerts-using-rest-api.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
@ITOpsReborn Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.
