### ISSUE TITLE
创建Microsoft Visual c + + 可再发行 2019-x86部分的powershell有问题，会把D:\Downloads下面的所有文件都copy一份到DS001里面

### ISSUE THREAD

**Issue by maodahua** [MicrosoftDocs/windows-itpro-docs#6981]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e0eb8c97-caa0-bb05-4b91-14ad2adc4aac
* Version Independent ID: 0cc541a3-8198-c029-d795-308e673ee2f4
* Content: [创建 Windows10 引用映像 (Windows10) - Windows Deployment](https://docs.microsoft.com/zh-cn/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image)
* Content Source: [windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
From https://translate.google.com/:
> There is a problem with creating Microsoft Visual C++ redistributable PowerShell for the 2019-x86 part. All files under D:\Downloads will be copied to DS001
> [Enter feedback here]

(tried using https://www.bing.com/translator , but the output was less understandable)

**Comment by illfated** [comment]
I am guessing that this has something to do with the section https://docs.microsoft.com/zh-cn/windows/deployment/deploy-windows-mdt/create-a-windows-10-reference-image#%E5%88%9B%E5%BB%BA%E5%AE%89%E8%A3%85-microsoft-visual-c---%E5%8F%AF%E5%86%8D%E5%8F%91%E8%A1%8C-2019-x86create-the-install-microsoft-visual-c-redistributable-2019---x86
(**创建安装： Microsoft Visual c + + 可再发行 2019-x86**),
but I am uncertain if this is purely a technical issue or if anything could be wrong with the page translation.

**Comment by e0i** [comment]
@maodahua 

The issues section of this repository is intended for product documentation issues.

Please consider opening a product support ticket by the following link below for your problem.

Here is a related community discussion that seems to be related to your feedback that you might find useful: https://social.technet.microsoft.com/forums/en-US/9cc1efb0-9d96-4674-93f4-ed027ed90e6a/mdt-2010-cannot-find-path-ds001operating-systems-because-it-does-not-exist

For any further support queries, please refer to Windows 10 Support.

Thank you.
