### ISSUE TITLE
Possible data leakage when no hibernated state is used (Windows to Go)?

### ISSUE THREAD

**Issue by ericLH** [MicrosoftDocs/windows-itpro-docs#699]
When using a Windows 8 host system with hibernated state disabled and a Windows To Go also with a Windows 8 operating system, is there still the recommandation to use the **SAN policy "4" NoDefaultDriveLetter**?

> It is strongly recommended you do not change this policy to allow mounting of internal hard drives when booted into the Windows To Go workspace. If the internal drive contains a hibernated Windows 8 operating system, mounting the drive will lead to loss of hibernation state and therefor user state or any unsaved user data when the host operating system is booted.

[https://docs.microsoft.com/en-us/windows/deployment/planning/security-and-data-protection-considerations-for-windows-to-go#disk-discovery-and-data-leakage](url)

Is there still a possibility for data leakage or internal drive corruption when only Windows 8 is used with hibernated state disabled?

I ask because i want to use a "shared folder" on a extra partition on the internal host computer drive which can also be used from the Windows To Go System when booted from it.

@mtniehaus @nickbrower @brianlic-msft

**Comment by egallagh** [comment]
To my knowledge, the recommendations still stands. There is issue regarding data leakage if that disk is accessible to the file system because it has a drive letter. Consider the following scenario as just one example:
Corporate data on the Windows To Go drive.
Windows To Go drive is plugged into a running infected system.
Windows To Go drive becomes accessible to the file system because it gets a drive letter.
The infected system now has easy access to the data on the Windows To Go drive and could exfiltrate the data, encrypt the data (ransomware), etc.

If the systems have internet access, I would recommend secure cloud storage of the data that you want to share between the systems.
Hope this helps.
Ed Gallagher

**Comment by joinimran** [comment]
@ericLH Thank you for your query regarding the document. Please note this policy still stands active and it is recommended to ensure that this policy is enabled. 
Thanks.

**Comment by mypil** [comment]
@ericLH - Thank you for submitting feedback.

From our understanding, the issue has been answered by egallagh and joinimran. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
