### ISSUE TITLE
Lenovo failed to reboot

### ISSUE THREAD

**Issue by Magic6400** [MicrosoftDocs/windows-itpro-docs#6997]

**Comment by Magic6400** [comment]
![Uploading 0618202202_HDR.jpg…]()

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close

**Comment by mypil** [comment]
@Magic6400 -As mentioned by @illfated, we handle documentation updates here that can help to improve the existing MS docs. If you have some technical issues that require technical support or other support type questions, I would suggest opening a **[service ticket](https://support.microsoft.com/hub/4338813/windows-help?os=windows-10)** for Windows 10 products or visiting Microsoft Support forums. 

If you do find any documentation error, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 
Thank you.

**Comment by Magic6400** [comment]
Everything is working now, I need to give it an amount of time to verify that it is me. The protocol of the data source requires a two step verification. My phone is out of service due to not being able to pay the minimal amount of 190 usd. Thank you for the quick response.
