### ISSUE TITLE
Is this meant for regular users to do? Or is this a special maintenance procedure for IT personnel?

### ISSUE THREAD

**Issue by tank-t-bird** [MicrosoftDocs/windows-itpro-docs#7040]
Sounds crazy if this is meant for the regular user. Just saying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b706f0af-d504-a8ca-7c38-b8bb9283bfad
* Version Independent ID: 14f31acf-9f47-59a6-269f-62ab249fe560
* Content: [Servicing stack updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates)
* Content Source: [windows/deployment/update/servicing-stack-updates.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/servicing-stack-updates.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by RAJU2529** [comment]
For standard alone computers without domain, those users should maintain their self. 
But domain joined computers Connected to organization, system administrator must and should maintain

**Comment by illfated** [comment]
Just to be a little bit more specific than the answer above;

@tank-t-bird : Please note that **Servicing stack updates** is a topic for highly skilled users, usually employed by or hired by the IT Department in bigger companies (more than 50 employees) to perform the deployment and maintenance of dozens, maybe hundreds of computers. Based on my own experience, it is not a useful project to apply to a small/medium business with 20 employees or less, except for a scenario where the company changes its computers so frequently that it takes too much time to manage those computers individually.

Please note that most of the documentation in https://docs.microsoft.com/windows/ is designed for and aimed at IT Pros or developers with insider knowledge of how the operating system works, both on servers and client computers. This material is not meant for individual users, unless you are taking courses to prepare for any Microsoft exams covering this field.

**Comment by illfated** [comment]
@tank-t-bird : You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close

**Comment by tank-t-bird** [comment]
Hi @illfated , thanks so much for your detailed responses! Amazing, very clarifying and helpful.
