### ISSUE TITLE
Feedback button doesn't work

### ISSUE THREAD

**Issue by Rippsy** [MicrosoftDocs/windows-itpro-docs#7042]
The "This product" feedback option for the MDATP MacOs pages takes you to the Windows 10 feedback hub information page - and thus you cannot give any feedback on the product

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f72a75-ca85-0651-1512-8ffb62d0ab7b
* Version Independent ID: 6e15dd30-1db2-4a18-a18c-c343e1d508cd
* Content: [Resources for Microsoft Defender ATP for Mac - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/mac-resources)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/mac-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/mac-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
The existing Feedback buttons all point to the same page, https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app .

This code seems to be hidden in some part of the documentation which may not be available to outside contributors, perhaps only accessible by Microsoft internals.

Back in Oct 9, 2019, in commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/c98fd6507fed4c7d39f99bf2b0f7de0296fe4148 , the following note was added to this document:

  > [!NOTE]
  > Certain device information might be subject to upcoming releases. To send us feedback, use the Microsoft Defender ATP for Mac app and select **Help** > **Send feedback** on your device. Optionally, use the **Feedback** button in the Microsoft Defender Security Center.

The note above is no longer part of this document, maybe because the directory structure has been changed since then. Still, I believe this note needs to be added to **all** the [Microsoft Defender ATP for Mac](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-mac) pages.

**Comment by VLG17** [comment]
@Rippsy The recommendation is to use the official channel, meaning [User Voice](https://office365.uservoice.com/). It's the best way to send feedback to the product group, have it voted by other people who have the same issue and get it to the top of the list, thus giving it a better chance of being implemented faster.
