### ISSUE TITLE
Linux: unclear instructions

### ISSUE THREAD

**Issue by senorsmile** [MicrosoftDocs/windows-itpro-docs#7048]
In the page
[linux-install-with-ansible](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/linux-install-with-ansible.md
)

It says
> In Microsoft Defender Security Center, go to Settings > Device Management > Onboarding.

I traced this back to this page: 
[microsoft-defender-atp-linux](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux.md)

which mentions
> Access to the Microsoft Defender Security Center portal

There still aren't any indications where this portal is.  

It's very unclear why the instructions don't point directly to a repository.  This installation method seems so far outside of the way things are done within the Linux best practices, and especially within Ansible best practices.  Within the Ansible instructions, there should be zero bash required, and the ansible playbook itself should download the executable directly.  

I suspect most will give up before they even get something downloaded.

**Comment by illfated** [comment]
@konstruktoid : Is this something you are familiar with, or at least know enough to suggest how to move forward here?

**Comment by konstruktoid** [comment]
Hi @senorsmile, the Microsoft Defender Security Center portal is described at https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-security-center and is the management portal you or your Azure Active Directory administrator got access to if you're using the MDATP software.

Yes, the setup.sh script and related Ansible code can use  the `unarchive` module instead, so there's some improvements possible.

`It's very unclear why the instructions don't point directly to a repository.`

It does? After the .zip file, you'll add the Microsoft signing key and then install `mdatp`. `apt` and `yum` instructions included.

`This installation method seems so far outside of the way things are done within the Linux best practices, and especially within Ansible best practices.`

How's that?

`Within the Ansible instructions, there should be zero bash required,` 

Within the Ansible instruction, there is zero amount of bash code? Replacing the `setup.sh` script with `unarchive` and such will be an improvement.
Regarding `script: /root/setup.sh`, are you referring to https://docs.ansible.com/ansible/latest/modules/script_module.html#notes and `It is usually preferable to write Ansible modules rather than pushing scripts.`?

`and the ansible playbook itself should download the executable directly.`

What executable are you referring too?
`mdatp` is installed via a package manager, and the `WindowsDefenderATPOnboardingPackage.zip` includes environment specific instruction such as `orgId`, `geoLocationUrl`, and a customer signature and you have to download the file from the Microsoft Defender Security Center portal as a logged in customer.

**Comment by senorsmile** [comment]
>> It's very unclear why the instructions don't point directly to a repository.

> It does? After the .zip file, you'll add the Microsoft signing key and then install mdatp. apt and yum instructions included.

I didn't see the apt_repository and yum_repository refs on first pass.  It appeared that the zip file above had the executable in it. 


I think I misunderstood what the product does. 

> Microsoft Defender Security Center

I found this page which provides a little more context for me:
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/evaluate-atp.md

This must be a separate product that the linux install must link with?  i.e. this is not a stand alone product?

**Comment by illfated** [comment]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/evaluate-atp.md

The link above should in theory be the source material for the official page, linked below:

- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/evaluate-atp
