### ISSUE TITLE
Rechtschreibung hilft Leben retten

### ISSUE THREAD

**Issue by ATR-Master** [MicrosoftDocs/windows-itpro-docs#7058]
Sinn-entstellende Fehler  (Rechtschreibung oder Übersetzung) machen es einem ziemlich schwer, den Inhalt Ihrer Artikel wirklich richtig und schnell zu verstehen bzw. zu erfassen. Bsp.: " ...Ihres Geräts festzulegen und welche Nutzdaten (wie **ESDS** oder Pakete)..." - hier sollte es wohl **ESDs** heißen und nicht ein Akronym mit 4 Großbuchstaben sein, oder?
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fcc8a7ec-75d7-894c-9499-cbb4c3807ea7
* Version Independent ID: a4c97095-7c09-1bff-690d-90c8cdeee6c2
* Content: [Erste Schritte mit Windows Update - Windows Deployment](https://docs.microsoft.com/de-de/windows/deployment/update/windows-update-overview)
* Content Source: [windows/deployment/update/windows-update-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/update/windows-update-overview.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
Guter Punkt, gut beobachtet. Das ist richtig, es sollte nur ein "Drei-Buchstaben-Initialismus" sein, im Plural. Ich frage mich, ob es genauso einfach wäre, den Plural S loszuwerden und den Initialismus als Mengenwort zu verwenden.

---

@TinaMcN : This is the following section in the /en-us/ document:

---
- **WU Arbiter handle**- Code that is included in the UpdateAgent binary. The arbiter gathers information about the device, and uses the CompDB(s) to output an action list. It is responsible for determining the final "composition state" of your device, and which payloads (like ESDs or packages) are needed to get your device up to date.
---

From a grammatical viewpoint, I wonder if it would be just as practical to simplify the initialism "ESD" to its singular form, as if it were a quantity description, instead of a singular entity referenced in plural.

Or would you prefer to have the page manually edited in this case?

**Comment by e0i** [comment]
@TinaMcN Seems like a manual translation task. Please let us know whether any revisions to the original article would in fact improve the automated translation. Thank you.

**Comment by TinaMcN** [comment]
@ATR-Master Vielen Dank, dass Sie über dieses Problem berichtet haben.
@OfficeGlobal please human translate this article and let us know when it's updated.

**Comment by TinaMcN** [comment]
@ATR-Master Der Artikel wird nun von einem Menschen übersetzt.  Können Sie bitte überprüfen, ob das Problem jetzt behoben ist?

**Comment by e0i** [comment]
I have manually verified that the plural suffix has been revised accordingly. Thank you for the feedback.
