### ISSUE TITLE
Licensing question / clarification

### ISSUE THREAD

**Issue by jrochet** [MicrosoftDocs/windows-itpro-docs#707]
Is it possible to purchase a minimal number of WDATP licenses, to enable WDATP in the tenant, but then not assign end-users a license and just focus on machines rather than users?

It's not clear why users need to be assigned a WDATP license, and since Windows 10 Pro, Windows 7 & 8.1 are supported, it seems like there is a lot of machine-specific functionality that is available without bothering to assign licenses to users.

Please elaborate on the bare minimum licensing (# of licenses / what licenses) required to use WDATP.

**Comment by mjcaparas** [comment]
Hello jrochet, 

Do you mind further clarifying your question as there's no possibility to assign licenses to users for WDATP?

Also, for information on licensing requirements please see: [Minimum requirements](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-atp/minimum-requirements-windows-defender-advanced-threat-protection).

**Comment by jrochet** [comment]
Hello @mjcaparas ,

In Office (365) Admin Center, under Users -> Active Users, Windows Defender Advanced Threat Protection licenses can indeed be assigned to users.  I will include a screenshot:
https://i.imgur.com/A1oEKJp.png

The minimum requirements are indeed what I referred to already.  The licensing requirements state:
"Licensing requirements
Windows Defender Advanced Threat Protection requires one of the following Microsoft Volume Licensing offers:

Windows 10 Enterprise E5
Windows 10 Education E5
Microsoft 365 E5 (M365 E5) which includes Windows 10 Enterprise E5"

And then the Endpoints:
"Endpoint hardware and software requirements
The Windows Defender ATP agent only supports the following editions of Windows 10:

Windows 10 Enterprise
Windows 10 Education
Windows 10 Pro
Windows 10 Pro Education
Endpoints on your network must be running one of these editions.

The hardware requirements for Windows Defender ATP on endpoints is the same as those for the supported editions."

So I guess I'm confused how many licenses I would need to buy of, let's say for this example Windows 10 Enterprise E5.  Is the number of licenses required to match the number of endpoints that are onboarded into WDATP?  Or, do I just need to purchase a single Windows 10 Enterprise E5 license and then WDATP is available for me to onboard all my devices to it?  Finally, going back to the users, they do appear to be capable of having WDATP licenses assigned, I'm not sure what to say more beyond the screenshot.

Thanks in advance.

**Comment by mjcaparas** [comment]
Hi jrochet, 

Thank you for further explaining. To answer your question - yes, the number of licenses required need to match the number of endpoints that are onboarded to the service. 

With regards to the screenshot, although users appear to be capable of being assigned a license, it doesn't have a correlation to the machine being monitored. 

I hope that helps.

**Comment by jrochet** [comment]
Thanks for the answer!

**Comment by mzafzal1** [comment]
So we dont need to assign any license to any user/machine? What will happen if I have for e.g 50 licenses and I onboarded 60 endpoints?

**Comment by mjcaparas** [comment]
You will need 60 licenses to onboard 60 endpoints.

**Comment by philschman** [comment]
> ... yes, the number of licenses required need to match the number of endpoints that are onboarded to the service.
> 
> With regards to the screenshot, although users appear to be capable of being assigned a license, it doesn't have a correlation to the machine being monitored.
> 
> I hope that helps.

@mjcaparas Is this information correct anymore? I don't have to assign the Defender ATP licenses to the users. Only the number of licenses have to be correct for the ATP onboarded devices?

I'm asking because I have problems in a customer environment where devices will be removed from the list of ATP devices in the Security Portal after a unknown amount of time. If I will onboard the device again it will not show up in the list. I thought this could be a Licensing problem, but we have 100 Licenses for WDATP and only a few clients (about 15) onboarded to WDATP.

The documentation for Defender ATP doesn't say anything about the Licensing assignments. Could you please add these information to "Docs"?

Thanks in advance!

**Comment by claymen** [comment]
> > ... yes, the number of licenses required need to match the number of endpoints that are onboarded to the service.
> > With regards to the screenshot, although users appear to be capable of being assigned a license, it doesn't have a correlation to the machine being monitored.
> > I hope that helps.
> 
> @mjcaparas Is this information correct anymore? I don't have to assign the Defender ATP licenses to the users. Only the number of licenses have to be correct for the ATP onboarded devices?
> 
> I'm asking because I have problems in a customer environment where devices will be removed from the list of ATP devices in the Security Portal after a unknown amount of time. If I will onboard the device again it will not show up in the list. I thought this could be a Licensing problem, but we have 100 Licenses for WDATP and only a few clients (about 15) onboarded to WDATP.
> 
> The documentation for Defender ATP doesn't say anything about the Licensing assignments. Could you please add these information to "Docs"?
> 
> Thanks in advance!

Did you ever get a response to this? As the documentation doesn't align with what was posted (granted it is quite an old post) but am seeking similar clarification.

For example as per this link https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide

> Eligible licensed users may use Microsoft Defender for Endpoint on up to five concurrent devices. Microsoft Defender for Endpoint is also available for purchase from a Cloud Solution Provider (CSP). RDSH VMs do not require a separate Defender for Endpoint license.

So that would imply the endpoint count in terms of devices cannot simply match the licensed users. As a user could be licensed for up to five concurrent devices, and additionally using the term concurrent, may mean that over time they shift through devices, so could have the endpoint installed on more that are not in use.

Additionally, I was under the understanding that you cannot delete machines, you can offboard but this is run from the client side. So if a machine is destroyed and cannot have the script run to offboard, that the machine will remain in the portal for some time before slowly ageing out. So this too would not make those numbers match.

For some background, the issue we have is that we may have say 100 endpoints, but have 400 staff, this presents some challenges in licensing this given other products license based on endpoint. I understand the advantage of licensing per user, but historically this is why there has been Device and User based licensing to meet those needs. Is there going to be something similar?

And finally, what happens when an unlicensed user logs onto a machine with defender? This could happen from a temporary contractor coming to site. Or possibly a mixed license user, e.g. an M365F3 user jumps onto a machine, are they now not protected? Given that this would be perfectly workable with device based licensing of a competing product.

**Comment by Floroy** [comment]
@claymen did you get an answer to that? These are exactly the questions we have when we switch to MDE regarding licensing.

**Comment by roberts951** [comment]
@claymen fast forward another year - I am also seeking answers to these questions. If anyone has some information kindly share what you can.

**Comment by roberts951** [comment]
@Floroy @claymen fast forward another year - I am also seeking answers to these questions. If anyone has some information kindly share what you can.
