### ISSUE TITLE
MAC and Linux Support

### ISSUE THREAD

**Issue by v-rapate** [MicrosoftDocs/windows-itpro-docs#7129]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 034ffda3-6ef7-13f4-6341-82ac3c11f455
* Version Independent ID: 5527ef3f-6361-b037-d9c3-3d520cf2ef2c
* Content: [Threat & Vulnerability Management supported operating systems and platforms - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by v-rapate** [comment]
Microsoft Defender ATP for Linux is now generally available!
https://techcommunity.microsoft.com/t5/microsoft-defender-atp/microsoft-defender-atp-for-linux-is-now-generally-available/ba-p/1482344

Deploy Microsoft Defender ATP for Mac in just a few clicks
https://techcommunity.microsoft.com/t5/microsoft-defender-atp/deploy-microsoft-defender-atp-for-mac-in-just-a-few-clicks/ba-p/1341619

**Comment by RAJU2529** [comment]
@e0i . Assign user to check PR #7133

**Comment by levinec** [comment]
Hi @RAJU2529  and @v-rapate, thanks for your feedback. However, not all Microsoft Defender ATP capabilities have the same supported operating systems/platforms (including threat and vulnerability management). That's why we have one page for Microsoft Defender ATP requirements: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements, and a different one for threat and vulnerability management: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-supported-os. Currently, Mac and Linux are not supported for threat and vulnerability management. Hope that clears that up!
