### ISSUE TITLE
Why is this thing blocking my apps and where do I turn it off

### ISSUE THREAD

**Issue by RatishISURI** [MicrosoftDocs/windows-itpro-docs#7140]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd0fe29-5db5-b752-5bcf-5ac2581baa9a
* Version Independent ID: 52b8d4ca-54ea-7345-12b0-df4fdf633083
* Content: [Enable Block at First Sight to detect malware in seconds - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/configure-block-at-first-sight-microsoft-defender-antivirus)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/configure-block-at-first-sight-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/configure-block-at-first-sight-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by beerisgood** [comment]
What get blocked?

**Comment by RatishISURI** [comment]
a c++ app where I was testing sdl2

**Comment by e0i** [comment]
@RatishISURI 

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.
