### ISSUE TITLE
EnterpriseDesktopAppManagement - Get Commands Return Empty Responses

### ISSUE THREAD

**Issue by sriram-kakarala** [MicrosoftDocs/windows-itpro-docs#7154]
Hi,

I have been trying the **EnterpriseDesktopAppManagement** CSP and able to install the MSI remotely. However querying for Status, InstallPath and Uninstall commands are not working.
The Get queries are returning empty responses and Delete command though returns success the app actually does not get uninstalled.

Any clues on what may be happening here?

Thanks,
Sriram

**Comment by RAJU2529** [comment]
@sriram-kakarala . Which article are you referring ?

**Comment by e0i** [comment]
The issues section of this repository is intended for documentation and content-related issues.

Please open a support ticket via the link below so that that your question gets answered quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
