### ISSUE TITLE
The available options and their effects on a Windows 10 1909 device are not reflecting the actual situation.

### ISSUE THREAD

**Issue by RaimondMoerman** [MicrosoftDocs/windows-itpro-docs#7155]
I am configuring the Endpoint Protection device configuration profile for our Windows 10 devices.
In the drop down list for "Local device security options>>Interactive Logon>>Display>>User information on lock screen"  we have only **3** options available (this is also mentioned in the documentation):

1 - User display name, domain and user names
2 - User display name only
3 - Do not display user information

But when setting this policy from the local security policy editor (secpol.msc) on a Windows 10 1909 device we see not 3 but **4** options:

1 - User display name, domain and user names
2 - User display name only
3 - Do not display user information
4 - Only domain and user names

The effects of setting this policy to option **1** results in displaying the "User display name, domain and user names" on the lock screen and only the password field being blanked out. This is the expected behavior for option 1.
The effects of setting this policy to option **2** results in displaying nothing and both username and password field being blanked out, so effectively this is option **3** being applied.  Obviously this is unexpected and unwanted behavior!
The effects of setting this policy to option **3** results in displaying nothing and both username and password field being blanked out. This is the expected behavior for option 3.
The effects of setting this policy to option **4** results in displaying the "User display name" on the lock screen and only the password field being blanked out, so effectively this is option **2** being applied. Obviously this is unexpected and unwanted behavior!

Please look into this and provide us with an Endpoint Protection device configuration profile that lists all **4** options and reflects the correct behavior of these options on the device.
 
Kind regards, Raimond

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773b74b2-7dc2-d0e5-1e3b-bd6445bceda4
* Version Independent ID: 34b55057-9078-6bd0-a9ac-2f6403b84be7
* Content: [Policy CSP - LocalPoliciesSecurityOptions - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions#localpoliciessecurityoptions-interactivelogon-displayuserinformationwhenthesessionislocked)
* Content Source: [windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localpoliciessecurityoptions.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@RaimondMoerman . Just now i checked on windows 10 v2004 build no 19041.331   by using Group policy admx templates and by using  secpol.msc  

all the 4 options are displayed in both the ways.

so you must update the latest admx templates.

**Comment by RaimondMoerman** [comment]
Hello, thank you for your andere but the issue I reported is not in the GPO templates but in the Intune MDM Device Configuration Profile for Endpoint Protection.
That only lists 3 options and does not give expected results.
Please look in to that.

Kind regards, Raimond

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RAJU2529** [comment]
@RaimondMoerman , Sorry i dont know about intune MDM configuration. Keep waiting for the expert users solutions

**Comment by MaratMussabekov** [comment]
Hello @RaimondMoerman ,

**In the drop down list for "Local device security options>>Interactive Logon>>Display>>User information on lock screen" we have only 3 options available (this is also mentioned in the documentation):** - I am not sure why the option 4 is not added here, may be it is because this option is for on-premises domains only. Anyway, it will be added to the documentation only after it is added to the product.

**The effects of setting this policy to option 2 results in displaying nothing and both username and password field being blanked out,** - This is expected behaviour for any computer running Windows 10 later than 1607. To make long story short: after 1607, if **Block user from showing account details on sign-in** policy is not enabled (I believe its your case), only options 1 and 4 will show the domain\username. In case this policy is enabled, only display name is shown regardless of option you have chosen.
For more details, read https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-display-user-information-when-the-session-is-locked#interaction-with-related-group-policy-settings. The article need to be updated (it doesn't show the option 4, I will create a PR to fix that), but it still provides the general information.

**The effects of setting this policy to option 4 results in displaying the "User display name" on the lock screen and only the password field being blanked out** - for me it displayed username and domain name as expected:
![изображение](https://user-images.githubusercontent.com/48041687/90710984-07729b80-e2b9-11ea-9124-19cef4fe0184.png)
Are you sure you logged in as a domain user?

Thank you

**Comment by RaimondMoerman** [comment]
@MaratMussabekov Tja k you for your reply.
We log in using our email address as the user name as the devices are Intune MDM managed Autopilot deployed Azure AD joined devices in strand of On-Premise Domain joined devices.
So what I want to achieve is to only show the e-mail address and below that the blanked out password field that we van user to unlock the device 
Thank you again for your support!

Kind regards, Raimond
