### ISSUE TITLE
Elaborate on "Policy management" section

### ISSUE THREAD

**Issue by SteffanH** [MicrosoftDocs/windows-itpro-docs#7173]
Can this section be expanded upon ?
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-threshold#policy-management

It currently does not, for example, say how this can be configured using InTune/EndPoint Manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82cb96d5-5901-a1ea-a32d-12f22c5c4a09
* Version Independent ID: d8073688-6782-c4b2-58c8-6a8650bfeb9c
* Content: [Account lockout threshold (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/account-lockout-threshold)
* Content Source: [windows/security/threat-protection/security-policy-settings/account-lockout-threshold.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/account-lockout-threshold.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @SteffanH - Thank you for your query. As of now, there is no requested information can be added as this policy is not available in intune but is requested via the UserVoice channel. Please vote for this so that it can be available. Once it will be available, that policy section will be updated.

Thanks.
Imran.
