### ISSUE TITLE
“Precedence for provisioning packages” section 

### ISSUE THREAD

**Issue by lesca** [MicrosoftDocs/windows-itpro-docs#782]
*System Integrator* and *OEM*, which one's rank level is 3? The example says *System Integrator* is 3, the order list says it is 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f207b491-f262-43cf-1002-8f3fb2a052c6
* Version Independent ID: 5358ed30-928c-e397-04e7-7f4c602777e2
* Content: [How provisioning works in Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-how-it-works)
* Content Source: [windows/configuration/provisioning-packages/provisioning-how-it-works.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/provisioning-packages/provisioning-how-it-works.md)
* Service: **unspecified**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
@lesca I'll remove the example because I can see how it makes it confusing. 

The precedence is the numbered list. The rank is any value between 0 and 99 that the builder enters. 

The precedence order is applied first. If there are multiple packages with the same precedence (like two OEM packages), then the rank is applied.
