### ISSUE TITLE
Troubleshooting Windows Autopilot

### ISSUE THREAD

**Issue by Arijit746255** [MicrosoftDocs/windows-itpro-docs#7941]
[Enter feedback here]
When writing a troubleshooting guide for Autopilot, try to put all the events not a part of it. The guide is missing the event IDs 165, 167 & its explanation etc. Hence this guide is incomplete and NOT AT ALL USEFUL. It is expected from Microsoft to release a complete troubleshoting guide expecially if they want bulk of their users to test MS products. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcfcc02-d931-66e3-6f4f-c14b936358e6
* Version Independent ID: 8972647b-ba21-b68f-b698-5fb6e9e9f1fd
* Content: [Troubleshooting Windows Autopilot - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting)
* Content Source: [windows/deployment/windows-autopilot/troubleshooting.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-autopilot/troubleshooting.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by joinimran** [comment]
Hello @Arijit746255 - Thank you for your feedback. I have checked and I was not able to find the mentioned event numbers from any reliable sources. If you have details regarding these event numbers, please do share with me so that I can add up the missing information. As of now, everything looks good.

Thanks.
