### ISSUE TITLE
[Question] After config, Some thing now working/misunderstand/affect by something else

### ISSUE THREAD

**Issue by Alceatraz** [MicrosoftDocs/windows-itpro-docs#7978]
Hello:

I follow the guide and success config bitlock network unlock, All things working fine, But if I unplug workstation network cable, Make it absoulte disconnect, The workstation still boot up and login (show the login screen), Is this failed? Or system contains some cache can unlock disk even network disconnect ?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 91c13083-9b29-e54b-fd85-8033ec665fcd
* Version Independent ID: ce8c4647-69bc-95d4-2192-6e737d5ad5da
* Content: [BitLocker 如何启用网络解锁（Windows 10） - Microsoft 365 Security](https://docs.microsoft.com/zh-cn/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#%E7%BD%91%E7%BB%9C%E8%A7%A3%E9%94%81%E6%A0%B8%E5%BF%83%E8%A6%81%E6%B1%82network-unlock-core-requirements)
* Content Source: [windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

Unfortunately, I don't know this subject well enough to give you a guaranteed correct answer.

Maybe someone from the technical writers' team will reply to you some day (don't know when).

Until then, I will offer a guess on my part, that Network Unlock technology is not about locking a device or computer from user login directly from the console.

I am guessing that Network Unlock allows administration tools and WDS to access the device remotely, but does not block the operating system if network is disconnected.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
Note to myself: There is a broken link anchor in this page, only visible on the /en-us/ page, the HTML tag `</a>` is missing from this heading:

- https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-how-to-enable-network-unlock#install-the-wds-server-role

**Comment by illfated** [comment]
@e0i : Do you know if it would be useful to have this ticket question answered by one of the tech writers, for future reference?
