### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by edinili** [MicrosoftDocs/windows-itpro-docs#8062]
The URL referenced on this page returns a 404.

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-containers-help-protect-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329b43eb-db67-4458-730a-65e21a5d95c2
* Version Independent ID: 3bb2c84f-60db-0512-c44c-e6c011c36285
* Content: [Policy CSP - DeviceGuard - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-deviceguard)
* Content Source: [windows/client-management/mdm/policy-csp-deviceguard.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-deviceguard.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Looks like there are a couple of alternatives on hand to deal with that issue:

1. Remove the text and its link (URL) since it is broken and the target page is either deleted or moved & changed.
2. Compare related pages and see if one of them is close enough to match the original page content.
3. Wait for however long it may take for the author who changed the page to resolve this issue.

Original page content in the web archives (Wayback Machine): https://web.archive.org/web/20180302010708/https://docs.microsoft.com/en-us/windows/security/hardware-protection/how-hardware-based-containers-help-protect-windows

Some of the challenges regarding the topic "containers" is that it means different things to different users. To developers, it may just as well mean "Docker" or related container solutions, whereas some IT Administrators may have their focus on VM containers in the Azure environment. Anyway, let me list a couple of alternative pages I have found during a quick search:

- https://docs.microsoft.com/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows
- https://www.microsoft.com/security/blog/2017/10/23/hardening-the-system-and-maintaining-integrity-with-windows-defender-system-guard/ (2017 blog in the same style as the working URL)
- https://docs.microsoft.com/windows/security/threat-protection/windows-defender-system-guard/system-guard-secure-launch-and-smm-protection
- https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/overview-hardware-based-isolation

**Comment by RAJU2529** [comment]
I think most equivalent link 

**https://docs.microsoft.com/windows/security/threat-protection/windows-defender-system-guard/how-hardware-based-root-of-trust-helps-protect-windows**

**Comment by illfated** [comment]
Fair enough, looks like a useful choice. Would you like to make a PR for it, or do you think we should ask for confirmation from the MS Docs team members before suggesting that change?

**Comment by RAJU2529** [comment]
@illfated . You  create PR

**Comment by e0i** [comment]
The issue is in the backlog and one of the independent contributors is going to provide a correction soon. Thank you for discussion.

**Comment by e0i** [comment]
The broken link has been replaced via #8134.
