### ISSUE TITLE
Bitlocker

### ISSUE THREAD

**Issue by jorgelhp** [MicrosoftDocs/windows-itpro-docs#8129]
Good afternoon.

Bitlocker has the function of Enable automatic unlock.

My doubt is:

I have 2 units ...
one with operating system, and one with data.

The operating system unit in addition to Bitlocker has system protection by itself.

Is the automatic data unlocking enabled, if a person formats the operating system unit, will they have access to the data unit, since automatic unlocking is enabled and still on the same machine?

**Comment by e0i** [comment]
@jorgelhp 

Would you be able to clarify which article this problem stems from? What exactly is misleading within the article?

We would like to follow-up with content updates accordingly.

Thank you for providing feedback.

**Comment by jorgelhp** [comment]
I did not understand.

Looking for help on windows10 bitlocker...

**Comment by e0i** [comment]
@jorgelhp 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
