### ISSUE TITLE
Clarify Supported Browsers

### ISSUE THREAD

**Issue by DanielWahlgren** [MicrosoftDocs/windows-itpro-docs#8212]
Hi,
The documentation does not list suppored browsers under "Prerequisites", leading readers to believe Chrome/Firefox, as referenced in User experience, is only examples of browsers where Network Protection is used to enable web content filtering.

Tests using Opera show that while Network Protection works, Web Content Filtering does not.

Please also improve the text regarding this product being in Public Preview. As is, it is not stated, just that the documentation has some information that may be about things that are not yet fully released.

Other than that, thank you everyone involed for the great work you do with the documentation. I use it almost daily and it truly is a great resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d1d825-ab12-2f37-b692-5266487ef16f
* Version Independent ID: fef750ac-311b-28b4-1661-16385997815b
* Content: [Web content filtering - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/web-content-filtering.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
Hi @DanielWahlgren. Yes we are currently in public preview. That is the legal text we use to say that the product has not been fully released. 

All browsers and 3rd party applications are supported (though not native integration) through the network protection stack. The sites in WCF should be blocked in Opera, Firefox and Chrome. We just tested Opera and don’t see any issues (screen shot below). Make sure your policies are set up correctly. 

Because the user experience is not the same as Edge (see below as well), some users may not realize that the connection is blocked. The notification becomes browser dependent (see how firefox is also different) and a toast is issued. The toast is also suppressed and timed so users are not getting bombarded with notifications (for example when a site attempts to open multiple blocked sites that are embedded). 

Hope that helps!

Opera: ![image](https://user-images.githubusercontent.com/40870842/92655736-b72e9e00-f2a6-11ea-8fba-6e316303f5a4.png)
Firefox: ![image](https://user-images.githubusercontent.com/40870842/92655841-dc231100-f2a6-11ea-9df9-0e0cece74bd5.png)
Edge: ![image](https://user-images.githubusercontent.com/40870842/92655928-01178400-f2a7-11ea-8a8e-d5fc80b48250.png)
