### ISSUE TITLE
Can you add an example on how to use this?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/windows-itpro-docs#8231]
Can you add an example on how to use this?

Most other CSP reference pages have at least one example.

Nothing on the internet about how to use this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53820d20-c512-286d-d5ce-c2f208d3eedd
* Version Independent ID: 19d56d9d-4ddf-b4ff-3f0a-f57766b42bc7
* Content: [Registry CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/registry-csp)
* Content Source: [windows/client-management/mdm/registry-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/registry-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @mtwelve - Thank you for posting your query. Please note that Registry CSP is only for Windows 10 Mobile OEM configuration. There are other pre-requisite that needs should be used as before using this CSP. Please see the note 
![image](https://user-images.githubusercontent.com/47118050/99178621-e9d99480-2736-11eb-87ea-09fd0acd0a66.png)

Because of this reason, no associated example can be added for this CSP.  If there is anything specific you are looking for, please contact Microsoft Support.

Thanks.
Imran.
