### ISSUE TITLE
Windows 2004 default VErsion is missing

### ISSUE THREAD

**Issue by SteBeSec** [MicrosoftDocs/windows-itpro-docs#8232]
Unter the part [Platform version included with Windows 10 releases](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus?ocid=cx-kb-mocamp#platform-version-included-with-windows-10-releases) the Windows Version 2004 is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1528404e-3ead-d3aa-e0aa-59e5a8b4889a
* Version Independent ID: d8c3bf1c-232e-a388-326d-830447baef19
* Content: [Manage Microsoft Defender Antivirus updates and apply baselines - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus?ocid=cx-kb-mocamp)
* Content Source: [windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
I wonder if this can be deduced from the fact that the release date of Version 2004 is May 27, 2020 and pick the matching version information from the pivot chart https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus?ocid=cx-kb-mocamp#monthly-platform-and-engine-versions :

May-2020 (Platform: 4.18.2005.4 | Engine: 1.1.17100.2)
 Security intelligence update version: **1.317.20.0**
 Released: **May 26, 2020**
 Platform: **4.18.2005.4**
 Engine: **1.1.17100.2**
 Support phase: **Technical upgrade Support (Only)**

**Comment by Cyberchipz** [comment]
I ran across a **potential exploit** on my system using iexplorer & mshta.exe earlier this month; first I've seen something like this potential "fileless malware" in action.  I began researching mitigation via an article "Out of sight but not invisible: Defeating fileless malware with behavior monitoring, AMSI, and next-gen AV" and the path led me to the article "Microsoft recommended block rules" and ultimately here.  I was wondering, since this isn't available, if it's still needed; I presume yes.  **_And if so, is there any indication of when we'll see new parameters?_**

I've been an IT most of my life, I'm 67 and retired, use Defender ATP, and CFA (Controlled folder access).  I occasionally run into issues which which Microsoft processes to allow access; and was looking for a list of rules or additional mitigation techniques and was reading and learning to apply these rules when I noticed 2004 was missing. 

I am hoping since _whatever_ didn't get the folder access it apparently wanted, the attack was mitigated.  I find it ironic that this occurred the same day; but within a few days after I upgraded firmware on a piece of networked equipment! 8-o  I don't believe in coincidence; but almost a week could be coincidental.  I'm thinking Microsoft should pop alerts when a block by this is initiated; or at least something I could see more handily than visiting the CFA section.

Since the system runs quite well most of the time with CFA and often it's obvious what to give permissions to; and since I had no guidelines, I presently remove permissions once a task is complete; I'm seeking to expand my repertoire.  The potential exploit was accompanied by iexplorer and within milliseconds the mshta.exe failure to access folders. When I discovered it my internal alarms went off.  So, I'm also seeking advice.  

I would like to implement this list of Block Rules, considering the existing climate and it being an election year; I'm not surprised to run into something 'new to me' I didn't recognize.  It appears that the attempt was unsuccessful; but, how would one know other than nothing obvious happened.  I only discovered it when I was doing something that _might_ have generated a block via CFA, went to check and saw the iexplore and mshta blocks mentioned above.  Since blocks are fairly rare events for me.  Of course I research them.

With so many issues being listed, this but being one of them; I'm just looking for advice before I attempt to follow and attempt the actions suggested by 'illfated' in his post above.  I'm not completely over my head here; but, this _is_ a new 'thing' for me.

**_Any help would be much appreciated!  Is this ruleset being depreciated since 2004_**. Or, this is just a side issue since it has not been updated since 2004 came ou? Or am I just an early bird?  And I guess I should ask, would implementing this rule set assist in mitigation (obviously yes) but would it help specifically with mitigating fileless attacks like this "living off the land", my land, our land, my machine, my network?

I've always followed the advances in attack methods, like one gawks at a wreck on the highway. I've been a White Hat since my youth; but, sometimes wearing that hat leaves me, perhaps...not "quite" as curious about playing around; a disadvantage I acknowledge.  I have at the least a basic grasp of what's happening since my first developments were in Machine language, and I've followed OS technology since C64, Timex Sinclair, TRS80 and TI 99/4! lol  At 16, I bottle fed coding on an IBM 360 in the late 60's. :-/  Man I feel old.

Thank you ahead of time for any help.  This is also my first time using Github for anything like what I'm here for today.

**Comment by illfated** [comment]
@Cyberchipz : Thank you for the informative post and quite interesting read. I hope the current feedback will be able to highlight the need for accurate and up-to-date information, especially when it comes to security software. I can only advice patience with the procedures to have the documentation updated.

Please note / disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

Also, in case you are in need of more direct feedback for any software security issues or similarly related challenges in the operating system, I recommend joining the Microsoft forums to get in touch with fellow users for a more "hands-on" dialogue.

**Comment by e0i** [comment]
Hello, @SteBeSec Thank you for sharing in-depth with the community your experiences and concerns. 

The content has been revised according to your feedback and the missing version detail have been included via PR #8477.

Feel free to re-open this issue with a discussion if you feel that the your concerns have not been addressed documentation-wise. Thank you again, and stay healthy.
