### ISSUE TITLE
Allow Download folder in Assigned access mode Windows 10 is not working 

### ISSUE THREAD

**Issue by rashidkeezhal** [MicrosoftDocs/windows-itpro-docs#8237]
I cannot allow downloads folder in multi app kiosk mode (Assigned access) in Windows 10 64X (2004). 

This is the code I am trying to enable downloads folder and getting error.

            <rs5:FileExplorerNamespaceRestrictions>
                <rs5:AllowedNamespace Name="Downloads"/>
            </rs5:FileExplorerNamespaceRestrictions>

Full XML code attached
[Code.txt](https://github.com/MicrosoftDocs/windows-itpro-docs/files/5187869/Code.txt)

Error is: 

Set-CimInstance : A general error occurred that is not covered by a more specific error code.
At line:1 char:1
+ Set-CimInstance -CimInstance $obj
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MDM_AssignedAcc..../Vendor/MSFT"):CimInstance) [Set-CimInstance], CimE
   xception
    + FullyQualifiedErrorId : MI RESULT 1,Microsoft.Management.Infrastructure.CimCmdlets.SetCimInstanceCommand

**Comment by RAJU2529** [comment]
@rashidkeezhal . which article are you referring ?
I don't have knowledge about kiosk mode.

instead of writing simply downloads, write the full path of the downloads folder.

**Comment by rashidkeezhal** [comment]
> @rashidkeezhal . which article are you referring ?
> 
> I don't have knowledge about kiosk mode.
> 
> 
> 
> instead of writing simply downloads, write the full path of the downloads folder.

@RAJU2529 This is for windows 10 AssignedAccess (KIOSK Mode). And only downloads folder allowed using mentioned command. (C:\Users\*username*\downloads)

**Comment by e0i** [comment]
Hello, @rashidkeezhal  thank you for providing feedback.

The issues section of this repository is intended for documentation feedback.

Please consider opening a support ticket via the following link for your question so that it gets answered quickly:

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this ticket if you feel that documentation also needs to be updated.
