### ISSUE TITLE
Operating system deployment did not complete successfully

### ISSUE THREAD

**Issue by EagleChops** [MicrosoftDocs/windows-itpro-docs#8251]
The above is the title of my Deployment Summary after the task sequence fails. Expanding the Details it starts with:
FAILURE ( 5616 ): 15299 Verify BCDBootEx  and then there are several lines which can't be copied and don't have time stamps.

I'm hoping for some assistance here and thought GitHub was the place to seek it. I can provide logs and what ever other pertinent info may be of use.

Also, I just happened to notice that my log files are from the future. Not sure how that happens but it's probably not a positive thing ...

Thanks!
EC

**Comment by RAJU2529** [comment]
@EagleChops , could you tell me which instructions did you followed, and which operating system did you tried to installing? 
did the motherboard and all related parts to compatible with each other,

**Comment by e0i** [comment]
@EagleChops 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

The issues section of this repository is being used to track problems related to the documentation articles.

Thank you.

**Comment by EagleChops** [comment]
Thanks e0i I'll do that.
