### ISSUE TITLE
NoAutoRebootWithLoggedOnUsers does not work

### ISSUE THREAD

**Issue by c0f** [MicrosoftDocs/windows-itpro-docs#8258]
Hi, Setting NoAutoRebootWithLoggedOnUsers via the Registry or GP does not work.  Windows Update will continue to automatically reboot even with logged in users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184809a-63ff-ecc2-ab67-9c9f4df900f8
* Version Independent ID: ac25ee6c-4c57-58b3-1313-e4a53f53c5a1
* Content: [Manage device restarts after updates (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-restart)
* Content Source: [windows/deployment/update/waas-restart.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-restart.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@arcarley can you advise?

**Comment by arcarley** [comment]
@c0f you likely have configured other policies that take precedence over "NoAutoRebootWithLoggedOnUsers". Typically, I would not recommend using this policy and instead utilize Active Hours in order to prevent updates during active hours until the deadline. This will also prevent automatic reboots when the user is using the device until the deadline is reached.

**Comment by e0i** [comment]
Hello @c0f 

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
