### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#8298]
Hello,
Discovered that after "WIP profiles" or "Azure portal" was updated by Microsoft, our WIP profile lost the EFS DRA certificate in profile. We have documentation of the initial setup we did, and the certificate was present in the WIP profile and in the computer registry. By working with MS Support, they inform that cannot find the reason.

Question for the following situation, maybe someone can help:

1. WIP profile deployed to all devices
2. Some devices do have certificate present and some newer enrolled don't
3. If we add the certificate back, on the devices where the EFS DRA certificate already exists, all will be working fine? What will happen with the EFS DRA certificate that already exists and with a new one?

If we do a test in a way that we use groups like include/exclude the devices from WIP profiles, then in the reality it is unassigning one profile and assigning another profile, so not a good test :)

Then maybe it will be good to add an FAQ, like: "how to proceed if certificate removed from WIP profile and how to add it back"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e6e551-830e-f69e-31bc-e109e5b594f4
* Version Independent ID: 3396045c-8295-b801-aba5-11a11dd62dc0
* Content: [Make & verify an EFS Data Recovery Agent certificate (Windows 10) - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate)
* Content Source: [windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/windows-information-protection/create-and-verify-an-efs-dra-certificate.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by nhanla** [comment]
Hello fellow, 

I'm having an issue about WIP DRA too:
1. I've created DRA and upload to Intune => great
2. On Azure AD Joined client, using cipher /c I can see the work data can restore with Recovery Certificates I just uploaded => great
3. On Hybrid Azure AD Joined client, it show Administrator/domainlocal Recovery Certificate instead of my DRA certificate, why?

Here is my record, you can view for more details: https://ocis4-my.sharepoint.com/:v:/g/personal/lanhan_sg_cmc_com_vn/Ef-p6kPfYT5BhWMxdBxZKw8B1buL4gFp1Rl5o_U7cmMD5A?e=DLQOyC
