### ISSUE TITLE
Intune - WIP - DRA certificate for Hybrid Azure AD Joined

### ISSUE THREAD

**Issue by nhanla** [MicrosoftDocs/windows-itpro-docs#8317]
Hello fellow,

I'm having an issue about WIP DRA:

1. I've created DRA and upload to Intune => great
2. On Azure AD Joined client, using cipher /c I can see the work data can restore with Recovery Certificates I just uploaded => great
3. On Hybrid Azure AD Joined client, it show Administrator/domainlocal Recovery Certificate instead of my DRA certificate, why?

Thank you guys.

**Comment by e0i** [comment]
The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
