### ISSUE TITLE
Bluetooth Pairing link is broken

### ISSUE THREAD

**Issue by Ben-Montgomery** [MicrosoftDocs/windows-itpro-docs#8328]
The link for Bluetooth Pairing is broken ("Improving your Bluetooth pairing experience").

**Comment by e0i** [comment]
The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
