### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by deavisdude** [MicrosoftDocs/windows-itpro-docs#8344]
[Enter feedback here]
I am trying to repair my frequently crashing windows pc using DISM. Unfortunately the component store has been corrupted so I was directed here to attempt to fix the problem.
My issues when following this guide:
    Step 3: file not found
    Step 4: files not found
    Step 5: about 40% of the files are missing
    Finally: after a reboot dism still cannot fix my PC
Any idea what I can do now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
@deavisdude : Missing files or folders do not necessarily mean that failing to get a result from deleting or renaming should cause the procedure to fail completely. There can be other reasons why Windows Update does not work for you. When comparing with a working Windows Update, some files do not exist on my system:

```
Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>Dir "%ALLUSERSPROFILE%\Application Data\Microsoft\Network\Downloader\qmgr*.dat"
 Volume in drive C is Samsung SSD 840 EVO 250GB
 Volume Serial Number is 22DB-96F8

 Directory of C:\ProgramData\Application Data\Microsoft\Network\Downloader

File Not Found

C:\WINDOWS\system32>Del "%ALLUSERSPROFILE%\Application Data\Microsoft\Network\Downloader\qmgr*.dat"
Could Not Find C:\ProgramData\Application Data\Microsoft\Network\Downloader\qmgr*.dat

C:\WINDOWS\system32>_
```

From your comment: Step 5: about 40% of the files are missing

As far as I can see, Step 5 in the page says the following:
```
cd /d %windir%\system32
```

You may want to run `msdt.exe` or the Windows Updates Troubleshooting Wizard.

By the way, your issue might be caused by something more than what is covered in the page, even though the page content targets many Windows Update issues.

For example, I had to run the `MediaCreationTool2004.exe` program from https://www.microsoft.com/en-us/software-download/windows10 to restore Windows Update to a working state after KB4571756 failed to install with error 0x800f081f. The process may take several hours (my computer took 4 hours at least), just make sure that the process has selected to keep all files and settings.

Also, for me, it seemed to be important to have run the Windows Updates Troubleshooter first, which fixed 2 or 3 incorrect settings (registry entries/services) before running the full upgrade via MediaCreationTool2004.

**Comment by RAJU2529** [comment]
use offline sfc Scannow using install.wim  
or use dism  restore health 
search dism online command

**Comment by illfated** [comment]
@deavisdude : if possible, I recommend running some of the repair wizards, just to make sure that any trivial issues get corrected by the OS itself.

**Comment by e0i** [comment]
Hello @deavisdude 

The issue is being closed since your question seems to be answered by the community. 

Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
