### ISSUE TITLE
The scripts mentioned on this page are hosted at Technet Gallery which is closing down

### ISSUE THREAD

**Issue by desbest** [MicrosoftDocs/windows-itpro-docs#8357]
The scripts mentioned on this page are hosted at Technet Gallery which is closing down
Someone should move the scripts somewhere else to the article still works.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886426b5-8548-1cfc-ccd2-fd03e549c967
* Version Independent ID: 599aea76-47e4-dccc-799c-2d8acf549546
* Content: [Windows Update - Additional resources - Windows Deployment](https://docs.microsoft.com/en-gb/windows/deployment/update/windows-update-resources)
* Content Source: [windows/deployment/update/windows-update-resources.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-resources.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
I notice you have created a PR to suggest adding a backup link on this page, (#8358 **Technet Gallery is shutting down**).

The motivation and idea is good, although I think Microsoft Docs will need to store the backup on a page owned by the organization.

**Comment by illfated** [comment]
See also issue ticket #6841 (**Unclear wording**) where this topic has been discussed from a different angle (descriptive text interpretation).

Notice in particular that this script already has a GitHub page:

> Reading the Q & A section of that TechNet gallery page, I found that the script author has created both an introductory page (README.md) and a wiki page for this script tool, here on GitHub:
>
> - https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/README.md
> - https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/docs/wiki/en/Home.md

**Comment by desbest** [comment]
The script hosted on Technet Gallery is not on the github links provided.

**Comment by illfated** [comment]
Fair enough. I have not checked the contents, so there is that. I guess I just thought it was the same, seeing that the other ticket was created from the exact same page.

I see now that there are 2 separate scripts on the page:
- Reset Windows Update Client settings script - https://gallery.technet.microsoft.com/scriptcenter/Reset-WindowsUpdateps1-e0c5eb78 by Ryan Nemeth
- Reset Windows Update Agent script - https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc by Manuel F. Gil

By the way, I have looked up how this is connected now, finding that the GitHub page is the linked script page from Manuel F. Gil, who is the author of the same script as the one you have linked from your own gist in your PR. I know there is a difference between those scripts, but that is mainly because Manuel F. Gil has developed the script while hosting it on GitHub. Yes, it has changed, but has it changed so much that it doesn't work as described anymore?

Anyway, if the original script works and needs to be hosted somewhere else, I presume we need to wait until the Microsoft Docs team decides on a new hosting page in their own domain or within their own GitHub organization.

**Comment by e0i** [comment]
The author of this article group, **jaimeo** has checked with the SME to find out whether the scripts are to be hosted at Script Center or the Powershell Gallery. He has mentioned that, 

> We will find appropriate homes for these scripts.

https://github.com/MicrosoftDocs/windows-itpro-docs/pull/8358#issuecomment-700869107

Closing the issue based on the author’s response above. 

Thank you for the discussion.
