### ISSUE TITLE
Microsoft SQL Server 2012 SP4 Support?

### ISSUE THREAD

**Issue by sys228** [MicrosoftDocs/windows-itpro-docs#837]
Is Microsoft SQL Server 2012 SP4 now supported for MBAM 2.5 stand-alone topologies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd86f5e-6388-d226-2460-997fc24945d9
* Version Independent ID: aa827a7d-725a-a5d0-f6aa-3f1df8cc310a
* Content: [MBAM 2.5 Supported Configurations](https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/mbam-v25/mbam-25-supported-configurations)
* Content Source: [mdop/mbam-v25/mbam-25-supported-configurations.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/mdop/mbam-v25/mbam-25-supported-configurations.md)
* Service: **unspecified**
* GitHub Login: @jamiejdt
* Microsoft Alias: **jamiet**

**Comment by e0i** [comment]
Hello, @sys228  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
