### ISSUE TITLE
Windows ATP - dependency?

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/windows-itpro-docs#8428]
Does the Allow Telemetry GPO setting affect the Windows ATP now known as Windows Defender for Endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c364e-fcf4-8667-17d7-f9a3ec71e1a9
* Version Independent ID: f98f8870-d594-f5df-f6b6-44c9806db7d8
* Content: [Configure Windows diagnostic data in your organization (Windows 10) - Windows Privacy](https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization)
* Content Source: [windows/privacy/configure-windows-diagnostic-data-in-your-organization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/privacy/configure-windows-diagnostic-data-in-your-organization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Hello, @brink668  thank you for providing feedback.

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you.
