### ISSUE TITLE
Conflict of advice?

### ISSUE THREAD

**Issue by stevenoneill-jmfamily** [MicrosoftDocs/windows-itpro-docs#8458]
The advice regarding passive mode on this page appears to directly conflict with the advice on a linked page here:
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/microsoft-defender-antivirus-compatibility#fn1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#microsoft-defender-antivirus-configuration-requirement)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by nam31** [comment]
@stevenoneill-jmfamily can you please point out exactly which part of the document appears to directly conflict with the advice on the linked page?

**Comment by rogerxrp** [comment]
Felt the same - what is the recommended approach when using third party AV? is it to uninstall defender AV or set to passive with EDR on block mode on?
------- Here are the two statements -----
If you install a third-party antivirus product, you should **consider uninstalling** Microsoft Defender Antivirus on Windows Server 2016 or 2019 to prevent problems caused by having multiple antivirus products installed on a machine.

If you are using Windows Server, version 1803 or Windows Server 2019, you **can enable passive mode** by setting this registry key:

**Comment by VLG17** [comment]
@stevenoneill-jmfamily @rogerxrp [The article that has a contradicting statement](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements#microsoft-defender-antivirus-configuration-requirement) talks about a specific scenario, onboarding **servers** (not aplicable to client endpoints) to Microsoft Defender for Endpoint. My understanding is that having Microsoft Defender Antivirus installed (passive mode) is a prerequisite in order to be able to onboard. More details [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/switch-to-microsoft-defender-setup).

> **If you are onboarding servers** and Microsoft Defender Antivirus is not the active antimalware on your servers, you shouldn't uninstall Microsoft Defender Antivirus. You'll need to configure it to run on passive mode. For more information, see Onboard servers.


The recommendation is described under the FAQ for [Antivirus and antimalware software](https://support.microsoft.com/en-us/windows/antivirus-and-antimalware-software-faq-31f2a46e-fad6-b713-45cf-b9db579973e6#multiple-products)

![image](https://user-images.githubusercontent.com/41186174/100268299-749f6800-2f5d-11eb-9862-de2d5495c851.png)

**Comment by stevenoneill** [comment]
For example, my understanding from observation and practice is that Windows 2016 Servers are on-boarded via Microsoft Monitoring Agent.  That is, you can onboard via MMA even after uninstalling Windows Defender.  I don't think Defender has anything to do with the on-boarding process.  

So maybe an additional contradiction in addition to the original one?

**Comment by nam31** [comment]
Hi @mjcaparas, can you please give your insights here?

**Comment by mjcaparas** [comment]
The guidance on the minimum requirements page is provided generic, while details are provided on the link "For more information, see Microsoft Defender Antivirus compatibility".

I can understand though that this might be confusing. I'll update the statement to state depending on the server version, Microsoft Defender Antivirus will need to be configured accordingly.
