### ISSUE TITLE
Create an NDES-Intune authentication certificate template

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/windows-itpro-docs#8527]
Hello,

When running step: "Create an NDES-Intune authentication certificate template"
The default compatibility is for "Windows Server 2003", this is fine to keep like this or maybe 2012 or 2016 must be selected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f709fd4-0b5d-b238-4060-222d550cd538
* Version Independent ID: fb3f29da-2236-c47d-6bea-8efbcec8d7d3
* Content: [Using Certificates for AADJ On-premises Single-sign On single sign-on - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-hybrid-aadj-sso-cert.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by nam31** [comment]
@lightupdifire Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.

**Comment by lightupdifire** [comment]
@nam31 
The question was addresses to the documentation only. Most people onboarding to the Windows Server **2019**, but in THIS documentation print screens are with Windows Server **2003** for default compatibility.
Then question to document owners, why it is not well explained which other compatibility can be selected to build this setup in **2020**?

**Comment by nam31** [comment]
I will assign this to our team for investigation. Thank you for your contribution to making the docs better. Much appreciated.

**Comment by MaratMussabekov** [comment]
Hello @lightupdifire ,
it wasn't mentioned in the article because the default value should be left. 
In fact, you can select whatever compatibility option from that list, it will not change anything. 

**Most people onboarding to the Windows Server 2019, but in THIS documentation print screens are with Windows Server 2003 for default compatibility.** - compatibility with Windows Server 2003 means that there could be problems if versions _prior_ to Windows Server 2003 are used, it will not cause any problem to any Windows Server version after 2003.

**why it is not well explained which other compatibility can be selected to build this setup in 2020?** - I believe current state is perfectly fine, why it should be mentioned if the default value is ok? I mean, if you duplicate the template, there are 11 tabs of options presented, it is an obvious decision to describe only the options that should be changed. If the author will describe all the options that should be left by default, the article will be overloaded.

Thank you

**Comment by lightupdifire** [comment]
@MaratMussabekov 
Then please add at least "In fact, you can select whatever compatibility option from that list, it will not change anything."
Else, when we planning Security, thinking of new versions, etc. the humanity force us to select highest available and supported version, but you don't know if this version will work. And if running setup on Server 2019, immidetely have a questions about compatibility of 2003, will it work? Who knows? What if we follow all steps until end and we will receive an error, then is it possible that it is due compatibility 2003<>2019?

**Comment by MaratMussabekov** [comment]
Hello,
I am still not sure whether it worth mentioning, since the parameter doesn't change anything in the context of deployment of AAD Join single-sign on.
Dear @nam31 , would it be possible to contact the owner of the article?

Thank you

**Comment by mapalko** [comment]
I'm in agreement with Marat. When setting up a certificate template there are a ton of different options available that can be changed or modified. We only specify the options that should be modified and must be set. It is not possible to have a full list of all compatible options or configurations. 

Changing the compatibility setting generally changes the options that are available for configuration on a template. Setting an older version means, any newer features added in a later server version will not be able to be configured. In this case, because we do not need any newer features added after the default value, we don't change the compatibility version. If you change to a later compatibility version it should not remove the existing capabilities. For more information see: https://social.technet.microsoft.com/wiki/contents/articles/13303.windows-server-2012-certificate-template-versions-and-options.aspx

**Comment by lightupdifire** [comment]
@mapalko 
We don't need all ton of the different options. We need a configuration that will make this setup to work, but please understand that we are running in 2020 and focusing on Security and we try to onboard all maximum possible newest features and options available. 

Server 2003 and Server 2008 out of support, why should we select anything related to those versions? 

And again, you share article to the server 2012, that Applies to Windows Server 2012, I have seen this in many Microsoft docs, referring to the old articles when you try to set up the new 2016/2019 server/services, where settings different, print screens different, decisions different, etc. For me as a customer it sounds like: here is your new 2020 car, it can do like this and like that, but if you like to change something, go to the garage for old spare parts :) 

From my side, it was just advice, for making the documentation better, so the next person, who will try setting up the same, and maybe will run already Windows Server 2021, will not think about 2003 or 2008 server versions and its compatibility.

If you think that it is nothing to add to this document, then please let's close this comment discussion.
