### ISSUE TITLE
Trial link is a loop

### ISSUE THREAD

**Issue by charles-James-River** [MicrosoftDocs/windows-itpro-docs#8565]
The link to start a trial doesn't end on a page where you can start a trial, if you click Get Started it leads you back to the documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bdb99e4-289a-c09a-c35c-2774fc52a402
* Version Independent ID: 4d325389-c9b8-2601-0ff4-c7b6bf5a6c28
* Content: [Microsoft Defender Advanced Threat Protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
OK. I see. It took me a little while to understand that this is about the link on the www.microsoft.com page (which I assume does not have any direct way to report).

- docs.microsoft.com page: https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-advanced-threat-protection
| Want to experience Microsoft Defender ATP? [Sign up for a free trial.](https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp?ocid=docs-wdatp-main-abovefoldlink)

- Microsoft 365 page: https://www.microsoft.com/microsoft-365/windows/microsoft-defender-atp?ocid=docs-wdatp-main-abovefoldlink
(where the text "Get Started" can be found below 2 buttons)

I must have messed up something, because after my first visit, then closing the tabs, I can not open the page again due to some unexpected user access violation issue.

**Comment by charles-James-River** [comment]
Ya sorry, I could have been more clear. 

Expected: Click on "Sign up for a free trial" and get to a place where you can start a trial or request to start a trial through an onboarding process. 

Actual: Click on "Sign up for a free trial" - no way to start or request to start a trial, only link that sounds like it would start a trial "Get Started" takes you back to documentation (loop) other links on the page (purchase, contact) are generic pages that do not directly reference the Defender for Endpoints SKU thus themselves do not have a way to start the Defender for Endpoints trial.

**Comment by illfated** [comment]
See Pull Request #8603 for removal of that incorrect text.
Reasoning: "Microsoft Defender for Endpoint is a part of Microsoft 365 enterprise, which doesn't have a trial version."

**Comment by nam31** [comment]
Closing via #8603
