### ISSUE TITLE
Wrong download link for Mixed Reality FOD

### ISSUE THREAD

**Issue by byleistr** [MicrosoftDocs/windows-itpro-docs#8574]
Source: windows/application-management/manage-windows-mixed-reality.md

The download links for the Mixed Reality FOD .cab files for versions 2004 and 1909 point to identical files, although differently named. Check out the md5 sums:
Microsoft-Windows-Holographic-Desktop-FOD-Package~31bf3856ad364e35~amd64~~.cab:
94c065bd11cd6881bf90ece5d4235ea1  
Microsoft-Windows-Holographic-Desktop-FOD-Package-31bf3856ad364e35-amd64.cab:
94c065bd11cd6881bf90ece5d4235ea1  

In fact, the both contain the FOD for OS build 18362 (aka 1909), so the link for version 2004 seems to be wrong.
Also, is there a new FOD .cab for 20H2?

**Comment by RAJU2529** [comment]
@byleistr . Which article are you referring to?. I think new .cab file might be release by 20h2 team within 2022

**Comment by byleistr** [comment]
@RAJU2529 
This one: [Enable or block Windows Mixed Reality apps in enterprises](https://docs.microsoft.com/en-us/windows/application-management/manage-windows-mixed-reality)

**Comment by illfated** [comment]
Since this is about a page that does not seem to have any Edit button or Feedback blob, we would need to edit the GitHub page directly to suggest changes.

@byleistr : Just to let you know; GitHub pages (comments in particular, but also `.md` pages) uses MarkDown interpretation of its content. As such, it usually interpretes the occurrence of double tilde characters, before and after text, as a tag to use the ~~strikethrough~~ format.

Therefore, I have quoted your comment from above, to add a MarkDown (MD) code block fence around your referenced code below:

> Source: [windows/application-management/manage-windows-mixed-reality.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/application-management/manage-windows-mixed-reality.md)
>
> ```
> The download links for the Mixed Reality FOD .cab files for versions 2004 and 1909 point to identical files, although differently named. Check out the md5 sums:
> Microsoft-Windows-Holographic-Desktop-FOD-Package~31bf3856ad364e35~amd64~~.cab:
> 94c065bd11cd6881bf90ece5d4235ea1
> Microsoft-Windows-Holographic-Desktop-FOD-Package-31bf3856ad364e35-amd64.cab:
> 94c065bd11cd6881bf90ece5d4235ea1
> ```
>
> In fact, the both contain the FOD for OS build 18362 (aka 1909), so the link for version 2004 seems to be wrong.
> Also, is there a new FoD .cab for 20H2?

I am not quite sure if I can start making a suggestion to change the content yet, before this gets confirmed by one of the MS Docs team members or one of the MS Docs team tech writers.

**Comment by MaratMussabekov** [comment]
Dear @tmlyon,
link to the updated FOD file, added by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/71b3d5e0a37363ae00149d8ffc6267cb5dcf9b16#diff-63a5fb093b9fc2e0d1d7e9a16d35acea8d139a03a893aa4167634b2648707822 seems to be incorrect, could you please advise, which link should be used here?
Issue also mentioned in https://github.com/MicrosoftDocs/feedback/issues/2739

Thank you
