### ISSUE TITLE
Broken link to MSDN blog

### ISSUE THREAD

**Issue by loganrosen** [MicrosoftDocs/windows-itpro-docs#8579]
There's a broken link to [Protecting the pre-OS environment with UEFI](https://blogs.msdn.com/b/b8/archive/2011/09/22/protecting-the-pre-os-environment-with-uefi.aspx) on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c795c8ef-7caf-b8a7-4118-b00b1899eef8
* Version Independent ID: cd85b6b4-d160-0c44-15ea-4b7c02fbe0eb
* Content: [Secure the Windows 10 boot process - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/secure-the-windows-10-boot-process)
* Content Source: [windows/security/information-protection/secure-the-windows-10-boot-process.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/secure-the-windows-10-boot-process.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Thank you for reporting the broken link. I do my best to keep an eye out for reports like this one, because correcting the links is a fairly straightforward task.

Unfortunately, the document is no longer located within the microsoft.com domain and can therefore no longer be updated in that link. Unless the original author decides to upload the document to microsoft.com and verify that it is restored and authentic, we can only suggest external references to the original document from 2011:

- https://web.archive.org/web/20120131151529/http://blogs.msdn.com/b/b8/archive/2011/09/22/protecting-the-pre-os-environment-with-uefi.aspx
- https://www.ghacks.net/2011/09/23/windows-8-boot-security-and-third-party-operating-systems/

As you can see above, I was only able to find verbatim copies of the document in the WayBack Machine (web.archive.org) and on the site ghacks.net .

**Comment by illfated** [comment]
See also Pull Request #8604 for removal of the outdated link and its text description.

**Comment by nam31** [comment]
Closing via #8604 
Thanks
