### ISSUE TITLE
XPS Outstanding Issue

### ISSUE THREAD

**Issue by wattsdp** [MicrosoftDocs/windows-itpro-docs#858]
I see that there was a change in how XPS Viewer is managed in 1803, but was there a change in the app that will fix the issue with the version in 1709?  It would constantly crash when trying to copy data from an XPS document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c274f8df-31da-f58a-36af-dc7eb6ace762
* Version Independent ID: 0e33637d-e094-edbc-04f9-e8d5e6c642c6
* Content: [Windows 10, version 1803 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1803-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1803-removed-features.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Noemata** [comment]
The XPS Viewer copy/paste was intentionally broken (by the left hand of Microsoft) to try and wean folks off using this feature since it was scheduled to be deprecated.  What better way to get folks to stop using a feature than to break it.

Unfortunately, Microsoft want's us to drink the Kool Aid on certain tech initiatives, like XPS, but when we actually do Microsoft is seemingly surprised by our stupidity.

At Microsoft, the right hand doesn't always know what the left hand is doing.  The infighting still persists.

It's safe to assume the XPS Viewer copy/paste bug will never be fixed because the left hand of Microsoft wants us to switch to PDF.  You'll have to take it up with the right hand if you want this fixed.

**Comment by lizap** [comment]
Probably your best bet for getting help with the XPS Viewer is over at support.microsoft.com. Here's a [query](https://support.microsoft.com/en-us/search?query=xps%20crashes) that might be useful. Thanks for your comment - I apologize for not having more information for you.
