### ISSUE TITLE
The position of the "Important" section of Update/AllowAutoUpdate is incorrect. (Update/AllowAutoUpdate の「Important」セクションの位置が正しくありません)

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [MicrosoftDocs/windows-itpro-docs#8580]
The "Important" section of Update/AllowAutoUpdate should properly be listed right after the support value number 5.
※I am translating from Japanese to English using a translation service.

Japanese (日本語) :
Update/AllowAutoUpdate の「重要」セクションは、正しくはサポート値5番の直後に記載する必要があります。
※翻訳サービスを使用して、日本語から英語に翻訳しています。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ca58bd-f279-7739-0140-c4bd56784768
* Version Independent ID: 1d2ecc90-58a3-6bcd-84ae-ef04d7a3b7b4
* Content: [Policy CSP - Update - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-update#feedback)
* Content Source: [windows/client-management/mdm/policy-csp-update.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-update.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
Oh. Right. It took me a while to understand what you referred to, but now I see it. Both the English (en-us) and the translated versions of this page shows the 
![image](https://user-images.githubusercontent.com/38162891/98127150-a79e9080-1eb6-11eb-9b81-e3277e5f1f0b.png) blob directly below the policy support table, instead of after the explanation description further down on the page.

I also see why it would be more sensible to connect the 
![image](https://user-images.githubusercontent.com/38162891/98127291-cef55d80-1eb6-11eb-8158-3ae953f24add.png) blob after "the supported values list" (0 - 5), below point 5, to make it clear that the important message is about the last entry (5 – Turn off automatic updates.)

I will perform an edit, complete a PR and wait for it to be accepted by the MS Docs team as an update to this page. Thank you for pointing out the logical confusion.

---
ああ。 正しい。 あなたが何を言っているのか理解するのに少し時間がかかりましたが、今はわかりました。 このページの英語版（en-us）と翻訳版の両方で、ページのさらに下の説明の説明の後ではなく、ポリシーサポートテーブルのすぐ下に画像のブロブが表示されます。

また、ポイント5の下の「サポートされている値のリスト」（0-5）の後に画像blobを接続して、重要なメッセージが最後のエントリに関するものであることを明確にする方が賢明な理由もわかります（5 –自動をオフにする 更新。）

編集を行い、PRを完了し、このページの更新としてMicrosoft Docsチームに受け入れられるのを待ちます。 論理的な混乱を指摘していただきありがとうございます。
