### ISSUE TITLE
registry value location 

### ISSUE THREAD

**Issue by liuxuechen8844** [MicrosoftDocs/windows-itpro-docs#8585]
The registry value will created under the path "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection" if running the PowerShell command to enable it. However, the created path is different as the one you provided in the article. It is confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71868539-63d8-b250-f9d4-83a4052f4f74
* Version Independent ID: ed5658cf-173f-47bf-ed76-a68d89ea5c4b
* Content: [Turn on network protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection?source=docs)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by RAJU2529** [comment]
@liuxuechen8844 . If possible ,, tell me the created registry  path location by powershell command

**Comment by VLG17** [comment]
The article states that the regkey is under: Computer ->HKEY_LOCAL_MACHINE -> SOFTWARE > Policies > Microsoft > Windows Defender > Windows Defender Exploit Guard > Network Protection

You are stating that it's under: Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection

All the public documentation is confirming what the article states. Could you share a printscreen of what you're seeing and the Windows version that you are using?

**Comment by RAJU2529** [comment]
@VLG17 .  i understood like below,  
 when the users enable  network protection  through the group policy editor, then registry keys will be created under this path 
**Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection**

but the  when the users enable  network protection using PowerShell command, then the registry key will be modified or newly created under this path 
**Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection**

**Comment by VLG17** [comment]
@RAJU2529 My understanding is that the issue is not around the difference between using group policy vs powershell in terms of location, but between what he's seeing in his environment when using Powershell and what the article states.

All my findings confirm the article so that why I asked for a printscreen of what @liuxuechen8844 is seeing.

**Comment by nam31** [comment]
@liuxuechen8844 Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
