### ISSUE TITLE
Something seems wrong with a sentence..

### ISSUE THREAD

**Issue by jpvj** [MicrosoftDocs/windows-itpro-docs#8587]
"Alternatively, you can *create copy* the .ADMX and .ADML files from a Windows 10,"

Should it be "Alternatively, you can *create a copy of* the .ADMX and .ADML files from a Windows 10," ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ab668a-e750-0503-7c17-093d0ea43644
* Version Independent ID: 37e38b31-4599-3b00-230b-7a488ee71fb2
* Content: [Configure Windows Hello for Business Policy settings - key trust - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-key-trust-policy-settings.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Very good point, good catch. Thank you for pointing out the text in need of grammatical improvement. It seems to have been like that ever since the pages were imported to GitHub from wherever they were hosted before. Very first commit for this document page: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/53a0dd521b6b63f02c6d9caad30d4b38c1d1d90d (`hello-key-trust-policy-settings.md` file link: https://github.com/MicrosoftDocs/windows-itpro-docs/commit/53a0dd521b6b63f02c6d9caad30d4b38c1d1d90d#diff-1f69fb982bc7e4145286e2856354ff2bcb8f6b3ff425da54dcd608ae1904c5f7).

**Comment by illfated** [comment]
PR #8594 is created to resolve this issue. Feel free to browse, comment, or post improvement suggestions.

**Comment by nam31** [comment]
Closing via #8594 
Thanks
