### ISSUE TITLE
Software Discovery Date

### ISSUE THREAD

**Issue by mgaryGCM** [MicrosoftDocs/windows-itpro-docs#8661]
Is there a way to determine when a given piece of software was discovered or identified by MD ATP? This would be very helpful to identify new software and changes to the environment. If there is a field that I can use to query in Advanced Hunting I can perform that as well.

Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc646df4-fc3c-9a3d-7f17-b12777c4a659
* Version Independent ID: 1b37afc4-6615-e88a-d9d4-6cb29e26059e
* Content: [Software inventory in threat and vulnerability management - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/tvm-software-inventory.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by nam31** [comment]
@mgaryGCM Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
