### ISSUE TITLE
Missing Block persistence through WMI event subscription option on the document

### ISSUE THREAD

**Issue by ambarishrh** [MicrosoftDocs/windows-itpro-docs#8694]
[Enter feedback here]

Microsoft defender for endpoint security recommendation says "Block persistence through WMI event subscription" with a link for ASR policy to the page https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription where it shows as 

**Intune name: Not yet available

Configuration Manager name: Not yet available**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d747289-63b2-f71a-b40c-31b52982215c
* Version Independent ID: b52f6593-03f2-aa57-ec0e-eaef560dcaf0
* Content: [Use attack surface reduction rules to prevent malware infection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#block-persistence-through-wmi-event-subscription)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction.md)
* Product: **w10**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by MaratMussabekov** [comment]
Hello @ambarishrh ,
could you please explain what's incorrect with the documentation in your opinion?
it states "Not yet available", because it is not yet available in Intune and Configuration Manager, and could only be set using GPO or PowerShell by using GUID.

Thank you

**Comment by MaratMussabekov** [comment]
Dear @ambarishrh ,
could you please clarify, what's incorrect with the documentation in your opinion?

Thank you

**Comment by ambarishrh** [comment]
Dear Marat

Thank you for your reply, probably not the documentation part that is
incorrect. On Defender portal, as a recommendation, it says the ASR rule
needs to be created, and points out to this documentation. If it is not
available, may be the portal should say that this is only available using
GPO.

Thanks again for your help

**Comment by nam31** [comment]
@ambarishrh, Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. 
Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience, you could add your feedback via the [Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). You might find others have made a similar request that you can add to, or you can open a new one.
