### ISSUE TITLE
Video links are broken

### ISSUE THREAD

**Issue by mr-fujnz** [MicrosoftDocs/windows-itpro-docs#8710]
Video links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23a14bad-9353-85fa-7f9f-b5db2be529f6
* Version Independent ID: ade91093-e916-281c-5645-00b4c3643d1c
* Content: [Windows Hello for Business Videos - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-videos)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-videos.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-videos.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by illfated** [comment]
Hmm, that is not my experience. What does it look like, from your side?

All the videos are playing just fine here, as if they were played directly from YouTube:

- https://youtu.be/G-GJuDWbBE8
. https://youtu.be/cC24rPBvdhA
- https://youtu.be/mXJS615IGLM
- https://youtu.be/RImGsIjSJ1s
- https://youtu.be/WPmzoP_vMek
- https://youtu.be/FJqHPTZTpNM
- https://youtu.be/etXJsZb8Fso
- https://youtu.be/KcVTq8lTlkI

All these links have been copied by clicking the video button
![image](https://user-images.githubusercontent.com/38162891/100279571-1bd4cd00-2f67-11eb-882b-e41ceec4ee50.png)
from inside all of the videos listed above.

**Comment by illfated** [comment]
Also, I visited the page https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-videos — is that the same page as you used?

**Comment by mr-fujnz** [comment]
Hi

https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-videos

This is what I'm seeing.

![image](https://user-images.githubusercontent.com/45184726/100281546-fda2b780-2fce-11eb-9910-18074d57f88e.png)

Cheers,

**Comment by illfated** [comment]
https://www.youtube-nocookie.com/embed/G-GJuDWbBE8 works all right for me, it shows the entire video as a web page.

I even have ublock origin enabled, along with 3 or 4 GitHub Chrome extensions, making it quite odd that you don't see the video and how it appears as in your image.

Let me paste parts of the page, just to see if it depends on the site or not.

## Overview of Windows Hello for Business and Features

Watch Pieter Wigleven explain Windows Hello for Business, Multi-factor Unlock, and Dynamic Lock

> [!VIDEO https://www.youtube.com/embed/G-GJuDWbBE8]

***

Hmm. I wonder if this is about how the URL is encapsulated, but still, it does not explain why it appears perfectly OK in my browser. Maybe it is because I am logged in, both here on GitHub (with my github login) and on the docs.microsoft.com site (with my Microsoft account login).

**Comment by illfated** [comment]
HTML content in the Content Details box, as viewed from the docs.microsoft.com page, by using the "view page source" feature in Chrome:

<details>
<summary>Content Details</summary>


--
  | <p><strong>Applies to</strong></p>
  | <ul>
  | <li>Windows 10</li>
  | </ul>
  | <h2 id="overview-of-windows-hello-for-business-and-features">Overview of Windows Hello for Business and Features</h2>
  | <p>Watch Pieter Wigleven explain Windows Hello for Business, Multi-factor Unlock, and Dynamic Lock</p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/G-GJuDWbBE8" frameborder="0" allowfullscreen="true"></iframe></div>
  | <h2 id="why-pin-is-more-secure-than-a-password">Why PIN is more secure than a password</h2>
  | <p>Watch Dana Huang explain why a Windows Hello for Business PIN is more secure than a password.</p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/cC24rPBvdhA" frameborder="0" allowfullscreen="true"></iframe></div>
  | <h2 id="microsofts-passwordless-strategy">Microsoft's passwordless strategy</h2>
  | <p>Watch Karanbir Singh's Ignite 2017 presentation <strong>Microsoft's guide for going password-less</strong></p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/mXJS615IGLM" frameborder="0" allowfullscreen="true"></iframe></div>
  | <h2 id="windows-hello-for-business-provisioning">Windows Hello for Business Provisioning</h2>
  | <p>Watch Matthew Palko and Ravi Vennapusa explain how Windows Hello for Business provisioning works.</p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/RImGsIjSJ1s" frameborder="0" allowfullscreen="true"></iframe></div>
  | <h2 id="windows-hello-for-business-authentication">Windows Hello for Business Authentication</h2>
  | <p>Watch Matthew Palko and Ravi Vennapusa explain how Windows Hello for Business authentication works.</p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/WPmzoP_vMek" frameborder="0" allowfullscreen="true"></iframe></div>
  | <h2 id="windows-hello-for-business-user-enrollment-experience">Windows Hello for Business user enrollment experience</h2>
  | <p>The user experience for Windows Hello for Business occurs after user sign-in, after you deploy Windows Hello for Business policy settings to your environment.</p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/FJqHPTZTpNM" frameborder="0" allowfullscreen="true"></iframe></div>
  | </br>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/etXJsZb8Fso" frameborder="0" allowfullscreen="true"></iframe></div>
  | <h2 id="windows-hello-for-business-forgotten-pin-user-experience">Windows Hello for Business forgotten PIN user experience</h2>
  | <p>If the user can sign-in with a password, they can reset their PIN by clicking the &quot;I forgot my PIN&quot; link in settings.  Beginning with the Fall Creators Update, users can reset their PIN above the lock screen by clicking the &quot;I forgot my PIN&quot; link on the PIN credential provider.</p>
  | <div class="embeddedvideo"><iframe src="https://www.youtube-nocookie.com/embed/KcVTq8lTlkI" frameborder="0" allowfullscreen="true"></iframe></div>
  | <p>For on-premises deployments, devices must be well connected to their on-premises network (domain controllers and/or certificate authority) to reset their PINs.  Hybrid customers can on-board their Azure tenant to use the Windows Hello for Business PIN reset service to reset their PINs without access to their corporate network.</p>
  |  
  | 

</details>

I was about to paste it as open text, but the videos don't show up (for me) without the full page source. So still not sure how it can be pasted properly here without finding the correct MarkDown method of displaying embedded video content.

**Comment by illfated** [comment]
Using the page http://embedyoutube.org/, I have managed to create a viewable link below here in this comment

[![Updates to Windows Hello for Business](http://img.youtube.com/vi/G-GJuDWbBE8/0.jpg)](http://www.youtube.com/watch?v=G-GJuDWbBE8 "Windows Hello for Business")

**Comment by illfated** [comment]
URL MarkDown code, as used in the webpage linked above:

```
[![Updates to Windows Hello for Business](http://img.youtube.com/vi/G-GJuDWbBE8/0.jpg)](http://www.youtube.com/watch?v=G-GJuDWbBE8 "Windows Hello for Business")
```

**Comment by illfated** [comment]
Also, just to add an image of how the referenced docs.microsoft.com page looks in my browser:

![image](https://user-images.githubusercontent.com/38162891/100286895-ea163300-2f73-11eb-80f1-b2cc2cb34ceb.png)

**Comment by RAJU2529** [comment]
i also checked the article, all videos are played without problems

**Comment by illfated** [comment]
@mr-fujnz : The issue seems to be only on your computer, it is not a problem with the document. I can only recommend that you try any and all browsers you can get your hands on, while also testing www.youtube.com to see if you are able to play their videos.

You may also need to check your Firewall settings or other limitations, maybe one of the intermediary hosts between you and the video source (or the video URL itself) is blocked in your settings or in your network. I don't know. There are too many unknowns in your case.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by illfated** [comment]
#please-close
