### ISSUE TITLE
Restict option

### ISSUE THREAD

**Issue by larsinus** [MicrosoftDocs/windows-itpro-docs#8730]
Using the restrict option 'R' in the .xml doesn't work.
It does nothing, but when I switch to 'U' to update it adds my groups.
Would like to have 'R' work to make sure only those users/groups are part of the local group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0c55a7-9aaa-d395-409e-59c2595c8e9e
* Version Independent ID: cf8e5a71-a8fc-1d43-6eed-03d3f2490693
* Content: [Policy CSP - LocalUsersAndGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups)
* Content Source: [windows/client-management/mdm/policy-csp-localusersandgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localusersandgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by e0i** [comment]
Thank you for providing feedback.

Note that the feedback section that you have used to submit this issue is intended for product documentation issues only.

Please consider opening a product feedback ticket for any of your suggestions or feature requests to help Microsoft improve your experience. Find the link to Feedback Hub below:

[Microsoft Windows 10 Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub)

Thanks.
