### ISSUE TITLE
found over 700 infected files

### ISSUE THREAD

**Issue by ghost785** [MicrosoftDocs/windows-itpro-docs#8754]
Does this mean my computer is hosting a virus or worm or any type of malware? 
I think i got hacked and im running scans after a clean format of the harddrive. 
Im showing 700 infected files. I want to contain the virus somehow and get 
the report of what is happening.. I have a host computer that i can back up all the 
infected files to and reverse engineering all the folders to see what type of ZeroDay
fucking bull shit is this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by ghost785** [comment]
It sounds stupid to ask i know but im still fucking racking the numbers sitting at almost 20,000 infected

**Comment by beerisgood** [comment]
@ghost785
This isn't the right place for help with a virus infection but you can get help at https://malwaretips.com/
Even if i would clean the whole PC.

Good luck

**Comment by ghost785** [comment]
at this point clicking on any link isn't an option. Thank you for your response. I ran a scan from MSERT and it came back with 20,000 files infected. is that legit or not?

**Comment by beerisgood** [comment]
This is definitely not safe.
Shut down your PC and start from scratch. You can download Windows 10 and/ or build a bootable medium:
https://www.microsoft.com/en-us/windows/get-windows-10

But you should download / build that on a clean PC.

**Comment by illfated** [comment]
I totally agree. Also, I suggest getting expert help from someone else if you need to salvage anything from your current computer contents. In such cases, your computer drive needs to be detached and backed up in such a fashion that infected files don't get a chance to be activated by your infected operating system.

Short answer: For backup, get expert help locally. For restoring your computer to normal, do as suggested above, get reinstall media (i.e. USB drive) from a safe computer and reinstall by booting from the flash drive.

**Comment by illfated** [comment]
#please-close

**Comment by ghost785** [comment]
Ok guys.. Good shit/ thanks for all the answers.. i didn't think of creating an instillation media from a well know src.. thanks.  Hey you guys... So i was trying to trap the virus... I did some recon on the files.. anyone want to help???

**Comment by ghost785** [comment]
I have a host computer.. I tried to analyze it but i failed.. I wiped everything.. thought i backed up the files to try and run on a non networked host.. maybe im doing the wrong thing.. just looking for a little help

**Comment by illfated** [comment]
Please get help locally, or call Microsoft Support for your region.
This is not a support instance.
This repository is only for Microsoft Docs documentation page issues.

**Comment by ghost785** [comment]
Ok I understand that. but what do i turn over to Microsoft..

**Comment by illfated** [comment]
That is for them to decide and you to find out.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by ghost785** [comment]
Hey illfated thanks

**Comment by ghost785** [comment]
oh and i do have an "improvement suggestion" use a VPN and Norton Anti virus. Thought i had the virus contained and then i was going to analyze it but i think my system fixed it so now im lost. but thanks
