### ISSUE TITLE
Get a error when trying to activate a product key for Windows 10 Pro

### ISSUE THREAD

**Issue by FaithDIckinson** [MicrosoftDocs/windows-itpro-docs#8785]
Get a 0xc004F050 error when trying to activate a product key to go from Windows 10 Home to Windows 10 Pro. We purchased an upgrade product key for our non-profit.

**Comment by illfated** [comment]
Please contact your nearest Microsoft Support instance for OS licensing.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by denisebmsft** [comment]
@FaithDIckinson we are sorry you are having trouble. @illfated is correct; this is a technical support case. That is the best and fastest path to getting your issue resolved.
