### ISSUE TITLE
Is MDATP health data stored in some table that can be queried using KQL?

### ISSUE THREAD

**Issue by haiderim** [MicrosoftDocs/windows-itpro-docs#8825]
These reports must be fetching data from some table in the backend, can we query using KQL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 828b08db-32e7-c3e7-afaf-a6badf0daa93
* Version Independent ID: 17a248e0-965b-c2cc-acb9-377ba8eba1f8
* Content: [Device health and compliance report in Microsoft Defender ATP - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/machine-reports)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/machine-reports.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/machine-reports.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Good question. I don't know myself, but hopefully you will receive an answer from the current topic author sooner or later.

**Comment by nam31** [comment]
@haiderim The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Or try the following resources to get in touch with users who may be able to help you:

TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
Microsoft Community: https://answers.microsoft.com/

Thank you
