### ISSUE TITLE
Please clarify the ownership parameter under ms-device-enrollment

### ISSUE THREAD

**Issue by zerovertex** [MicrosoftDocs/windows-itpro-docs#8828]
Please clarify what the 1,2, and 3 correspond with under the ownership parameter of ms-device-enrollment. Only 2 options are discussed in the description so the reader has no way to know which option corresponds with which ownership type. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39ae2ccd-9f3f-dcb5-3a20-46b1b4fd3d53
* Version Independent ID: b381c208-94b1-2d22-ef16-a57c138a7d72
* Content: [MDM enrollment of Windows 10-based devices - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/mdm-enrollment-of-windows-devices)
* Content Source: [windows/client-management/mdm/mdm-enrollment-of-windows-devices.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/mdm-enrollment-of-windows-devices.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
if I understand it correctly, the ownership parameter can have three possible values - corporate owned, private device or ask during enrollment. However, I didn't find on any public source which value means which number (1, 2 or 3).

Dear @manikadhiman,
Could you please advise?

Thank you

**Comment by dferreira042** [comment]
It apparently means nothing.  In fact, it may hurt other things.  I tried this today on 3 different VM's:
ms-device-enrollment:?mode=AADJ&ownership=1
ms-device-enrollment:?mode=AADJ&ownership=2
ms-device-enrollment:?mode=AADJ&ownership=3

Each of these came in as Personal devices and none of these actually prompted me to select.  But here's the problem: when I DON'T add the ownership, then the devices register in AAD as Azure AD Joined.  When I add ownership, then the devices register as Azure AD Registered.

So since I want all of these to be corporate owned, it looks like I will have to skip the ownership parameter and then run a PowerShell script after the fact to change ownership.

**Comment by Kateyanne** [comment]
@MaratMussabekov should we close this Issue now?

**Comment by illfated** [comment]
I am fairly certain this ticket is resolved in PR #9407 .
