### ISSUE TITLE
No longer getting "com.microsoft:mdm.unenrollment.userrequest" in the meta tags

### ISSUE THREAD

**Issue by kamalmaheshwari** [MicrosoftDocs/windows-itpro-docs#8849]
[Enter feedback here]
We are no longer getting "com.microsoft:mdm.unenrollment.userrequest" . We are using that to determining that the generic alert is for user initiated unenrollment. 

This behavior can be seen on various windows versions like : 1803, 1809, 1903, 1909 and 2004. We are getting the same result. 
Is there some change that has happened in this area which has caused this??
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d8375f-a60e-dbad-453b-80c933249b1b
* Version Independent ID: 2b233d8a-6eda-ce21-9da5-6a2ccee81372
* Content: [Disconnecting from the management infrastructure (unenrollment) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/disconnecting-from-mdm-unenrollment)
* Content Source: [windows/client-management/mdm/disconnecting-from-mdm-unenrollment.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/disconnecting-from-mdm-unenrollment.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by nam31** [comment]
@kamalmaheshwari Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
