### ISSUE TITLE
Broken link - Distribute offline apps

### ISSUE THREAD

**Issue by joaonltome** [MicrosoftDocs/windows-itpro-docs#8942]
Hi all.

In Distribute offline apps (https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps) the link Manage apps from Microsoft Store for Business with Microsoft Intune that points to https://docs.microsoft.com/en-us/intune/deploy-use/manage-apps-you-purchased-from-the-windows-store-for-business-with-microsoft-intune rports error 404. Probably the destination has changed URL. I believe that it should point to the doc How to manage volume purchased apps from the Microsoft Store for Business with Microsoft Intune - https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business.

Can you double check this and fix it please?

**Comment by illfated** [comment]
Thank you for the report and solution suggestion. This issue can be found in the following section:
- https://docs.microsoft.com/en-us/microsoft-store/distribute-offline-apps#distribution-options-for-offline-licensed-apps

I see why you were unable to bring the expected content along with your ticket, because the source page does not have any **[ Edit ]** button or link at the top of the page.

I will check around to see if there is a local path in this GitHub repository to replicate that docs.microsoft.com document directory location. If not found, this may need to be looked into by the MS Docs team members. Back soon (I hope).

**Comment by illfated** [comment]
Looks like I found a match:
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/store-for-business/distribute-offline-apps.md#distribution-options-for-offline-licensed-apps

OK, so I just need to browse the /mem/intune/ directory to see if your suggested document is the best selection. Checking. BRB.

**Comment by illfated** [comment]
Fair enough, your link https://docs.microsoft.com/mem/intune/apps/windows-store-for-business seems to fit the intended profile, even if some of the wording is different in the page title and so on, but I think it will be the way forward. I also presume it will be a reasonable opportunity to get feedback from the MS Docs team in a PR, just in case the link description text should stay the same or if it needs to match the current (new) page title. Thank you very much so far. Let's see how this goes.

**Comment by illfated** [comment]
There you go. PR #8950 is ready for review, comments, and suggestions.
