### ISSUE TITLE
RemoteApp Slowness

### ISSUE THREAD

**Issue by j4v4g33k** [MicrosoftDocs/windows-itpro-docs#896]
Since the Windows 10, version 1803 was applied...Remote App acted very slow with network connectivity and user response time to a server on the same LAN network.  I rolled back to version 1709 on 15 (to test) computers and Remote App on those 15 computers behaved normally with no network or user response delays.  What changes in version 1803 may cause this type of behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c274f8df-31da-f58a-36af-dc7eb6ace762
* Version Independent ID: 0e33637d-e094-edbc-04f9-e8d5e6c642c6
* Content: [Windows 10, version 1803 - Features that have been removed](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-1803-removed-features)
* Content Source: [windows/deployment/planning/windows-10-1803-removed-features.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/planning/windows-10-1803-removed-features.md)
* Service: **w10**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by jvsam** [comment]
@officedocsbot assign @jvsam

**Comment by nam31** [comment]
@j4v4g33k Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)

Thank you.
