### ISSUE TITLE
Request that XML content be available in XML file format

### ISSUE THREAD

**Issue by wheatiesthecereal** [MicrosoftDocs/windows-itpro-docs#8999]
Hi, I like to request that xml content of this article be made made available in the form of an xml file so that we can leverage its content programmatically. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8740b8-c1f2-4b88-3d4d-66cdbf20215f
* Version Independent ID: 7986a684-b35d-06bd-be30-dfca9923cb9c
* Content: [Microsoft recommended driver block rules (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules.md)
* Product: **w10**
* GitHub Login: @jgeurten
* Microsoft Alias: **dansimp**

**Comment by jgeurten** [comment]
Hi @David Trejo<mailto:datrejo@microsoft.com>,

Following up on this ask. The xml has been added to the \Windows\schemas\CodeIntegrity\ path a few months ago. We will not backport the changes because its just not worth it. However, the xml will be accessible on the next production build of Windows as well as the last several months worth + new flighting builds for Windows Insiders.


Thanks,
Jordan

**Comment by e0i** [comment]
Closing based on the Jordan's comment above
