### ISSUE TITLE
i want  to edit this artcle 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9006]
some commands should be  edited, i could not  able to find the content source address for the below article 
**https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-driver-servicing-command-line-options-s14**

**Comment by illfated** [comment]
I believe it is because that particular repository has not yet been opened for public contribution:
- https://docs.microsoft.com/en-us/windows-hardware/get-started/
- https://docs.microsoft.com/en-us/windows-hardware/design/
- https://docs.microsoft.com/en-us/windows-hardware/customize/
- https://docs.microsoft.com/en-us/windows-hardware/manufacture/
- https://docs.microsoft.com/en-us/windows-hardware/service/
- https://docs.microsoft.com/en-us/windows-hardware/test/

I searched for "hardware" underneath https://github.com/MicrosoftDocs , that search only returned https://github.com/MicrosoftDocs/licensed-hardware (which does not contain anything useful for regular documentation contribution).

**Comment by RAJU2529** [comment]
@illfated , Thanks for replying, in that article, the wrong command is  written, so i want to chnage it

**Comment by illfated** [comment]
I understand that you would want to contribute with corrections to the page, if there is a wrong command there.

I can only suggest using the feature "**Is this page helpful?**" on the right hand side by clicking the thumbs down (👎🏻) icon and fill in the information you want to send to the maintainers of that page.

**Comment by nam31** [comment]
@RAJU2529  Thank you for submitting this feedback.
I will assign this to our team for investigation. Thank you for your contribution to making the docs better. Much appreciated.

**Comment by illfated** [comment]
@RAJU2529 : Based on the feedback from @nam31, you can also contribute by posting more details about what is wrong on that page (https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-driver-servicing-command-line-options-s14) here in this ticket, and what should be written there instead.

Would this be a reasonable suggestion for what can be done to correct that page?

**Comment by RAJU2529** [comment]
@illfated .thanks for replying. this  : is missing

**Comment by illfated** [comment]
> . thanks for replying. this symbol : is missing

OK, fair enough. But could you add the full context, maybe the whole sentence (or code block, if it is a command) so we get which part of the document this is for?

**Comment by Reeced40** [comment]
@RAJU2529 @illfated thank you for pointing this out. I don't have access to the content source so if you locate it please can you send me the link and I'll do the PR. Please also indicate where in the doc the : is missing.

**Comment by RAJU2529** [comment]
@Reeced40, Sorry  content source  is not available to edit.

**Comment by illfated** [comment]
Maybe we could ask someone in the Windows Driver Developer Doc Team (@windows-driver-content) team if they could look into this issue?

**Comment by Reeced40** [comment]
@nam31 please can you ask someone at Microsoft to assist as the content source is not available to us.
