### ISSUE TITLE
Smart Screen

### ISSUE THREAD

**Issue by StoneyD1612** [MicrosoftDocs/windows-itpro-docs#9048]
I'm furious,  I want to install Signal Now App, and Defender blocks it! I try the 'it's OK
--- option and it keeps blocking it
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen overview (Windows 10) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by StoneyD1612** [comment]
It's an install program, why would I take a picture of it?

**Comment by illfated** [comment]
Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by StoneyD1612** [comment]
I didn't choose to come to this **no-help** forum, this is where it sent me. I guess I shouldn't be surprised by the response.

**Comment by illfated** [comment]
Sorry that your software sent you here. The developers need to hear about this obvious inconvenience.

Could you post the problem via the built-in Windows Feedback App, to post it where the devs read the tickets?
