### ISSUE TITLE
WinPE PXE boot for an UEFI system

### ISSUE THREAD

**Issue by MaxPower2005** [MicrosoftDocs/windows-itpro-docs#9059]
I was able to successfully setup whole WinPE PXE infrastructure and boot a target using "legacy" mode, but it failed for the same target when using UEFI mode.
The symptom is that after loading the "boot.wim" file, the system seems to freeze (black screen, no reaction to keyboard).

Is there something else which needs to be changed/adapted besides replacing "PXEboot.n12" with its UEFI equivalent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a95648-e93d-fdd5-b52f-afca6e49a139
* Version Independent ID: 607d9bc8-de81-eb28-5326-434e1cf6a696
* Content: [Configure a PXE server to load Windows PE (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/configure-a-pxe-server-to-load-windows-pe)
* Content Source: [windows/deployment/configure-a-pxe-server-to-load-windows-pe.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/configure-a-pxe-server-to-load-windows-pe.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by nam31** [comment]
@MaxPower2005, Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
