### ISSUE TITLE
Supported Windows Server versions

### ISSUE THREAD

**Issue by gunterda** [MicrosoftDocs/windows-itpro-docs#9077]
This page states that Windows Server 2012 R2 is a supported version. Is it also the case for Windows Server 2012? In the remainder documentation it often only states Windows Server 2016 and Server 2019 as supported Server Version, e.g. when talking about Microsoft Defender Antivirus. So to me it's quick unclear which Server Version are now really supported in MDEP.
Thanks,
Gunter
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aca66a-5a8b-64d2-7201-a7b915c5d309
* Version Independent ID: c3cc0543-db20-a8f2-288c-d1dea5ea479f
* Content: [Minimum requirements for Microsoft Defender for Endpoint - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by VLG17** [comment]
@gunterda Looking as [this blog post](https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/protecting-windows-server-with-windows-defender-atp/ba-p/267114) from 2018 about Protecting Windows Server with Windows Defender ATP (former name of Microsoft Defender for Endpoint), we can see that Windows Server 2012 was also supported.

Also it's stated that: 

> The Microsoft-recommended configuration for the best security is staying current with Windows. **While we provide support for previous versions of Windows, the latest releases provide superior security capabilities**. If you are running previous versions of Windows, one of the most important things you can be doing is getting a plan to update your Windows environment.  

In my opinion I don't thin adding Windows Server 2012 to the lists helps, because the best thing would be to upgrate asap to R2, thus being in the best scenario possible, in terms of security, for that specific Windows Server version.

**Comment by illfated** [comment]
I concur. In general, Windows Server 2012 is not supported, because (among other reasons) upgrading to Windows Server 2012 R2 is fairly manageable for most scenarios. Also, as VLG17 indicated, 2012 R2 is better security-wise.
