### ISSUE TITLE
WDATP Network Protection - registry and exceptions

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/windows-itpro-docs#9079]
Hello Microsoft Documentation Team,
there are several problems with this page,
**1. Issue with missing registry:**
The page referring to "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection" key for Network Protection settings. However i checked on two test machines, running 1909 and 20H2 Windows 10 and there is no such location in the registry. Can you check if it is changed and update the page if this the case. In my setup MDATP is configured via Intune and Network Protection is blocking test page (https://smartscreentestratings2.net) - that is test PCs are working fine. It is just registry settings are not there.

![image](https://user-images.githubusercontent.com/63236635/106986457-490dda80-6763-11eb-91a1-6b6e512e87a5.png)

**2. Not explained where "unblock" list of "Network Protection" is stored and how to reset the list**
User has an option to unblock the "Network Protection" action:
![image](https://user-images.githubusercontent.com/63236635/106986426-3abfbe80-6763-11eb-979f-b86e678838cc.png)
But it is not clear where (in the registry) this is stored and how to list the values using powershell or registry or GUI and how to clear the allowed "unblocked" list

**3. Not explained how to hide "Unblock" option from the user**

It is not explained if "Unblock" option can be hidden from the user (using Intune, Registry or GPO)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71868539-63d8-b250-f9d4-83a4052f4f74
* Version Independent ID: ed5658cf-173f-47bf-ed76-a68d89ea5c4b
* Content: [Turn on network protection - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/enable-network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by joinimran** [comment]
Hello @SergGu - Thank you for your feedback. Can you please confirm what happened when you click on Unblock?

Please note that the registry path is correct. 

![image](https://user-images.githubusercontent.com/47118050/109426833-5f7d1e00-7a11-11eb-91c6-cc0e1a73055a.png)

**Comment by levinec** [comment]
@SergGu 
For #1, it looks like you went to "Microsoft\Windows Defender Advanced Threat Protection" instead of "Microsoft\Windows Defender". Windows Defender is one folder below. 

For #2, this seems to be connected to the new attack surface reduction ["Warn" mode](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction#warn-mode-for-users) that can be enabled. If you [set the ASR rules to "Block"](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/enable-attack-surface-reduction) instead, the user won't be able to unblock. 

For #3, you can review [attack surface reduction events](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/event-views) and [network protection events](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/network-protection#requirements) in the Microsoft Defender Security Center and Windows Event Viewer.

**Comment by nam31** [comment]
@SergGu Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.

**Comment by aexlz** [comment]
Hello, I want to catch up with this conversation.
We are facing the exact same problem like @SergGu. 
Users are able to unblock with 3rd-Party-Browsers. 
NetworkProtection is enabled and the Toast-Notifcation appears. 

I do not think, that this is related to the Warn-Capabilitiy. 
ASR-Rules and NetworkProtection are two different functionalities within ExploitGuard. 
Apart from that there is no ASR-Rule on our side, which is on Warn-Mode.

The only way setting back to default is re-installing the 3rd-Party-Browser. 

Thanks for your help.

**Comment by mselley** [comment]
Did anyone ever find a way of resetting the Unblock list?
