### ISSUE TITLE
No Documentation regarding creating direct links in MDATP/DFE

### ISSUE THREAD

**Issue by cac0ns3c** [MicrosoftDocs/windows-itpro-docs#9105]
Hi, 

I'm looking to create direct links to MDATP queries same as [Link](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-shared-queries#create-a-direct-link-to-a-query)

For example: https://securitycenter.windows.com/hunting?query=H4sIAAAAAAAEAHNhSGUoY8hkSAbSbkA6B0i7AkVSGfIYShiKGRQYuBhqgGQ5QwZQrAiIFeDq_BgSGXLBIskM-WD1iUCZPLAuJSAvFcgqAbIAQzi36WQAAAA&runQuery=true&timeRangeId=week

if you take the query parameter `H4sIAAAAAAAEAHNhSGUoY8hkSAbSbkA6B0i7AkVSGfIYShiKGRQYuBhqgGQ5QwZQrAiIFeDq_BgSGXLBIskM-WD1iUCZPLAuJSAvFcgqAbIAQzi36WQAAAA`
and throw it into CyberChef using this recipe:

```
From_Base64('A-Za-z0-9-_',true)
Gunzip()
Decode_text('UTF-16LE (1200)')
```

you will get the query that you ran.
i'm tried to do the opposite way 

```
Encode_text('UTF-8 (65001)')
Gzip('None (Store)','','',false)
To_Base64('A-Za-z0-9-_')
```

and i'm not getting the same output.

**Comment by nam31** [comment]
@cac0ns3c, Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Windows 10 Support](https://support.microsoft.com/en-gb/windows?ui=en-US&rs=en-GB&ad=GB)
Thank you.
