### ISSUE TITLE
適用対象no

### ISSUE THREAD

**Issue by dev-nawa** [MicrosoftDocs/windows-itpro-docs#9151]
適用対象の OS が異なるため以下の通り変更が必要です
【変更前】
*****************************************************************************
適用対象
•	Windows 10
•	Windows 10 Mobile
•	Microsoft Edge
*****************************************************************************
【変更後】
*****************************************************************************
適用対象
•	Windows 10
•	Windows 10 Mobile
•	Microsoft Edge
•	Windows Server 8.1 以降
•	Windows Server 2012以降
*****************************************************************************

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4edaae97-455b-d25a-9228-5309e24b4aa3
* Version Independent ID: d38e56a7-d553-e519-95a9-dc93e2cdc771
* Content: [Microsoft Defender SmartScreen の概要 (Windows 10) - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview?source=docs)
* Content Source: [windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by illfated** [comment]
Translated via online MT (Bing/Google):

*******************

Applies to no

Changes are required as follows because the applicable OS is different

【Before change】

Applies to
• Windows 10
• Windows 10 Mobile
• Microsoft Edge

【After change】

Applies to
• Windows 10
• Windows 10 Mobile
• Microsoft Edge
• Windows Server 8.1 or later
• Windows Server 2012 or later

********

Applicable target no

Since the applicable OS is different, the following changes are required.

【Change before】

Applicable target
• Windows 10
• Windows 10 Mobile
• Microsoft Edge

[After change]

Applicable target
• Windows 10
• Windows 10 Mobile
• Microsoft Edge
• Windows Server 8.1 or later
• Windows Server 2012 or later

**Comment by illfated** [comment]
As far as I know, "Windows Server 8.1" does not exist. 

Microsoft Windows 8.1 is a version of Microsoft Windows for Desktop/Laptop/Notepad use, just like Windows 10.

Other than that, it looks like you are asking for the addition of **Windows Server 2012 or later** to be added to the page. This probably needs to be added in the EN-US version of the page first, because that page is the main source of automatic Machine Translation:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview
- https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview.md

**Comment by illfated** [comment]
Direct Link to open a New issue Ticket for the /en-us/ page (US English):
- https://github.com/MicrosoftDocs/windows-itpro-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%204edaae97-455b-d25a-9228-5309e24b4aa3%0A*%20Version%20Independent%20ID%3A%20d38e56a7-d553-e519-95a9-dc93e2cdc771%0A*%20Content%3A%20%5BMicrosoft%20Defender%20SmartScreen%20overview%20(Windows%2010)%20-%20Windows%20security%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fsecurity%2Fthreat-protection%2Fmicrosoft-defender-smartscreen%2Fmicrosoft-defender-smartscreen-overview)%0A*%20Content%20Source%3A%20%5Bwindows%2Fsecurity%2Fthreat-protection%2Fmicrosoft-defender-smartscreen%2Fmicrosoft-defender-smartscreen-overview.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fblob%2Fpublic%2Fwindows%2Fsecurity%2Fthreat-protection%2Fmicrosoft-defender-smartscreen%2Fmicrosoft-defender-smartscreen-overview.md)%0A*%20Product%3A%20**m365-security**%0A*%20Technology%3A%20**mde**%0A*%20GitHub%20Login%3A%20%40mjcaparas%0A*%20Microsoft%20Alias%3A%20**macapara**

(This is to let the link & ticket creation insert most of the ticket content directly from the link itself.)

**Comment by illfated** [comment]
Never mind. The repositories are not different, the only difference is the source pages taking us users here to GitHub when the ticket is opened.

**Comment by illfated** [comment]
I guess the main point here is to check if the source page needs to be updated regarding which OS versions (Server/Desktop, 2012/8.1/10 and so on).

**Comment by e0i** [comment]
Closing via https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9199#issuecomment-786694081
