### ISSUE TITLE
ネットワーク保護の対象 OS について

### ISSUE THREAD

**Issue by dev-nawa** [MicrosoftDocs/windows-itpro-docs#9152]
ネットワーク保護の対象 OS が異なるため、以下の変更が必要です

【変更前】
*****************************************************************************
ネットワーク保護には、Windows 10 Pro または Enterprise と Microsoft Defender ウイルス対策のリアルタイム保護が必要です。

【変更後】
*****************************************************************************
ネットワーク保護には、Windows 10 Pro または Enterprise、Windows Server 2016以降と Microsoft Defender ウイルス対策のリアルタイム保護が必要です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 71064247-63c3-cb57-5f05-a1ea40b01d97
* Version Independent ID: 684863fb-0302-945d-d42e-ed35f5e6269d
* Content: [ネットワーク保護を使用して、不良サイトへの接続を防止する - Windows security](https://docs.microsoft.com/ja-jp/windows/security/threat-protection/microsoft-defender-atp/network-protection)
* Content Source: [windows/security/threat-protection/microsoft-defender-atp/network-protection.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/microsoft-defender-atp/network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by illfated** [comment]
**About network-protected operating system**

The following changes are required because the operating system is protected differently:

【Before change】

Network protection requires real-time protection for Windows 10 Pro or Enterprise and Microsoft Defender antivirus.

【After change】

Network protection requires real-time protection for Windows 10 Pro or Enterprise, Windows Server 2016 and later, and Microsoft Defender antivirus.

**********

**About the target OS for network protection**
 
The following changes are required because the target OS for network protection is different.

【Change before】

Network protection requires real-time protection against Windows 10 Pro or Enterprise and Microsoft Defender Antivirus.

[After change]

Network protection requires real-time protection for Windows 10 Pro or Enterprise, Windows Server 2016 or later, and Microsoft Defender Antivirus.
