### ISSUE TITLE
AccountOU

### ISSUE THREAD

**Issue by kyjeeper** [MicrosoftDocs/windows-itpro-docs#918]
Could you provide a little more detail on what goes in the AccountOU field? Does it need to be the LDAP path to the OU? What is an example of the content for that field? If nothing is provided in that field, does the Active Directory domain join automatically put the machine in the Computer container?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313b8527-ba38-682f-5291-7c56ef58b122
* Version Independent ID: 88d93eac-44d2-46d2-0763-4380dc8cfdb8
* Content: [Accounts (Windows 10)](https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-accounts)
* Content Source: [windows/configuration/wcd/wcd-accounts.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/configuration/wcd/wcd-accounts.md)
* Service: **w10**
* GitHub Login: @jdeckerMS
* Microsoft Alias: **jdecker**

**Comment by jdeckerms** [comment]
Hi @kyjeeper those are good questions! I haven't been able to find an answer for the last question (what happens if no value is specified), but I did get the other answer, and I'll be updating the topic to include it: Use the full path for the organizational unit. For example: OU=testOU,DC=domain,DC=Domain,DC=com.
