### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/windows-itpro-docs#9235]
Hi, this article was last updated 3 years ago and wanted some clarification of the text in the "notes" section at the top of the page is still correct.  Q. Are you 100% saying it is not possible \ supported to set the DSCP tags in a **hybrid Azure AD joined** machine via intune? This either has to be done via a GPO or some PowerShell script maybe triggered via intune?

It is this sentence 
"Currently, this CSP is not supported on Azure AD Hybrid joined devices and for devices using GPO and CSP at the same time"

Ideally the above sentence could  be clarified / bullet pointed or improve the punctuation,  as someone may read it that "its not supported on hybrid azure AD joined devices if some policies are also set by GPO but otherwise it is supported".

Effectively modern desktops are typically updated by intune Policies, alot of large enterprise customers are hybrid azure ad joined and for Teams and OneDrive applying QOS via GPO seems like a step backwards, so can we use CSP to set QOS policies on Hybrid Azure AD joined machines?" 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb8b93e-0c1a-8b47-472f-effef5f9209e
* Version Independent ID: 8a2615e2-a77b-c08e-b91c-3ce33e0539b2
* Content: [NetworkQoSPolicy CSP - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/networkqospolicy-csp)
* Content Source: [windows/client-management/mdm/networkqospolicy-csp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/networkqospolicy-csp.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello,
**this article was last updated 3 years ago** - it was edited many times since then (last change was 3 month ago), but for some reason the date attribute of the article wasn't updated.
**Are you 100% saying it is not possible \ supported to set the DSCP tags in a hybrid Azure AD joined machine via intune?** - yes, it is not supported yet

**It is this sentence
"Currently, this CSP is not supported on Azure AD Hybrid joined devices and for devices using GPO and CSP at the same time"
Ideally the above sentence could be clarified / bullet pointed or improve the punctuation, as someone may read it that "its not supported on hybrid azure AD joined devices if some policies are also set by GPO but otherwise it is supported".** - yes, that make sense, since it is not obvious whether "at the same time" related to "GPO and CSP" or to "Azure AD Hybrid joined devices and for devices using GPO". I will create a PR.

**applying QOS via GPO seems like a step backwards** - it sure is a step backwards, may be in future it will work.

Thank you
