### ISSUE TITLE
Add note for GCC High and DoD

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/windows-itpro-docs#9250]
Windows 10 Subscription Activation is not available for GCC High/DoD. And the guidance to customers is to use MAK or KMS keys. Can you add a blue or purple box be added with this note? Please validate with the product owners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd18b4c7-1c71-916d-cb5c-8322903e8ed5
* Version Independent ID: 7b4c1663-1b1a-2952-7bf8-b0cb724013af
* Content: [Windows 10 Subscription Activation - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/windows-10-subscription-activation)
* Content Source: [windows/deployment/windows-10-subscription-activation.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/windows-10-subscription-activation.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello, there is already a note about GCC\GCC High tenants.
As for DoD, this type of licensing is currently in preview.
Thank you

**Comment by nam31** [comment]
@kerbo Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
