### ISSUE TITLE
Step 9 contradicts other docs on auto enrollment

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/windows-itpro-docs#9340]
This page is describing the auto enrollment of an Active Directory joined device as it instructing about setting a GPO in Active Directory.  This means the device will be Hybrid Joined.  The setting to allow users to join devices to Azure Active Directory does not apply Hybrid Joined devices according to this doc (see purple note) https://docs.microsoft.com/en-us/azure/active-directory/devices/device-management-azure-portal#configure-device-settings  There needs to be clarity over the correct setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy?source=docs)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by joinimran** [comment]
Hello @jandreacola - Thank you for rising your query. I have gone through both of the documents and other documents and it feels like that there the purple note should not be added in the document as there no other document talks about this. See another document https://docs.microsoft.com/en-us/azure/active-directory/devices/azureadjoin-plan#configure-your-device-settings for the same.

I would request you to open a feedback in that specific document so that the author can review the settings and make necessary changes in the document.

Thanks
Imran.

**Comment by nam31** [comment]
@jandreacola Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
