### ISSUE TITLE
Can't create computer after following instructions

### ISSUE THREAD

**Issue by joshuaalm** [MicrosoftDocs/windows-itpro-docs#9362]
https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information.md

I think the instructions should include adding 'db_datawriter' to the roles for the intended MDT database user account.  I was not able to add a computer to my database from within Deployment Workbench until I had added this role to my own account, but was able to do so after adding that role.  Please let me know if I have missed something in the instructions that contradicts this.

**Comment by illfated** [comment]
(just adding the ticket content which would have been generated if the ticket had been opened using the button **[This page]** instead of going directly to GitHub)

***

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6204280-0cde-d489-7973-f0e62c854675
* Version Independent ID: fd7b5637-b83c-0f93-247d-c8cf2942a475
* Content: [Use MDT database to stage Windows 10 deployment info (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information)
* Content Source: [windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by MaratMussabekov** [comment]
Hello, I also checked, and if I run workbench using the user that I used in [Configure database permissions](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/use-the-mdt-database-to-stage-windows-10-deployment-information#configure-database-permissions), I also cannot create an object in database.
Dear @greg-lindsay, can you please confirm?
Thank you
