### ISSUE TITLE
Issues with linked PCPTool

### ISSUE THREAD

**Issue by wmjdgla** [MicrosoftDocs/windows-itpro-docs#9425]
Under the section Use PCPTool to decode Measured Boot logs:
"PCPTool is part of the [TPM Platform Crypto-Provider Toolkit](https://www.microsoft.com/download/details.aspx?id=52487)..."

3 issues with this:
1. The description gives the impression that the tool can be run immediately after download. In fact the download is a Visual Studio solution and one has to build it themselves before they can run it.
2. Trying to build the solution produces compilation errors because the code repeatedly references a non-existent struct member. e.g. Support.cpp L530:
       `for(UINT32 n = 0; n < sizeof(pEntry->digest.data); n++)`
`pEntry` is a `PTCG_PCClientPCREventStruct` and its `digest` member is just a byte array. There is no `data` member under `digest`.
3. After fixing the issues and getting the solution to compile, I found that it is unable to decode Measured Boot log files from systems using TPM 2.0. The page makes no mention about this. The tool would parse and output the 1st event log entry and then terminate with error. Stepping into the code shows that it failed at Support.cpp L517. The code is unable to correct parse the log data and is getting a nonsensical value for `pEntry->eventDataSize`, resulting in a nonsensical `cbEntry` value and thereby failing the check at L514. The new code at https://github.com/microsoft/TSS.MSR/tree/master/PCPTool.v11 seems to work fine, albeit it also has some other compilation issues that needs to be fixed first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688de6fb-2db0-8aa4-c89c-bda8e3a5c1c0
* Version Independent ID: e3415e74-19f4-0267-a9b9-f8fe444cd258
* Content: [Decode Measured Boot logs to track PCR changes - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs)
* Content Source: [windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by joinimran** [comment]
Hello @wmjdgla - Thank you for raising your concern. For 1 part, I have created a PR. For the rest of the points, please open a support case with Microsoft so that can be taken care of by the development team.

Thanks.
Imran.

@e0i - FYI Please.

**Comment by illfated** [comment]
( ref. #9544 )

**Comment by tymees** [comment]
Chiming in on part 3:

Updating the documentation to link to the newer version linked by wmjdgla would be preferable as well. The version currently linked simply won't work on newer system, while the newer one works fine. 

As for the compile issues mentioned, I suspect it's because of using newer build tools. Using the VS 2019 build tools, you get all sorts of issues as described above. However, using the build tools the solution is asking for (2012 in case of the older version, 2015 for the newer one) compilation goes smoothly over here. 

Thus, I don't think a support case with Microsoft is required in order to provide up-to-date documentation. Updating the tool to work with the newer build tools is preferable, but not required.

**Comment by tymees** [comment]
I find it strange that you can't link to Microsoft repositories on Github because of ownership issues, as both the repository in question and Github itself are owned by Microsoft. (And the fact that I came here through a feedback link present on most pages is strange in that context as well)

As a workaround for that interesting bit of policy, wouldn't it be possible to create new ZIP sourced from the Microsoft Github repository and host it in the same place the current version is hosted? The code in question is [owned by Microsoft](https://github.com/microsoft/TSS.MSR/blob/master/LICENSE). If someone else is responsible for handling that, I would be happy to contact them if you could provide some contact details. If this isn't possible, please at least add a warning saying it isn't guaranteed to work with newer TPMs. 

As a side note, a simple search through docs.microsoft.com finds several pages linking to code in MS Github repositories: [1](https://docs.microsoft.com/en-us/windows/client-management/mdm/azure-active-directory-integration-with-mdm), [2](https://docs.microsoft.com/en-us/windows/configuration/mobile-devices/provisioning-nfc) and [3](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/wdac-wizard). Do different policies apply to those sections of the docs? If not, it might be a good idea to remove those as well then.

**Comment by joinimran** [comment]
@tymees - Sorry I missed this and got confused with some other issue. Let me check and update the link if it gets approved.

Thanks
Imran.
