### ISSUE TITLE
Lots of unclarity here

### ISSUE THREAD

**Issue by identityiskey** [MicrosoftDocs/windows-itpro-docs#9443]
[Enter feedback here]
There is a lot of unclarity here 
==> For the OnPrem PIN Reset
1. Screenshots are missing for the user experience
2. How long does it take after the PIN reset until fingerprint and PIN can be reused to sign-in - after our tests there is a delay (about 30 minutes). It is unclear what is the issue for the delay (domain controller replication, azure replication, ADFS etc.???)
3. In Certificate Trust -> What needs to be done to get the user certificate (smartcard EKU) back?

==>Azure PIN reset
1. Can AzurePIN reset used even when the client / user was initially enrolled without the Group Policy set?
2. Screenshots are missing for the user experience
3. How does the AzurePIN reset work technically? Are there any delays expected? Does it work with Certificate trust?
4. Is the SSRP feature necessary for AzurePIN reset and how should it be configured?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dae9da-eaf0-c209-7c65-be8d2c1ada12
* Version Independent ID: 28b6788d-7982-23c2-5f19-f80690ebc0ce
* Content: [Pin Reset - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset)
* Content Source: [windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/identity-protection/hello-for-business/hello-feature-pin-reset.md)
* Product: **w10**
* GitHub Login: @mapalko
* Microsoft Alias: **mapalko**

**Comment by mapalko** [comment]
For on-prem PIN reset, what is the deployment type (key trust or cert trust)? In on-prem PIN reset, the existing user key is deleted and a new key is provisioned. For hybrid deployments, the key is always registered to Azure AD and then synced to AD. This occurs during a normal AAD sync cycle, which is usually every 30 minutes. If you are using key trust, the key needs to sync to AD before the user can sign in with Hello. For cert trust, a certificate should be enrolled before that sync has occurred which enables logon. As a part of provisioning, WHFB will automatically attempt to do certificate enrollment. If you aren't seeing the cert enrolling you should verify in the WHFB event log if there are certificate enrollment errors.

For Azure PIN reset, there are both group policy and MDM policy to enable this feature. How it was enabled should not impact how the flow actually occurs. When Azure PIN reset is enabled on the client, the client will generate a 256bit AES key that is added as a protector to the user's WHFB keys, similar to the PIN. This key is encrypted on the client using a public key that is retrieved from the Azure PIN reset service, and the encrypted key protector is stored locally on the device. 

When PIN reset is initiated and the user auths+MFAs, the encrypted secret is sent to the PIN reset service, decrypted, and returned to the client. The client will use the decrypted key to authorize changing the PIN protector on the user's keys and then the unencrypted secret is cleared from memory. This flow is the same for cert and key trust. There are no delays with this flow since the underlying user keys are not changing. This flow does not require SSPR.

I will draft some changes to add this into the documentation.

**Comment by identityiskey** [comment]
A:
Actually the one test case I described was cert trust and default PIN reset (Destructive). After about 30 minutes to 1 Hour I was able to log in again with fingerprint / PIN. And after some time the Self Signed Certificate came back but never the one from our PKI. So the smartcard auth functionality is not really back.

B: Does that mean that you can also switch to Azure based PIN reset on already enrolled WHFB clients? It sounds that this is the more viable method to minimize disruption.

C: Some screenshots for the user experience for the different types of PIN reset would be good as well.

**Comment by mapalko** [comment]
For A, do you know why the enrollment failed? For example did you reset without line of sight to the CA/enrollment authority?

For B, You can turn Azure based PIN reset on for existing enrollments. After the policy is set, we can create the reset protector post provisioning the next time the user signs with their pin and authorizes their keys.

For C, we can work on adding those. It was quicker to push the text changes first.

**Comment by mapalko** [comment]
I am no longer the area owner for this docs section.

**Comment by yogkumgit** [comment]
@paolomatarazzo

**Comment by paolomatarazzo** [comment]
This document has been updated multiple time since @identityiskey 's submission. I believe the content is accurate. Closing the issue, but @identityiskey please let me know if you think otherwise and I'll address the problem.
