### ISSUE TITLE
Method 1 misses the main step!

### ISSUE THREAD

**Issue by fredphoesh** [MicrosoftDocs/windows-itpro-docs#9482]
Method 1 does  not include the step to do a startup repair!!!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc264df-cbd1-ac1f-3926-841fcab7dc31
* Version Independent ID: 67c2aea4-0d28-3d8e-e935-8af05291c94e
* Content: [Advanced troubleshooting for Windows boot problems - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems)
* Content Source: [windows/client-management/advanced-troubleshooting-boot-problems.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/advanced-troubleshooting-boot-problems.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
(Here is the referenced documentation content:)

- https://docs.microsoft.com/en-us/windows/client-management/advanced-troubleshooting-boot-problems#method-1-startup-repair-tool

***

The Startup Repair tool automatically fixes many common problems. The tool also lets you quickly diagnose and repair more complex startup problems. When the computer detects a startup problem, the computer starts the Startup Repair tool. When the tool starts, it performs diagnostics. These diagnostics include analyzing startup log files to determine the cause of the problem. When the Startup Repair tool determines the cause, the tool tries to fix the problem automatically.

To do this, follow these steps.

> [!NOTE]
> For additional methods to start WinRE, see [Windows Recovery Environment (Windows RE)](/windows-hardware/manufacture/desktop/windows-recovery-environment--windows-re--technical-reference#span-identrypointsintowinrespanspan-identrypointsintowinrespanspan-identrypointsintowinrespanentry-points-into-winre).
1. Start the system to the installation media for the installed version of Windows. For more information, see [Create installation media for Windows](https://support.microsoft.com/help/15088).

2. On the **Install Windows** screen, select **Next** > **Repair your computer**.

3. On the **System Recovery Options** screen, select **Next** > **Command Prompt**.

4. After Startup Repair, select **Shutdown**, then turn on your PC to see if Windows can boot properly.

The Startup Repair tool generates a log file to help you understand the startup problems and the repairs that were made. You can find the log file in the following location:

**%windir%\System32\LogFiles\Srt\Srttrail.txt**


For more information see, [A Stop error occurs, or the computer stops responding when you try to start Windows Vista or Windows 7](https://support.microsoft.com/help/925810/a-stop-error-occurs-or-the-computer-stops-responding-when-you-try-to-s)

***

Fair point, it looks like something is missing between step 3 and step 4.
There seems to be a logical gap **3.** Launching the **Command Prompt** and **4.** select **Shutdown** , no indication of any repair action to perform after opening the command prompt.

Then again, it has been a handful of years since I last had to use any of these methods, so I don't remember what happens in the background.

**Comment by RAJU2529** [comment]
I am going to edit this article now
