### ISSUE TITLE
これでは内容が読めない

### ISSUE THREAD

**Issue by harmonix-tm** [MicrosoftDocs/windows-itpro-docs#9488]
改善を求めます。
![なぜ見終わる前に聞くのか](https://user-images.githubusercontent.com/50851391/116965568-1d11df00-ace9-11eb-9fdb-b382ce9cdab0.jpg)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1cb9f2a2-76ad-8301-7d80-e33a7bb80a1b
* Version Independent ID: dd070c32-53d5-53d6-7ba2-a4361b5263bb
* Content: [Windows Update の一般的なエラーと軽減策 - Windows Deployment](https://docs.microsoft.com/ja-jp/windows/deployment/update/windows-update-errors)
* Content Source: [windows/deployment/update/windows-update-errors.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/windows-update-errors.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **greglin**

**Comment by illfated** [comment]
This issue is slightly different from the earlier ones. The page appears to show the content correctly if your browser view is set to 100%.

To reproduce the issue above, you need to **increase the view resolution**, i.e. **magnify the view to 125% or greater** (as if you need to blow up the view to see it from afar, or as if you have got bad eyesight).

**Comment by illfated** [comment]
Oh, and by the way, just to let you know: This issue is present in any language, including US English:
- https://docs.microsoft.com/en-us/windows/deployment/update/windows-update-errors

If you are using an external pointing unit with a scroll wheel, **hold down the Ctrl key while scrolling**, to zoom in and out in the browser magnification view.

**Comment by dstrome** [comment]
@harmonix-tm @illfated - I'm not able to reproduce this issue. I've tried multiple browsers, languages, articles, zoom levels, and window sizes. The "Is this helpful" pane doesn't draw over any content. Looking at the screenshot above, the pane also doesn't draw over the introductory text above the table.

What you may be experiencing is the table width exceeding the size of the content pane. As the text increases, or the width of the window shrinks, it's possible for the table to take up more room than is available in the content pane. This is because tables have a minimum width. When the space available becomes less than that minimum width, the table will remain that width and a scroll bar will appear at the bottom of it. You can then use the scroll bar to scroll to see the content that isn't able to fit in the content pane. 

Please confirm whether this is what you're experiencing.

**Comment by illfated** [comment]
Oh. I see. Good call. That is exactly what is happening. Thank you.

The table manages to stay within the central part of the page up to 110%, but as soon as you reach 125% or higher, it becomes a sideways scrollable section.

**Comment by illfated** [comment]
@harmonix-tm : Please confirm that this is the same as you are seeing. I am able to see what has been described above in any language, so this is not a bugged page per se, only a limitation due to the table taking up most of the page space.

オンライン機械翻訳サービスを使用して翻訳：/ Translated using an online machine translation service :

これがあなたが見ているものと同じであることを確認してください。 上記の内容はどの言語でも見ることができるので、これ自体はバグのあるページではなく、ページスペースの大部分を占めるテーブルによる制限にすぎません。
