### ISSUE TITLE
New Microsoft Business Premium License - Intune Policies have Remediation Error

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/windows-itpro-docs#9509]
Every since we switched to Business Premium License, several of our Intune Windows Configuration Profiles have Remediation Errors. All of our existing laptop users who originally had a Mobility and Security E3 license who now have Business Premium have no issue.

Any new users who are starting out with Business Premium are having the remediation issue. We are audited and the fact these errors are showing up aren't just an inconvience, they have serious consequences. This needs to be resolved ASAP, Support indicates it' a known issue but it's unnacceptable. We rely heavily on your product.

![image](https://user-images.githubusercontent.com/18271134/117521824-b698f500-af64-11eb-9975-6a76b0aae7de.png)

![image](https://user-images.githubusercontent.com/18271134/117521844-cadcf200-af64-11eb-8ed6-a100e6b4523e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b0c55a7-9aaa-d395-409e-59c2595c8e9e
* Version Independent ID: cf8e5a71-a8fc-1d43-6eed-03d3f2490693
* Content: [Policy CSP - LocalUsersAndGroups - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-localusersandgroups)
* Content Source: [windows/client-management/mdm/policy-csp-localusersandgroups.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/policy-csp-localusersandgroups.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by afield1235** [comment]
@nam31  Any update on this? It's causing a lot of issues with our auditing.

**Comment by e0i** [comment]
@afield1235 We handle content feedback under the issues section of this repository that hosts documentation, not the product. It is recommended that you continue seeking answers through appropriate support channels. Thanks.

**Comment by illfated** [comment]
@afield1235 : Please use a real support instance like Microsoft Support or Microsoft Forums. This repository is intended for documentation improvement only.

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
