### ISSUE TITLE
Not Deleting Infected Files.

### ISSUE THREAD

**Issue by TechPro33** [MicrosoftDocs/windows-itpro-docs#9525]
Why isn't the Microsoft Safety Scanner deleting the infected files it finds during the scan??? Like it finds 400 Files Infected but yet at the end it says No Infected Files Found.  Then I run it again and it still finds 400 Files Infected.  Also the log file says no Infected Files Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bb1ce3-9128-5385-4417-d22eb5f8cb77
* Version Independent ID: cb6ba731-a2c2-e9b9-7c3e-db781b1b5222
* Content: [Microsoft Safety Scanner Download - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download)
* Content Source: [windows/security/threat-protection/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/intelligence/safety-scanner-download.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
That seems very odd, could it be that your computer is infected with software blocking MSS from actually removing the discovered infections? If so, maybe the malware on your computer is so devious that it traps parts of the MSS processes and stops it before it can complete the scan.

If I were you, I would definitely consider unplugging your computer, shutting it down and use a different computer with external drive docking to make backups of whatever you would like to keep, before completely reinstalling your infected computer.

You could choose to contact Microsoft Support to get help with removing viruses on your computer, but it could easily end up being so compromised that you would need to perform backup & reinstall anyway (just an educated guess on my part).

**Comment by TechPro33** [comment]
No I think the program is not working correctly.

**Comment by illfated** [comment]
Fair enough, that could also be a possible alternative. Maybe we need a newer version of the application to resolve this issue, but I don't know. I hope someone from the tech writer team could have some suggestions on how to move forward with this issue ticket.

**Comment by e0i** [comment]
This is a documentation repository and the technical writer team cannot provide answers to every support query. Hence, Please consider consider contacting [Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) for this feedback.

Thank you for this feedback, and for the community for raising reasonable points for this discussion.

**Comment by akyratea** [comment]
Also, have this issue, it would be nice if the user was given a detailed list of the infected files so we could take care of ourselves manually. 

Just wait for a newer version, we'll see if the problem it's with the application or our computers.

**Comment by akyratea** [comment]
Also, have this issue, it would be nice if the user was given a detailed list of the infected files so we could delete them manually.

Just wait for a newer version, we'll see if the problem it's with the application or our computers.

**Comment by init-bobJames** [comment]
Hello. Happy this application exists, thank you guys.

I believe the detections, for me, are for PUPs, of which I have 5 'Files Infected' detected before the end of the scan.

At the end of the scan I am told nothing is found. 

I think the application should write to the log on the fly for any detections, PUP or otherwise and mark them clearly.

Application seems to go back over to the PUPs in its scan at the end, before showing the final view of no threats found.

The log files do not contain these 'Files Infected' data, be they PUPs or otherwise, perhaps unsigned applications.

My feedback is that the logs do not seem to contain all the information gathered from the application.

Put these events in the log and I would be much happier. 

Is there documentation on this issue stating that PUPs are not shown in the logs?

Thank you

---------------------------------------------------------------------------------------
Microsoft Safety Scanner v1.355, (build 1.355.2198.0)
Started On Thu Jan 20 05:35:17 2022

Engine: 1.1.18800.4
Signatures: 1.355.2198.0
MpGear: 1.1.16330.1
Run Mode: Interactive Graphical Mode

Results Summary:
----------------
No infection found.
Successfully Submitted MAPS Report
Successfully Submitted Heartbeat Report
Microsoft Safety Scanner Finished On Thu Jan 20 05:43:36 2022


Return code: 0 (0x0)
