### ISSUE TITLE
MFA MDM enrollment Hybrid Azure AD joined

### ISSUE THREAD

**Issue by wander1992** [MicrosoftDocs/windows-itpro-docs#9533]
Hi :)

We used this page to enable MDM for Hybrid Azure AD joined computers. We found out that a lot of computers were enrolling correctly but some did not. We thought that it had nothing to do with MFA because a lot of computers were enrolling without any issues. The notifications for the MFA prompt were never showed on the computers that did not enroll.

A lot of people experience the same issue (lot's of Reddit posts.)

I think it is helpful to mention how the MFA works on this page (and that is it possible that some computers enroll en some don't if Conditional Access is enforcing MFA)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad012591-5c74-f1cd-d3a2-443768e8ceee
* Version Independent ID: 918ea4bc-0849-3745-5d9d-a21a973bcd3b
* Content: [Enroll a Windows 10 device automatically using Group Policy - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy#feedback)
* Content Source: [windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/mdm/enroll-a-windows-10-device-automatically-using-group-policy.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **dansimp**

**Comment by VLG17** [comment]
@wander1992 The article states that `If multi-factor authentication is required, the user will get a prompt to complete the authentication. Once the enrollment is configured, the user can check the status in the Settings page.`

You're saying that "The notifications for the MFA prompt were never showed on the computers that did not enroll", so that's a confirmation of the problem in itself, right?

What I'm saying is that if you don't receive the MFA prompt then the enrollment will not complete. Now, did you find out why you were not getting the MFA prompt in the scenario where MFA was enforced by Conditional Access?
