### ISSUE TITLE
Wording Kompromiss -> Kompromitierung

### ISSUE THREAD

**Issue by easyMaxi** [MicrosoftDocs/windows-itpro-docs#9578]
Hey! I don't believe this can be solved in English. It references the German version of the documentation.
In short: "compromised" is translated with "compromise" as in "making a compromise".
--
Mir ist im Text etwas aufgefallen, dass durch die Übersetzung einen anderen Sinn bekommen hat. Zumindest glaube ich das.

Es geht um den folgenden Teil: "und glauben, dass ihre Kennwortauswahl vor Einer Kompromissbereitschaft geschützt ist."

Ich vermute mal hier ist "vor einer Kompromitierung" gemeint.
Wenn nicht, ist mir zumindest nicht klar, was hier ausgedrückt werden soll.

Im Englischen Text steht "compromised" (also "kompromittiert"). 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 98f30760-4999-dcb1-26da-097477dc31bc
* Version Independent ID: 6cef6a81-a4aa-bb3b-4f1c-78cf98aba958
* Content: [Minimales Kennwortalter (Windows 10) - Windows security](https://docs.microsoft.com/de-de/windows/security/threat-protection/security-policy-settings/minimum-password-age)
* Content Source: [windows/security/threat-protection/security-policy-settings/minimum-password-age.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/security-policy-settings/minimum-password-age.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by illfated** [comment]
English document section:

***

### Vulnerability

Users may have favorite passwords that they like to use because they are easy to remember and they believe that their password choice is secure from compromise. Unfortunately, passwords can be compromised and if an attacker is targeting a specific individual user account, with knowledge of data about that user, reuse of old passwords can cause a security breach.

To address password reuse, you must use a combination of security settings. Using this policy setting with the [Enforce password history](https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/enforce-password-history) policy setting prevents the easy reuse of old passwords. For example, if you configure the Enforce password history policy setting to ensure that users cannot reuse any of their last 12 passwords, but you do not configure the **Minimum password age** policy setting to a number that is greater than 0, users could change their password 13 times in a few minutes and reuse their original password. Configure this policy setting to a number that is greater than 0 for the Enforce password history policy setting to be effective.

***

quoted part of sentence one:

> [...] and they believe that their password choice is secure from compromise.

German version:

> [...] und glauben, dass ihre Kennwortauswahl vor Einer **Kompromissbereitschaft** geschützt ist.

***

**Suggested replacement** (provided by @easyMaxi):

[...] und glauben, dass ihre Kennwortauswahl vor einer **Kompromitierung** geschützt ist.

***

@TinaMcN : I presume you will need to send this one in for manual translation.

**Comment by TinaMcN** [comment]
@easyMaxi thanks very much for reporting this issue and @illfated thank you for the helpful details.  I believe this is an issue caused by machine translation so I sent it to be human translated which usually takes 2-3 business days.   Hopefully that will fix the problem.

**Comment by TinaMcN** [comment]
@easyMaxi the article is now human translated.  Can you please review it and see if it is now fixed?

**Comment by illfated** [comment]
https://docs.microsoft.com/de-de/windows/security/threat-protection/security-policy-settings/minimum-password-age#vulnerability

### Sicherheitsrisiko

Benutzer haben möglicherweise Lieblingskennwörter, die sie gerne verwenden, da sie leicht zu merken sind und sie der Meinung sind, dass ihr gewähltes Kennwort vor Gefährdungen sicher ist. Leider können Kennwörter gefährdet sein, und wenn es ein Angreifer auf ein bestimmtes Benutzerkonto abgesehen hat und Daten von diesem Benutzer kennt, kann die Wiederverwendung von alten Kennwörtern zu einer Sicherheitsverletzung führen.

***

Looks good to me. The affected sentence is completely rewritten, making a different choice of words to make sure that security and vulnerability is in focus.

**Comment by easyMaxi** [comment]
Looks definitely better to me!

I am not sure whether this is something that you want to address, but "Gefährdung" is a very broad word for "in danger."
The actual problem, correct me if I am wrong, of reusing passwords is that if the password is "compromised"/stolen ("offen gelegt"/"geklaut"?!) it can be used on other platforms. If the text wants to name the actual problem it would benefit from a more concrete wording. At least that was my thought while reading it.

My amateur translation would be something like that.
"ihr gewähltes Kennwort vor Diebstahl geschützt ist. Leider kann es dazu kommen, dass Kennwörter geklaut werden, und"

But again this is a detail and the translation is better than before!

**Comment by TinaMcN** [comment]
@easyMaxi thanks for checking the article again.  I passed on your feedback to a German linguistic expert and they will advise on the best translation to use in this scenario.

**Comment by TinaMcN** [comment]
@easyMaxi the German linguistic expert reviewed your feedback.  His comments are "I have indirectly applied the feedback, because I agree. However, not in the sentence that the feedback refers to, but the following sentence . Here "can be compromised" has been changed to 'können gestohlen werden' which corresponds to the feedback. I think the term 'Gefährdung' is fine in sentence 1, but the approach to say 'be more explicit when translating compromise (as noun or verb)' is correct. People tend to be rather vague. "   The article has been published with the changes, please close if it looks ok to you now.  And thanks again for the feedback!

**Comment by easyMaxi** [comment]
Looks good to me. Thanks for being so responsive!
