### ISSUE TITLE
No data in WaaSUpdateStatus table 3 days

### ISSUE THREAD

**Issue by xuegao112** [MicrosoftDocs/windows-itpro-docs#9694]
Hi team, I met one issue that my 100+ machines has no data send to this table in 3 day. But actually per my check WaaSDeploymentStatus's latest data is today and the last scan time is 1 day ago.
Do you have any insights about this? I tried to run the script and it's succeeded...

**Comment by RAJU2529** [comment]
@xuegao112 Which article are you referring to?

**Comment by xuegao112** [comment]
Hi @RAJU2529  This one:
https://docs.microsoft.com/en-us/windows/deployment/update/update-compliance-get-started

**Comment by e0i** [comment]
@xuegao112 

The issues section of this repository is intended for product documentation issues only.

Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Feel free to re-open this issue if you think there is a problem with the documentation.

Thank you.
