### ISSUE TITLE
Support for upgrade paths from LTSC are not clear

### ISSUE THREAD

**Issue by ptilsen** [MicrosoftDocs/windows-itpro-docs#9715]
This section implies that LTSB can be converted to semi-annual channel as part of an in-place upgrade, and gives an _example_ of moving to Enterprise, but does not elaborate on what other editions, if any, are supported. 
`You can upgrade from Windows 10 LTSC to Windows 10 semi-annual channel, provided that you upgrade to the same or a newer build version. For example, Windows 10 Enterprise 2016 LTSB can be upgraded to Windows 10 Enterprise version 1607 or later. `

The upgrade matrix does not cover LTSC to SAC, and so it is unclear if LTSC can be migrated to Home, Pro, Education, or other edition variants via an in-place upgrade. Supported paths for edition changes made as part of in-place upgrades should be explicitly specified in this document.

The text of this document also conflicts with the "Supported Downgrade Paths" section of [Windows 10 edition upgrade](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades), which indicates that _no_ downgrade path from LTSC is supported. The documents should be aligned, perhaps with the explanation that edition conversion from LTSC is only supported as part of the in-place upgrade process, if that is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08436cb0-d0b6-0961-9e57-291b24d73644
* Version Independent ID: 36264f52-d3ac-4e50-f8e8-b09d6b210490
* Content: [Windows 10 upgrade paths (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-upgrade-paths)
* Content Source: [windows/deployment/upgrade/windows-10-upgrade-paths.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/upgrade/windows-10-upgrade-paths.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by greg-lindsay** [comment]
The article says "In-place upgrade from Windows 7, Windows 8.1, or Windows 10 General Availability Channel to Windows 10 LTSC is not supported."

You can move from LTSC to GAC (previously SAC), but you cannot go the other direction. Since LTSC is an Enterprise edition, you can't upgrade to another edition - these are considered downgrades.

The downgrade article doesn't specify GAC or LTSC channels. However, you cannot have LTSC on any other edition than Enterprise, so it would be impossible to (for example) downgrade to LTSC Home because that edition doesn't exist. Valid downgrades from Enterprise to other editions should work for LTSC but of course these channels would all be GAC not LTSC.
