### ISSUE TITLE
more intel processors are added  or not in future for windows 11

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windows-itpro-docs#9729]
@akovarms  @themar-msft

i have seen compatible processor intel processor list to install windows 11 on the following website 
**https://docs.microsoft.com/windows-hardware/design/minimum/supported/windows-11-supported-intel-processors**

by my laptop processor model is not listed, so that means my  laptop will not able to install windows 11 os later this year 
 intel core i5 -7200U .
Will the intel  processor list updated further or not 
Plrease reply.

**Comment by WozSoftware** [comment]
I am very interested in this also. 

Just been chatting to support and been told that if you can run 21H1 you can run 11 yet the CPU list and also the system checker state otherwise. 

So which is right?

**Comment by RAJU2529** [comment]
yes you can run windows 11 on top of windows 10 21h1.

**Comment by WozSoftware** [comment]
No, from what they were saying it implies in your case that your  i5 -7200U will be fine come release as long as your system supports 21H1 although there is the TPM extra restriction. It is still unclear if TPM 2 is a hard limit as that is a mixed message where some docs state TPM2 is a soft limit and TPM 1.2 is the hard limit

**Comment by RAJU2529** [comment]
i5 7200u  embedded with intel TPM 2.0 version

**Comment by WozSoftware** [comment]
Sounds like you should be good. That said the messaging from MS is diabolical over the release. This is really shaping up fast to be the next Win 8 unless they sort their message out.

I am sort of in the same boat. My main rig is fine, Ryzen 3600 but my server rig has a XEON E5 V4 which lists as unsupported.

I pity those that spent the $2000+ on an i9 9980 HEDT cpu as that is not on the list yet 18 core at 4ghz and 9th gen if the list turns out to be true.

Gut feel is the CPU list is the cpus that MS will let system integrators sell new Win 11 machines with, if that is the case they need to spell that out

**Comment by RAJU2529** [comment]
@WozSoftware , i give one hint, if you managed to get windows 11 iso file, then extract it,   install windows 11 on new SSD or HDD by using only with **install.esd** file or **install.wim**  file  and windows 10 PE bootable

**Comment by RAJU2529** [comment]
@denisebmsft . Yesterday night  successfully I installed windows 11 insider preview build 22000.51  on intel core i5 7th gen 7200U based laptop .
Please forward this processor  model  to windows 11 engineering team.
But one drawback standard security features are not available eventhough TPM 2.0 active booted with uefi mode with sucure boot enabled.

**Comment by denisebmsft** [comment]
@RAJU2529 thank you for this information. I'm not the writer assigned to this content but will make sure to forward to my colleague who is on point.

**Comment by RAJU2529** [comment]
@denisebmsft > Thanks for replying sir
