### ISSUE TITLE
CVE graph missing time range

### ISSUE THREAD

**Issue by marekr** [MicrosoftDocs/windows-itpro-docs#976]
The bargraph of CVEs does not denote the time range the CVEs totals were collected over ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f11f40c1-5631-3757-bcb0-a31d50506c1f
* Version Independent ID: eaee8c73-7d36-027a-11c7-077a264d36be
* Content: [Beginning your General Data Protection Regulation (GDPR) journey for Windows 10 (Windows 10)](https://docs.microsoft.com/en-us/windows/privacy/gdpr-win10-whitepaper#feedback)
* Content Source: [windows/privacy/gdpr-win10-whitepaper.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/privacy/gdpr-win10-whitepaper.md)
* Service: **unspecified**
* Product: **w10**
* GitHub Login: @pwiglemsft
* Microsoft Alias: **pwigle**

**Comment by DaniHalfin** [comment]
Hi @marekr , we currently do not intend to commit any updates to the current GDPR whitepaper. We are looking at releasing an alternative \ updated version.
In order to correct this issue, we'll need to revisit the collected data, which we will do in a future version\alternative of this whitepaper.

Thank you for raising this issue, and I'm sorry I can't offer a better answer.
