### ISSUE TITLE
Windows Password Requirments - Hard to find / kinda worthless doc 

### ISSUE THREAD

**Issue by McNinja** [MicrosoftDocs/windows-itpro-docs#9787]
Was expecting a very clear / easy to read and digest list of bullet points or something easy to fine for the password complexity. I could not find anything really useful at all on the manufacture site and had to look else where. This is pretty bad that yalls documentation is kinda worthless round this and 3rd party sites have this information very clearly laid out and easy to digest. 

EX: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-policy

Let me go click through 5+ pages to maybe get a basic idea on the length / complexity requirements and what not.... :|

**Comment by geoken** [comment]
So are you saying the documentation is worthless because it contains too much information? Seems like that's usually the opposite of what people complain about when they're saying documentation is not helpful.

Personally, I think this is the best way. The official docs should have as much info as humanly possible, and if it's too much and need the cliff notes version - then you can refer to some third party who summarizes it.

**Comment by e0i** [comment]
Hello @McNinja,

Thank you for taking the time to bring your opinion about the documentation.

However, this feedback is not specific enough be actionable.

It would be helpful if you have mentioned in specific terms something that doesn’t work with a given article, and we would be happy to help.
