### ISSUE TITLE
What do you mean by foreground and background throttling? And how to apply the change?

### ISSUE THREAD

**Issue by WiliTest** [MicrosoftDocs/windows-itpro-docs#9788]
**Do foreground and background has something to do with the active window,** or with the automatic vs manual (button) way to check the update, or something else? 

**And does the change directly apply** (it doesn't seem to be the case). Or do we need to wait  to apply (how long?), or to reboot the computer?

The documentation is missing these points.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb67e518-6f60-23e0-2545-c2839e2b4159
* Version Independent ID: e9a31629-e3cb-0367-31c4-5661284d89bf
* Content: [Delivery Optimization for Windows 10 updates - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/update/waas-delivery-optimization)
* Content Source: [windows/deployment/update/waas-delivery-optimization.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/update/waas-delivery-optimization.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by VLG17** [comment]
@WiliTest In the context of Delivery Optimization for Windows client updates, foreground implies that a user action is needed (you need to explicitely click on download, update, etc) where as background means that windows will start the download on it's own, without needing any user interaction.

In order to enforce different bandwidth settings for delivery optimization you can use Group Policy or an MDM solution like Intune. Actions like waiting/restarting will depend on the method used to deploy the settings.
