### ISSUE TITLE
Link to  Add-TPMSelfWriteACE.vbs doesnt work

### ISSUE THREAD

**Issue by wadeal** [MicrosoftDocs/windows-itpro-docs#9849]
Page has a link to required script  Add-TPMSelfWriteACE.vbs. When I click this doesn't go to this script just a general download page where searching for this script doesnt work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c3977f-3b78-1d8e-ad8f-50538ad1934f
* Version Independent ID: 46b9ab6d-7a30-4dab-70fa-e1c97cc3ec3e
* Content: [Set up MDT for BitLocker (Windows 10) - Windows Deployment](https://docs.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker)
* Content Source: [windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/deployment/deploy-windows-mdt/set-up-mdt-for-bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by RAJU2529** [comment]
@greg-lindsay. issue is confirmed by me also. Script ls missing.

**Comment by greg-lindsay** [comment]
The script is also referenced at https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766015(v=ws.10)?redirectedfrom=MSDN 

It appears the download was removed. I think this was due to removal of SHA1 signed uploads.  It is also available here: https://github.com/DeploymentArtist/DF4/blob/master/BitLocker%20and%20TPM/Add-TPMSelfWriteACE.vbs

To fix this I am likely going to have to re-upload the script to the DLC and edit the link to point to the new upload.  In the meantime, it's possible to just copy the script from the link I provided here.

**Comment by greg-lindsay** [comment]
I've replaced the script center link with a link directly to the author's github source.

**Comment by RAJU2529** [comment]
@greg-lindsay . Thanks for updating script link. Just now I visited link and I have seen it .

**Comment by e0i** [comment]
Thank you, @greg-lindsay
