### ISSUE TITLE
Document missing critical information regarding RD for macOS...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/windows-itpro-docs#9852]
Guys,

Can somebody please, at least in some way, acknowledge the existence of Microsoft Remote Desktop client for macOS? 

Even if it's just to say, hopefully, "go look here for how to do it" or, worst case even, "this isn't currently supported."

Thanks,

David.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e1cc18-3fc2-d7fa-7ff3-20fc9a3596d4
* Version Independent ID: 8ed24664-ce8c-7c08-654a-d3ef267f274f
* Content: [Connect to remote Azure Active Directory-joined PC (Windows 10) - Windows Client Management](https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc)
* Content Source: [windows/client-management/connect-to-remote-aadj-pc.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/client-management/connect-to-remote-aadj-pc.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by greg-lindsay** [comment]
Hi - I've used RDP for MacOS myself and it worked. However, it's not simple for me to know the details of this app. For example, perhaps it needs an update to work when a new version of Windows is released. Generally the article referenced here will only discuss Microsoft apps and products. You'd need to check with Apple for information about whether or not their app is working to connect to the current version of Windows.

This particular article is written because RDP uses an FQDN to connect to endpoints, and with AADJ devices the FQDN isn't as simple as connecting to an on-prem domain joined device.
