### ISSUE TITLE
Set-Cipolicysetting example

### ISSUE THREAD

**Issue by kimoppalfens** [MicrosoftDocs/windows-itpro-docs#9936]
Hi,

The bottom of this page has an example that tries to explain how to resolve a blocked event in the applocker msi log.
It's unclear to me how you get to the **bold** values used in that command, copied below.

 Set-CIPolicySetting -FilePath <path to policy xml>\WDAC_policy.xml -Key **8856f961-340a-11d0-a96b-00c04fd705a2** -Provider **WSH** -Value True -ValueName EnterpriseDefinedClsId -ValueType Boolean

Kim
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f316427f-86b4-1b53-727b-64b49cd0e16f
* Version Independent ID: 834aaa0f-ede0-9819-e4b3-ba49217da5da
* Content: [Allow COM object registration in a WDAC policy (Windows) - Windows security](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy?source=docs)
* Content Source: [windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/threat-protection/windows-defender-application-control/allow-com-object-registration-in-windows-defender-application-control-policy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by MaratMussabekov** [comment]
Hello @kimoppalfens ,
key is the GUID of the object, in the example it is taken from event XML.
I understand why you was confused, article had incorrect GUID, it was fixed by https://github.com/MicrosoftDocs/windows-itpro-docs/commit/7e6cb0a4b5cbb7ae9e442f768582571e76076886#diff-00a8188e62fa43be4d9b2e6814c6b15689eab49439faf49322250bff34838819
**provider** is a platform where code will run, WSH means Windows Script Host. If you want to add COM object and you do not know provider value, you can simply use **AllHostIds** (it will allow all platforms).
Thank you

**Comment by kimoppalfens** [comment]
That makes a whole lot more sense. Thanks for fixing this.
